// Class: ReadMLP_ANN_N3_NC200
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : MLP::MLP_ANN_N3_NC200
TMVA Release   : 4.2.1         [262657]
ROOT Release   : 6.06/01       [394753]
Creator        : brucms16
Date           : Wed Sep  7 03:25:34 2016
Host           : Linux vocms0315.cern.ch 2.6.32-573.26.1.el6.x86_64 #1 SMP Wed May 4 09:23:05 CEST 2016 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /home/t3cms/brucms16/CMSSW_8_0_14/src/UserCode/SkeletonAnalysis/macros
Training events: 15056
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
NCycles: "200" [Number of training cycles]
HiddenLayers: "N,N,N+3" [Specification of hidden layer architecture]
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
VarTransform: "Norm" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
H: "False" [Print method-specific help message]
LearningRate: "9.000000e-02" [ANN learning rate parameter]
DecayRate: "1.000000e-02" [Decay rate for learning parameter]
# Default:
NeuronType: "sigmoid" [Neuron activation function type]
RandomSeed: "1" [Random seed for initial synapse weights (0 means unique seed for each run; default value '1')]
EstimatorType: "CE" [MSE (Mean Square Estimator) for Gaussian Likelihood or CE(Cross-Entropy) for Bernoulli Likelihood]
NeuronInputType: "sum" [Neuron input function type]
VerbosityLevel: "Default" [Verbosity level]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
TrainingMethod: "BP" [Train with Back-Propagation (BP), BFGS Algorithm (BFGS), or Genetic Algorithm (GA - slower and worse)]
TestRate: "10" [Test for overtraining performed at each #th epochs]
EpochMonitoring: "False" [Provide epoch-wise monitoring plots according to TestRate (caution: causes big ROOT output file!)]
Sampling: "1.000000e+00" [Only 'Sampling' (randomly selected) events are trained each epoch]
SamplingEpoch: "1.000000e+00" [Sampling is used for the first 'SamplingEpoch' epochs, afterwards, all events are taken for training]
SamplingImportance: "1.000000e+00" [ The sampling weights of events in epochs which successful (worse estimator than before) are multiplied with SamplingImportance, else they are divided.]
SamplingTraining: "True" [The training sample is sampled]
SamplingTesting: "False" [The testing sample is sampled]
ResetStep: "50" [How often BFGS should reset history]
Tau: "3.000000e+00" [LineSearch "size step"]
BPMode: "sequential" [Back-propagation learning mode: sequential or batch]
BatchSize: "-1" [Batch size: number of events/batch, only set if in Batch Mode, -1 for BatchSize=number_of_events]
ConvergenceImprove: "1.000000e-30" [Minimum improvement which counts as improvement (<0 means automatic convergence check is turned off)]
ConvergenceTests: "-1" [Number of steps (without improvement) required for convergence (<0 means automatic convergence check is turned off)]
UseRegulator: "False" [Use regulator to avoid over-training]
UpdateLimit: "10000" [Maximum times of regulator update]
CalculateErrors: "False" [Calculates inverse Hessian matrix at the end of the training to be able to calculate the uncertainties of an MVA value]
WeightRange: "1.000000e+00" [Take the events for the estimator calculations from small deviations from the desired value to large deviations only over the weight range]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 11
Jet1Pt                        Jet1Pt                        Jet1Pt                        Jet1Pt                                                          'F'    [110.048698425,1572.76037598]
LepPt                         LepPt                         LepPt                         LepPt                                                           'F'    [5.00075817108,29.9984378815]
LepChg                        LepChg                        LepChg                        LepChg                                                          'F'    [-1,1]
LepEta                        LepEta                        LepEta                        LepEta                                                          'F'    [-2.48411560059,2.49880051613]
Met                           Met                           Met                           Met                                                             'F'    [280.020294189,1289.47937012]
mt                            mt                            mt                            mt                                                              'F'    [0.000537815736607,300.527191162]
HT20                          HT20                          HT20                          HT20                                                            'F'    [112.003395081,4504.87304688]
NbLoose30                     NbLoose30                     NbLoose30                     NbLoose30                                                       'F'    [0,6]
Njet                          Njet                          Njet                          Njet                                                            'F'    [1,14]
JetHBpt                       JetHBpt                       JetHBpt                       JetHBpt                                                         'F'    [-999,1378.42883301]
DrJetHBLep                    DrJetHBLep                    DrJetHBLep                    DrJetHBLep                                                      'F'    [-999,5.38026332855]
NSpec 0


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadMLP_ANN_N3_NC200 : public IClassifierReader {

 public:

   // constructor
   ReadMLP_ANN_N3_NC200( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadMLP_ANN_N3_NC200" ),
        fNvars( 11 ),
        fIsNormalised( false )
   {      
      // the training input variables
      const char* inputVars[] = { "Jet1Pt", "LepPt", "LepChg", "LepEta", "Met", "mt", "HT20", "NbLoose30", "Njet", "JetHBpt", "DrJetHBLep" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = -1;
      fVmax[0] = 1;
      fVmin[1] = -1;
      fVmax[1] = 0.99999988079071;
      fVmin[2] = -1;
      fVmax[2] = 1;
      fVmin[3] = -1;
      fVmax[3] = 1;
      fVmin[4] = -1;
      fVmax[4] = 1;
      fVmin[5] = -1;
      fVmax[5] = 1;
      fVmin[6] = -1;
      fVmax[6] = 1;
      fVmin[7] = -1;
      fVmax[7] = 1;
      fVmin[8] = -1;
      fVmax[8] = 1;
      fVmin[9] = -1;
      fVmax[9] = 1;
      fVmin[10] = -1;
      fVmax[10] = 1;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';
      fType[4] = 'F';
      fType[5] = 'F';
      fType[6] = 'F';
      fType[7] = 'F';
      fType[8] = 'F';
      fType[9] = 'F';
      fType[10] = 'F';

      // initialize constants
      Initialize();

      // initialize transformation
      InitTransform();
   }

   // destructor
   virtual ~ReadMLP_ANN_N3_NC200() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // input variable transformation

   double fMin_1[3][11];
   double fMax_1[3][11];
   void InitTransform_1();
   void Transform_1( std::vector<double> & iv, int sigOrBgd ) const;
   void InitTransform();
   void Transform( std::vector<double> & iv, int sigOrBgd ) const;

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[11];
   double fVmax[11];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[11];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)

   double ActivationFnc(double x) const;
   double OutputActivationFnc(double x) const;

   int fLayers;
   int fLayerSize[5];
   double fWeightMatrix0to1[12][12];   // weight matrix from layer 0 to 1
   double fWeightMatrix1to2[12][12];   // weight matrix from layer 1 to 2
   double fWeightMatrix2to3[15][12];   // weight matrix from layer 2 to 3
   double fWeightMatrix3to4[1][15];   // weight matrix from layer 3 to 4

   double * fWeights[5];
};

inline void ReadMLP_ANN_N3_NC200::Initialize()
{
   // build network structure
   fLayers = 5;
   fLayerSize[0] = 12; fWeights[0] = new double[12]; 
   fLayerSize[1] = 12; fWeights[1] = new double[12]; 
   fLayerSize[2] = 12; fWeights[2] = new double[12]; 
   fLayerSize[3] = 15; fWeights[3] = new double[15]; 
   fLayerSize[4] = 1; fWeights[4] = new double[1]; 
   // weight matrix from layer 0 to 1
   fWeightMatrix0to1[0][0] = 0.939248032209533;
   fWeightMatrix0to1[1][0] = 0.689357351668077;
   fWeightMatrix0to1[2][0] = 1.39364078755687;
   fWeightMatrix0to1[3][0] = 3.89141740111423;
   fWeightMatrix0to1[4][0] = -2.01624361409584;
   fWeightMatrix0to1[5][0] = -0.634954228672624;
   fWeightMatrix0to1[6][0] = 1.50502581731643;
   fWeightMatrix0to1[7][0] = 1.66076141741705;
   fWeightMatrix0to1[8][0] = -2.40714794502069;
   fWeightMatrix0to1[9][0] = -0.382012740181895;
   fWeightMatrix0to1[10][0] = -3.34885399247006;
   fWeightMatrix0to1[0][1] = 2.46221607949405;
   fWeightMatrix0to1[1][1] = -0.407500044168145;
   fWeightMatrix0to1[2][1] = -3.08849461296582;
   fWeightMatrix0to1[3][1] = -0.456637271048371;
   fWeightMatrix0to1[4][1] = 0.905765775216562;
   fWeightMatrix0to1[5][1] = -1.85016691383196;
   fWeightMatrix0to1[6][1] = 2.37660773822939;
   fWeightMatrix0to1[7][1] = -0.0431978541255559;
   fWeightMatrix0to1[8][1] = 3.2366415553631;
   fWeightMatrix0to1[9][1] = 1.12484867372077;
   fWeightMatrix0to1[10][1] = -0.164285327855737;
   fWeightMatrix0to1[0][2] = 1.41269682181145;
   fWeightMatrix0to1[1][2] = 0.0507138991065807;
   fWeightMatrix0to1[2][2] = 0.391881658030469;
   fWeightMatrix0to1[3][2] = -3.84620526343104;
   fWeightMatrix0to1[4][2] = 1.24447302436113;
   fWeightMatrix0to1[5][2] = 0.606951959783197;
   fWeightMatrix0to1[6][2] = -3.66335333680128;
   fWeightMatrix0to1[7][2] = 0.278459488261123;
   fWeightMatrix0to1[8][2] = -0.297188341737439;
   fWeightMatrix0to1[9][2] = -0.0289036887505116;
   fWeightMatrix0to1[10][2] = -0.750387524751349;
   fWeightMatrix0to1[0][3] = -0.0498316493261455;
   fWeightMatrix0to1[1][3] = 0.0918528952461813;
   fWeightMatrix0to1[2][3] = 1.5575316958659;
   fWeightMatrix0to1[3][3] = -0.776537057640272;
   fWeightMatrix0to1[4][3] = 1.53624507788676;
   fWeightMatrix0to1[5][3] = -2.48090726912143;
   fWeightMatrix0to1[6][3] = 0.519026036757362;
   fWeightMatrix0to1[7][3] = 1.06822251407007;
   fWeightMatrix0to1[8][3] = -0.299269831354532;
   fWeightMatrix0to1[9][3] = 5.2810810313044;
   fWeightMatrix0to1[10][3] = -3.08818271133779;
   fWeightMatrix0to1[0][4] = 6.26243881372564;
   fWeightMatrix0to1[1][4] = -3.38716101863156;
   fWeightMatrix0to1[2][4] = 8.97133696951656;
   fWeightMatrix0to1[3][4] = 0.79608792683264;
   fWeightMatrix0to1[4][4] = 2.20706874987702;
   fWeightMatrix0to1[5][4] = 6.4515411192855;
   fWeightMatrix0to1[6][4] = 3.99349461554618;
   fWeightMatrix0to1[7][4] = 1.19353688885094;
   fWeightMatrix0to1[8][4] = -4.44363184068983;
   fWeightMatrix0to1[9][4] = -0.0300728349037554;
   fWeightMatrix0to1[10][4] = -0.91084038026848;
   fWeightMatrix0to1[0][5] = -1.54419184826753;
   fWeightMatrix0to1[1][5] = -16.7283975904596;
   fWeightMatrix0to1[2][5] = -0.00603805973425847;
   fWeightMatrix0to1[3][5] = 3.40438324891439;
   fWeightMatrix0to1[4][5] = 0.233769553329707;
   fWeightMatrix0to1[5][5] = -2.83693120467542;
   fWeightMatrix0to1[6][5] = 0.070123788245415;
   fWeightMatrix0to1[7][5] = -0.543096421155204;
   fWeightMatrix0to1[8][5] = 2.76967717265008;
   fWeightMatrix0to1[9][5] = 2.55114346400836;
   fWeightMatrix0to1[10][5] = 3.32333481932699;
   fWeightMatrix0to1[0][6] = -1.44237230050065;
   fWeightMatrix0to1[1][6] = 3.28909795844145;
   fWeightMatrix0to1[2][6] = -4.23816224742842;
   fWeightMatrix0to1[3][6] = -0.750961163012132;
   fWeightMatrix0to1[4][6] = -0.606163307966936;
   fWeightMatrix0to1[5][6] = -1.96332198669316;
   fWeightMatrix0to1[6][6] = -0.0768516860017849;
   fWeightMatrix0to1[7][6] = 0.827048198103322;
   fWeightMatrix0to1[8][6] = 3.71489261914424;
   fWeightMatrix0to1[9][6] = 1.59585957523129;
   fWeightMatrix0to1[10][6] = -0.760752174856845;
   fWeightMatrix0to1[0][7] = -6.5522352738715;
   fWeightMatrix0to1[1][7] = -0.296174270838237;
   fWeightMatrix0to1[2][7] = -3.80085168682949;
   fWeightMatrix0to1[3][7] = 0.396856889364413;
   fWeightMatrix0to1[4][7] = 1.59323720510032;
   fWeightMatrix0to1[5][7] = 1.293903821898;
   fWeightMatrix0to1[6][7] = -2.81038884210922;
   fWeightMatrix0to1[7][7] = -1.14044451651102;
   fWeightMatrix0to1[8][7] = 0.62969498288364;
   fWeightMatrix0to1[9][7] = 0.123728304058521;
   fWeightMatrix0to1[10][7] = -0.78481576066021;
   fWeightMatrix0to1[0][8] = -5.94821672253;
   fWeightMatrix0to1[1][8] = 0.200767856270734;
   fWeightMatrix0to1[2][8] = -0.704882382631974;
   fWeightMatrix0to1[3][8] = 1.41250683689924;
   fWeightMatrix0to1[4][8] = 1.66734230381793;
   fWeightMatrix0to1[5][8] = -0.83108325474696;
   fWeightMatrix0to1[6][8] = -2.2444449108859;
   fWeightMatrix0to1[7][8] = 1.67095391192401;
   fWeightMatrix0to1[8][8] = -3.81604935867956;
   fWeightMatrix0to1[9][8] = -5.73065601395496;
   fWeightMatrix0to1[10][8] = -6.64638728315422;
   fWeightMatrix0to1[0][9] = -1.34358103566985;
   fWeightMatrix0to1[1][9] = 3.04522861244798;
   fWeightMatrix0to1[2][9] = -5.04759155459467;
   fWeightMatrix0to1[3][9] = 0.966959374782262;
   fWeightMatrix0to1[4][9] = 1.3697168446146;
   fWeightMatrix0to1[5][9] = -0.174439640020836;
   fWeightMatrix0to1[6][9] = 3.59828860984916;
   fWeightMatrix0to1[7][9] = -1.03648900455189;
   fWeightMatrix0to1[8][9] = 0.454973038633598;
   fWeightMatrix0to1[9][9] = -1.28927585021701;
   fWeightMatrix0to1[10][9] = -0.291573145676294;
   fWeightMatrix0to1[0][10] = -1.70424217394066;
   fWeightMatrix0to1[1][10] = -2.36893881939722;
   fWeightMatrix0to1[2][10] = 1.16906443875654;
   fWeightMatrix0to1[3][10] = 1.03206476767813;
   fWeightMatrix0to1[4][10] = -1.77513474537914;
   fWeightMatrix0to1[5][10] = 2.57333268416569;
   fWeightMatrix0to1[6][10] = 0.560930935438894;
   fWeightMatrix0to1[7][10] = -0.746306423136617;
   fWeightMatrix0to1[8][10] = -0.517086492799243;
   fWeightMatrix0to1[9][10] = -2.71894747405596;
   fWeightMatrix0to1[10][10] = -4.48929479893132;
   fWeightMatrix0to1[0][11] = 0.24095071061;
   fWeightMatrix0to1[1][11] = -3.04074456641946;
   fWeightMatrix0to1[2][11] = 2.40095761178163;
   fWeightMatrix0to1[3][11] = 1.32891584387914;
   fWeightMatrix0to1[4][11] = -0.395155751108779;
   fWeightMatrix0to1[5][11] = 0.338700543883893;
   fWeightMatrix0to1[6][11] = 0.273218310658807;
   fWeightMatrix0to1[7][11] = -1.59221014765093;
   fWeightMatrix0to1[8][11] = 0.190926436118415;
   fWeightMatrix0to1[9][11] = -1.15215423180485;
   fWeightMatrix0to1[10][11] = -4.58845088828836;
   // weight matrix from layer 1 to 2
   fWeightMatrix1to2[0][0] = 0.464801057177412;
   fWeightMatrix1to2[1][0] = -0.73270905433072;
   fWeightMatrix1to2[2][0] = 1.53750323079461;
   fWeightMatrix1to2[3][0] = -1.35751313178007;
   fWeightMatrix1to2[4][0] = 3.28250210857423;
   fWeightMatrix1to2[5][0] = -2.15182424138414;
   fWeightMatrix1to2[6][0] = -1.29604092387111;
   fWeightMatrix1to2[7][0] = 3.60283558022976;
   fWeightMatrix1to2[8][0] = 1.78969485044498;
   fWeightMatrix1to2[9][0] = -3.68003573797413;
   fWeightMatrix1to2[10][0] = -1.74163745762445;
   fWeightMatrix1to2[0][1] = 1.24876438888486;
   fWeightMatrix1to2[1][1] = -3.52863521435052;
   fWeightMatrix1to2[2][1] = 0.831499555660196;
   fWeightMatrix1to2[3][1] = 3.20333766407098;
   fWeightMatrix1to2[4][1] = -2.49533544574976;
   fWeightMatrix1to2[5][1] = 0.300149211574669;
   fWeightMatrix1to2[6][1] = -2.1636494509152;
   fWeightMatrix1to2[7][1] = -5.05743264607878;
   fWeightMatrix1to2[8][1] = -2.21441242669521;
   fWeightMatrix1to2[9][1] = -0.951953350545873;
   fWeightMatrix1to2[10][1] = -1.48497542402866;
   fWeightMatrix1to2[0][2] = -0.91569730152563;
   fWeightMatrix1to2[1][2] = 0.29580616123462;
   fWeightMatrix1to2[2][2] = 2.00279313864195;
   fWeightMatrix1to2[3][2] = -2.49679244737305;
   fWeightMatrix1to2[4][2] = -0.53000515220976;
   fWeightMatrix1to2[5][2] = -1.16539206666002;
   fWeightMatrix1to2[6][2] = 3.43612903628745;
   fWeightMatrix1to2[7][2] = 3.0393219243912;
   fWeightMatrix1to2[8][2] = 2.66403850551415;
   fWeightMatrix1to2[9][2] = -1.92494149395206;
   fWeightMatrix1to2[10][2] = 1.78235575531516;
   fWeightMatrix1to2[0][3] = -0.605703426845977;
   fWeightMatrix1to2[1][3] = -0.854232183134631;
   fWeightMatrix1to2[2][3] = 1.3106716158831;
   fWeightMatrix1to2[3][3] = -1.55094515881259;
   fWeightMatrix1to2[4][3] = -0.318239747442502;
   fWeightMatrix1to2[5][3] = 0.989071908686067;
   fWeightMatrix1to2[6][3] = 2.14119741814504;
   fWeightMatrix1to2[7][3] = 0.561468336661268;
   fWeightMatrix1to2[8][3] = 2.60857804271772;
   fWeightMatrix1to2[9][3] = 4.07222295138565;
   fWeightMatrix1to2[10][3] = -1.90512209981357;
   fWeightMatrix1to2[0][4] = 0.507251868639096;
   fWeightMatrix1to2[1][4] = -0.0234253376651696;
   fWeightMatrix1to2[2][4] = 0.641560643059344;
   fWeightMatrix1to2[3][4] = -1.92032698059512;
   fWeightMatrix1to2[4][4] = -1.06625692071428;
   fWeightMatrix1to2[5][4] = 1.26793382654564;
   fWeightMatrix1to2[6][4] = 2.50309601385826;
   fWeightMatrix1to2[7][4] = -0.860186429560448;
   fWeightMatrix1to2[8][4] = 0.193616088397922;
   fWeightMatrix1to2[9][4] = -0.407540717439914;
   fWeightMatrix1to2[10][4] = 0.320393732744625;
   fWeightMatrix1to2[0][5] = 0.86200512541002;
   fWeightMatrix1to2[1][5] = -0.0998881280500291;
   fWeightMatrix1to2[2][5] = 0.988869760104637;
   fWeightMatrix1to2[3][5] = -2.67578971405719;
   fWeightMatrix1to2[4][5] = 2.73338236420428;
   fWeightMatrix1to2[5][5] = 2.33163160148405;
   fWeightMatrix1to2[6][5] = 2.58335400255584;
   fWeightMatrix1to2[7][5] = -1.746875009188;
   fWeightMatrix1to2[8][5] = -1.16339573376406;
   fWeightMatrix1to2[9][5] = -4.43219260411716;
   fWeightMatrix1to2[10][5] = 0.0444399256295244;
   fWeightMatrix1to2[0][6] = 0.826909018050989;
   fWeightMatrix1to2[1][6] = -1.22047155366641;
   fWeightMatrix1to2[2][6] = 3.33626310936826;
   fWeightMatrix1to2[3][6] = -0.818133119338258;
   fWeightMatrix1to2[4][6] = -0.0748403938921302;
   fWeightMatrix1to2[5][6] = -2.78068884761601;
   fWeightMatrix1to2[6][6] = 1.6829541690918;
   fWeightMatrix1to2[7][6] = 3.60992526949197;
   fWeightMatrix1to2[8][6] = 0.46804698649678;
   fWeightMatrix1to2[9][6] = -1.0179839188506;
   fWeightMatrix1to2[10][6] = 1.88175952058524;
   fWeightMatrix1to2[0][7] = 1.09545391954615;
   fWeightMatrix1to2[1][7] = 0.438679924138356;
   fWeightMatrix1to2[2][7] = -0.156924807835916;
   fWeightMatrix1to2[3][7] = -1.80973920243458;
   fWeightMatrix1to2[4][7] = -0.949658345441055;
   fWeightMatrix1to2[5][7] = 1.83608583557404;
   fWeightMatrix1to2[6][7] = 1.41145073754569;
   fWeightMatrix1to2[7][7] = 0.850229744108727;
   fWeightMatrix1to2[8][7] = 0.371240733077454;
   fWeightMatrix1to2[9][7] = 2.00348075591737;
   fWeightMatrix1to2[10][7] = -1.66609429243407;
   fWeightMatrix1to2[0][8] = -1.88548077030045;
   fWeightMatrix1to2[1][8] = -0.542329359617743;
   fWeightMatrix1to2[2][8] = -3.23834617379243;
   fWeightMatrix1to2[3][8] = 3.19994543061026;
   fWeightMatrix1to2[4][8] = 1.02702380410183;
   fWeightMatrix1to2[5][8] = -1.98151562971981;
   fWeightMatrix1to2[6][8] = -2.08479989400481;
   fWeightMatrix1to2[7][8] = -3.00483138986667;
   fWeightMatrix1to2[8][8] = -3.06730105961918;
   fWeightMatrix1to2[9][8] = 1.21174161145242;
   fWeightMatrix1to2[10][8] = 0.392938610431583;
   fWeightMatrix1to2[0][9] = 0.792359815526092;
   fWeightMatrix1to2[1][9] = 0.717071654745835;
   fWeightMatrix1to2[2][9] = -4.29073443845359;
   fWeightMatrix1to2[3][9] = 1.72346338113981;
   fWeightMatrix1to2[4][9] = -3.14134163021534;
   fWeightMatrix1to2[5][9] = 1.03512939018202;
   fWeightMatrix1to2[6][9] = -0.379230396406237;
   fWeightMatrix1to2[7][9] = -2.19949214086101;
   fWeightMatrix1to2[8][9] = -2.27928465371194;
   fWeightMatrix1to2[9][9] = -0.507686333222408;
   fWeightMatrix1to2[10][9] = -0.445214396327963;
   fWeightMatrix1to2[0][10] = -3.0718751816341;
   fWeightMatrix1to2[1][10] = -1.37041209890688;
   fWeightMatrix1to2[2][10] = -4.53825187526293;
   fWeightMatrix1to2[3][10] = 1.57104013271221;
   fWeightMatrix1to2[4][10] = -1.78032779763195;
   fWeightMatrix1to2[5][10] = -2.04243188046081;
   fWeightMatrix1to2[6][10] = 0.463146609682922;
   fWeightMatrix1to2[7][10] = -5.50725624628333;
   fWeightMatrix1to2[8][10] = -2.32785114073255;
   fWeightMatrix1to2[9][10] = -1.92266112532845;
   fWeightMatrix1to2[10][10] = -0.583104636506032;
   fWeightMatrix1to2[0][11] = 2.01738205387343;
   fWeightMatrix1to2[1][11] = 0.997950162205062;
   fWeightMatrix1to2[2][11] = 0.192967435278335;
   fWeightMatrix1to2[3][11] = -0.961339205350162;
   fWeightMatrix1to2[4][11] = -1.70087762247692;
   fWeightMatrix1to2[5][11] = -0.154723722891492;
   fWeightMatrix1to2[6][11] = -2.14423888583465;
   fWeightMatrix1to2[7][11] = 2.07150243484893;
   fWeightMatrix1to2[8][11] = -0.849467284368575;
   fWeightMatrix1to2[9][11] = 1.55171465412602;
   fWeightMatrix1to2[10][11] = -0.965453366736447;
   // weight matrix from layer 2 to 3
   fWeightMatrix2to3[0][0] = -1.49251273104447;
   fWeightMatrix2to3[1][0] = -0.551995526441898;
   fWeightMatrix2to3[2][0] = -2.88215327068185;
   fWeightMatrix2to3[3][0] = 0.177927772415087;
   fWeightMatrix2to3[4][0] = -1.0534221543001;
   fWeightMatrix2to3[5][0] = -1.2542264515866;
   fWeightMatrix2to3[6][0] = -1.74867268908454;
   fWeightMatrix2to3[7][0] = 0.357502067475825;
   fWeightMatrix2to3[8][0] = 0.69290735641634;
   fWeightMatrix2to3[9][0] = -0.466486666278773;
   fWeightMatrix2to3[10][0] = -1.52971181196659;
   fWeightMatrix2to3[11][0] = -0.647610620638778;
   fWeightMatrix2to3[12][0] = -0.101864463543216;
   fWeightMatrix2to3[13][0] = 0.24800702660022;
   fWeightMatrix2to3[0][1] = 0.837000566610898;
   fWeightMatrix2to3[1][1] = -0.211818537424076;
   fWeightMatrix2to3[2][1] = -0.286666439215571;
   fWeightMatrix2to3[3][1] = -0.382102480912629;
   fWeightMatrix2to3[4][1] = -1.77220514568736;
   fWeightMatrix2to3[5][1] = -0.587670518212559;
   fWeightMatrix2to3[6][1] = -1.76249076236411;
   fWeightMatrix2to3[7][1] = -1.52247553348415;
   fWeightMatrix2to3[8][1] = -1.24189595471805;
   fWeightMatrix2to3[9][1] = 1.48297960301876;
   fWeightMatrix2to3[10][1] = -1.68497011273327;
   fWeightMatrix2to3[11][1] = 1.44055770488995;
   fWeightMatrix2to3[12][1] = -1.63857665505979;
   fWeightMatrix2to3[13][1] = 1.05072145012444;
   fWeightMatrix2to3[0][2] = -3.38787904082726;
   fWeightMatrix2to3[1][2] = 0.658707561044951;
   fWeightMatrix2to3[2][2] = -1.08090900665771;
   fWeightMatrix2to3[3][2] = -2.79779437153657;
   fWeightMatrix2to3[4][2] = -0.919825308979658;
   fWeightMatrix2to3[5][2] = 0.288894717385528;
   fWeightMatrix2to3[6][2] = -2.43524349072598;
   fWeightMatrix2to3[7][2] = -2.50228487986337;
   fWeightMatrix2to3[8][2] = -2.37646120613942;
   fWeightMatrix2to3[9][2] = -1.89338541056035;
   fWeightMatrix2to3[10][2] = 0.447606269291466;
   fWeightMatrix2to3[11][2] = -1.10166110623169;
   fWeightMatrix2to3[12][2] = -0.193915093250824;
   fWeightMatrix2to3[13][2] = -1.17047852126689;
   fWeightMatrix2to3[0][3] = 0.911183333181773;
   fWeightMatrix2to3[1][3] = -1.63609928059699;
   fWeightMatrix2to3[2][3] = -2.70008675038227;
   fWeightMatrix2to3[3][3] = -2.29480538419885;
   fWeightMatrix2to3[4][3] = -0.0193961878691545;
   fWeightMatrix2to3[5][3] = -1.32896112391915;
   fWeightMatrix2to3[6][3] = -1.15863553431055;
   fWeightMatrix2to3[7][3] = 1.93001152606041;
   fWeightMatrix2to3[8][3] = 0.656781496365491;
   fWeightMatrix2to3[9][3] = 0.00161449961177069;
   fWeightMatrix2to3[10][3] = 2.15078687310875;
   fWeightMatrix2to3[11][3] = -2.87206873502301;
   fWeightMatrix2to3[12][3] = 0.819073740655845;
   fWeightMatrix2to3[13][3] = 0.26506039707853;
   fWeightMatrix2to3[0][4] = -3.03297878550756;
   fWeightMatrix2to3[1][4] = -0.913445750162262;
   fWeightMatrix2to3[2][4] = 0.738418682998588;
   fWeightMatrix2to3[3][4] = -0.909480726124216;
   fWeightMatrix2to3[4][4] = -0.673582096231634;
   fWeightMatrix2to3[5][4] = 1.65475550208163;
   fWeightMatrix2to3[6][4] = 1.97700717460617;
   fWeightMatrix2to3[7][4] = 2.33108097639205;
   fWeightMatrix2to3[8][4] = -2.84468306241118;
   fWeightMatrix2to3[9][4] = 0.343659691953241;
   fWeightMatrix2to3[10][4] = -2.49122055261041;
   fWeightMatrix2to3[11][4] = 1.99257353435762;
   fWeightMatrix2to3[12][4] = -3.024293890435;
   fWeightMatrix2to3[13][4] = -2.06215446859771;
   fWeightMatrix2to3[0][5] = 0.53623795659277;
   fWeightMatrix2to3[1][5] = 1.39500513934863;
   fWeightMatrix2to3[2][5] = 2.11159262799802;
   fWeightMatrix2to3[3][5] = 0.777928155448599;
   fWeightMatrix2to3[4][5] = 0.201236483051406;
   fWeightMatrix2to3[5][5] = -0.178837434773396;
   fWeightMatrix2to3[6][5] = -0.928797997789701;
   fWeightMatrix2to3[7][5] = 0.947286513937342;
   fWeightMatrix2to3[8][5] = 2.91297412728578;
   fWeightMatrix2to3[9][5] = -1.7624471796077;
   fWeightMatrix2to3[10][5] = 0.563534451957877;
   fWeightMatrix2to3[11][5] = -1.61135324815583;
   fWeightMatrix2to3[12][5] = -0.353990464094917;
   fWeightMatrix2to3[13][5] = -0.0505449819583689;
   fWeightMatrix2to3[0][6] = -1.39974037837649;
   fWeightMatrix2to3[1][6] = -1.33862646042381;
   fWeightMatrix2to3[2][6] = 2.40101510163907;
   fWeightMatrix2to3[3][6] = 1.85059934239877;
   fWeightMatrix2to3[4][6] = -0.292078134719284;
   fWeightMatrix2to3[5][6] = -0.506301554091524;
   fWeightMatrix2to3[6][6] = -1.01073129033949;
   fWeightMatrix2to3[7][6] = -2.30263282569828;
   fWeightMatrix2to3[8][6] = -2.45449471059165;
   fWeightMatrix2to3[9][6] = 0.541180107236147;
   fWeightMatrix2to3[10][6] = -1.12000857347525;
   fWeightMatrix2to3[11][6] = -1.10618194227686;
   fWeightMatrix2to3[12][6] = -0.361182811033631;
   fWeightMatrix2to3[13][6] = -2.15190510714084;
   fWeightMatrix2to3[0][7] = -3.42132334843124;
   fWeightMatrix2to3[1][7] = -1.79855856898195;
   fWeightMatrix2to3[2][7] = 1.45045699055536;
   fWeightMatrix2to3[3][7] = -0.974742252899285;
   fWeightMatrix2to3[4][7] = -2.50199943299893;
   fWeightMatrix2to3[5][7] = -1.19161678506924;
   fWeightMatrix2to3[6][7] = -1.78727197517633;
   fWeightMatrix2to3[7][7] = -3.82754018774388;
   fWeightMatrix2to3[8][7] = 0.454787338940017;
   fWeightMatrix2to3[9][7] = -2.72607952731825;
   fWeightMatrix2to3[10][7] = -1.7475361635666;
   fWeightMatrix2to3[11][7] = 3.14063481639089;
   fWeightMatrix2to3[12][7] = -0.0429104654442098;
   fWeightMatrix2to3[13][7] = 0.212097938237549;
   fWeightMatrix2to3[0][8] = -1.50906752511026;
   fWeightMatrix2to3[1][8] = 1.25275424480707;
   fWeightMatrix2to3[2][8] = 3.72015020538564;
   fWeightMatrix2to3[3][8] = 1.23043453612029;
   fWeightMatrix2to3[4][8] = -1.35961000926256;
   fWeightMatrix2to3[5][8] = -1.09348797313873;
   fWeightMatrix2to3[6][8] = -2.48335101231103;
   fWeightMatrix2to3[7][8] = -0.248056651887513;
   fWeightMatrix2to3[8][8] = 0.816210027383286;
   fWeightMatrix2to3[9][8] = -1.03843402616818;
   fWeightMatrix2to3[10][8] = 0.46251018798421;
   fWeightMatrix2to3[11][8] = 1.6955916459374;
   fWeightMatrix2to3[12][8] = 1.11373172419408;
   fWeightMatrix2to3[13][8] = -1.37478759743346;
   fWeightMatrix2to3[0][9] = 3.06084095841854;
   fWeightMatrix2to3[1][9] = 0.871895005104997;
   fWeightMatrix2to3[2][9] = -3.77449447907323;
   fWeightMatrix2to3[3][9] = -0.760136410928782;
   fWeightMatrix2to3[4][9] = -1.27547555079682;
   fWeightMatrix2to3[5][9] = 1.00619463481076;
   fWeightMatrix2to3[6][9] = 0.63956720812716;
   fWeightMatrix2to3[7][9] = 1.17848832429231;
   fWeightMatrix2to3[8][9] = 2.36716224113383;
   fWeightMatrix2to3[9][9] = -0.522025154315713;
   fWeightMatrix2to3[10][9] = 1.76449656833265;
   fWeightMatrix2to3[11][9] = -0.488058182727163;
   fWeightMatrix2to3[12][9] = 0.975637988164458;
   fWeightMatrix2to3[13][9] = -1.34723015426903;
   fWeightMatrix2to3[0][10] = 0.773791151552894;
   fWeightMatrix2to3[1][10] = -1.82733406100259;
   fWeightMatrix2to3[2][10] = 0.305832905621521;
   fWeightMatrix2to3[3][10] = 1.31836502837865;
   fWeightMatrix2to3[4][10] = -0.727763187262257;
   fWeightMatrix2to3[5][10] = -0.861205663030492;
   fWeightMatrix2to3[6][10] = 0.0724682164917887;
   fWeightMatrix2to3[7][10] = -1.85165756113712;
   fWeightMatrix2to3[8][10] = 0.406275520986263;
   fWeightMatrix2to3[9][10] = -2.14330208098603;
   fWeightMatrix2to3[10][10] = 0.170953905239348;
   fWeightMatrix2to3[11][10] = -0.91342061717944;
   fWeightMatrix2to3[12][10] = 2.0583777522781;
   fWeightMatrix2to3[13][10] = 0.965058858283444;
   fWeightMatrix2to3[0][11] = 1.1771429552516;
   fWeightMatrix2to3[1][11] = -0.247563585264987;
   fWeightMatrix2to3[2][11] = -2.2241982158802;
   fWeightMatrix2to3[3][11] = -0.741492549214082;
   fWeightMatrix2to3[4][11] = -0.157460300923263;
   fWeightMatrix2to3[5][11] = -1.96174326712716;
   fWeightMatrix2to3[6][11] = -0.65226089810507;
   fWeightMatrix2to3[7][11] = -0.0452772824366744;
   fWeightMatrix2to3[8][11] = -1.66449033276342;
   fWeightMatrix2to3[9][11] = -1.95276345978742;
   fWeightMatrix2to3[10][11] = -2.00103081464179;
   fWeightMatrix2to3[11][11] = -0.563888167683429;
   fWeightMatrix2to3[12][11] = -1.33277203752302;
   fWeightMatrix2to3[13][11] = -2.87011710738792;
   // weight matrix from layer 3 to 4
   fWeightMatrix3to4[0][0] = -3.80959822057568;
   fWeightMatrix3to4[0][1] = -1.23944239426384;
   fWeightMatrix3to4[0][2] = 2.88980302198977;
   fWeightMatrix3to4[0][3] = 0.930762456096086;
   fWeightMatrix3to4[0][4] = -0.9789951002252;
   fWeightMatrix3to4[0][5] = -0.90016141829114;
   fWeightMatrix3to4[0][6] = -2.75156495904018;
   fWeightMatrix3to4[0][7] = -1.62549082087419;
   fWeightMatrix3to4[0][8] = -2.80634736175596;
   fWeightMatrix3to4[0][9] = -1.67572614973698;
   fWeightMatrix3to4[0][10] = -1.87693090530643;
   fWeightMatrix3to4[0][11] = 0.833924858032517;
   fWeightMatrix3to4[0][12] = -1.4369857563057;
   fWeightMatrix3to4[0][13] = 0.729088634777848;
   fWeightMatrix3to4[0][14] = 0.266341783331142;
}

inline double ReadMLP_ANN_N3_NC200::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   if (inputValues.size() != (unsigned int)fLayerSize[0]-1) {
      std::cout << "Input vector needs to be of size " << fLayerSize[0]-1 << std::endl;
      return 0;
   }

   for (int l=0; l<fLayers; l++)
      for (int i=0; i<fLayerSize[l]; i++) fWeights[l][i]=0;

   for (int l=0; l<fLayers-1; l++)
      fWeights[l][fLayerSize[l]-1]=1;

   for (int i=0; i<fLayerSize[0]-1; i++)
      fWeights[0][i]=inputValues[i];

   // layer 0 to 1
   for (int o=0; o<fLayerSize[1]-1; o++) {
      for (int i=0; i<fLayerSize[0]; i++) {
         double inputVal = fWeightMatrix0to1[o][i] * fWeights[0][i];
         fWeights[1][o] += inputVal;
      }
      fWeights[1][o] = ActivationFnc(fWeights[1][o]);
   }
   // layer 1 to 2
   for (int o=0; o<fLayerSize[2]-1; o++) {
      for (int i=0; i<fLayerSize[1]; i++) {
         double inputVal = fWeightMatrix1to2[o][i] * fWeights[1][i];
         fWeights[2][o] += inputVal;
      }
      fWeights[2][o] = ActivationFnc(fWeights[2][o]);
   }
   // layer 2 to 3
   for (int o=0; o<fLayerSize[3]-1; o++) {
      for (int i=0; i<fLayerSize[2]; i++) {
         double inputVal = fWeightMatrix2to3[o][i] * fWeights[2][i];
         fWeights[3][o] += inputVal;
      }
      fWeights[3][o] = ActivationFnc(fWeights[3][o]);
   }
   // layer 3 to 4
   for (int o=0; o<fLayerSize[4]; o++) {
      for (int i=0; i<fLayerSize[3]; i++) {
         double inputVal = fWeightMatrix3to4[o][i] * fWeights[3][i];
         fWeights[4][o] += inputVal;
      }
      fWeights[4][o] = OutputActivationFnc(fWeights[4][o]);
   }

   return fWeights[4][0];
}

double ReadMLP_ANN_N3_NC200::ActivationFnc(double x) const {
   // sigmoid
   return 1.0/(1.0+exp(-x));
}
double ReadMLP_ANN_N3_NC200::OutputActivationFnc(double x) const {
   // sigmoid
   return 1.0/(1.0+exp(-x));
}
   
// Clean up
inline void ReadMLP_ANN_N3_NC200::Clear() 
{
   // clean up the arrays
   for (int lIdx = 0; lIdx < 5; lIdx++) {
      delete[] fWeights[lIdx];
   }
}
   inline double ReadMLP_ANN_N3_NC200::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            iV.reserve(inputValues.size());
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
         else {
            std::vector<double> iV;
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(*varIt);
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
      }

      return retval;
   }

//_______________________________________________________________________
inline void ReadMLP_ANN_N3_NC200::InitTransform_1()
{
   // Normalization transformation, initialisation
   fMin_1[0][0] = 110.048698425;
   fMax_1[0][0] = 1277.92980957;
   fMin_1[1][0] = 110.057556152;
   fMax_1[1][0] = 1572.76037598;
   fMin_1[2][0] = 110.048698425;
   fMax_1[2][0] = 1572.76037598;
   fMin_1[0][1] = 5.00075817108;
   fMax_1[0][1] = 29.9497737885;
   fMin_1[1][1] = 5.00135278702;
   fMax_1[1][1] = 29.9984378815;
   fMin_1[2][1] = 5.00075817108;
   fMax_1[2][1] = 29.9984378815;
   fMin_1[0][2] = -1;
   fMax_1[0][2] = 1;
   fMin_1[1][2] = -1;
   fMax_1[1][2] = 1;
   fMin_1[2][2] = -1;
   fMax_1[2][2] = 1;
   fMin_1[0][3] = -2.4711689949;
   fMax_1[0][3] = 2.37911462784;
   fMin_1[1][3] = -2.48411560059;
   fMax_1[1][3] = 2.49880051613;
   fMin_1[2][3] = -2.48411560059;
   fMax_1[2][3] = 2.49880051613;
   fMin_1[0][4] = 280.2293396;
   fMax_1[0][4] = 1251.49438477;
   fMin_1[1][4] = 280.020294189;
   fMax_1[1][4] = 1289.47937012;
   fMin_1[2][4] = 280.020294189;
   fMax_1[2][4] = 1289.47937012;
   fMin_1[0][5] = 0.0557334087789;
   fMax_1[0][5] = 300.527191162;
   fMin_1[1][5] = 0.000537815736607;
   fMax_1[1][5] = 215.792510986;
   fMin_1[2][5] = 0.000537815736607;
   fMax_1[2][5] = 300.527191162;
   fMin_1[0][6] = 117.352531433;
   fMax_1[0][6] = 2347.48510742;
   fMin_1[1][6] = 112.003395081;
   fMax_1[1][6] = 4504.87304688;
   fMin_1[2][6] = 112.003395081;
   fMax_1[2][6] = 4504.87304688;
   fMin_1[0][7] = 0;
   fMax_1[0][7] = 5;
   fMin_1[1][7] = 0;
   fMax_1[1][7] = 6;
   fMin_1[2][7] = 0;
   fMax_1[2][7] = 6;
   fMin_1[0][8] = 1;
   fMax_1[0][8] = 11;
   fMin_1[1][8] = 1;
   fMax_1[1][8] = 14;
   fMin_1[2][8] = 1;
   fMax_1[2][8] = 14;
   fMin_1[0][9] = 20.0573444366;
   fMax_1[0][9] = 1057.04370117;
   fMin_1[1][9] = -999;
   fMax_1[1][9] = 1378.42883301;
   fMin_1[2][9] = -999;
   fMax_1[2][9] = 1378.42883301;
   fMin_1[0][10] = 6.27087429166e-05;
   fMax_1[0][10] = 4.95768356323;
   fMin_1[1][10] = -999;
   fMax_1[1][10] = 5.38026332855;
   fMin_1[2][10] = -999;
   fMax_1[2][10] = 5.38026332855;
}

//_______________________________________________________________________
inline void ReadMLP_ANN_N3_NC200::Transform_1( std::vector<double>& iv, int cls) const
{
   // Normalization transformation
   if (cls < 0 || cls > 2) {
   if (2 > 1 ) cls = 2;
      else cls = 2;
   }
   const int nVar = 11;

   // get indices of used variables

   // define the indices of the variables which are transformed by this transformation
   static std::vector<int> indicesGet;
   static std::vector<int> indicesPut;

   if ( indicesGet.empty() ) { 
      indicesGet.reserve(fNvars);
      indicesGet.push_back( 0);
      indicesGet.push_back( 1);
      indicesGet.push_back( 2);
      indicesGet.push_back( 3);
      indicesGet.push_back( 4);
      indicesGet.push_back( 5);
      indicesGet.push_back( 6);
      indicesGet.push_back( 7);
      indicesGet.push_back( 8);
      indicesGet.push_back( 9);
      indicesGet.push_back( 10);
   } 
   if ( indicesPut.empty() ) { 
      indicesPut.reserve(fNvars);
      indicesPut.push_back( 0);
      indicesPut.push_back( 1);
      indicesPut.push_back( 2);
      indicesPut.push_back( 3);
      indicesPut.push_back( 4);
      indicesPut.push_back( 5);
      indicesPut.push_back( 6);
      indicesPut.push_back( 7);
      indicesPut.push_back( 8);
      indicesPut.push_back( 9);
      indicesPut.push_back( 10);
   } 

   static std::vector<double> dv;
   dv.resize(nVar);
   for (int ivar=0; ivar<nVar; ivar++) dv[ivar] = iv[indicesGet.at(ivar)];
   for (int ivar=0;ivar<11;ivar++) {
      double offset = fMin_1[cls][ivar];
      double scale  = 1.0/(fMax_1[cls][ivar]-fMin_1[cls][ivar]);
      iv[indicesPut.at(ivar)] = (dv[ivar]-offset)*scale * 2 - 1;
   }
}

//_______________________________________________________________________
inline void ReadMLP_ANN_N3_NC200::InitTransform()
{
   InitTransform_1();
}

//_______________________________________________________________________
inline void ReadMLP_ANN_N3_NC200::Transform( std::vector<double>& iv, int sigOrBgd ) const
{
   Transform_1( iv, sigOrBgd );
}
