// Class: ReadMLP_ANN_N0_NC700
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : MLP::MLP_ANN_N0_NC700
TMVA Release   : 4.2.1         [262657]
ROOT Release   : 6.06/01       [394753]
Creator        : brucms16
Date           : Wed Sep  7 01:33:46 2016
Host           : Linux vocms0315.cern.ch 2.6.32-573.26.1.el6.x86_64 #1 SMP Wed May 4 09:23:05 CEST 2016 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /home/t3cms/brucms16/CMSSW_8_0_14/src/UserCode/SkeletonAnalysis/macros
Training events: 15056
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
NCycles: "700" [Number of training cycles]
HiddenLayers: "N,N,N+0" [Specification of hidden layer architecture]
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
VarTransform: "Norm" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
H: "False" [Print method-specific help message]
LearningRate: "9.000000e-02" [ANN learning rate parameter]
DecayRate: "1.000000e-02" [Decay rate for learning parameter]
# Default:
NeuronType: "sigmoid" [Neuron activation function type]
RandomSeed: "1" [Random seed for initial synapse weights (0 means unique seed for each run; default value '1')]
EstimatorType: "CE" [MSE (Mean Square Estimator) for Gaussian Likelihood or CE(Cross-Entropy) for Bernoulli Likelihood]
NeuronInputType: "sum" [Neuron input function type]
VerbosityLevel: "Default" [Verbosity level]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
TrainingMethod: "BP" [Train with Back-Propagation (BP), BFGS Algorithm (BFGS), or Genetic Algorithm (GA - slower and worse)]
TestRate: "10" [Test for overtraining performed at each #th epochs]
EpochMonitoring: "False" [Provide epoch-wise monitoring plots according to TestRate (caution: causes big ROOT output file!)]
Sampling: "1.000000e+00" [Only 'Sampling' (randomly selected) events are trained each epoch]
SamplingEpoch: "1.000000e+00" [Sampling is used for the first 'SamplingEpoch' epochs, afterwards, all events are taken for training]
SamplingImportance: "1.000000e+00" [ The sampling weights of events in epochs which successful (worse estimator than before) are multiplied with SamplingImportance, else they are divided.]
SamplingTraining: "True" [The training sample is sampled]
SamplingTesting: "False" [The testing sample is sampled]
ResetStep: "50" [How often BFGS should reset history]
Tau: "3.000000e+00" [LineSearch "size step"]
BPMode: "sequential" [Back-propagation learning mode: sequential or batch]
BatchSize: "-1" [Batch size: number of events/batch, only set if in Batch Mode, -1 for BatchSize=number_of_events]
ConvergenceImprove: "1.000000e-30" [Minimum improvement which counts as improvement (<0 means automatic convergence check is turned off)]
ConvergenceTests: "-1" [Number of steps (without improvement) required for convergence (<0 means automatic convergence check is turned off)]
UseRegulator: "False" [Use regulator to avoid over-training]
UpdateLimit: "10000" [Maximum times of regulator update]
CalculateErrors: "False" [Calculates inverse Hessian matrix at the end of the training to be able to calculate the uncertainties of an MVA value]
WeightRange: "1.000000e+00" [Take the events for the estimator calculations from small deviations from the desired value to large deviations only over the weight range]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 11
Jet1Pt                        Jet1Pt                        Jet1Pt                        Jet1Pt                                                          'F'    [110.048698425,1572.76037598]
LepPt                         LepPt                         LepPt                         LepPt                                                           'F'    [5.00075817108,29.9984378815]
LepChg                        LepChg                        LepChg                        LepChg                                                          'F'    [-1,1]
LepEta                        LepEta                        LepEta                        LepEta                                                          'F'    [-2.48411560059,2.49880051613]
Met                           Met                           Met                           Met                                                             'F'    [280.020294189,1289.47937012]
mt                            mt                            mt                            mt                                                              'F'    [0.000537815736607,300.527191162]
HT20                          HT20                          HT20                          HT20                                                            'F'    [112.003395081,4504.87304688]
NbLoose30                     NbLoose30                     NbLoose30                     NbLoose30                                                       'F'    [0,6]
Njet                          Njet                          Njet                          Njet                                                            'F'    [1,14]
JetHBpt                       JetHBpt                       JetHBpt                       JetHBpt                                                         'F'    [-999,1378.42883301]
DrJetHBLep                    DrJetHBLep                    DrJetHBLep                    DrJetHBLep                                                      'F'    [-999,5.38026332855]
NSpec 0


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadMLP_ANN_N0_NC700 : public IClassifierReader {

 public:

   // constructor
   ReadMLP_ANN_N0_NC700( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadMLP_ANN_N0_NC700" ),
        fNvars( 11 ),
        fIsNormalised( false )
   {      
      // the training input variables
      const char* inputVars[] = { "Jet1Pt", "LepPt", "LepChg", "LepEta", "Met", "mt", "HT20", "NbLoose30", "Njet", "JetHBpt", "DrJetHBLep" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = -1;
      fVmax[0] = 1;
      fVmin[1] = -1;
      fVmax[1] = 0.99999988079071;
      fVmin[2] = -1;
      fVmax[2] = 1;
      fVmin[3] = -1;
      fVmax[3] = 1;
      fVmin[4] = -1;
      fVmax[4] = 1;
      fVmin[5] = -1;
      fVmax[5] = 1;
      fVmin[6] = -1;
      fVmax[6] = 1;
      fVmin[7] = -1;
      fVmax[7] = 1;
      fVmin[8] = -1;
      fVmax[8] = 1;
      fVmin[9] = -1;
      fVmax[9] = 1;
      fVmin[10] = -1;
      fVmax[10] = 1;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';
      fType[4] = 'F';
      fType[5] = 'F';
      fType[6] = 'F';
      fType[7] = 'F';
      fType[8] = 'F';
      fType[9] = 'F';
      fType[10] = 'F';

      // initialize constants
      Initialize();

      // initialize transformation
      InitTransform();
   }

   // destructor
   virtual ~ReadMLP_ANN_N0_NC700() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // input variable transformation

   double fMin_1[3][11];
   double fMax_1[3][11];
   void InitTransform_1();
   void Transform_1( std::vector<double> & iv, int sigOrBgd ) const;
   void InitTransform();
   void Transform( std::vector<double> & iv, int sigOrBgd ) const;

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[11];
   double fVmax[11];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[11];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)

   double ActivationFnc(double x) const;
   double OutputActivationFnc(double x) const;

   int fLayers;
   int fLayerSize[5];
   double fWeightMatrix0to1[12][12];   // weight matrix from layer 0 to 1
   double fWeightMatrix1to2[12][12];   // weight matrix from layer 1 to 2
   double fWeightMatrix2to3[12][12];   // weight matrix from layer 2 to 3
   double fWeightMatrix3to4[1][12];   // weight matrix from layer 3 to 4

   double * fWeights[5];
};

inline void ReadMLP_ANN_N0_NC700::Initialize()
{
   // build network structure
   fLayers = 5;
   fLayerSize[0] = 12; fWeights[0] = new double[12]; 
   fLayerSize[1] = 12; fWeights[1] = new double[12]; 
   fLayerSize[2] = 12; fWeights[2] = new double[12]; 
   fLayerSize[3] = 12; fWeights[3] = new double[12]; 
   fLayerSize[4] = 1; fWeights[4] = new double[1]; 
   // weight matrix from layer 0 to 1
   fWeightMatrix0to1[0][0] = 0.900538892509604;
   fWeightMatrix0to1[1][0] = 2.0548612197372;
   fWeightMatrix0to1[2][0] = 4.13627681940665;
   fWeightMatrix0to1[3][0] = -0.0926787612815141;
   fWeightMatrix0to1[4][0] = -0.218339757587024;
   fWeightMatrix0to1[5][0] = -1.65704482846866;
   fWeightMatrix0to1[6][0] = -3.28483622622424;
   fWeightMatrix0to1[7][0] = 1.95879943221351;
   fWeightMatrix0to1[8][0] = 0.513381911577529;
   fWeightMatrix0to1[9][0] = 0.164880476708879;
   fWeightMatrix0to1[10][0] = -1.74864165183438;
   fWeightMatrix0to1[0][1] = 1.64771189413062;
   fWeightMatrix0to1[1][1] = -2.15709081593229;
   fWeightMatrix0to1[2][1] = 0.0405850029750296;
   fWeightMatrix0to1[3][1] = 0.251431793790948;
   fWeightMatrix0to1[4][1] = 1.77185493234602;
   fWeightMatrix0to1[5][1] = -0.791368853413864;
   fWeightMatrix0to1[6][1] = 5.55922511506728;
   fWeightMatrix0to1[7][1] = 0.171986718673432;
   fWeightMatrix0to1[8][1] = 2.66682680478113;
   fWeightMatrix0to1[9][1] = 2.88439290649416;
   fWeightMatrix0to1[10][1] = -2.11851414291994;
   fWeightMatrix0to1[0][2] = 0.936886906343541;
   fWeightMatrix0to1[1][2] = -1.0597050225878;
   fWeightMatrix0to1[2][2] = -0.499246681050902;
   fWeightMatrix0to1[3][2] = 0.26877523291927;
   fWeightMatrix0to1[4][2] = -1.14562123862233;
   fWeightMatrix0to1[5][2] = -3.08279185267995;
   fWeightMatrix0to1[6][2] = -0.576807794701507;
   fWeightMatrix0to1[7][2] = -0.18903211852985;
   fWeightMatrix0to1[8][2] = -0.340853197484414;
   fWeightMatrix0to1[9][2] = 1.84932124591304;
   fWeightMatrix0to1[10][2] = 0.801503653839206;
   fWeightMatrix0to1[0][3] = -1.32007323474084;
   fWeightMatrix0to1[1][3] = 2.66051651752141;
   fWeightMatrix0to1[2][3] = 0.40439639738082;
   fWeightMatrix0to1[3][3] = 0.143947385754694;
   fWeightMatrix0to1[4][3] = 8.53640840455023;
   fWeightMatrix0to1[5][3] = -0.1316102615584;
   fWeightMatrix0to1[6][3] = -1.01863205499719;
   fWeightMatrix0to1[7][3] = 0.694139513593487;
   fWeightMatrix0to1[8][3] = -2.05363928597668;
   fWeightMatrix0to1[9][3] = -0.319516877268963;
   fWeightMatrix0to1[10][3] = 0.280258378875746;
   fWeightMatrix0to1[0][4] = 5.11527172839235;
   fWeightMatrix0to1[1][4] = -0.207106566216712;
   fWeightMatrix0to1[2][4] = 4.40813800501552;
   fWeightMatrix0to1[3][4] = 1.9390445425579;
   fWeightMatrix0to1[4][4] = 0.0518563781379074;
   fWeightMatrix0to1[5][4] = -0.262423016888904;
   fWeightMatrix0to1[6][4] = -1.0763596707486;
   fWeightMatrix0to1[7][4] = 1.74593165862111;
   fWeightMatrix0to1[8][4] = -8.95308105936036;
   fWeightMatrix0to1[9][4] = 0.418835583981039;
   fWeightMatrix0to1[10][4] = -7.94482100186836;
   fWeightMatrix0to1[0][5] = -1.37262824717225;
   fWeightMatrix0to1[1][5] = -2.31492960123585;
   fWeightMatrix0to1[2][5] = -11.599191412523;
   fWeightMatrix0to1[3][5] = 17.5944177753132;
   fWeightMatrix0to1[4][5] = 0.668012025411952;
   fWeightMatrix0to1[5][5] = -2.66636307948684;
   fWeightMatrix0to1[6][5] = 0.872493554586384;
   fWeightMatrix0to1[7][5] = -0.466153885098471;
   fWeightMatrix0to1[8][5] = -1.58510908674914;
   fWeightMatrix0to1[9][5] = 2.99772269294513;
   fWeightMatrix0to1[10][5] = -2.74446355822674;
   fWeightMatrix0to1[0][6] = -1.14950993385168;
   fWeightMatrix0to1[1][6] = -1.44496043005668;
   fWeightMatrix0to1[2][6] = 0.945454024959058;
   fWeightMatrix0to1[3][6] = -4.40182227544339;
   fWeightMatrix0to1[4][6] = 0.697122518214656;
   fWeightMatrix0to1[5][6] = -1.55051801516437;
   fWeightMatrix0to1[6][6] = 1.61214865432753;
   fWeightMatrix0to1[7][6] = 1.00309749801677;
   fWeightMatrix0to1[8][6] = 6.42263191467007;
   fWeightMatrix0to1[9][6] = 0.796954554804211;
   fWeightMatrix0to1[10][6] = 2.38462654327242;
   fWeightMatrix0to1[0][7] = -6.3793706768774;
   fWeightMatrix0to1[1][7] = -0.928435760497086;
   fWeightMatrix0to1[2][7] = 1.09693642408779;
   fWeightMatrix0to1[3][7] = 0.749552429159119;
   fWeightMatrix0to1[4][7] = 0.0413016418498643;
   fWeightMatrix0to1[5][7] = 2.66222299593111;
   fWeightMatrix0to1[6][7] = -0.578503678045071;
   fWeightMatrix0to1[7][7] = -1.03548854661054;
   fWeightMatrix0to1[8][7] = 2.01549516038332;
   fWeightMatrix0to1[9][7] = 0.86193984238401;
   fWeightMatrix0to1[10][7] = 3.05954662295953;
   fWeightMatrix0to1[0][8] = -7.79610113631632;
   fWeightMatrix0to1[1][8] = -2.20350513533821;
   fWeightMatrix0to1[2][8] = 0.679655938186632;
   fWeightMatrix0to1[3][8] = -0.746245693251941;
   fWeightMatrix0to1[4][8] = 0.432881847372289;
   fWeightMatrix0to1[5][8] = -2.40380032837523;
   fWeightMatrix0to1[6][8] = -2.05073921441434;
   fWeightMatrix0to1[7][8] = 1.47015654369428;
   fWeightMatrix0to1[8][8] = 1.6592631216289;
   fWeightMatrix0to1[9][8] = -8.7270147036375;
   fWeightMatrix0to1[10][8] = -5.12786301370701;
   fWeightMatrix0to1[0][9] = -1.08682381836025;
   fWeightMatrix0to1[1][9] = -2.65534341500983;
   fWeightMatrix0to1[2][9] = -2.4257399925983;
   fWeightMatrix0to1[3][9] = -2.44667542381678;
   fWeightMatrix0to1[4][9] = -0.307336093434859;
   fWeightMatrix0to1[5][9] = -2.57896290223373;
   fWeightMatrix0to1[6][9] = -2.44902888302952;
   fWeightMatrix0to1[7][9] = -1.04220058840114;
   fWeightMatrix0to1[8][9] = 2.59210224689056;
   fWeightMatrix0to1[9][9] = -1.33685987267841;
   fWeightMatrix0to1[10][9] = 1.72205399247394;
   fWeightMatrix0to1[0][10] = -2.28529695649401;
   fWeightMatrix0to1[1][10] = 0.42022330481529;
   fWeightMatrix0to1[2][10] = 0.992413719792081;
   fWeightMatrix0to1[3][10] = 1.98375012914865;
   fWeightMatrix0to1[4][10] = -1.79480227966107;
   fWeightMatrix0to1[5][10] = 0.855218319470567;
   fWeightMatrix0to1[6][10] = -0.269907030077765;
   fWeightMatrix0to1[7][10] = -0.960120637617237;
   fWeightMatrix0to1[8][10] = -1.61226502678796;
   fWeightMatrix0to1[9][10] = -2.20029364532742;
   fWeightMatrix0to1[10][10] = -3.87345122402076;
   fWeightMatrix0to1[0][11] = -0.324502348989995;
   fWeightMatrix0to1[1][11] = -0.192879501103925;
   fWeightMatrix0to1[2][11] = 1.89913267134257;
   fWeightMatrix0to1[3][11] = 2.3202616218;
   fWeightMatrix0to1[4][11] = -0.400426222598574;
   fWeightMatrix0to1[5][11] = -1.13492279212219;
   fWeightMatrix0to1[6][11] = -0.245504593625907;
   fWeightMatrix0to1[7][11] = -1.81885352556891;
   fWeightMatrix0to1[8][11] = -0.959232013840806;
   fWeightMatrix0to1[9][11] = -0.925808871636973;
   fWeightMatrix0to1[10][11] = -4.20393553782723;
   // weight matrix from layer 1 to 2
   fWeightMatrix1to2[0][0] = 0.391758060828182;
   fWeightMatrix1to2[1][0] = -1.19652136747764;
   fWeightMatrix1to2[2][0] = 1.66901917956119;
   fWeightMatrix1to2[3][0] = 1.17870578087075;
   fWeightMatrix1to2[4][0] = 4.1569736750447;
   fWeightMatrix1to2[5][0] = -1.96279419460134;
   fWeightMatrix1to2[6][0] = -0.674082679963729;
   fWeightMatrix1to2[7][0] = 5.03352263934596;
   fWeightMatrix1to2[8][0] = 3.32402237265036;
   fWeightMatrix1to2[9][0] = -0.121056978199179;
   fWeightMatrix1to2[10][0] = -2.70909140582187;
   fWeightMatrix1to2[0][1] = -0.446235030015859;
   fWeightMatrix1to2[1][1] = -1.39664509747451;
   fWeightMatrix1to2[2][1] = 2.82583618255565;
   fWeightMatrix1to2[3][1] = 2.28810009744395;
   fWeightMatrix1to2[4][1] = -0.654245918693095;
   fWeightMatrix1to2[5][1] = -0.642616921265399;
   fWeightMatrix1to2[6][1] = -1.22659755080237;
   fWeightMatrix1to2[7][1] = -2.58655760601028;
   fWeightMatrix1to2[8][1] = 0.818907956414311;
   fWeightMatrix1to2[9][1] = 3.3470253295991;
   fWeightMatrix1to2[10][1] = -1.09171756784485;
   fWeightMatrix1to2[0][2] = 0.206706445196832;
   fWeightMatrix1to2[1][2] = 0.125747194096908;
   fWeightMatrix1to2[2][2] = 1.46109880554512;
   fWeightMatrix1to2[3][2] = -1.93192490969815;
   fWeightMatrix1to2[4][2] = 3.09349977467188;
   fWeightMatrix1to2[5][2] = -1.44936137021518;
   fWeightMatrix1to2[6][2] = 0.76921148650615;
   fWeightMatrix1to2[7][2] = -0.252416259864462;
   fWeightMatrix1to2[8][2] = 4.59295522115392;
   fWeightMatrix1to2[9][2] = 3.44717076873507;
   fWeightMatrix1to2[10][2] = -2.12237068138886;
   fWeightMatrix1to2[0][3] = -1.32001476561362;
   fWeightMatrix1to2[1][3] = -0.167432145971754;
   fWeightMatrix1to2[2][3] = 5.83129044087622;
   fWeightMatrix1to2[3][3] = -3.24905445402638;
   fWeightMatrix1to2[4][3] = -1.08431080083925;
   fWeightMatrix1to2[5][3] = 1.46516388625986;
   fWeightMatrix1to2[6][3] = 2.24722625774384;
   fWeightMatrix1to2[7][3] = 1.29017304406279;
   fWeightMatrix1to2[8][3] = 2.94221658805386;
   fWeightMatrix1to2[9][3] = 4.72135093880609;
   fWeightMatrix1to2[10][3] = -1.81505413437103;
   fWeightMatrix1to2[0][4] = -0.370799291393594;
   fWeightMatrix1to2[1][4] = 0.157146562782639;
   fWeightMatrix1to2[2][4] = 0.289401213614591;
   fWeightMatrix1to2[3][4] = -1.96891666680826;
   fWeightMatrix1to2[4][4] = -3.73174088235948;
   fWeightMatrix1to2[5][4] = 1.05020005563969;
   fWeightMatrix1to2[6][4] = 2.60697458420994;
   fWeightMatrix1to2[7][4] = -4.34132391676816;
   fWeightMatrix1to2[8][4] = -0.948230955721161;
   fWeightMatrix1to2[9][4] = -0.745032856553221;
   fWeightMatrix1to2[10][4] = 2.92795191284971;
   fWeightMatrix1to2[0][5] = 2.4068369983547;
   fWeightMatrix1to2[1][5] = -0.48417722351357;
   fWeightMatrix1to2[2][5] = 0.0198445915769155;
   fWeightMatrix1to2[3][5] = -2.60758357276412;
   fWeightMatrix1to2[4][5] = 0.67435478115468;
   fWeightMatrix1to2[5][5] = 1.3524133768184;
   fWeightMatrix1to2[6][5] = -0.382033621717656;
   fWeightMatrix1to2[7][5] = 0.719136366697037;
   fWeightMatrix1to2[8][5] = -0.283124863678222;
   fWeightMatrix1to2[9][5] = -2.65337920498833;
   fWeightMatrix1to2[10][5] = 1.3069110131209;
   fWeightMatrix1to2[0][6] = 1.87724904346704;
   fWeightMatrix1to2[1][6] = -1.92969514891371;
   fWeightMatrix1to2[2][6] = -1.9185550402564;
   fWeightMatrix1to2[3][6] = 1.87340028009458;
   fWeightMatrix1to2[4][6] = 0.82630917259592;
   fWeightMatrix1to2[5][6] = -1.88678021079754;
   fWeightMatrix1to2[6][6] = 1.07519568974375;
   fWeightMatrix1to2[7][6] = 1.1685078788816;
   fWeightMatrix1to2[8][6] = -2.60053278262956;
   fWeightMatrix1to2[9][6] = -1.58301033411945;
   fWeightMatrix1to2[10][6] = 3.78873799132907;
   fWeightMatrix1to2[0][7] = 1.01802927299558;
   fWeightMatrix1to2[1][7] = 0.432120158577623;
   fWeightMatrix1to2[2][7] = -0.171581516018053;
   fWeightMatrix1to2[3][7] = -2.10611625388177;
   fWeightMatrix1to2[4][7] = -0.967697119987791;
   fWeightMatrix1to2[5][7] = 1.72373092512858;
   fWeightMatrix1to2[6][7] = 1.20633734106403;
   fWeightMatrix1to2[7][7] = 0.830140405172912;
   fWeightMatrix1to2[8][7] = 0.149604612762217;
   fWeightMatrix1to2[9][7] = 1.89607668407081;
   fWeightMatrix1to2[10][7] = -1.70650776858064;
   fWeightMatrix1to2[0][8] = -0.264580455224843;
   fWeightMatrix1to2[1][8] = -0.79467257168465;
   fWeightMatrix1to2[2][8] = -2.50579352541494;
   fWeightMatrix1to2[3][8] = 4.87584831197117;
   fWeightMatrix1to2[4][8] = 2.98687379677416;
   fWeightMatrix1to2[5][8] = -1.13038716373861;
   fWeightMatrix1to2[6][8] = 4.12799911173664;
   fWeightMatrix1to2[7][8] = -0.668927878035473;
   fWeightMatrix1to2[8][8] = -2.62256344730006;
   fWeightMatrix1to2[9][8] = -4.54831682649012;
   fWeightMatrix1to2[10][8] = 3.28348910101935;
   fWeightMatrix1to2[0][9] = 0.96912014602593;
   fWeightMatrix1to2[1][9] = 0.911484689730987;
   fWeightMatrix1to2[2][9] = -2.37506007191059;
   fWeightMatrix1to2[3][9] = 2.59742439873836;
   fWeightMatrix1to2[4][9] = -2.68391992959127;
   fWeightMatrix1to2[5][9] = 1.06322556728793;
   fWeightMatrix1to2[6][9] = -1.2493418448266;
   fWeightMatrix1to2[7][9] = -0.165864306475105;
   fWeightMatrix1to2[8][9] = -2.91057579456651;
   fWeightMatrix1to2[9][9] = -3.07397909078768;
   fWeightMatrix1to2[10][9] = -0.0462901987392106;
   fWeightMatrix1to2[0][10] = -2.66524668655393;
   fWeightMatrix1to2[1][10] = -1.97873776140504;
   fWeightMatrix1to2[2][10] = -4.69983775305434;
   fWeightMatrix1to2[3][10] = 1.97820721434443;
   fWeightMatrix1to2[4][10] = -1.74458279316896;
   fWeightMatrix1to2[5][10] = -1.88576329914289;
   fWeightMatrix1to2[6][10] = 0.967655629542402;
   fWeightMatrix1to2[7][10] = -0.425317079009868;
   fWeightMatrix1to2[8][10] = -1.3363332929437;
   fWeightMatrix1to2[9][10] = -3.67635974810495;
   fWeightMatrix1to2[10][10] = 0.904312331922327;
   fWeightMatrix1to2[0][11] = 1.91185377932912;
   fWeightMatrix1to2[1][11] = 1.34800380896899;
   fWeightMatrix1to2[2][11] = -1.00716285537361;
   fWeightMatrix1to2[3][11] = 0.134127556155362;
   fWeightMatrix1to2[4][11] = -1.21082709225751;
   fWeightMatrix1to2[5][11] = -1.268439753268;
   fWeightMatrix1to2[6][11] = -2.43591726486886;
   fWeightMatrix1to2[7][11] = -0.794718379394304;
   fWeightMatrix1to2[8][11] = 0.200808189483971;
   fWeightMatrix1to2[9][11] = 2.30280968926105;
   fWeightMatrix1to2[10][11] = -1.22250337711732;
   // weight matrix from layer 2 to 3
   fWeightMatrix2to3[0][0] = 0.843969358223197;
   fWeightMatrix2to3[1][0] = -2.39092866644161;
   fWeightMatrix2to3[2][0] = -2.11306980398956;
   fWeightMatrix2to3[3][0] = 1.26342962927322;
   fWeightMatrix2to3[4][0] = 0.453429447311695;
   fWeightMatrix2to3[5][0] = -2.6285097533217;
   fWeightMatrix2to3[6][0] = -1.24719917486871;
   fWeightMatrix2to3[7][0] = 0.898844532654854;
   fWeightMatrix2to3[8][0] = -0.139123169653183;
   fWeightMatrix2to3[9][0] = 0.757389068833807;
   fWeightMatrix2to3[10][0] = -1.72232953205512;
   fWeightMatrix2to3[0][1] = -0.117364409509203;
   fWeightMatrix2to3[1][1] = 1.13217521898181;
   fWeightMatrix2to3[2][1] = 0.961968084595789;
   fWeightMatrix2to3[3][1] = 1.24137513568505;
   fWeightMatrix2to3[4][1] = -0.352632553207553;
   fWeightMatrix2to3[5][1] = 0.217459553886787;
   fWeightMatrix2to3[6][1] = -0.157234407287649;
   fWeightMatrix2to3[7][1] = -1.04084857920605;
   fWeightMatrix2to3[8][1] = -0.751059916548566;
   fWeightMatrix2to3[9][1] = -1.52232275683251;
   fWeightMatrix2to3[10][1] = -2.15390795645417;
   fWeightMatrix2to3[0][2] = -3.15638382149222;
   fWeightMatrix2to3[1][2] = 2.29264174931121;
   fWeightMatrix2to3[2][2] = -1.85272962398399;
   fWeightMatrix2to3[3][2] = 0.514131850166121;
   fWeightMatrix2to3[4][2] = -1.60200223007344;
   fWeightMatrix2to3[5][2] = 0.106130275942371;
   fWeightMatrix2to3[6][2] = -1.77025773197054;
   fWeightMatrix2to3[7][2] = -1.1333367508636;
   fWeightMatrix2to3[8][2] = 2.0944370167557;
   fWeightMatrix2to3[9][2] = -3.83043837887136;
   fWeightMatrix2to3[10][2] = 1.17121489297443;
   fWeightMatrix2to3[0][3] = 1.79304631037511;
   fWeightMatrix2to3[1][3] = -3.57318231491246;
   fWeightMatrix2to3[2][3] = -1.64120809323878;
   fWeightMatrix2to3[3][3] = -0.401706253942652;
   fWeightMatrix2to3[4][3] = -1.60130290550746;
   fWeightMatrix2to3[5][3] = 0.403253955666698;
   fWeightMatrix2to3[6][3] = -0.153625774612211;
   fWeightMatrix2to3[7][3] = 1.6322188238801;
   fWeightMatrix2to3[8][3] = -4.09035700449006;
   fWeightMatrix2to3[9][3] = 1.66799718649522;
   fWeightMatrix2to3[10][3] = -2.35880027590168;
   fWeightMatrix2to3[0][4] = -2.21637496314636;
   fWeightMatrix2to3[1][4] = -3.48861795105901;
   fWeightMatrix2to3[2][4] = 0.947235066751478;
   fWeightMatrix2to3[3][4] = -2.6272506611343;
   fWeightMatrix2to3[4][4] = -1.44598720673765;
   fWeightMatrix2to3[5][4] = 0.877713942179921;
   fWeightMatrix2to3[6][4] = -0.316636205962912;
   fWeightMatrix2to3[7][4] = -1.6638413871975;
   fWeightMatrix2to3[8][4] = 3.15455342586177;
   fWeightMatrix2to3[9][4] = -1.64034378874559;
   fWeightMatrix2to3[10][4] = 1.43979716242352;
   fWeightMatrix2to3[0][5] = 0.906561682513701;
   fWeightMatrix2to3[1][5] = -0.720727944871162;
   fWeightMatrix2to3[2][5] = -0.81677266758358;
   fWeightMatrix2to3[3][5] = 0.111805959319159;
   fWeightMatrix2to3[4][5] = -1.20484043858553;
   fWeightMatrix2to3[5][5] = 0.464728095922064;
   fWeightMatrix2to3[6][5] = 1.92210239552469;
   fWeightMatrix2to3[7][5] = 1.44384386548995;
   fWeightMatrix2to3[8][5] = 1.58047654467808;
   fWeightMatrix2to3[9][5] = -1.33129008631962;
   fWeightMatrix2to3[10][5] = 0.651793658417815;
   fWeightMatrix2to3[0][6] = -3.33919150935066;
   fWeightMatrix2to3[1][6] = -0.155722280605665;
   fWeightMatrix2to3[2][6] = -1.91772225837622;
   fWeightMatrix2to3[3][6] = -2.80102643511284;
   fWeightMatrix2to3[4][6] = -0.910054193903165;
   fWeightMatrix2to3[5][6] = 0.301062000550147;
   fWeightMatrix2to3[6][6] = 0.86578509770275;
   fWeightMatrix2to3[7][6] = 1.42277825685605;
   fWeightMatrix2to3[8][6] = -0.620956657947218;
   fWeightMatrix2to3[9][6] = 2.79728540435039;
   fWeightMatrix2to3[10][6] = -2.43921081023164;
   fWeightMatrix2to3[0][7] = 0.219347345096267;
   fWeightMatrix2to3[1][7] = 3.49151404195215;
   fWeightMatrix2to3[2][7] = -1.59322957746347;
   fWeightMatrix2to3[3][7] = -1.66677943564188;
   fWeightMatrix2to3[4][7] = -1.58369586960869;
   fWeightMatrix2to3[5][7] = -1.40843490222476;
   fWeightMatrix2to3[6][7] = -0.918513373930474;
   fWeightMatrix2to3[7][7] = -2.70922331431005;
   fWeightMatrix2to3[8][7] = -1.08757133622309;
   fWeightMatrix2to3[9][7] = -1.07198818259622;
   fWeightMatrix2to3[10][7] = 2.96805645354648;
   fWeightMatrix2to3[0][8] = 0.854827817160641;
   fWeightMatrix2to3[1][8] = -0.0114647432758874;
   fWeightMatrix2to3[2][8] = -0.964670292642811;
   fWeightMatrix2to3[3][8] = -3.21402203851001;
   fWeightMatrix2to3[4][8] = -1.86832952135879;
   fWeightMatrix2to3[5][8] = -0.230670753883698;
   fWeightMatrix2to3[6][8] = -0.663875764333605;
   fWeightMatrix2to3[7][8] = -1.94348011484086;
   fWeightMatrix2to3[8][8] = 0.617667736409089;
   fWeightMatrix2to3[9][8] = -3.18928344727733;
   fWeightMatrix2to3[10][8] = -2.15884675552883;
   fWeightMatrix2to3[0][9] = -3.57473935255736;
   fWeightMatrix2to3[1][9] = 0.721542127722662;
   fWeightMatrix2to3[2][9] = -1.43124109436619;
   fWeightMatrix2to3[3][9] = -2.40874667126797;
   fWeightMatrix2to3[4][9] = -0.787098634338456;
   fWeightMatrix2to3[5][9] = -2.10538785206377;
   fWeightMatrix2to3[6][9] = -2.3206887571446;
   fWeightMatrix2to3[7][9] = 0.603896996929055;
   fWeightMatrix2to3[8][9] = -0.0161295742857394;
   fWeightMatrix2to3[9][9] = -3.00819098573428;
   fWeightMatrix2to3[10][9] = 2.45570163108364;
   fWeightMatrix2to3[0][10] = 0.409284238557242;
   fWeightMatrix2to3[1][10] = -1.12620915164523;
   fWeightMatrix2to3[2][10] = -0.0331124000575029;
   fWeightMatrix2to3[3][10] = 2.35997401845224;
   fWeightMatrix2to3[4][10] = 1.06500034361526;
   fWeightMatrix2to3[5][10] = 0.0864627995599929;
   fWeightMatrix2to3[6][10] = -0.819829736402305;
   fWeightMatrix2to3[7][10] = -0.0766665435855587;
   fWeightMatrix2to3[8][10] = -3.67088145656373;
   fWeightMatrix2to3[9][10] = 3.61536713385132;
   fWeightMatrix2to3[10][10] = -0.24573864972524;
   fWeightMatrix2to3[0][11] = 0.0075312707160812;
   fWeightMatrix2to3[1][11] = -0.205437779861506;
   fWeightMatrix2to3[2][11] = 0.77145341183968;
   fWeightMatrix2to3[3][11] = 1.77736147918372;
   fWeightMatrix2to3[4][11] = -2.19784169802666;
   fWeightMatrix2to3[5][11] = -0.26438189778589;
   fWeightMatrix2to3[6][11] = 0.357980832690577;
   fWeightMatrix2to3[7][11] = -1.76548513310408;
   fWeightMatrix2to3[8][11] = -1.89597007844173;
   fWeightMatrix2to3[9][11] = -0.729908248729275;
   fWeightMatrix2to3[10][11] = -0.821095129082135;
   // weight matrix from layer 3 to 4
   fWeightMatrix3to4[0][0] = -1.47786375316938;
   fWeightMatrix3to4[0][1] = 3.7952459899152;
   fWeightMatrix3to4[0][2] = 1.69629810607235;
   fWeightMatrix3to4[0][3] = -2.15870001014298;
   fWeightMatrix3to4[0][4] = 1.17733571509707;
   fWeightMatrix3to4[0][5] = -0.36828916768281;
   fWeightMatrix3to4[0][6] = -0.214111095007517;
   fWeightMatrix3to4[0][7] = -2.54871061968309;
   fWeightMatrix3to4[0][8] = 1.77191057526372;
   fWeightMatrix3to4[0][9] = -1.8079000609212;
   fWeightMatrix3to4[0][10] = 2.01256978877;
   fWeightMatrix3to4[0][11] = -0.0114073950718803;
}

inline double ReadMLP_ANN_N0_NC700::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   if (inputValues.size() != (unsigned int)fLayerSize[0]-1) {
      std::cout << "Input vector needs to be of size " << fLayerSize[0]-1 << std::endl;
      return 0;
   }

   for (int l=0; l<fLayers; l++)
      for (int i=0; i<fLayerSize[l]; i++) fWeights[l][i]=0;

   for (int l=0; l<fLayers-1; l++)
      fWeights[l][fLayerSize[l]-1]=1;

   for (int i=0; i<fLayerSize[0]-1; i++)
      fWeights[0][i]=inputValues[i];

   // layer 0 to 1
   for (int o=0; o<fLayerSize[1]-1; o++) {
      for (int i=0; i<fLayerSize[0]; i++) {
         double inputVal = fWeightMatrix0to1[o][i] * fWeights[0][i];
         fWeights[1][o] += inputVal;
      }
      fWeights[1][o] = ActivationFnc(fWeights[1][o]);
   }
   // layer 1 to 2
   for (int o=0; o<fLayerSize[2]-1; o++) {
      for (int i=0; i<fLayerSize[1]; i++) {
         double inputVal = fWeightMatrix1to2[o][i] * fWeights[1][i];
         fWeights[2][o] += inputVal;
      }
      fWeights[2][o] = ActivationFnc(fWeights[2][o]);
   }
   // layer 2 to 3
   for (int o=0; o<fLayerSize[3]-1; o++) {
      for (int i=0; i<fLayerSize[2]; i++) {
         double inputVal = fWeightMatrix2to3[o][i] * fWeights[2][i];
         fWeights[3][o] += inputVal;
      }
      fWeights[3][o] = ActivationFnc(fWeights[3][o]);
   }
   // layer 3 to 4
   for (int o=0; o<fLayerSize[4]; o++) {
      for (int i=0; i<fLayerSize[3]; i++) {
         double inputVal = fWeightMatrix3to4[o][i] * fWeights[3][i];
         fWeights[4][o] += inputVal;
      }
      fWeights[4][o] = OutputActivationFnc(fWeights[4][o]);
   }

   return fWeights[4][0];
}

double ReadMLP_ANN_N0_NC700::ActivationFnc(double x) const {
   // sigmoid
   return 1.0/(1.0+exp(-x));
}
double ReadMLP_ANN_N0_NC700::OutputActivationFnc(double x) const {
   // sigmoid
   return 1.0/(1.0+exp(-x));
}
   
// Clean up
inline void ReadMLP_ANN_N0_NC700::Clear() 
{
   // clean up the arrays
   for (int lIdx = 0; lIdx < 5; lIdx++) {
      delete[] fWeights[lIdx];
   }
}
   inline double ReadMLP_ANN_N0_NC700::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            iV.reserve(inputValues.size());
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
         else {
            std::vector<double> iV;
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(*varIt);
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
      }

      return retval;
   }

//_______________________________________________________________________
inline void ReadMLP_ANN_N0_NC700::InitTransform_1()
{
   // Normalization transformation, initialisation
   fMin_1[0][0] = 110.048698425;
   fMax_1[0][0] = 1277.92980957;
   fMin_1[1][0] = 110.057556152;
   fMax_1[1][0] = 1572.76037598;
   fMin_1[2][0] = 110.048698425;
   fMax_1[2][0] = 1572.76037598;
   fMin_1[0][1] = 5.00075817108;
   fMax_1[0][1] = 29.9497737885;
   fMin_1[1][1] = 5.00135278702;
   fMax_1[1][1] = 29.9984378815;
   fMin_1[2][1] = 5.00075817108;
   fMax_1[2][1] = 29.9984378815;
   fMin_1[0][2] = -1;
   fMax_1[0][2] = 1;
   fMin_1[1][2] = -1;
   fMax_1[1][2] = 1;
   fMin_1[2][2] = -1;
   fMax_1[2][2] = 1;
   fMin_1[0][3] = -2.4711689949;
   fMax_1[0][3] = 2.37911462784;
   fMin_1[1][3] = -2.48411560059;
   fMax_1[1][3] = 2.49880051613;
   fMin_1[2][3] = -2.48411560059;
   fMax_1[2][3] = 2.49880051613;
   fMin_1[0][4] = 280.2293396;
   fMax_1[0][4] = 1251.49438477;
   fMin_1[1][4] = 280.020294189;
   fMax_1[1][4] = 1289.47937012;
   fMin_1[2][4] = 280.020294189;
   fMax_1[2][4] = 1289.47937012;
   fMin_1[0][5] = 0.0557334087789;
   fMax_1[0][5] = 300.527191162;
   fMin_1[1][5] = 0.000537815736607;
   fMax_1[1][5] = 215.792510986;
   fMin_1[2][5] = 0.000537815736607;
   fMax_1[2][5] = 300.527191162;
   fMin_1[0][6] = 117.352531433;
   fMax_1[0][6] = 2347.48510742;
   fMin_1[1][6] = 112.003395081;
   fMax_1[1][6] = 4504.87304688;
   fMin_1[2][6] = 112.003395081;
   fMax_1[2][6] = 4504.87304688;
   fMin_1[0][7] = 0;
   fMax_1[0][7] = 5;
   fMin_1[1][7] = 0;
   fMax_1[1][7] = 6;
   fMin_1[2][7] = 0;
   fMax_1[2][7] = 6;
   fMin_1[0][8] = 1;
   fMax_1[0][8] = 11;
   fMin_1[1][8] = 1;
   fMax_1[1][8] = 14;
   fMin_1[2][8] = 1;
   fMax_1[2][8] = 14;
   fMin_1[0][9] = 20.0573444366;
   fMax_1[0][9] = 1057.04370117;
   fMin_1[1][9] = -999;
   fMax_1[1][9] = 1378.42883301;
   fMin_1[2][9] = -999;
   fMax_1[2][9] = 1378.42883301;
   fMin_1[0][10] = 6.27087429166e-05;
   fMax_1[0][10] = 4.95768356323;
   fMin_1[1][10] = -999;
   fMax_1[1][10] = 5.38026332855;
   fMin_1[2][10] = -999;
   fMax_1[2][10] = 5.38026332855;
}

//_______________________________________________________________________
inline void ReadMLP_ANN_N0_NC700::Transform_1( std::vector<double>& iv, int cls) const
{
   // Normalization transformation
   if (cls < 0 || cls > 2) {
   if (2 > 1 ) cls = 2;
      else cls = 2;
   }
   const int nVar = 11;

   // get indices of used variables

   // define the indices of the variables which are transformed by this transformation
   static std::vector<int> indicesGet;
   static std::vector<int> indicesPut;

   if ( indicesGet.empty() ) { 
      indicesGet.reserve(fNvars);
      indicesGet.push_back( 0);
      indicesGet.push_back( 1);
      indicesGet.push_back( 2);
      indicesGet.push_back( 3);
      indicesGet.push_back( 4);
      indicesGet.push_back( 5);
      indicesGet.push_back( 6);
      indicesGet.push_back( 7);
      indicesGet.push_back( 8);
      indicesGet.push_back( 9);
      indicesGet.push_back( 10);
   } 
   if ( indicesPut.empty() ) { 
      indicesPut.reserve(fNvars);
      indicesPut.push_back( 0);
      indicesPut.push_back( 1);
      indicesPut.push_back( 2);
      indicesPut.push_back( 3);
      indicesPut.push_back( 4);
      indicesPut.push_back( 5);
      indicesPut.push_back( 6);
      indicesPut.push_back( 7);
      indicesPut.push_back( 8);
      indicesPut.push_back( 9);
      indicesPut.push_back( 10);
   } 

   static std::vector<double> dv;
   dv.resize(nVar);
   for (int ivar=0; ivar<nVar; ivar++) dv[ivar] = iv[indicesGet.at(ivar)];
   for (int ivar=0;ivar<11;ivar++) {
      double offset = fMin_1[cls][ivar];
      double scale  = 1.0/(fMax_1[cls][ivar]-fMin_1[cls][ivar]);
      iv[indicesPut.at(ivar)] = (dv[ivar]-offset)*scale * 2 - 1;
   }
}

//_______________________________________________________________________
inline void ReadMLP_ANN_N0_NC700::InitTransform()
{
   InitTransform_1();
}

//_______________________________________________________________________
inline void ReadMLP_ANN_N0_NC700::Transform( std::vector<double>& iv, int sigOrBgd ) const
{
   Transform_1( iv, sigOrBgd );
}
