// Class: ReadMLP_ANN_N2_NC600
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : MLP::MLP_ANN_N2_NC600
TMVA Release   : 4.2.1         [262657]
ROOT Release   : 6.06/01       [394753]
Creator        : brucms16
Date           : Wed Sep  7 02:55:42 2016
Host           : Linux vocms0315.cern.ch 2.6.32-573.26.1.el6.x86_64 #1 SMP Wed May 4 09:23:05 CEST 2016 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /home/t3cms/brucms16/CMSSW_8_0_14/src/UserCode/SkeletonAnalysis/macros
Training events: 15056
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
NCycles: "600" [Number of training cycles]
HiddenLayers: "N,N,N+2" [Specification of hidden layer architecture]
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
VarTransform: "Norm" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
H: "False" [Print method-specific help message]
LearningRate: "9.000000e-02" [ANN learning rate parameter]
DecayRate: "1.000000e-02" [Decay rate for learning parameter]
# Default:
NeuronType: "sigmoid" [Neuron activation function type]
RandomSeed: "1" [Random seed for initial synapse weights (0 means unique seed for each run; default value '1')]
EstimatorType: "CE" [MSE (Mean Square Estimator) for Gaussian Likelihood or CE(Cross-Entropy) for Bernoulli Likelihood]
NeuronInputType: "sum" [Neuron input function type]
VerbosityLevel: "Default" [Verbosity level]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
TrainingMethod: "BP" [Train with Back-Propagation (BP), BFGS Algorithm (BFGS), or Genetic Algorithm (GA - slower and worse)]
TestRate: "10" [Test for overtraining performed at each #th epochs]
EpochMonitoring: "False" [Provide epoch-wise monitoring plots according to TestRate (caution: causes big ROOT output file!)]
Sampling: "1.000000e+00" [Only 'Sampling' (randomly selected) events are trained each epoch]
SamplingEpoch: "1.000000e+00" [Sampling is used for the first 'SamplingEpoch' epochs, afterwards, all events are taken for training]
SamplingImportance: "1.000000e+00" [ The sampling weights of events in epochs which successful (worse estimator than before) are multiplied with SamplingImportance, else they are divided.]
SamplingTraining: "True" [The training sample is sampled]
SamplingTesting: "False" [The testing sample is sampled]
ResetStep: "50" [How often BFGS should reset history]
Tau: "3.000000e+00" [LineSearch "size step"]
BPMode: "sequential" [Back-propagation learning mode: sequential or batch]
BatchSize: "-1" [Batch size: number of events/batch, only set if in Batch Mode, -1 for BatchSize=number_of_events]
ConvergenceImprove: "1.000000e-30" [Minimum improvement which counts as improvement (<0 means automatic convergence check is turned off)]
ConvergenceTests: "-1" [Number of steps (without improvement) required for convergence (<0 means automatic convergence check is turned off)]
UseRegulator: "False" [Use regulator to avoid over-training]
UpdateLimit: "10000" [Maximum times of regulator update]
CalculateErrors: "False" [Calculates inverse Hessian matrix at the end of the training to be able to calculate the uncertainties of an MVA value]
WeightRange: "1.000000e+00" [Take the events for the estimator calculations from small deviations from the desired value to large deviations only over the weight range]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 11
Jet1Pt                        Jet1Pt                        Jet1Pt                        Jet1Pt                                                          'F'    [110.048698425,1572.76037598]
LepPt                         LepPt                         LepPt                         LepPt                                                           'F'    [5.00075817108,29.9984378815]
LepChg                        LepChg                        LepChg                        LepChg                                                          'F'    [-1,1]
LepEta                        LepEta                        LepEta                        LepEta                                                          'F'    [-2.48411560059,2.49880051613]
Met                           Met                           Met                           Met                                                             'F'    [280.020294189,1289.47937012]
mt                            mt                            mt                            mt                                                              'F'    [0.000537815736607,300.527191162]
HT20                          HT20                          HT20                          HT20                                                            'F'    [112.003395081,4504.87304688]
NbLoose30                     NbLoose30                     NbLoose30                     NbLoose30                                                       'F'    [0,6]
Njet                          Njet                          Njet                          Njet                                                            'F'    [1,14]
JetHBpt                       JetHBpt                       JetHBpt                       JetHBpt                                                         'F'    [-999,1378.42883301]
DrJetHBLep                    DrJetHBLep                    DrJetHBLep                    DrJetHBLep                                                      'F'    [-999,5.38026332855]
NSpec 0


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadMLP_ANN_N2_NC600 : public IClassifierReader {

 public:

   // constructor
   ReadMLP_ANN_N2_NC600( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadMLP_ANN_N2_NC600" ),
        fNvars( 11 ),
        fIsNormalised( false )
   {      
      // the training input variables
      const char* inputVars[] = { "Jet1Pt", "LepPt", "LepChg", "LepEta", "Met", "mt", "HT20", "NbLoose30", "Njet", "JetHBpt", "DrJetHBLep" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = -1;
      fVmax[0] = 1;
      fVmin[1] = -1;
      fVmax[1] = 0.99999988079071;
      fVmin[2] = -1;
      fVmax[2] = 1;
      fVmin[3] = -1;
      fVmax[3] = 1;
      fVmin[4] = -1;
      fVmax[4] = 1;
      fVmin[5] = -1;
      fVmax[5] = 1;
      fVmin[6] = -1;
      fVmax[6] = 1;
      fVmin[7] = -1;
      fVmax[7] = 1;
      fVmin[8] = -1;
      fVmax[8] = 1;
      fVmin[9] = -1;
      fVmax[9] = 1;
      fVmin[10] = -1;
      fVmax[10] = 1;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';
      fType[4] = 'F';
      fType[5] = 'F';
      fType[6] = 'F';
      fType[7] = 'F';
      fType[8] = 'F';
      fType[9] = 'F';
      fType[10] = 'F';

      // initialize constants
      Initialize();

      // initialize transformation
      InitTransform();
   }

   // destructor
   virtual ~ReadMLP_ANN_N2_NC600() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // input variable transformation

   double fMin_1[3][11];
   double fMax_1[3][11];
   void InitTransform_1();
   void Transform_1( std::vector<double> & iv, int sigOrBgd ) const;
   void InitTransform();
   void Transform( std::vector<double> & iv, int sigOrBgd ) const;

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[11];
   double fVmax[11];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[11];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)

   double ActivationFnc(double x) const;
   double OutputActivationFnc(double x) const;

   int fLayers;
   int fLayerSize[5];
   double fWeightMatrix0to1[12][12];   // weight matrix from layer 0 to 1
   double fWeightMatrix1to2[12][12];   // weight matrix from layer 1 to 2
   double fWeightMatrix2to3[14][12];   // weight matrix from layer 2 to 3
   double fWeightMatrix3to4[1][14];   // weight matrix from layer 3 to 4

   double * fWeights[5];
};

inline void ReadMLP_ANN_N2_NC600::Initialize()
{
   // build network structure
   fLayers = 5;
   fLayerSize[0] = 12; fWeights[0] = new double[12]; 
   fLayerSize[1] = 12; fWeights[1] = new double[12]; 
   fLayerSize[2] = 12; fWeights[2] = new double[12]; 
   fLayerSize[3] = 14; fWeights[3] = new double[14]; 
   fLayerSize[4] = 1; fWeights[4] = new double[1]; 
   // weight matrix from layer 0 to 1
   fWeightMatrix0to1[0][0] = -0.724904836222671;
   fWeightMatrix0to1[1][0] = 1.04320218684925;
   fWeightMatrix0to1[2][0] = 1.18518284510476;
   fWeightMatrix0to1[3][0] = 0.245019613268437;
   fWeightMatrix0to1[4][0] = -1.54749300577813;
   fWeightMatrix0to1[5][0] = -1.3547094624758;
   fWeightMatrix0to1[6][0] = 1.02152389565726;
   fWeightMatrix0to1[7][0] = 2.03941774660265;
   fWeightMatrix0to1[8][0] = -2.89142156209392;
   fWeightMatrix0to1[9][0] = 0.368606311761361;
   fWeightMatrix0to1[10][0] = -6.51386391249886;
   fWeightMatrix0to1[0][1] = -0.591261522931429;
   fWeightMatrix0to1[1][1] = -0.249562921416473;
   fWeightMatrix0to1[2][1] = -0.360743236748896;
   fWeightMatrix0to1[3][1] = -2.98889333140432;
   fWeightMatrix0to1[4][1] = 0.281327252050421;
   fWeightMatrix0to1[5][1] = 1.55263644309627;
   fWeightMatrix0to1[6][1] = 2.16226642035754;
   fWeightMatrix0to1[7][1] = 0.239146657016096;
   fWeightMatrix0to1[8][1] = 5.11075222358964;
   fWeightMatrix0to1[9][1] = 2.31612253930112;
   fWeightMatrix0to1[10][1] = -1.22250568738618;
   fWeightMatrix0to1[0][2] = 0.405051957373678;
   fWeightMatrix0to1[1][2] = 0.17652684110916;
   fWeightMatrix0to1[2][2] = -0.762346827535219;
   fWeightMatrix0to1[3][2] = -1.51437435860236;
   fWeightMatrix0to1[4][2] = -1.64359326190562;
   fWeightMatrix0to1[5][2] = -4.83268335774609;
   fWeightMatrix0to1[6][2] = -3.4798804475996;
   fWeightMatrix0to1[7][2] = 0.343284059789228;
   fWeightMatrix0to1[8][2] = -1.24892265832413;
   fWeightMatrix0to1[9][2] = 1.48857930529111;
   fWeightMatrix0to1[10][2] = -0.203255859459477;
   fWeightMatrix0to1[0][3] = 1.61820289311743;
   fWeightMatrix0to1[1][3] = 0.459409993824833;
   fWeightMatrix0to1[2][3] = -1.49495430525169;
   fWeightMatrix0to1[3][3] = 0.503551577957902;
   fWeightMatrix0to1[4][3] = 8.85824270790694;
   fWeightMatrix0to1[5][3] = -3.47367075118304;
   fWeightMatrix0to1[6][3] = 1.81652769458696;
   fWeightMatrix0to1[7][3] = 1.00555783971683;
   fWeightMatrix0to1[8][3] = -0.707900602248262;
   fWeightMatrix0to1[9][3] = -0.219244380533542;
   fWeightMatrix0to1[10][3] = -0.659810821680054;
   fWeightMatrix0to1[0][4] = 5.50507008156497;
   fWeightMatrix0to1[1][4] = -2.41763684508578;
   fWeightMatrix0to1[2][4] = 11.9786789188826;
   fWeightMatrix0to1[3][4] = 5.12272337416658;
   fWeightMatrix0to1[4][4] = -0.616720021045515;
   fWeightMatrix0to1[5][4] = -1.35507246138335;
   fWeightMatrix0to1[6][4] = 4.14565872092993;
   fWeightMatrix0to1[7][4] = 1.34472508903098;
   fWeightMatrix0to1[8][4] = -4.92048971614103;
   fWeightMatrix0to1[9][4] = 0.44435766506651;
   fWeightMatrix0to1[10][4] = -1.0493301688212;
   fWeightMatrix0to1[0][5] = 1.10392134168102;
   fWeightMatrix0to1[1][5] = -16.0040414248953;
   fWeightMatrix0to1[2][5] = -3.51867475829694;
   fWeightMatrix0to1[3][5] = 1.61074820241295;
   fWeightMatrix0to1[4][5] = 1.27115286143546;
   fWeightMatrix0to1[5][5] = 1.92830362780667;
   fWeightMatrix0to1[6][5] = 0.583572603459384;
   fWeightMatrix0to1[7][5] = -0.488915003681896;
   fWeightMatrix0to1[8][5] = 2.8060227811452;
   fWeightMatrix0to1[9][5] = 2.73751797693677;
   fWeightMatrix0to1[10][5] = 2.25609210438266;
   fWeightMatrix0to1[0][6] = -3.53935392393389;
   fWeightMatrix0to1[1][6] = 3.82409830642713;
   fWeightMatrix0to1[2][6] = -5.02681587660736;
   fWeightMatrix0to1[3][6] = -4.1478820463053;
   fWeightMatrix0to1[4][6] = 1.50060219287027;
   fWeightMatrix0to1[5][6] = -0.625002283526452;
   fWeightMatrix0to1[6][6] = -0.450774872940198;
   fWeightMatrix0to1[7][6] = 1.0420942075678;
   fWeightMatrix0to1[8][6] = 4.14402697138127;
   fWeightMatrix0to1[9][6] = 2.61143006359526;
   fWeightMatrix0to1[10][6] = -1.37386066677152;
   fWeightMatrix0to1[0][7] = -5.7492020493989;
   fWeightMatrix0to1[1][7] = -1.92410446825361;
   fWeightMatrix0to1[2][7] = -0.825497483109951;
   fWeightMatrix0to1[3][7] = 0.728393306362828;
   fWeightMatrix0to1[4][7] = -0.149876061329191;
   fWeightMatrix0to1[5][7] = 2.52173511866485;
   fWeightMatrix0to1[6][7] = -2.04044822494901;
   fWeightMatrix0to1[7][7] = -0.972426852886914;
   fWeightMatrix0to1[8][7] = 0.966454091335942;
   fWeightMatrix0to1[9][7] = -0.220989524947018;
   fWeightMatrix0to1[10][7] = 0.767508423045614;
   fWeightMatrix0to1[0][8] = -4.12367296464137;
   fWeightMatrix0to1[1][8] = 0.560720116338613;
   fWeightMatrix0to1[2][8] = 1.0445141426632;
   fWeightMatrix0to1[3][8] = -0.00893593942734552;
   fWeightMatrix0to1[4][8] = -1.20916726555383;
   fWeightMatrix0to1[5][8] = -2.81101104609;
   fWeightMatrix0to1[6][8] = -1.48180641548805;
   fWeightMatrix0to1[7][8] = 1.69668880910228;
   fWeightMatrix0to1[8][8] = -1.01217970187971;
   fWeightMatrix0to1[9][8] = -8.69331913436676;
   fWeightMatrix0to1[10][8] = -4.41755506600728;
   fWeightMatrix0to1[0][9] = -2.2164825572574;
   fWeightMatrix0to1[1][9] = 3.72479677370773;
   fWeightMatrix0to1[2][9] = -5.36624171719229;
   fWeightMatrix0to1[3][9] = 0.722633912307976;
   fWeightMatrix0to1[4][9] = -0.0499395291016619;
   fWeightMatrix0to1[5][9] = -0.708962798315319;
   fWeightMatrix0to1[6][9] = 1.92822423956069;
   fWeightMatrix0to1[7][9] = -0.828580613306636;
   fWeightMatrix0to1[8][9] = -4.9996372449284;
   fWeightMatrix0to1[9][9] = -0.237735804326002;
   fWeightMatrix0to1[10][9] = -0.908980698399825;
   fWeightMatrix0to1[0][10] = -3.01980049838469;
   fWeightMatrix0to1[1][10] = -2.17247805396079;
   fWeightMatrix0to1[2][10] = 1.50550052927571;
   fWeightMatrix0to1[3][10] = 1.24685938340115;
   fWeightMatrix0to1[4][10] = -2.53016602245987;
   fWeightMatrix0to1[5][10] = 1.25165503917164;
   fWeightMatrix0to1[6][10] = 0.614602664165986;
   fWeightMatrix0to1[7][10] = -0.761080955375185;
   fWeightMatrix0to1[8][10] = -0.28085748318207;
   fWeightMatrix0to1[9][10] = -1.66547452904938;
   fWeightMatrix0to1[10][10] = -4.32382809341091;
   fWeightMatrix0to1[0][11] = -1.12636820938009;
   fWeightMatrix0to1[1][11] = -2.80755388582494;
   fWeightMatrix0to1[2][11] = 2.54298099886341;
   fWeightMatrix0to1[3][11] = 1.45941644954595;
   fWeightMatrix0to1[4][11] = -1.08297030546404;
   fWeightMatrix0to1[5][11] = -0.792558623752272;
   fWeightMatrix0to1[6][11] = 0.349538859037268;
   fWeightMatrix0to1[7][11] = -1.62069982920447;
   fWeightMatrix0to1[8][11] = 0.40385792414891;
   fWeightMatrix0to1[9][11] = -0.318548546075083;
   fWeightMatrix0to1[10][11] = -4.51303502454435;
   // weight matrix from layer 1 to 2
   fWeightMatrix1to2[0][0] = -0.812535436217889;
   fWeightMatrix1to2[1][0] = -1.8154589610038;
   fWeightMatrix1to2[2][0] = 1.1555769162166;
   fWeightMatrix1to2[3][0] = 2.82447046054936;
   fWeightMatrix1to2[4][0] = 4.20986673092553;
   fWeightMatrix1to2[5][0] = -2.29204370608899;
   fWeightMatrix1to2[6][0] = 0.0888688199394679;
   fWeightMatrix1to2[7][0] = 5.24038683956771;
   fWeightMatrix1to2[8][0] = 1.52701506850904;
   fWeightMatrix1to2[9][0] = -0.710149291565783;
   fWeightMatrix1to2[10][0] = -5.53770768708447;
   fWeightMatrix1to2[0][1] = 1.14338406677846;
   fWeightMatrix1to2[1][1] = -2.54993877583903;
   fWeightMatrix1to2[2][1] = 3.94136155886551;
   fWeightMatrix1to2[3][1] = 2.33289766753821;
   fWeightMatrix1to2[4][1] = 0.271322817392589;
   fWeightMatrix1to2[5][1] = -0.382507544506305;
   fWeightMatrix1to2[6][1] = -1.03155951805338;
   fWeightMatrix1to2[7][1] = -6.39752004423842;
   fWeightMatrix1to2[8][1] = -0.469128032918578;
   fWeightMatrix1to2[9][1] = -0.637196962577283;
   fWeightMatrix1to2[10][1] = -1.14232363767785;
   fWeightMatrix1to2[0][2] = -5.20989198916457;
   fWeightMatrix1to2[1][2] = 0.919021868033209;
   fWeightMatrix1to2[2][2] = 3.3849024663038;
   fWeightMatrix1to2[3][2] = 2.72169416338433;
   fWeightMatrix1to2[4][2] = 0.146475066445314;
   fWeightMatrix1to2[5][2] = -1.23502310645009;
   fWeightMatrix1to2[6][2] = 2.75622466189;
   fWeightMatrix1to2[7][2] = 5.0871674620688;
   fWeightMatrix1to2[8][2] = 1.50439424629478;
   fWeightMatrix1to2[9][2] = -0.0319349338193509;
   fWeightMatrix1to2[10][2] = -0.787746957104474;
   fWeightMatrix1to2[0][3] = -1.52444364050119;
   fWeightMatrix1to2[1][3] = -1.78777640356911;
   fWeightMatrix1to2[2][3] = -0.154601371035719;
   fWeightMatrix1to2[3][3] = -3.87810736676633;
   fWeightMatrix1to2[4][3] = -0.234272571155064;
   fWeightMatrix1to2[5][3] = 1.47052504096032;
   fWeightMatrix1to2[6][3] = 1.41854977540959;
   fWeightMatrix1to2[7][3] = 1.03334579387822;
   fWeightMatrix1to2[8][3] = 3.04332842835748;
   fWeightMatrix1to2[9][3] = 2.31561251672783;
   fWeightMatrix1to2[10][3] = -3.00135530711032;
   fWeightMatrix1to2[0][4] = 1.59718754659755;
   fWeightMatrix1to2[1][4] = -2.31190850883551;
   fWeightMatrix1to2[2][4] = -3.35457914850739;
   fWeightMatrix1to2[3][4] = -2.02568312430888;
   fWeightMatrix1to2[4][4] = -3.14756278075899;
   fWeightMatrix1to2[5][4] = 0.646076088512441;
   fWeightMatrix1to2[6][4] = 2.78705927494676;
   fWeightMatrix1to2[7][4] = -1.10400529898908;
   fWeightMatrix1to2[8][4] = -3.88542161360237;
   fWeightMatrix1to2[9][4] = -2.46939278255262;
   fWeightMatrix1to2[10][4] = -3.18960716676452;
   fWeightMatrix1to2[0][5] = -0.804042230012329;
   fWeightMatrix1to2[1][5] = -0.609202640227;
   fWeightMatrix1to2[2][5] = 1.81125379360696;
   fWeightMatrix1to2[3][5] = 0.422827614583117;
   fWeightMatrix1to2[4][5] = 0.210417547569767;
   fWeightMatrix1to2[5][5] = 1.78570580973049;
   fWeightMatrix1to2[6][5] = 1.17967584098221;
   fWeightMatrix1to2[7][5] = -4.55230513991541;
   fWeightMatrix1to2[8][5] = -1.37613777771269;
   fWeightMatrix1to2[9][5] = -2.6459675979472;
   fWeightMatrix1to2[10][5] = 1.39007871567437;
   fWeightMatrix1to2[0][6] = -0.862676402100807;
   fWeightMatrix1to2[1][6] = -1.62432083507016;
   fWeightMatrix1to2[2][6] = 2.62209806399657;
   fWeightMatrix1to2[3][6] = -0.0511422535444216;
   fWeightMatrix1to2[4][6] = 1.06083923038779;
   fWeightMatrix1to2[5][6] = -2.15663413248507;
   fWeightMatrix1to2[6][6] = 3.88013026577912;
   fWeightMatrix1to2[7][6] = 2.3715064096714;
   fWeightMatrix1to2[8][6] = 0.864520458407748;
   fWeightMatrix1to2[9][6] = 0.450998165739058;
   fWeightMatrix1to2[10][6] = 1.64701377020042;
   fWeightMatrix1to2[0][7] = 0.998607314826956;
   fWeightMatrix1to2[1][7] = 0.463995754149507;
   fWeightMatrix1to2[2][7] = -0.0345589393537811;
   fWeightMatrix1to2[3][7] = -2.1832986237728;
   fWeightMatrix1to2[4][7] = -0.920290824230956;
   fWeightMatrix1to2[5][7] = 1.70502713793257;
   fWeightMatrix1to2[6][7] = 1.30566839723955;
   fWeightMatrix1to2[7][7] = 0.775956881001707;
   fWeightMatrix1to2[8][7] = 0.0549203484123881;
   fWeightMatrix1to2[9][7] = 2.02562858205836;
   fWeightMatrix1to2[10][7] = -1.59768030245526;
   fWeightMatrix1to2[0][8] = 0.854860709385062;
   fWeightMatrix1to2[1][8] = 0.197223627392567;
   fWeightMatrix1to2[2][8] = -3.99665690994387;
   fWeightMatrix1to2[3][8] = -0.181578318743186;
   fWeightMatrix1to2[4][8] = -0.13785599268373;
   fWeightMatrix1to2[5][8] = -1.25548991266327;
   fWeightMatrix1to2[6][8] = -2.13089729827019;
   fWeightMatrix1to2[7][8] = 1.40860598136721;
   fWeightMatrix1to2[8][8] = -4.22201135784584;
   fWeightMatrix1to2[9][8] = -3.26129196896012;
   fWeightMatrix1to2[10][8] = 2.6812871923687;
   fWeightMatrix1to2[0][9] = -0.907391077887056;
   fWeightMatrix1to2[1][9] = 1.9081387961995;
   fWeightMatrix1to2[2][9] = -2.9593751174122;
   fWeightMatrix1to2[3][9] = 3.83843889797736;
   fWeightMatrix1to2[4][9] = -1.92967086097852;
   fWeightMatrix1to2[5][9] = 0.772014676608175;
   fWeightMatrix1to2[6][9] = -1.73391781375642;
   fWeightMatrix1to2[7][9] = -3.65596135573121;
   fWeightMatrix1to2[8][9] = 0.651368447832516;
   fWeightMatrix1to2[9][9] = -3.64437623662178;
   fWeightMatrix1to2[10][9] = -2.48786424844619;
   fWeightMatrix1to2[0][10] = -1.55492584805383;
   fWeightMatrix1to2[1][10] = -2.61762619607413;
   fWeightMatrix1to2[2][10] = -3.12075173818879;
   fWeightMatrix1to2[3][10] = 0.773138879321876;
   fWeightMatrix1to2[4][10] = -4.77261674487632;
   fWeightMatrix1to2[5][10] = -1.64981510305249;
   fWeightMatrix1to2[6][10] = 1.19252713302496;
   fWeightMatrix1to2[7][10] = -2.64569214352213;
   fWeightMatrix1to2[8][10] = 0.274703825001999;
   fWeightMatrix1to2[9][10] = -0.330214693977374;
   fWeightMatrix1to2[10][10] = 0.669278932750136;
   fWeightMatrix1to2[0][11] = 2.85048295452306;
   fWeightMatrix1to2[1][11] = 1.07563300035676;
   fWeightMatrix1to2[2][11] = 0.018447524560487;
   fWeightMatrix1to2[3][11] = -3.09014660650069;
   fWeightMatrix1to2[4][11] = -1.82811440033032;
   fWeightMatrix1to2[5][11] = -1.07810239074323;
   fWeightMatrix1to2[6][11] = -3.40957609422763;
   fWeightMatrix1to2[7][11] = 1.78064705572705;
   fWeightMatrix1to2[8][11] = 1.12759131276;
   fWeightMatrix1to2[9][11] = 2.43935771225336;
   fWeightMatrix1to2[10][11] = 0.00258681046807197;
   // weight matrix from layer 2 to 3
   fWeightMatrix2to3[0][0] = 0.670989938528363;
   fWeightMatrix2to3[1][0] = -2.29869710760672;
   fWeightMatrix2to3[2][0] = -2.00484363449103;
   fWeightMatrix2to3[3][0] = 0.746119943276831;
   fWeightMatrix2to3[4][0] = 1.00139820301877;
   fWeightMatrix2to3[5][0] = -0.948902922986223;
   fWeightMatrix2to3[6][0] = -1.31909958016192;
   fWeightMatrix2to3[7][0] = -0.329741340336165;
   fWeightMatrix2to3[8][0] = 1.87720530733498;
   fWeightMatrix2to3[9][0] = -1.51017794790241;
   fWeightMatrix2to3[10][0] = -0.861594184198787;
   fWeightMatrix2to3[11][0] = -2.91220342084256;
   fWeightMatrix2to3[12][0] = 0.606669642064068;
   fWeightMatrix2to3[0][1] = 0.522896172736681;
   fWeightMatrix2to3[1][1] = 0.735560895651516;
   fWeightMatrix2to3[2][1] = 1.89166183746481;
   fWeightMatrix2to3[3][1] = -0.396046919750911;
   fWeightMatrix2to3[4][1] = -0.551528873164841;
   fWeightMatrix2to3[5][1] = -1.59689566752713;
   fWeightMatrix2to3[6][1] = -0.841848742550192;
   fWeightMatrix2to3[7][1] = -2.62667727793152;
   fWeightMatrix2to3[8][1] = -1.60711623606327;
   fWeightMatrix2to3[9][1] = -1.27167174535098;
   fWeightMatrix2to3[10][1] = 2.3077395360043;
   fWeightMatrix2to3[11][1] = -1.68777094617152;
   fWeightMatrix2to3[12][1] = 0.971508792834822;
   fWeightMatrix2to3[0][2] = -4.23579679901477;
   fWeightMatrix2to3[1][2] = 1.64333867655692;
   fWeightMatrix2to3[2][2] = -3.95991166342512;
   fWeightMatrix2to3[3][2] = -0.494785046955252;
   fWeightMatrix2to3[4][2] = -0.112387246262467;
   fWeightMatrix2to3[5][2] = -2.25031766466264;
   fWeightMatrix2to3[6][2] = -1.23404394081904;
   fWeightMatrix2to3[7][2] = -1.2843078566373;
   fWeightMatrix2to3[8][2] = -4.11162518153444;
   fWeightMatrix2to3[9][2] = -3.35539192522715;
   fWeightMatrix2to3[10][2] = -3.7550068099619;
   fWeightMatrix2to3[11][2] = -1.30655678462282;
   fWeightMatrix2to3[12][2] = 0.144943801713999;
   fWeightMatrix2to3[0][3] = -2.47837125252487;
   fWeightMatrix2to3[1][3] = 0.541203156751006;
   fWeightMatrix2to3[2][3] = -1.67634498636937;
   fWeightMatrix2to3[3][3] = -3.7618299557864;
   fWeightMatrix2to3[4][3] = -2.73085047322492;
   fWeightMatrix2to3[5][3] = -1.64660871267486;
   fWeightMatrix2to3[6][3] = -2.54483956427741;
   fWeightMatrix2to3[7][3] = -1.01906476234664;
   fWeightMatrix2to3[8][3] = -1.82162506728246;
   fWeightMatrix2to3[9][3] = -3.34342322344684;
   fWeightMatrix2to3[10][3] = 0.302907349491897;
   fWeightMatrix2to3[11][3] = 1.65848472700391;
   fWeightMatrix2to3[12][3] = -2.36513514024941;
   fWeightMatrix2to3[0][4] = 0.749658672432936;
   fWeightMatrix2to3[1][4] = -2.21824439896816;
   fWeightMatrix2to3[2][4] = 2.92552964007787;
   fWeightMatrix2to3[3][4] = 0.384818349203398;
   fWeightMatrix2to3[4][4] = -1.25610657883259;
   fWeightMatrix2to3[5][4] = -1.52609895044716;
   fWeightMatrix2to3[6][4] = -0.61883502889865;
   fWeightMatrix2to3[7][4] = -2.44387571767254;
   fWeightMatrix2to3[8][4] = -0.300232944538494;
   fWeightMatrix2to3[9][4] = 2.76930271737997;
   fWeightMatrix2to3[10][4] = 1.45610766398997;
   fWeightMatrix2to3[11][4] = -0.219709263778864;
   fWeightMatrix2to3[12][4] = -1.92530657233538;
   fWeightMatrix2to3[0][5] = 0.554586473146086;
   fWeightMatrix2to3[1][5] = -2.03579063385153;
   fWeightMatrix2to3[2][5] = 0.34054884867899;
   fWeightMatrix2to3[3][5] = -1.66255464917184;
   fWeightMatrix2to3[4][5] = -2.07427840338294;
   fWeightMatrix2to3[5][5] = 0.05073761287455;
   fWeightMatrix2to3[6][5] = 1.81754115403951;
   fWeightMatrix2to3[7][5] = 0.509063058418694;
   fWeightMatrix2to3[8][5] = 0.562109099140035;
   fWeightMatrix2to3[9][5] = 0.261051465595209;
   fWeightMatrix2to3[10][5] = -0.357116926304232;
   fWeightMatrix2to3[11][5] = -0.418704071718326;
   fWeightMatrix2to3[12][5] = 0.178710066327915;
   fWeightMatrix2to3[0][6] = 0.470020478590173;
   fWeightMatrix2to3[1][6] = -0.49346854793366;
   fWeightMatrix2to3[2][6] = 0.864100577957661;
   fWeightMatrix2to3[3][6] = -2.58056207991707;
   fWeightMatrix2to3[4][6] = -1.58287106059295;
   fWeightMatrix2to3[5][6] = -0.60993140630893;
   fWeightMatrix2to3[6][6] = -1.16245913728151;
   fWeightMatrix2to3[7][6] = -1.81688261557255;
   fWeightMatrix2to3[8][6] = -0.152715474866955;
   fWeightMatrix2to3[9][6] = 2.37238657069793;
   fWeightMatrix2to3[10][6] = 0.284049628628221;
   fWeightMatrix2to3[11][6] = -2.23106372003053;
   fWeightMatrix2to3[12][6] = -2.16493787979269;
   fWeightMatrix2to3[0][7] = -2.46983874570019;
   fWeightMatrix2to3[1][7] = -0.607025254862783;
   fWeightMatrix2to3[2][7] = 2.12696037766291;
   fWeightMatrix2to3[3][7] = -2.22217257655633;
   fWeightMatrix2to3[4][7] = -1.97165643747093;
   fWeightMatrix2to3[5][7] = -0.175697186338083;
   fWeightMatrix2to3[6][7] = -3.18243997772892;
   fWeightMatrix2to3[7][7] = -2.79527795429803;
   fWeightMatrix2to3[8][7] = -2.41850659749577;
   fWeightMatrix2to3[9][7] = -0.00542077589299344;
   fWeightMatrix2to3[10][7] = -0.983525987477482;
   fWeightMatrix2to3[11][7] = -3.91964922781881;
   fWeightMatrix2to3[12][7] = -1.21347311551439;
   fWeightMatrix2to3[0][8] = -2.89084507466369;
   fWeightMatrix2to3[1][8] = -0.800813441713788;
   fWeightMatrix2to3[2][8] = 2.10736645918263;
   fWeightMatrix2to3[3][8] = -1.92841146020133;
   fWeightMatrix2to3[4][8] = -1.43861319793418;
   fWeightMatrix2to3[5][8] = 1.21217791726001;
   fWeightMatrix2to3[6][8] = 0.340940810026604;
   fWeightMatrix2to3[7][8] = -0.629534443502996;
   fWeightMatrix2to3[8][8] = -1.41840608651019;
   fWeightMatrix2to3[9][8] = 0.765813909849868;
   fWeightMatrix2to3[10][8] = 0.722720597586933;
   fWeightMatrix2to3[11][8] = -0.305970463249754;
   fWeightMatrix2to3[12][8] = -1.5428010709879;
   fWeightMatrix2to3[0][9] = -1.88754496970513;
   fWeightMatrix2to3[1][9] = -2.17450885156041;
   fWeightMatrix2to3[2][9] = 0.722933604501054;
   fWeightMatrix2to3[3][9] = 0.592155494251886;
   fWeightMatrix2to3[4][9] = 0.445431891584048;
   fWeightMatrix2to3[5][9] = 0.563469161121896;
   fWeightMatrix2to3[6][9] = 1.96487999086392;
   fWeightMatrix2to3[7][9] = 1.09572571847238;
   fWeightMatrix2to3[8][9] = -2.0164885939244;
   fWeightMatrix2to3[9][9] = 1.37116381911879;
   fWeightMatrix2to3[10][9] = 0.238020849269462;
   fWeightMatrix2to3[11][9] = -3.95911469803805;
   fWeightMatrix2to3[12][9] = -0.90004383999043;
   fWeightMatrix2to3[0][10] = -2.82483889054579;
   fWeightMatrix2to3[1][10] = 0.384872304641826;
   fWeightMatrix2to3[2][10] = -0.242060537118301;
   fWeightMatrix2to3[3][10] = 2.67010835184271;
   fWeightMatrix2to3[4][10] = 2.6889219886701;
   fWeightMatrix2to3[5][10] = -0.654029726307797;
   fWeightMatrix2to3[6][10] = 3.70255338045285;
   fWeightMatrix2to3[7][10] = 2.23068361823096;
   fWeightMatrix2to3[8][10] = -1.73050959351101;
   fWeightMatrix2to3[9][10] = -0.835378709197959;
   fWeightMatrix2to3[10][10] = 1.68508275015908;
   fWeightMatrix2to3[11][10] = -3.51065745315997;
   fWeightMatrix2to3[12][10] = 0.615802287990414;
   fWeightMatrix2to3[0][11] = 1.51544048768044;
   fWeightMatrix2to3[1][11] = -0.412293570340678;
   fWeightMatrix2to3[2][11] = -1.5796600865918;
   fWeightMatrix2to3[3][11] = -0.245552850058202;
   fWeightMatrix2to3[4][11] = -1.37794209918568;
   fWeightMatrix2to3[5][11] = 0.102983734745769;
   fWeightMatrix2to3[6][11] = -1.3521265931842;
   fWeightMatrix2to3[7][11] = -0.497074370034408;
   fWeightMatrix2to3[8][11] = 0.624400269517613;
   fWeightMatrix2to3[9][11] = -1.0988233731954;
   fWeightMatrix2to3[10][11] = -0.905778610069704;
   fWeightMatrix2to3[11][11] = 1.48309540911969;
   fWeightMatrix2to3[12][11] = -1.65463169674653;
   // weight matrix from layer 3 to 4
   fWeightMatrix3to4[0][0] = -4.11807044822717;
   fWeightMatrix3to4[0][1] = -1.99800037361299;
   fWeightMatrix3to4[0][2] = 2.15654365278262;
   fWeightMatrix3to4[0][3] = -3.21753852150663;
   fWeightMatrix3to4[0][4] = -2.38671013137561;
   fWeightMatrix3to4[0][5] = -1.19602944552723;
   fWeightMatrix3to4[0][6] = -3.23407142850377;
   fWeightMatrix3to4[0][7] = -2.13548512807006;
   fWeightMatrix3to4[0][8] = -3.67578569763058;
   fWeightMatrix3to4[0][9] = 2.61364307909956;
   fWeightMatrix3to4[0][10] = 1.72178114003892;
   fWeightMatrix3to4[0][11] = -3.78979616026116;
   fWeightMatrix3to4[0][12] = -1.59624004481388;
   fWeightMatrix3to4[0][13] = 0.69020868601644;
}

inline double ReadMLP_ANN_N2_NC600::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   if (inputValues.size() != (unsigned int)fLayerSize[0]-1) {
      std::cout << "Input vector needs to be of size " << fLayerSize[0]-1 << std::endl;
      return 0;
   }

   for (int l=0; l<fLayers; l++)
      for (int i=0; i<fLayerSize[l]; i++) fWeights[l][i]=0;

   for (int l=0; l<fLayers-1; l++)
      fWeights[l][fLayerSize[l]-1]=1;

   for (int i=0; i<fLayerSize[0]-1; i++)
      fWeights[0][i]=inputValues[i];

   // layer 0 to 1
   for (int o=0; o<fLayerSize[1]-1; o++) {
      for (int i=0; i<fLayerSize[0]; i++) {
         double inputVal = fWeightMatrix0to1[o][i] * fWeights[0][i];
         fWeights[1][o] += inputVal;
      }
      fWeights[1][o] = ActivationFnc(fWeights[1][o]);
   }
   // layer 1 to 2
   for (int o=0; o<fLayerSize[2]-1; o++) {
      for (int i=0; i<fLayerSize[1]; i++) {
         double inputVal = fWeightMatrix1to2[o][i] * fWeights[1][i];
         fWeights[2][o] += inputVal;
      }
      fWeights[2][o] = ActivationFnc(fWeights[2][o]);
   }
   // layer 2 to 3
   for (int o=0; o<fLayerSize[3]-1; o++) {
      for (int i=0; i<fLayerSize[2]; i++) {
         double inputVal = fWeightMatrix2to3[o][i] * fWeights[2][i];
         fWeights[3][o] += inputVal;
      }
      fWeights[3][o] = ActivationFnc(fWeights[3][o]);
   }
   // layer 3 to 4
   for (int o=0; o<fLayerSize[4]; o++) {
      for (int i=0; i<fLayerSize[3]; i++) {
         double inputVal = fWeightMatrix3to4[o][i] * fWeights[3][i];
         fWeights[4][o] += inputVal;
      }
      fWeights[4][o] = OutputActivationFnc(fWeights[4][o]);
   }

   return fWeights[4][0];
}

double ReadMLP_ANN_N2_NC600::ActivationFnc(double x) const {
   // sigmoid
   return 1.0/(1.0+exp(-x));
}
double ReadMLP_ANN_N2_NC600::OutputActivationFnc(double x) const {
   // sigmoid
   return 1.0/(1.0+exp(-x));
}
   
// Clean up
inline void ReadMLP_ANN_N2_NC600::Clear() 
{
   // clean up the arrays
   for (int lIdx = 0; lIdx < 5; lIdx++) {
      delete[] fWeights[lIdx];
   }
}
   inline double ReadMLP_ANN_N2_NC600::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            iV.reserve(inputValues.size());
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
         else {
            std::vector<double> iV;
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(*varIt);
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
      }

      return retval;
   }

//_______________________________________________________________________
inline void ReadMLP_ANN_N2_NC600::InitTransform_1()
{
   // Normalization transformation, initialisation
   fMin_1[0][0] = 110.048698425;
   fMax_1[0][0] = 1277.92980957;
   fMin_1[1][0] = 110.057556152;
   fMax_1[1][0] = 1572.76037598;
   fMin_1[2][0] = 110.048698425;
   fMax_1[2][0] = 1572.76037598;
   fMin_1[0][1] = 5.00075817108;
   fMax_1[0][1] = 29.9497737885;
   fMin_1[1][1] = 5.00135278702;
   fMax_1[1][1] = 29.9984378815;
   fMin_1[2][1] = 5.00075817108;
   fMax_1[2][1] = 29.9984378815;
   fMin_1[0][2] = -1;
   fMax_1[0][2] = 1;
   fMin_1[1][2] = -1;
   fMax_1[1][2] = 1;
   fMin_1[2][2] = -1;
   fMax_1[2][2] = 1;
   fMin_1[0][3] = -2.4711689949;
   fMax_1[0][3] = 2.37911462784;
   fMin_1[1][3] = -2.48411560059;
   fMax_1[1][3] = 2.49880051613;
   fMin_1[2][3] = -2.48411560059;
   fMax_1[2][3] = 2.49880051613;
   fMin_1[0][4] = 280.2293396;
   fMax_1[0][4] = 1251.49438477;
   fMin_1[1][4] = 280.020294189;
   fMax_1[1][4] = 1289.47937012;
   fMin_1[2][4] = 280.020294189;
   fMax_1[2][4] = 1289.47937012;
   fMin_1[0][5] = 0.0557334087789;
   fMax_1[0][5] = 300.527191162;
   fMin_1[1][5] = 0.000537815736607;
   fMax_1[1][5] = 215.792510986;
   fMin_1[2][5] = 0.000537815736607;
   fMax_1[2][5] = 300.527191162;
   fMin_1[0][6] = 117.352531433;
   fMax_1[0][6] = 2347.48510742;
   fMin_1[1][6] = 112.003395081;
   fMax_1[1][6] = 4504.87304688;
   fMin_1[2][6] = 112.003395081;
   fMax_1[2][6] = 4504.87304688;
   fMin_1[0][7] = 0;
   fMax_1[0][7] = 5;
   fMin_1[1][7] = 0;
   fMax_1[1][7] = 6;
   fMin_1[2][7] = 0;
   fMax_1[2][7] = 6;
   fMin_1[0][8] = 1;
   fMax_1[0][8] = 11;
   fMin_1[1][8] = 1;
   fMax_1[1][8] = 14;
   fMin_1[2][8] = 1;
   fMax_1[2][8] = 14;
   fMin_1[0][9] = 20.0573444366;
   fMax_1[0][9] = 1057.04370117;
   fMin_1[1][9] = -999;
   fMax_1[1][9] = 1378.42883301;
   fMin_1[2][9] = -999;
   fMax_1[2][9] = 1378.42883301;
   fMin_1[0][10] = 6.27087429166e-05;
   fMax_1[0][10] = 4.95768356323;
   fMin_1[1][10] = -999;
   fMax_1[1][10] = 5.38026332855;
   fMin_1[2][10] = -999;
   fMax_1[2][10] = 5.38026332855;
}

//_______________________________________________________________________
inline void ReadMLP_ANN_N2_NC600::Transform_1( std::vector<double>& iv, int cls) const
{
   // Normalization transformation
   if (cls < 0 || cls > 2) {
   if (2 > 1 ) cls = 2;
      else cls = 2;
   }
   const int nVar = 11;

   // get indices of used variables

   // define the indices of the variables which are transformed by this transformation
   static std::vector<int> indicesGet;
   static std::vector<int> indicesPut;

   if ( indicesGet.empty() ) { 
      indicesGet.reserve(fNvars);
      indicesGet.push_back( 0);
      indicesGet.push_back( 1);
      indicesGet.push_back( 2);
      indicesGet.push_back( 3);
      indicesGet.push_back( 4);
      indicesGet.push_back( 5);
      indicesGet.push_back( 6);
      indicesGet.push_back( 7);
      indicesGet.push_back( 8);
      indicesGet.push_back( 9);
      indicesGet.push_back( 10);
   } 
   if ( indicesPut.empty() ) { 
      indicesPut.reserve(fNvars);
      indicesPut.push_back( 0);
      indicesPut.push_back( 1);
      indicesPut.push_back( 2);
      indicesPut.push_back( 3);
      indicesPut.push_back( 4);
      indicesPut.push_back( 5);
      indicesPut.push_back( 6);
      indicesPut.push_back( 7);
      indicesPut.push_back( 8);
      indicesPut.push_back( 9);
      indicesPut.push_back( 10);
   } 

   static std::vector<double> dv;
   dv.resize(nVar);
   for (int ivar=0; ivar<nVar; ivar++) dv[ivar] = iv[indicesGet.at(ivar)];
   for (int ivar=0;ivar<11;ivar++) {
      double offset = fMin_1[cls][ivar];
      double scale  = 1.0/(fMax_1[cls][ivar]-fMin_1[cls][ivar]);
      iv[indicesPut.at(ivar)] = (dv[ivar]-offset)*scale * 2 - 1;
   }
}

//_______________________________________________________________________
inline void ReadMLP_ANN_N2_NC600::InitTransform()
{
   InitTransform_1();
}

//_______________________________________________________________________
inline void ReadMLP_ANN_N2_NC600::Transform( std::vector<double>& iv, int sigOrBgd ) const
{
   Transform_1( iv, sigOrBgd );
}
