// Class: ReadMLP_ANN_N2_NC1000
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : MLP::MLP_ANN_N2_NC1000
TMVA Release   : 4.2.1         [262657]
ROOT Release   : 6.06/01       [394753]
Creator        : brucms16
Date           : Wed Sep  7 03:23:52 2016
Host           : Linux vocms0315.cern.ch 2.6.32-573.26.1.el6.x86_64 #1 SMP Wed May 4 09:23:05 CEST 2016 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /home/t3cms/brucms16/CMSSW_8_0_14/src/UserCode/SkeletonAnalysis/macros
Training events: 15056
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
NCycles: "1000" [Number of training cycles]
HiddenLayers: "N,N,N+2" [Specification of hidden layer architecture]
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
VarTransform: "Norm" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
H: "False" [Print method-specific help message]
LearningRate: "9.000000e-02" [ANN learning rate parameter]
DecayRate: "1.000000e-02" [Decay rate for learning parameter]
# Default:
NeuronType: "sigmoid" [Neuron activation function type]
RandomSeed: "1" [Random seed for initial synapse weights (0 means unique seed for each run; default value '1')]
EstimatorType: "CE" [MSE (Mean Square Estimator) for Gaussian Likelihood or CE(Cross-Entropy) for Bernoulli Likelihood]
NeuronInputType: "sum" [Neuron input function type]
VerbosityLevel: "Default" [Verbosity level]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
TrainingMethod: "BP" [Train with Back-Propagation (BP), BFGS Algorithm (BFGS), or Genetic Algorithm (GA - slower and worse)]
TestRate: "10" [Test for overtraining performed at each #th epochs]
EpochMonitoring: "False" [Provide epoch-wise monitoring plots according to TestRate (caution: causes big ROOT output file!)]
Sampling: "1.000000e+00" [Only 'Sampling' (randomly selected) events are trained each epoch]
SamplingEpoch: "1.000000e+00" [Sampling is used for the first 'SamplingEpoch' epochs, afterwards, all events are taken for training]
SamplingImportance: "1.000000e+00" [ The sampling weights of events in epochs which successful (worse estimator than before) are multiplied with SamplingImportance, else they are divided.]
SamplingTraining: "True" [The training sample is sampled]
SamplingTesting: "False" [The testing sample is sampled]
ResetStep: "50" [How often BFGS should reset history]
Tau: "3.000000e+00" [LineSearch "size step"]
BPMode: "sequential" [Back-propagation learning mode: sequential or batch]
BatchSize: "-1" [Batch size: number of events/batch, only set if in Batch Mode, -1 for BatchSize=number_of_events]
ConvergenceImprove: "1.000000e-30" [Minimum improvement which counts as improvement (<0 means automatic convergence check is turned off)]
ConvergenceTests: "-1" [Number of steps (without improvement) required for convergence (<0 means automatic convergence check is turned off)]
UseRegulator: "False" [Use regulator to avoid over-training]
UpdateLimit: "10000" [Maximum times of regulator update]
CalculateErrors: "False" [Calculates inverse Hessian matrix at the end of the training to be able to calculate the uncertainties of an MVA value]
WeightRange: "1.000000e+00" [Take the events for the estimator calculations from small deviations from the desired value to large deviations only over the weight range]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 11
Jet1Pt                        Jet1Pt                        Jet1Pt                        Jet1Pt                                                          'F'    [110.048698425,1572.76037598]
LepPt                         LepPt                         LepPt                         LepPt                                                           'F'    [5.00075817108,29.9984378815]
LepChg                        LepChg                        LepChg                        LepChg                                                          'F'    [-1,1]
LepEta                        LepEta                        LepEta                        LepEta                                                          'F'    [-2.48411560059,2.49880051613]
Met                           Met                           Met                           Met                                                             'F'    [280.020294189,1289.47937012]
mt                            mt                            mt                            mt                                                              'F'    [0.000537815736607,300.527191162]
HT20                          HT20                          HT20                          HT20                                                            'F'    [112.003395081,4504.87304688]
NbLoose30                     NbLoose30                     NbLoose30                     NbLoose30                                                       'F'    [0,6]
Njet                          Njet                          Njet                          Njet                                                            'F'    [1,14]
JetHBpt                       JetHBpt                       JetHBpt                       JetHBpt                                                         'F'    [-999,1378.42883301]
DrJetHBLep                    DrJetHBLep                    DrJetHBLep                    DrJetHBLep                                                      'F'    [-999,5.38026332855]
NSpec 0


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadMLP_ANN_N2_NC1000 : public IClassifierReader {

 public:

   // constructor
   ReadMLP_ANN_N2_NC1000( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadMLP_ANN_N2_NC1000" ),
        fNvars( 11 ),
        fIsNormalised( false )
   {      
      // the training input variables
      const char* inputVars[] = { "Jet1Pt", "LepPt", "LepChg", "LepEta", "Met", "mt", "HT20", "NbLoose30", "Njet", "JetHBpt", "DrJetHBLep" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = -1;
      fVmax[0] = 1;
      fVmin[1] = -1;
      fVmax[1] = 0.99999988079071;
      fVmin[2] = -1;
      fVmax[2] = 1;
      fVmin[3] = -1;
      fVmax[3] = 1;
      fVmin[4] = -1;
      fVmax[4] = 1;
      fVmin[5] = -1;
      fVmax[5] = 1;
      fVmin[6] = -1;
      fVmax[6] = 1;
      fVmin[7] = -1;
      fVmax[7] = 1;
      fVmin[8] = -1;
      fVmax[8] = 1;
      fVmin[9] = -1;
      fVmax[9] = 1;
      fVmin[10] = -1;
      fVmax[10] = 1;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';
      fType[4] = 'F';
      fType[5] = 'F';
      fType[6] = 'F';
      fType[7] = 'F';
      fType[8] = 'F';
      fType[9] = 'F';
      fType[10] = 'F';

      // initialize constants
      Initialize();

      // initialize transformation
      InitTransform();
   }

   // destructor
   virtual ~ReadMLP_ANN_N2_NC1000() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // input variable transformation

   double fMin_1[3][11];
   double fMax_1[3][11];
   void InitTransform_1();
   void Transform_1( std::vector<double> & iv, int sigOrBgd ) const;
   void InitTransform();
   void Transform( std::vector<double> & iv, int sigOrBgd ) const;

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[11];
   double fVmax[11];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[11];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)

   double ActivationFnc(double x) const;
   double OutputActivationFnc(double x) const;

   int fLayers;
   int fLayerSize[5];
   double fWeightMatrix0to1[12][12];   // weight matrix from layer 0 to 1
   double fWeightMatrix1to2[12][12];   // weight matrix from layer 1 to 2
   double fWeightMatrix2to3[14][12];   // weight matrix from layer 2 to 3
   double fWeightMatrix3to4[1][14];   // weight matrix from layer 3 to 4

   double * fWeights[5];
};

inline void ReadMLP_ANN_N2_NC1000::Initialize()
{
   // build network structure
   fLayers = 5;
   fLayerSize[0] = 12; fWeights[0] = new double[12]; 
   fLayerSize[1] = 12; fWeights[1] = new double[12]; 
   fLayerSize[2] = 12; fWeights[2] = new double[12]; 
   fLayerSize[3] = 14; fWeights[3] = new double[14]; 
   fLayerSize[4] = 1; fWeights[4] = new double[1]; 
   // weight matrix from layer 0 to 1
   fWeightMatrix0to1[0][0] = -0.728916075705495;
   fWeightMatrix0to1[1][0] = 1.0357225380696;
   fWeightMatrix0to1[2][0] = 1.18191917301995;
   fWeightMatrix0to1[3][0] = 0.233792051273625;
   fWeightMatrix0to1[4][0] = -1.54751671903402;
   fWeightMatrix0to1[5][0] = -1.35167850122881;
   fWeightMatrix0to1[6][0] = 1.01833004161727;
   fWeightMatrix0to1[7][0] = 2.0413065584538;
   fWeightMatrix0to1[8][0] = -2.88605326611998;
   fWeightMatrix0to1[9][0] = 0.373156462329969;
   fWeightMatrix0to1[10][0] = -6.52631948577584;
   fWeightMatrix0to1[0][1] = -0.587983877700503;
   fWeightMatrix0to1[1][1] = -0.245973677118465;
   fWeightMatrix0to1[2][1] = -0.361871584747493;
   fWeightMatrix0to1[3][1] = -2.99231644439678;
   fWeightMatrix0to1[4][1] = 0.275937373702038;
   fWeightMatrix0to1[5][1] = 1.55280829384913;
   fWeightMatrix0to1[6][1] = 2.16234715181191;
   fWeightMatrix0to1[7][1] = 0.241352645399919;
   fWeightMatrix0to1[8][1] = 5.11109736620826;
   fWeightMatrix0to1[9][1] = 2.31268339834751;
   fWeightMatrix0to1[10][1] = -1.22321804137318;
   fWeightMatrix0to1[0][2] = 0.40626386733583;
   fWeightMatrix0to1[1][2] = 0.176754984905136;
   fWeightMatrix0to1[2][2] = -0.763716225874946;
   fWeightMatrix0to1[3][2] = -1.51639600463677;
   fWeightMatrix0to1[4][2] = -1.64529557992793;
   fWeightMatrix0to1[5][2] = -4.84259651096253;
   fWeightMatrix0to1[6][2] = -3.48881992573868;
   fWeightMatrix0to1[7][2] = 0.343384370619377;
   fWeightMatrix0to1[8][2] = -1.24914070331806;
   fWeightMatrix0to1[9][2] = 1.48841322764086;
   fWeightMatrix0to1[10][2] = -0.202204753775263;
   fWeightMatrix0to1[0][3] = 1.62327807717929;
   fWeightMatrix0to1[1][3] = 0.46241983592398;
   fWeightMatrix0to1[2][3] = -1.50045366540624;
   fWeightMatrix0to1[3][3] = 0.501346242978378;
   fWeightMatrix0to1[4][3] = 8.86228623282386;
   fWeightMatrix0to1[5][3] = -3.48035063079961;
   fWeightMatrix0to1[6][3] = 1.83060848429857;
   fWeightMatrix0to1[7][3] = 1.00408933867077;
   fWeightMatrix0to1[8][3] = -0.711907632959756;
   fWeightMatrix0to1[9][3] = -0.220709898208557;
   fWeightMatrix0to1[10][3] = -0.645987686954019;
   fWeightMatrix0to1[0][4] = 5.49878664883958;
   fWeightMatrix0to1[1][4] = -2.40818667597004;
   fWeightMatrix0to1[2][4] = 11.9917874997956;
   fWeightMatrix0to1[3][4] = 5.13004311880689;
   fWeightMatrix0to1[4][4] = -0.616922119161604;
   fWeightMatrix0to1[5][4] = -1.36521507315876;
   fWeightMatrix0to1[6][4] = 4.14785720541269;
   fWeightMatrix0to1[7][4] = 1.34380306462223;
   fWeightMatrix0to1[8][4] = -4.92630974494673;
   fWeightMatrix0to1[9][4] = 0.438770587398678;
   fWeightMatrix0to1[10][4] = -1.03684731830779;
   fWeightMatrix0to1[0][5] = 1.10788209490945;
   fWeightMatrix0to1[1][5] = -16.0156607951522;
   fWeightMatrix0to1[2][5] = -3.51424138696619;
   fWeightMatrix0to1[3][5] = 1.61682660820095;
   fWeightMatrix0to1[4][5] = 1.27594287506314;
   fWeightMatrix0to1[5][5] = 1.93969678079627;
   fWeightMatrix0to1[6][5] = 0.584458316175627;
   fWeightMatrix0to1[7][5] = -0.489079314881723;
   fWeightMatrix0to1[8][5] = 2.805010210102;
   fWeightMatrix0to1[9][5] = 2.73906440123181;
   fWeightMatrix0to1[10][5] = 2.26234945999334;
   fWeightMatrix0to1[0][6] = -3.54210431741534;
   fWeightMatrix0to1[1][6] = 3.83126956038468;
   fWeightMatrix0to1[2][6] = -5.03124428477384;
   fWeightMatrix0to1[3][6] = -4.15771104916806;
   fWeightMatrix0to1[4][6] = 1.50339362801684;
   fWeightMatrix0to1[5][6] = -0.623593485716502;
   fWeightMatrix0to1[6][6] = -0.451267467162471;
   fWeightMatrix0to1[7][6] = 1.04243009212674;
   fWeightMatrix0to1[8][6] = 4.1489337358967;
   fWeightMatrix0to1[9][6] = 2.62195919840882;
   fWeightMatrix0to1[10][6] = -1.37917117224593;
   fWeightMatrix0to1[0][7] = -5.75018658278485;
   fWeightMatrix0to1[1][7] = -1.9280788848565;
   fWeightMatrix0to1[2][7] = -0.822288692788493;
   fWeightMatrix0to1[3][7] = 0.735774331499458;
   fWeightMatrix0to1[4][7] = -0.150722822971568;
   fWeightMatrix0to1[5][7] = 2.52664022383738;
   fWeightMatrix0to1[6][7] = -2.04580521038717;
   fWeightMatrix0to1[7][7] = -0.972364519507764;
   fWeightMatrix0to1[8][7] = 0.964710737066233;
   fWeightMatrix0to1[9][7] = -0.227279149028119;
   fWeightMatrix0to1[10][7] = 0.769796139710078;
   fWeightMatrix0to1[0][8] = -4.12634435288809;
   fWeightMatrix0to1[1][8] = 0.560707804090556;
   fWeightMatrix0to1[2][8] = 1.04050741211601;
   fWeightMatrix0to1[3][8] = -0.0123085019541659;
   fWeightMatrix0to1[4][8] = -1.21681252284464;
   fWeightMatrix0to1[5][8] = -2.81167455230372;
   fWeightMatrix0to1[6][8] = -1.48521767457763;
   fWeightMatrix0to1[7][8] = 1.69723980882526;
   fWeightMatrix0to1[8][8] = -1.00994950567236;
   fWeightMatrix0to1[9][8] = -8.68531574218572;
   fWeightMatrix0to1[10][8] = -4.41763897007697;
   fWeightMatrix0to1[0][9] = -2.21439190778702;
   fWeightMatrix0to1[1][9] = 3.72876061259363;
   fWeightMatrix0to1[2][9] = -5.37688768791807;
   fWeightMatrix0to1[3][9] = 0.72718536473927;
   fWeightMatrix0to1[4][9] = -0.0533165628635025;
   fWeightMatrix0to1[5][9] = -0.705998743769562;
   fWeightMatrix0to1[6][9] = 1.92061835256942;
   fWeightMatrix0to1[7][9] = -0.828603173182017;
   fWeightMatrix0to1[8][9] = -5.00886073921217;
   fWeightMatrix0to1[9][9] = -0.239232139874713;
   fWeightMatrix0to1[10][9] = -0.914425921110567;
   fWeightMatrix0to1[0][10] = -3.0270677412734;
   fWeightMatrix0to1[1][10] = -2.17266376686112;
   fWeightMatrix0to1[2][10] = 1.50787859360614;
   fWeightMatrix0to1[3][10] = 1.24616954016403;
   fWeightMatrix0to1[4][10] = -2.53069871102513;
   fWeightMatrix0to1[5][10] = 1.25544845736201;
   fWeightMatrix0to1[6][10] = 0.609189293935687;
   fWeightMatrix0to1[7][10] = -0.760257691161391;
   fWeightMatrix0to1[8][10] = -0.279828491383747;
   fWeightMatrix0to1[9][10] = -1.66101849542349;
   fWeightMatrix0to1[10][10] = -4.32313416656099;
   fWeightMatrix0to1[0][11] = -1.13353457622223;
   fWeightMatrix0to1[1][11] = -2.80622955254107;
   fWeightMatrix0to1[2][11] = 2.54319122316794;
   fWeightMatrix0to1[3][11] = 1.4579085223394;
   fWeightMatrix0to1[4][11] = -1.08285601979135;
   fWeightMatrix0to1[5][11] = -0.788159310474302;
   fWeightMatrix0to1[6][11] = 0.343861329706377;
   fWeightMatrix0to1[7][11] = -1.61996361588342;
   fWeightMatrix0to1[8][11] = 0.403669069990923;
   fWeightMatrix0to1[9][11] = -0.313659279445542;
   fWeightMatrix0to1[10][11] = -4.51244194287782;
   // weight matrix from layer 1 to 2
   fWeightMatrix1to2[0][0] = -0.815814775904178;
   fWeightMatrix1to2[1][0] = -1.81672013114088;
   fWeightMatrix1to2[2][0] = 1.16128505757528;
   fWeightMatrix1to2[3][0] = 2.82909822104608;
   fWeightMatrix1to2[4][0] = 4.21653931560409;
   fWeightMatrix1to2[5][0] = -2.29232521819152;
   fWeightMatrix1to2[6][0] = 0.0827396489574803;
   fWeightMatrix1to2[7][0] = 5.24392631333074;
   fWeightMatrix1to2[8][0] = 1.52215572361347;
   fWeightMatrix1to2[9][0] = -0.712616059011508;
   fWeightMatrix1to2[10][0] = -5.54768047901258;
   fWeightMatrix1to2[0][1] = 1.14732578635496;
   fWeightMatrix1to2[1][1] = -2.54900894797391;
   fWeightMatrix1to2[2][1] = 3.94631708337064;
   fWeightMatrix1to2[3][1] = 2.33424636179373;
   fWeightMatrix1to2[4][1] = 0.281273890312866;
   fWeightMatrix1to2[5][1] = -0.383002653629403;
   fWeightMatrix1to2[6][1] = -1.02293609732628;
   fWeightMatrix1to2[7][1] = -6.39647985559028;
   fWeightMatrix1to2[8][1] = -0.468319377031385;
   fWeightMatrix1to2[9][1] = -0.65340711607884;
   fWeightMatrix1to2[10][1] = -1.14541230446767;
   fWeightMatrix1to2[0][2] = -5.23172216277644;
   fWeightMatrix1to2[1][2] = 0.920821512373848;
   fWeightMatrix1to2[2][2] = 3.38612780708316;
   fWeightMatrix1to2[3][2] = 2.73389506933195;
   fWeightMatrix1to2[4][2] = 0.147083032952193;
   fWeightMatrix1to2[5][2] = -1.23554781338685;
   fWeightMatrix1to2[6][2] = 2.76429434345213;
   fWeightMatrix1to2[7][2] = 5.09752530756784;
   fWeightMatrix1to2[8][2] = 1.50927321440648;
   fWeightMatrix1to2[9][2] = -0.0332164784119014;
   fWeightMatrix1to2[10][2] = -0.793639791023014;
   fWeightMatrix1to2[0][3] = -1.52721115055312;
   fWeightMatrix1to2[1][3] = -1.79292963469094;
   fWeightMatrix1to2[2][3] = -0.156691205874557;
   fWeightMatrix1to2[3][3] = -3.88593116341653;
   fWeightMatrix1to2[4][3] = -0.232667024767396;
   fWeightMatrix1to2[5][3] = 1.47369696604503;
   fWeightMatrix1to2[6][3] = 1.41371058472986;
   fWeightMatrix1to2[7][3] = 1.03793773260948;
   fWeightMatrix1to2[8][3] = 3.04841025010912;
   fWeightMatrix1to2[9][3] = 2.32741045191065;
   fWeightMatrix1to2[10][3] = -3.00952442204748;
   fWeightMatrix1to2[0][4] = 1.60111975077292;
   fWeightMatrix1to2[1][4] = -2.31759518324799;
   fWeightMatrix1to2[2][4] = -3.35531885034423;
   fWeightMatrix1to2[3][4] = -2.026807461862;
   fWeightMatrix1to2[4][4] = -3.15081322779533;
   fWeightMatrix1to2[5][4] = 0.641785600380757;
   fWeightMatrix1to2[6][4] = 2.7878835239214;
   fWeightMatrix1to2[7][4] = -1.09109571339109;
   fWeightMatrix1to2[8][4] = -3.89307499944741;
   fWeightMatrix1to2[9][4] = -2.46600326866713;
   fWeightMatrix1to2[10][4] = -3.20179619094428;
   fWeightMatrix1to2[0][5] = -0.804561295553818;
   fWeightMatrix1to2[1][5] = -0.610252145782803;
   fWeightMatrix1to2[2][5] = 1.81045176756644;
   fWeightMatrix1to2[3][5] = 0.424693652861796;
   fWeightMatrix1to2[4][5] = 0.207670030601051;
   fWeightMatrix1to2[5][5] = 1.7867996626083;
   fWeightMatrix1to2[6][5] = 1.17379873241993;
   fWeightMatrix1to2[7][5] = -4.56823414959211;
   fWeightMatrix1to2[8][5] = -1.38119326132262;
   fWeightMatrix1to2[9][5] = -2.65105916946577;
   fWeightMatrix1to2[10][5] = 1.39495449781102;
   fWeightMatrix1to2[0][6] = -0.864919530265127;
   fWeightMatrix1to2[1][6] = -1.62838413216547;
   fWeightMatrix1to2[2][6] = 2.63263015160917;
   fWeightMatrix1to2[3][6] = -0.0521239229004552;
   fWeightMatrix1to2[4][6] = 1.05621892355819;
   fWeightMatrix1to2[5][6] = -2.15948371519507;
   fWeightMatrix1to2[6][6] = 3.88772789567677;
   fWeightMatrix1to2[7][6] = 2.37280846438955;
   fWeightMatrix1to2[8][6] = 0.868357120287088;
   fWeightMatrix1to2[9][6] = 0.447842066665121;
   fWeightMatrix1to2[10][6] = 1.65358579532663;
   fWeightMatrix1to2[0][7] = 0.997998950611362;
   fWeightMatrix1to2[1][7] = 0.464038270265137;
   fWeightMatrix1to2[2][7] = -0.0343810952739068;
   fWeightMatrix1to2[3][7] = -2.18435322856301;
   fWeightMatrix1to2[4][7] = -0.919566901358928;
   fWeightMatrix1to2[5][7] = 1.70490101151991;
   fWeightMatrix1to2[6][7] = 1.30605413993066;
   fWeightMatrix1to2[7][7] = 0.776002588701124;
   fWeightMatrix1to2[8][7] = 0.0545180855126445;
   fWeightMatrix1to2[9][7] = 2.0258140300816;
   fWeightMatrix1to2[10][7] = -1.59755656805518;
   fWeightMatrix1to2[0][8] = 0.859637517473588;
   fWeightMatrix1to2[1][8] = 0.198263615590119;
   fWeightMatrix1to2[2][8] = -4.0086913467793;
   fWeightMatrix1to2[3][8] = -0.180290724270647;
   fWeightMatrix1to2[4][8] = -0.13906821592387;
   fWeightMatrix1to2[5][8] = -1.25550957329604;
   fWeightMatrix1to2[6][8] = -2.12450534513143;
   fWeightMatrix1to2[7][8] = 1.42012300951652;
   fWeightMatrix1to2[8][8] = -4.22367344167323;
   fWeightMatrix1to2[9][8] = -3.2686638680755;
   fWeightMatrix1to2[10][8] = 2.68085582519291;
   fWeightMatrix1to2[0][9] = -0.917477559097378;
   fWeightMatrix1to2[1][9] = 1.91216983637665;
   fWeightMatrix1to2[2][9] = -2.96539742087648;
   fWeightMatrix1to2[3][9] = 3.83726016292675;
   fWeightMatrix1to2[4][9] = -1.93308867391177;
   fWeightMatrix1to2[5][9] = 0.770586705141839;
   fWeightMatrix1to2[6][9] = -1.73495780274894;
   fWeightMatrix1to2[7][9] = -3.6612977149395;
   fWeightMatrix1to2[8][9] = 0.665294337321528;
   fWeightMatrix1to2[9][9] = -3.64011956074428;
   fWeightMatrix1to2[10][9] = -2.49335487656643;
   fWeightMatrix1to2[0][10] = -1.55253924117571;
   fWeightMatrix1to2[1][10] = -2.61580551454158;
   fWeightMatrix1to2[2][10] = -3.12983792448432;
   fWeightMatrix1to2[3][10] = 0.784917326492038;
   fWeightMatrix1to2[4][10] = -4.78282783431618;
   fWeightMatrix1to2[5][10] = -1.64758172312521;
   fWeightMatrix1to2[6][10] = 1.19863542285564;
   fWeightMatrix1to2[7][10] = -2.64322066114048;
   fWeightMatrix1to2[8][10] = 0.27479442264215;
   fWeightMatrix1to2[9][10] = -0.312061323039566;
   fWeightMatrix1to2[10][10] = 0.672340084710723;
   fWeightMatrix1to2[0][11] = 2.8518319565293;
   fWeightMatrix1to2[1][11] = 1.07560768431888;
   fWeightMatrix1to2[2][11] = 0.0239632099592338;
   fWeightMatrix1to2[3][11] = -3.09872955478188;
   fWeightMatrix1to2[4][11] = -1.82538550849168;
   fWeightMatrix1to2[5][11] = -1.07936389947774;
   fWeightMatrix1to2[6][11] = -3.41449298334301;
   fWeightMatrix1to2[7][11] = 1.77284031167049;
   fWeightMatrix1to2[8][11] = 1.12460831202219;
   fWeightMatrix1to2[9][11] = 2.43729238406065;
   fWeightMatrix1to2[10][11] = 0.00940163915821463;
   // weight matrix from layer 2 to 3
   fWeightMatrix2to3[0][0] = 0.678424053360122;
   fWeightMatrix2to3[1][0] = -2.30938583308252;
   fWeightMatrix2to3[2][0] = -2.00767106682819;
   fWeightMatrix2to3[3][0] = 0.740973772730146;
   fWeightMatrix2to3[4][0] = 0.998866113785735;
   fWeightMatrix2to3[5][0] = -0.950396230550641;
   fWeightMatrix2to3[6][0] = -1.32956032958449;
   fWeightMatrix2to3[7][0] = -0.334398428942271;
   fWeightMatrix2to3[8][0] = 1.88349856692091;
   fWeightMatrix2to3[9][0] = -1.51269565158302;
   fWeightMatrix2to3[10][0] = -0.853706713938921;
   fWeightMatrix2to3[11][0] = -2.92335621772225;
   fWeightMatrix2to3[12][0] = 0.6041762432296;
   fWeightMatrix2to3[0][1] = 0.526772990821548;
   fWeightMatrix2to3[1][1] = 0.73632893793011;
   fWeightMatrix2to3[2][1] = 1.8964743455886;
   fWeightMatrix2to3[3][1] = -0.399590218669188;
   fWeightMatrix2to3[4][1] = -0.553048788339757;
   fWeightMatrix2to3[5][1] = -1.59668399770594;
   fWeightMatrix2to3[6][1] = -0.843532639967302;
   fWeightMatrix2to3[7][1] = -2.62919987089674;
   fWeightMatrix2to3[8][1] = -1.60619335831438;
   fWeightMatrix2to3[9][1] = -1.27179531136398;
   fWeightMatrix2to3[10][1] = 2.3104414105368;
   fWeightMatrix2to3[11][1] = -1.68052964172988;
   fWeightMatrix2to3[12][1] = 0.971056466573401;
   fWeightMatrix2to3[0][2] = -4.24350629072171;
   fWeightMatrix2to3[1][2] = 1.64476680025247;
   fWeightMatrix2to3[2][2] = -3.96171970667842;
   fWeightMatrix2to3[3][2] = -0.490761927433825;
   fWeightMatrix2to3[4][2] = -0.111028262405957;
   fWeightMatrix2to3[5][2] = -2.25238712227385;
   fWeightMatrix2to3[6][2] = -1.24204037727063;
   fWeightMatrix2to3[7][2] = -1.28626464861284;
   fWeightMatrix2to3[8][2] = -4.11884396184315;
   fWeightMatrix2to3[9][2] = -3.35368787173338;
   fWeightMatrix2to3[10][2] = -3.75641483774662;
   fWeightMatrix2to3[11][2] = -1.30789653620923;
   fWeightMatrix2to3[12][2] = 0.143718879542682;
   fWeightMatrix2to3[0][3] = -2.49061385167663;
   fWeightMatrix2to3[1][3] = 0.546028405269927;
   fWeightMatrix2to3[2][3] = -1.68834035203439;
   fWeightMatrix2to3[3][3] = -3.76349310074414;
   fWeightMatrix2to3[4][3] = -2.73133821006472;
   fWeightMatrix2to3[5][3] = -1.64709676951372;
   fWeightMatrix2to3[6][3] = -2.55153067235174;
   fWeightMatrix2to3[7][3] = -1.01823178575129;
   fWeightMatrix2to3[8][3] = -1.82941689351841;
   fWeightMatrix2to3[9][3] = -3.35357114858706;
   fWeightMatrix2to3[10][3] = 0.299604353626069;
   fWeightMatrix2to3[11][3] = 1.66625311844839;
   fWeightMatrix2to3[12][3] = -2.36639298423188;
   fWeightMatrix2to3[0][4] = 0.747382226516515;
   fWeightMatrix2to3[1][4] = -2.22480658693368;
   fWeightMatrix2to3[2][4] = 2.92388460621863;
   fWeightMatrix2to3[3][4] = 0.384471157425969;
   fWeightMatrix2to3[4][4] = -1.25637910501222;
   fWeightMatrix2to3[5][4] = -1.52667399232418;
   fWeightMatrix2to3[6][4] = -0.61900381169493;
   fWeightMatrix2to3[7][4] = -2.44424068728107;
   fWeightMatrix2to3[8][4] = -0.302832005772137;
   fWeightMatrix2to3[9][4] = 2.77409970354444;
   fWeightMatrix2to3[10][4] = 1.45480819288478;
   fWeightMatrix2to3[11][4] = -0.219973377099013;
   fWeightMatrix2to3[12][4] = -1.92505882931736;
   fWeightMatrix2to3[0][5] = 0.554450786145033;
   fWeightMatrix2to3[1][5] = -2.03484015284613;
   fWeightMatrix2to3[2][5] = 0.338856377624554;
   fWeightMatrix2to3[3][5] = -1.66478023126965;
   fWeightMatrix2to3[4][5] = -2.07556802192058;
   fWeightMatrix2to3[5][5] = 0.0518796717151123;
   fWeightMatrix2to3[6][5] = 1.82129373830039;
   fWeightMatrix2to3[7][5] = 0.507033012710085;
   fWeightMatrix2to3[8][5] = 0.560458382905112;
   fWeightMatrix2to3[9][5] = 0.257868721847741;
   fWeightMatrix2to3[10][5] = -0.357684067166557;
   fWeightMatrix2to3[11][5] = -0.415466216380624;
   fWeightMatrix2to3[12][5] = 0.178302810748652;
   fWeightMatrix2to3[0][6] = 0.467379833261808;
   fWeightMatrix2to3[1][6] = -0.488615406132777;
   fWeightMatrix2to3[2][6] = 0.866163971744126;
   fWeightMatrix2to3[3][6] = -2.58457015834698;
   fWeightMatrix2to3[4][6] = -1.58850947421003;
   fWeightMatrix2to3[5][6] = -0.610111323285562;
   fWeightMatrix2to3[6][6] = -1.16062131504212;
   fWeightMatrix2to3[7][6] = -1.81851239433845;
   fWeightMatrix2to3[8][6] = -0.154565385186449;
   fWeightMatrix2to3[9][6] = 2.38169329724551;
   fWeightMatrix2to3[10][6] = 0.286809852119315;
   fWeightMatrix2to3[11][6] = -2.23500266289832;
   fWeightMatrix2to3[12][6] = -2.16571497884561;
   fWeightMatrix2to3[0][7] = -2.47263156952231;
   fWeightMatrix2to3[1][7] = -0.598124057359497;
   fWeightMatrix2to3[2][7] = 2.12668192716269;
   fWeightMatrix2to3[3][7] = -2.22812152914464;
   fWeightMatrix2to3[4][7] = -1.97465262700182;
   fWeightMatrix2to3[5][7] = -0.172217369247215;
   fWeightMatrix2to3[6][7] = -3.18282780836484;
   fWeightMatrix2to3[7][7] = -2.79497132895556;
   fWeightMatrix2to3[8][7] = -2.42445905173527;
   fWeightMatrix2to3[9][7] = -0.00818850983800629;
   fWeightMatrix2to3[10][7] = -0.983312038262382;
   fWeightMatrix2to3[11][7] = -3.92195715546626;
   fWeightMatrix2to3[12][7] = -1.21287950392828;
   fWeightMatrix2to3[0][8] = -2.8933002659981;
   fWeightMatrix2to3[1][8] = -0.802131288087908;
   fWeightMatrix2to3[2][8] = 2.11320116755054;
   fWeightMatrix2to3[3][8] = -1.92936793625333;
   fWeightMatrix2to3[4][8] = -1.43985571926001;
   fWeightMatrix2to3[5][8] = 1.21460768054664;
   fWeightMatrix2to3[6][8] = 0.343783808763286;
   fWeightMatrix2to3[7][8] = -0.631331053454252;
   fWeightMatrix2to3[8][8] = -1.41922710072736;
   fWeightMatrix2to3[9][8] = 0.765756114590766;
   fWeightMatrix2to3[10][8] = 0.719277462828955;
   fWeightMatrix2to3[11][8] = -0.314499960428757;
   fWeightMatrix2to3[12][8] = -1.54401998890514;
   fWeightMatrix2to3[0][9] = -1.89273648905935;
   fWeightMatrix2to3[1][9] = -2.17370494192075;
   fWeightMatrix2to3[2][9] = 0.71386297530636;
   fWeightMatrix2to3[3][9] = 0.589444021320011;
   fWeightMatrix2to3[4][9] = 0.445478477959493;
   fWeightMatrix2to3[5][9] = 0.566363756578831;
   fWeightMatrix2to3[6][9] = 1.97313648439787;
   fWeightMatrix2to3[7][9] = 1.0967002427884;
   fWeightMatrix2to3[8][9] = -2.02439713821362;
   fWeightMatrix2to3[9][9] = 1.36106966873394;
   fWeightMatrix2to3[10][9] = 0.238745787076558;
   fWeightMatrix2to3[11][9] = -3.95947358328938;
   fWeightMatrix2to3[12][9] = -0.901329835989878;
   fWeightMatrix2to3[0][10] = -2.83162625488504;
   fWeightMatrix2to3[1][10] = 0.380316349754799;
   fWeightMatrix2to3[2][10] = -0.238109820103602;
   fWeightMatrix2to3[3][10] = 2.6797329174931;
   fWeightMatrix2to3[4][10] = 2.69483008845905;
   fWeightMatrix2to3[5][10] = -0.655435229620449;
   fWeightMatrix2to3[6][10] = 3.71235398521582;
   fWeightMatrix2to3[7][10] = 2.23769355019042;
   fWeightMatrix2to3[8][10] = -1.73783078446671;
   fWeightMatrix2to3[9][10] = -0.830883266625389;
   fWeightMatrix2to3[10][10] = 1.69121438702965;
   fWeightMatrix2to3[11][10] = -3.50932167394023;
   fWeightMatrix2to3[12][10] = 0.615933695007247;
   fWeightMatrix2to3[0][11] = 1.52152771403428;
   fWeightMatrix2to3[1][11] = -0.415709554346816;
   fWeightMatrix2to3[2][11] = -1.57361176807913;
   fWeightMatrix2to3[3][11] = -0.242830613111964;
   fWeightMatrix2to3[4][11] = -1.37716934158527;
   fWeightMatrix2to3[5][11] = 0.104881669550218;
   fWeightMatrix2to3[6][11] = -1.35087953492105;
   fWeightMatrix2to3[7][11] = -0.495675797331934;
   fWeightMatrix2to3[8][11] = 0.628908915974708;
   fWeightMatrix2to3[9][11] = -1.10278124866957;
   fWeightMatrix2to3[10][11] = -0.904464853782927;
   fWeightMatrix2to3[11][11] = 1.48856571309834;
   fWeightMatrix2to3[12][11] = -1.65593445701441;
   // weight matrix from layer 3 to 4
   fWeightMatrix3to4[0][0] = -4.13385869659464;
   fWeightMatrix3to4[0][1] = -2.00707136301566;
   fWeightMatrix3to4[0][2] = 2.15546628658092;
   fWeightMatrix3to4[0][3] = -3.22287042340023;
   fWeightMatrix3to4[0][4] = -2.3892193429276;
   fWeightMatrix3to4[0][5] = -1.20281372729916;
   fWeightMatrix3to4[0][6] = -3.24612954274831;
   fWeightMatrix3to4[0][7] = -2.13957997912348;
   fWeightMatrix3to4[0][8] = -3.6874461805833;
   fWeightMatrix3to4[0][9] = 2.6228219437074;
   fWeightMatrix3to4[0][10] = 1.72868455386822;
   fWeightMatrix3to4[0][11] = -3.80155570049742;
   fWeightMatrix3to4[0][12] = -1.59555788360804;
   fWeightMatrix3to4[0][13] = 0.692871266786134;
}

inline double ReadMLP_ANN_N2_NC1000::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   if (inputValues.size() != (unsigned int)fLayerSize[0]-1) {
      std::cout << "Input vector needs to be of size " << fLayerSize[0]-1 << std::endl;
      return 0;
   }

   for (int l=0; l<fLayers; l++)
      for (int i=0; i<fLayerSize[l]; i++) fWeights[l][i]=0;

   for (int l=0; l<fLayers-1; l++)
      fWeights[l][fLayerSize[l]-1]=1;

   for (int i=0; i<fLayerSize[0]-1; i++)
      fWeights[0][i]=inputValues[i];

   // layer 0 to 1
   for (int o=0; o<fLayerSize[1]-1; o++) {
      for (int i=0; i<fLayerSize[0]; i++) {
         double inputVal = fWeightMatrix0to1[o][i] * fWeights[0][i];
         fWeights[1][o] += inputVal;
      }
      fWeights[1][o] = ActivationFnc(fWeights[1][o]);
   }
   // layer 1 to 2
   for (int o=0; o<fLayerSize[2]-1; o++) {
      for (int i=0; i<fLayerSize[1]; i++) {
         double inputVal = fWeightMatrix1to2[o][i] * fWeights[1][i];
         fWeights[2][o] += inputVal;
      }
      fWeights[2][o] = ActivationFnc(fWeights[2][o]);
   }
   // layer 2 to 3
   for (int o=0; o<fLayerSize[3]-1; o++) {
      for (int i=0; i<fLayerSize[2]; i++) {
         double inputVal = fWeightMatrix2to3[o][i] * fWeights[2][i];
         fWeights[3][o] += inputVal;
      }
      fWeights[3][o] = ActivationFnc(fWeights[3][o]);
   }
   // layer 3 to 4
   for (int o=0; o<fLayerSize[4]; o++) {
      for (int i=0; i<fLayerSize[3]; i++) {
         double inputVal = fWeightMatrix3to4[o][i] * fWeights[3][i];
         fWeights[4][o] += inputVal;
      }
      fWeights[4][o] = OutputActivationFnc(fWeights[4][o]);
   }

   return fWeights[4][0];
}

double ReadMLP_ANN_N2_NC1000::ActivationFnc(double x) const {
   // sigmoid
   return 1.0/(1.0+exp(-x));
}
double ReadMLP_ANN_N2_NC1000::OutputActivationFnc(double x) const {
   // sigmoid
   return 1.0/(1.0+exp(-x));
}
   
// Clean up
inline void ReadMLP_ANN_N2_NC1000::Clear() 
{
   // clean up the arrays
   for (int lIdx = 0; lIdx < 5; lIdx++) {
      delete[] fWeights[lIdx];
   }
}
   inline double ReadMLP_ANN_N2_NC1000::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            iV.reserve(inputValues.size());
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
         else {
            std::vector<double> iV;
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(*varIt);
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
      }

      return retval;
   }

//_______________________________________________________________________
inline void ReadMLP_ANN_N2_NC1000::InitTransform_1()
{
   // Normalization transformation, initialisation
   fMin_1[0][0] = 110.048698425;
   fMax_1[0][0] = 1277.92980957;
   fMin_1[1][0] = 110.057556152;
   fMax_1[1][0] = 1572.76037598;
   fMin_1[2][0] = 110.048698425;
   fMax_1[2][0] = 1572.76037598;
   fMin_1[0][1] = 5.00075817108;
   fMax_1[0][1] = 29.9497737885;
   fMin_1[1][1] = 5.00135278702;
   fMax_1[1][1] = 29.9984378815;
   fMin_1[2][1] = 5.00075817108;
   fMax_1[2][1] = 29.9984378815;
   fMin_1[0][2] = -1;
   fMax_1[0][2] = 1;
   fMin_1[1][2] = -1;
   fMax_1[1][2] = 1;
   fMin_1[2][2] = -1;
   fMax_1[2][2] = 1;
   fMin_1[0][3] = -2.4711689949;
   fMax_1[0][3] = 2.37911462784;
   fMin_1[1][3] = -2.48411560059;
   fMax_1[1][3] = 2.49880051613;
   fMin_1[2][3] = -2.48411560059;
   fMax_1[2][3] = 2.49880051613;
   fMin_1[0][4] = 280.2293396;
   fMax_1[0][4] = 1251.49438477;
   fMin_1[1][4] = 280.020294189;
   fMax_1[1][4] = 1289.47937012;
   fMin_1[2][4] = 280.020294189;
   fMax_1[2][4] = 1289.47937012;
   fMin_1[0][5] = 0.0557334087789;
   fMax_1[0][5] = 300.527191162;
   fMin_1[1][5] = 0.000537815736607;
   fMax_1[1][5] = 215.792510986;
   fMin_1[2][5] = 0.000537815736607;
   fMax_1[2][5] = 300.527191162;
   fMin_1[0][6] = 117.352531433;
   fMax_1[0][6] = 2347.48510742;
   fMin_1[1][6] = 112.003395081;
   fMax_1[1][6] = 4504.87304688;
   fMin_1[2][6] = 112.003395081;
   fMax_1[2][6] = 4504.87304688;
   fMin_1[0][7] = 0;
   fMax_1[0][7] = 5;
   fMin_1[1][7] = 0;
   fMax_1[1][7] = 6;
   fMin_1[2][7] = 0;
   fMax_1[2][7] = 6;
   fMin_1[0][8] = 1;
   fMax_1[0][8] = 11;
   fMin_1[1][8] = 1;
   fMax_1[1][8] = 14;
   fMin_1[2][8] = 1;
   fMax_1[2][8] = 14;
   fMin_1[0][9] = 20.0573444366;
   fMax_1[0][9] = 1057.04370117;
   fMin_1[1][9] = -999;
   fMax_1[1][9] = 1378.42883301;
   fMin_1[2][9] = -999;
   fMax_1[2][9] = 1378.42883301;
   fMin_1[0][10] = 6.27087429166e-05;
   fMax_1[0][10] = 4.95768356323;
   fMin_1[1][10] = -999;
   fMax_1[1][10] = 5.38026332855;
   fMin_1[2][10] = -999;
   fMax_1[2][10] = 5.38026332855;
}

//_______________________________________________________________________
inline void ReadMLP_ANN_N2_NC1000::Transform_1( std::vector<double>& iv, int cls) const
{
   // Normalization transformation
   if (cls < 0 || cls > 2) {
   if (2 > 1 ) cls = 2;
      else cls = 2;
   }
   const int nVar = 11;

   // get indices of used variables

   // define the indices of the variables which are transformed by this transformation
   static std::vector<int> indicesGet;
   static std::vector<int> indicesPut;

   if ( indicesGet.empty() ) { 
      indicesGet.reserve(fNvars);
      indicesGet.push_back( 0);
      indicesGet.push_back( 1);
      indicesGet.push_back( 2);
      indicesGet.push_back( 3);
      indicesGet.push_back( 4);
      indicesGet.push_back( 5);
      indicesGet.push_back( 6);
      indicesGet.push_back( 7);
      indicesGet.push_back( 8);
      indicesGet.push_back( 9);
      indicesGet.push_back( 10);
   } 
   if ( indicesPut.empty() ) { 
      indicesPut.reserve(fNvars);
      indicesPut.push_back( 0);
      indicesPut.push_back( 1);
      indicesPut.push_back( 2);
      indicesPut.push_back( 3);
      indicesPut.push_back( 4);
      indicesPut.push_back( 5);
      indicesPut.push_back( 6);
      indicesPut.push_back( 7);
      indicesPut.push_back( 8);
      indicesPut.push_back( 9);
      indicesPut.push_back( 10);
   } 

   static std::vector<double> dv;
   dv.resize(nVar);
   for (int ivar=0; ivar<nVar; ivar++) dv[ivar] = iv[indicesGet.at(ivar)];
   for (int ivar=0;ivar<11;ivar++) {
      double offset = fMin_1[cls][ivar];
      double scale  = 1.0/(fMax_1[cls][ivar]-fMin_1[cls][ivar]);
      iv[indicesPut.at(ivar)] = (dv[ivar]-offset)*scale * 2 - 1;
   }
}

//_______________________________________________________________________
inline void ReadMLP_ANN_N2_NC1000::InitTransform()
{
   InitTransform_1();
}

//_______________________________________________________________________
inline void ReadMLP_ANN_N2_NC1000::Transform( std::vector<double>& iv, int sigOrBgd ) const
{
   Transform_1( iv, sigOrBgd );
}
