// Class: ReadMLP_ANN_N3_NC300
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : MLP::MLP_ANN_N3_NC300
TMVA Release   : 4.2.1         [262657]
ROOT Release   : 6.06/01       [394753]
Creator        : brucms16
Date           : Wed Sep  7 03:28:08 2016
Host           : Linux vocms0315.cern.ch 2.6.32-573.26.1.el6.x86_64 #1 SMP Wed May 4 09:23:05 CEST 2016 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /home/t3cms/brucms16/CMSSW_8_0_14/src/UserCode/SkeletonAnalysis/macros
Training events: 15056
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
NCycles: "300" [Number of training cycles]
HiddenLayers: "N,N,N+3" [Specification of hidden layer architecture]
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
VarTransform: "Norm" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
H: "False" [Print method-specific help message]
LearningRate: "9.000000e-02" [ANN learning rate parameter]
DecayRate: "1.000000e-02" [Decay rate for learning parameter]
# Default:
NeuronType: "sigmoid" [Neuron activation function type]
RandomSeed: "1" [Random seed for initial synapse weights (0 means unique seed for each run; default value '1')]
EstimatorType: "CE" [MSE (Mean Square Estimator) for Gaussian Likelihood or CE(Cross-Entropy) for Bernoulli Likelihood]
NeuronInputType: "sum" [Neuron input function type]
VerbosityLevel: "Default" [Verbosity level]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
TrainingMethod: "BP" [Train with Back-Propagation (BP), BFGS Algorithm (BFGS), or Genetic Algorithm (GA - slower and worse)]
TestRate: "10" [Test for overtraining performed at each #th epochs]
EpochMonitoring: "False" [Provide epoch-wise monitoring plots according to TestRate (caution: causes big ROOT output file!)]
Sampling: "1.000000e+00" [Only 'Sampling' (randomly selected) events are trained each epoch]
SamplingEpoch: "1.000000e+00" [Sampling is used for the first 'SamplingEpoch' epochs, afterwards, all events are taken for training]
SamplingImportance: "1.000000e+00" [ The sampling weights of events in epochs which successful (worse estimator than before) are multiplied with SamplingImportance, else they are divided.]
SamplingTraining: "True" [The training sample is sampled]
SamplingTesting: "False" [The testing sample is sampled]
ResetStep: "50" [How often BFGS should reset history]
Tau: "3.000000e+00" [LineSearch "size step"]
BPMode: "sequential" [Back-propagation learning mode: sequential or batch]
BatchSize: "-1" [Batch size: number of events/batch, only set if in Batch Mode, -1 for BatchSize=number_of_events]
ConvergenceImprove: "1.000000e-30" [Minimum improvement which counts as improvement (<0 means automatic convergence check is turned off)]
ConvergenceTests: "-1" [Number of steps (without improvement) required for convergence (<0 means automatic convergence check is turned off)]
UseRegulator: "False" [Use regulator to avoid over-training]
UpdateLimit: "10000" [Maximum times of regulator update]
CalculateErrors: "False" [Calculates inverse Hessian matrix at the end of the training to be able to calculate the uncertainties of an MVA value]
WeightRange: "1.000000e+00" [Take the events for the estimator calculations from small deviations from the desired value to large deviations only over the weight range]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 11
Jet1Pt                        Jet1Pt                        Jet1Pt                        Jet1Pt                                                          'F'    [110.048698425,1572.76037598]
LepPt                         LepPt                         LepPt                         LepPt                                                           'F'    [5.00075817108,29.9984378815]
LepChg                        LepChg                        LepChg                        LepChg                                                          'F'    [-1,1]
LepEta                        LepEta                        LepEta                        LepEta                                                          'F'    [-2.48411560059,2.49880051613]
Met                           Met                           Met                           Met                                                             'F'    [280.020294189,1289.47937012]
mt                            mt                            mt                            mt                                                              'F'    [0.000537815736607,300.527191162]
HT20                          HT20                          HT20                          HT20                                                            'F'    [112.003395081,4504.87304688]
NbLoose30                     NbLoose30                     NbLoose30                     NbLoose30                                                       'F'    [0,6]
Njet                          Njet                          Njet                          Njet                                                            'F'    [1,14]
JetHBpt                       JetHBpt                       JetHBpt                       JetHBpt                                                         'F'    [-999,1378.42883301]
DrJetHBLep                    DrJetHBLep                    DrJetHBLep                    DrJetHBLep                                                      'F'    [-999,5.38026332855]
NSpec 0


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadMLP_ANN_N3_NC300 : public IClassifierReader {

 public:

   // constructor
   ReadMLP_ANN_N3_NC300( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadMLP_ANN_N3_NC300" ),
        fNvars( 11 ),
        fIsNormalised( false )
   {      
      // the training input variables
      const char* inputVars[] = { "Jet1Pt", "LepPt", "LepChg", "LepEta", "Met", "mt", "HT20", "NbLoose30", "Njet", "JetHBpt", "DrJetHBLep" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = -1;
      fVmax[0] = 1;
      fVmin[1] = -1;
      fVmax[1] = 0.99999988079071;
      fVmin[2] = -1;
      fVmax[2] = 1;
      fVmin[3] = -1;
      fVmax[3] = 1;
      fVmin[4] = -1;
      fVmax[4] = 1;
      fVmin[5] = -1;
      fVmax[5] = 1;
      fVmin[6] = -1;
      fVmax[6] = 1;
      fVmin[7] = -1;
      fVmax[7] = 1;
      fVmin[8] = -1;
      fVmax[8] = 1;
      fVmin[9] = -1;
      fVmax[9] = 1;
      fVmin[10] = -1;
      fVmax[10] = 1;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';
      fType[4] = 'F';
      fType[5] = 'F';
      fType[6] = 'F';
      fType[7] = 'F';
      fType[8] = 'F';
      fType[9] = 'F';
      fType[10] = 'F';

      // initialize constants
      Initialize();

      // initialize transformation
      InitTransform();
   }

   // destructor
   virtual ~ReadMLP_ANN_N3_NC300() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // input variable transformation

   double fMin_1[3][11];
   double fMax_1[3][11];
   void InitTransform_1();
   void Transform_1( std::vector<double> & iv, int sigOrBgd ) const;
   void InitTransform();
   void Transform( std::vector<double> & iv, int sigOrBgd ) const;

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[11];
   double fVmax[11];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[11];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)

   double ActivationFnc(double x) const;
   double OutputActivationFnc(double x) const;

   int fLayers;
   int fLayerSize[5];
   double fWeightMatrix0to1[12][12];   // weight matrix from layer 0 to 1
   double fWeightMatrix1to2[12][12];   // weight matrix from layer 1 to 2
   double fWeightMatrix2to3[15][12];   // weight matrix from layer 2 to 3
   double fWeightMatrix3to4[1][15];   // weight matrix from layer 3 to 4

   double * fWeights[5];
};

inline void ReadMLP_ANN_N3_NC300::Initialize()
{
   // build network structure
   fLayers = 5;
   fLayerSize[0] = 12; fWeights[0] = new double[12]; 
   fLayerSize[1] = 12; fWeights[1] = new double[12]; 
   fLayerSize[2] = 12; fWeights[2] = new double[12]; 
   fLayerSize[3] = 15; fWeights[3] = new double[15]; 
   fLayerSize[4] = 1; fWeights[4] = new double[1]; 
   // weight matrix from layer 0 to 1
   fWeightMatrix0to1[0][0] = 0.867571410546634;
   fWeightMatrix0to1[1][0] = 0.594384700070302;
   fWeightMatrix0to1[2][0] = 1.431191708731;
   fWeightMatrix0to1[3][0] = 4.11919336444273;
   fWeightMatrix0to1[4][0] = -2.01656768293664;
   fWeightMatrix0to1[5][0] = -0.553400541395452;
   fWeightMatrix0to1[6][0] = 1.45252827428751;
   fWeightMatrix0to1[7][0] = 1.54760859444129;
   fWeightMatrix0to1[8][0] = -2.29967258434775;
   fWeightMatrix0to1[9][0] = -0.378913474016866;
   fWeightMatrix0to1[10][0] = -3.39517772933438;
   fWeightMatrix0to1[0][1] = 2.48086014758266;
   fWeightMatrix0to1[1][1] = -0.402879807831984;
   fWeightMatrix0to1[2][1] = -3.14056353496638;
   fWeightMatrix0to1[3][1] = -0.442950192931518;
   fWeightMatrix0to1[4][1] = 0.939774244616972;
   fWeightMatrix0to1[5][1] = -1.87726123913297;
   fWeightMatrix0to1[6][1] = 2.38239396484752;
   fWeightMatrix0to1[7][1] = -0.118898726068396;
   fWeightMatrix0to1[8][1] = 3.15073224975742;
   fWeightMatrix0to1[9][1] = 1.10214867933829;
   fWeightMatrix0to1[10][1] = -0.212763376028323;
   fWeightMatrix0to1[0][2] = 1.41882203487126;
   fWeightMatrix0to1[1][2] = 0.0753727855269691;
   fWeightMatrix0to1[2][2] = 0.460172570517951;
   fWeightMatrix0to1[3][2] = -4.11163066614676;
   fWeightMatrix0to1[4][2] = 1.23939779953474;
   fWeightMatrix0to1[5][2] = 0.596340259547544;
   fWeightMatrix0to1[6][2] = -3.66020792930364;
   fWeightMatrix0to1[7][2] = 0.426571645983567;
   fWeightMatrix0to1[8][2] = -0.350552314524964;
   fWeightMatrix0to1[9][2] = -0.0942897744810148;
   fWeightMatrix0to1[10][2] = -0.771040292348931;
   fWeightMatrix0to1[0][3] = -0.0106155082937296;
   fWeightMatrix0to1[1][3] = 0.0687887843721969;
   fWeightMatrix0to1[2][3] = 1.5635528128218;
   fWeightMatrix0to1[3][3] = -0.953005124458514;
   fWeightMatrix0to1[4][3] = 1.53842128747819;
   fWeightMatrix0to1[5][3] = -2.44768331919535;
   fWeightMatrix0to1[6][3] = 0.59574215833873;
   fWeightMatrix0to1[7][3] = 1.03939118815867;
   fWeightMatrix0to1[8][3] = -0.359105015736152;
   fWeightMatrix0to1[9][3] = 5.23600840077312;
   fWeightMatrix0to1[10][3] = -3.0252842052122;
   fWeightMatrix0to1[0][4] = 6.29743183937469;
   fWeightMatrix0to1[1][4] = -3.07794212249553;
   fWeightMatrix0to1[2][4] = 9.06239789290762;
   fWeightMatrix0to1[3][4] = 0.728498542387651;
   fWeightMatrix0to1[4][4] = 2.39879027230811;
   fWeightMatrix0to1[5][4] = 6.70206816124514;
   fWeightMatrix0to1[6][4] = 4.04209119168785;
   fWeightMatrix0to1[7][4] = 1.13258739568713;
   fWeightMatrix0to1[8][4] = -4.38578858654234;
   fWeightMatrix0to1[9][4] = 0.105760874456131;
   fWeightMatrix0to1[10][4] = -0.637642638703026;
   fWeightMatrix0to1[0][5] = -1.58465333571663;
   fWeightMatrix0to1[1][5] = -17.4370346972076;
   fWeightMatrix0to1[2][5] = 0.0602505699830196;
   fWeightMatrix0to1[3][5] = 3.43605210522334;
   fWeightMatrix0to1[4][5] = 0.13182042351536;
   fWeightMatrix0to1[5][5] = -2.82814309327635;
   fWeightMatrix0to1[6][5] = 0.00315411040622832;
   fWeightMatrix0to1[7][5] = -0.660687649619979;
   fWeightMatrix0to1[8][5] = 2.76652949408491;
   fWeightMatrix0to1[9][5] = 2.42974759269103;
   fWeightMatrix0to1[10][5] = 3.38700037595835;
   fWeightMatrix0to1[0][6] = -1.39606259051067;
   fWeightMatrix0to1[1][6] = 3.4986072146901;
   fWeightMatrix0to1[2][6] = -4.3331768665177;
   fWeightMatrix0to1[3][6] = -0.728157567393152;
   fWeightMatrix0to1[4][6] = -0.606945618546081;
   fWeightMatrix0to1[5][6] = -1.95659991084275;
   fWeightMatrix0to1[6][6] = -0.115114033771796;
   fWeightMatrix0to1[7][6] = 0.706713351028508;
   fWeightMatrix0to1[8][6] = 3.71230715752564;
   fWeightMatrix0to1[9][6] = 1.72834934632328;
   fWeightMatrix0to1[10][6] = -0.717814853153501;
   fWeightMatrix0to1[0][7] = -6.61876507328679;
   fWeightMatrix0to1[1][7] = -0.341400698575691;
   fWeightMatrix0to1[2][7] = -3.77490495411609;
   fWeightMatrix0to1[3][7] = 0.355492895209997;
   fWeightMatrix0to1[4][7] = 1.6604395465191;
   fWeightMatrix0to1[5][7] = 1.38836217434298;
   fWeightMatrix0to1[6][7] = -2.91219301800899;
   fWeightMatrix0to1[7][7] = -1.25399866727737;
   fWeightMatrix0to1[8][7] = 0.668096160357021;
   fWeightMatrix0to1[9][7] = 0.186760463743881;
   fWeightMatrix0to1[10][7] = -0.84613559491717;
   fWeightMatrix0to1[0][8] = -5.91121138150045;
   fWeightMatrix0to1[1][8] = 0.241716284237421;
   fWeightMatrix0to1[2][8] = -0.746660706287754;
   fWeightMatrix0to1[3][8] = 1.32186844132757;
   fWeightMatrix0to1[4][8] = 1.626896087024;
   fWeightMatrix0to1[5][8] = -0.977205481292271;
   fWeightMatrix0to1[6][8] = -2.24828513812439;
   fWeightMatrix0to1[7][8] = 1.67811240722417;
   fWeightMatrix0to1[8][8] = -3.80509810144462;
   fWeightMatrix0to1[9][8] = -5.77093296215947;
   fWeightMatrix0to1[10][8] = -6.59447287813537;
   fWeightMatrix0to1[0][9] = -1.45465852917932;
   fWeightMatrix0to1[1][9] = 3.17066700756071;
   fWeightMatrix0to1[2][9] = -5.2512113396313;
   fWeightMatrix0to1[3][9] = 1.04332030951802;
   fWeightMatrix0to1[4][9] = 1.32045496153942;
   fWeightMatrix0to1[5][9] = 0.0719948912444556;
   fWeightMatrix0to1[6][9] = 3.70874360757796;
   fWeightMatrix0to1[7][9] = -1.08323349351778;
   fWeightMatrix0to1[8][9] = 0.427389215067531;
   fWeightMatrix0to1[9][9] = -1.28496426455023;
   fWeightMatrix0to1[10][9] = -0.347575552317968;
   fWeightMatrix0to1[0][10] = -1.76078236223704;
   fWeightMatrix0to1[1][10] = -2.32686695136422;
   fWeightMatrix0to1[2][10] = 1.20801818902207;
   fWeightMatrix0to1[3][10] = 1.02612461295064;
   fWeightMatrix0to1[4][10] = -1.75910974084918;
   fWeightMatrix0to1[5][10] = 2.69331071777198;
   fWeightMatrix0to1[6][10] = 0.507062202436003;
   fWeightMatrix0to1[7][10] = -0.620622858573388;
   fWeightMatrix0to1[8][10] = -0.493462763017072;
   fWeightMatrix0to1[9][10] = -2.59951882351744;
   fWeightMatrix0to1[10][10] = -4.40583692445137;
   fWeightMatrix0to1[0][11] = 0.19251713345895;
   fWeightMatrix0to1[1][11] = -3.00329158507782;
   fWeightMatrix0to1[2][11] = 2.43033156906922;
   fWeightMatrix0to1[3][11] = 1.31967565247065;
   fWeightMatrix0to1[4][11] = -0.378474894187279;
   fWeightMatrix0to1[5][11] = 0.453714635256649;
   fWeightMatrix0to1[6][11] = 0.208794724588323;
   fWeightMatrix0to1[7][11] = -1.46508799778467;
   fWeightMatrix0to1[8][11] = 0.225166539342743;
   fWeightMatrix0to1[9][11] = -1.0223069969174;
   fWeightMatrix0to1[10][11] = -4.49220482620592;
   // weight matrix from layer 1 to 2
   fWeightMatrix1to2[0][0] = 0.620108334898215;
   fWeightMatrix1to2[1][0] = -0.766795019210246;
   fWeightMatrix1to2[2][0] = 1.72273606377562;
   fWeightMatrix1to2[3][0] = -1.38806671003347;
   fWeightMatrix1to2[4][0] = 3.31255694112242;
   fWeightMatrix1to2[5][0] = -2.25928122065306;
   fWeightMatrix1to2[6][0] = -1.4376698190032;
   fWeightMatrix1to2[7][0] = 3.5666903327875;
   fWeightMatrix1to2[8][0] = 1.81134634203915;
   fWeightMatrix1to2[9][0] = -3.80542284449496;
   fWeightMatrix1to2[10][0] = -1.71372500264415;
   fWeightMatrix1to2[0][1] = 1.27485115878202;
   fWeightMatrix1to2[1][1] = -3.54429179213529;
   fWeightMatrix1to2[2][1] = 0.826323346825254;
   fWeightMatrix1to2[3][1] = 3.34505241450007;
   fWeightMatrix1to2[4][1] = -2.46338298964412;
   fWeightMatrix1to2[5][1] = 0.27970391023462;
   fWeightMatrix1to2[6][1] = -2.30839048959323;
   fWeightMatrix1to2[7][1] = -5.06649945958045;
   fWeightMatrix1to2[8][1] = -2.25369883341881;
   fWeightMatrix1to2[9][1] = -1.18174233554753;
   fWeightMatrix1to2[10][1] = -1.36258166828249;
   fWeightMatrix1to2[0][2] = -0.930436304371377;
   fWeightMatrix1to2[1][2] = 0.254724337146637;
   fWeightMatrix1to2[2][2] = 1.87473384039124;
   fWeightMatrix1to2[3][2] = -2.57965052003701;
   fWeightMatrix1to2[4][2] = -0.752782066361813;
   fWeightMatrix1to2[5][2] = -1.10438230968425;
   fWeightMatrix1to2[6][2] = 3.61904658772917;
   fWeightMatrix1to2[7][2] = 3.02156197547146;
   fWeightMatrix1to2[8][2] = 2.83770377125473;
   fWeightMatrix1to2[9][2] = -1.89522263749179;
   fWeightMatrix1to2[10][2] = 2.01227067895945;
   fWeightMatrix1to2[0][3] = -0.714288640474921;
   fWeightMatrix1to2[1][3] = -0.852857245746723;
   fWeightMatrix1to2[2][3] = 1.18472375688644;
   fWeightMatrix1to2[3][3] = -1.59699083546163;
   fWeightMatrix1to2[4][3] = -0.218882079246634;
   fWeightMatrix1to2[5][3] = 0.884190508469984;
   fWeightMatrix1to2[6][3] = 2.29195764783567;
   fWeightMatrix1to2[7][3] = 0.676205408140608;
   fWeightMatrix1to2[8][3] = 2.64203798199133;
   fWeightMatrix1to2[9][3] = 4.15483635911081;
   fWeightMatrix1to2[10][3] = -2.06674051028335;
   fWeightMatrix1to2[0][4] = 0.500392358607326;
   fWeightMatrix1to2[1][4] = -0.0435301338893835;
   fWeightMatrix1to2[2][4] = 0.636746038350964;
   fWeightMatrix1to2[3][4] = -1.88028732300222;
   fWeightMatrix1to2[4][4] = -1.02941798919485;
   fWeightMatrix1to2[5][4] = 1.28737176522324;
   fWeightMatrix1to2[6][4] = 2.62565495294823;
   fWeightMatrix1to2[7][4] = -0.947906657604398;
   fWeightMatrix1to2[8][4] = 0.173525798119731;
   fWeightMatrix1to2[9][4] = -0.38904976729475;
   fWeightMatrix1to2[10][4] = 0.365219620372118;
   fWeightMatrix1to2[0][5] = 0.791544240193818;
   fWeightMatrix1to2[1][5] = -0.123138015221951;
   fWeightMatrix1to2[2][5] = 1.05607334842262;
   fWeightMatrix1to2[3][5] = -2.71415834820677;
   fWeightMatrix1to2[4][5] = 2.8755262466878;
   fWeightMatrix1to2[5][5] = 2.44772812193035;
   fWeightMatrix1to2[6][5] = 2.84348692256176;
   fWeightMatrix1to2[7][5] = -1.9233138561202;
   fWeightMatrix1to2[8][5] = -1.31128155201839;
   fWeightMatrix1to2[9][5] = -4.58330405870599;
   fWeightMatrix1to2[10][5] = 0.0195965838737172;
   fWeightMatrix1to2[0][6] = 0.840767098315194;
   fWeightMatrix1to2[1][6] = -1.20031158681303;
   fWeightMatrix1to2[2][6] = 3.57572725985307;
   fWeightMatrix1to2[3][6] = -0.801844244541306;
   fWeightMatrix1to2[4][6] = -0.0623365695087969;
   fWeightMatrix1to2[5][6] = -2.89476774183682;
   fWeightMatrix1to2[6][6] = 1.80202440132588;
   fWeightMatrix1to2[7][6] = 3.48952662049167;
   fWeightMatrix1to2[8][6] = 0.360784039778254;
   fWeightMatrix1to2[9][6] = -1.17856156405391;
   fWeightMatrix1to2[10][6] = 1.88883875432974;
   fWeightMatrix1to2[0][7] = 1.09734195887874;
   fWeightMatrix1to2[1][7] = 0.43042824651611;
   fWeightMatrix1to2[2][7] = -0.167127845097514;
   fWeightMatrix1to2[3][7] = -1.79556046526205;
   fWeightMatrix1to2[4][7] = -0.942266954232746;
   fWeightMatrix1to2[5][7] = 1.8941920241769;
   fWeightMatrix1to2[6][7] = 1.43590052701138;
   fWeightMatrix1to2[7][7] = 0.898900560359194;
   fWeightMatrix1to2[8][7] = 0.439925880627175;
   fWeightMatrix1to2[9][7] = 1.99335501500098;
   fWeightMatrix1to2[10][7] = -1.64320298013538;
   fWeightMatrix1to2[0][8] = -1.94753349293819;
   fWeightMatrix1to2[1][8] = -0.578836901250727;
   fWeightMatrix1to2[2][8] = -3.23797986231433;
   fWeightMatrix1to2[3][8] = 3.23154952966982;
   fWeightMatrix1to2[4][8] = 1.07684304330517;
   fWeightMatrix1to2[5][8] = -2.24542312252753;
   fWeightMatrix1to2[6][8] = -2.34248466805168;
   fWeightMatrix1to2[7][8] = -3.07489962728471;
   fWeightMatrix1to2[8][8] = -2.98567358012571;
   fWeightMatrix1to2[9][8] = 1.30839705011595;
   fWeightMatrix1to2[10][8] = 0.327825982633608;
   fWeightMatrix1to2[0][9] = 0.990787904512882;
   fWeightMatrix1to2[1][9] = 0.834043687763208;
   fWeightMatrix1to2[2][9] = -4.4995279807631;
   fWeightMatrix1to2[3][9] = 1.50555834601286;
   fWeightMatrix1to2[4][9] = -3.07926161966046;
   fWeightMatrix1to2[5][9] = 0.984572833900736;
   fWeightMatrix1to2[6][9] = -0.328484374208533;
   fWeightMatrix1to2[7][9] = -2.31043543237767;
   fWeightMatrix1to2[8][9] = -2.27834590710546;
   fWeightMatrix1to2[9][9] = -0.292483478756317;
   fWeightMatrix1to2[10][9] = -0.387353297073698;
   fWeightMatrix1to2[0][10] = -3.25534965995446;
   fWeightMatrix1to2[1][10] = -1.32780885260027;
   fWeightMatrix1to2[2][10] = -4.69733935455987;
   fWeightMatrix1to2[3][10] = 1.67675435509054;
   fWeightMatrix1to2[4][10] = -2.07947076239965;
   fWeightMatrix1to2[5][10] = -2.10131045158145;
   fWeightMatrix1to2[6][10] = 0.559988877737941;
   fWeightMatrix1to2[7][10] = -5.71129653982227;
   fWeightMatrix1to2[8][10] = -2.37000904169078;
   fWeightMatrix1to2[9][10] = -1.97634277693646;
   fWeightMatrix1to2[10][10] = -0.607750313327069;
   fWeightMatrix1to2[0][11] = 1.98264310734491;
   fWeightMatrix1to2[1][11] = 0.974983437473193;
   fWeightMatrix1to2[2][11] = 0.0806184721264646;
   fWeightMatrix1to2[3][11] = -0.898252164428336;
   fWeightMatrix1to2[4][11] = -1.80255124425499;
   fWeightMatrix1to2[5][11] = -0.129528824056779;
   fWeightMatrix1to2[6][11] = -2.17812413948477;
   fWeightMatrix1to2[7][11] = 2.19453052774907;
   fWeightMatrix1to2[8][11] = -0.850850553472787;
   fWeightMatrix1to2[9][11] = 1.56711493966061;
   fWeightMatrix1to2[10][11] = -0.969810030125193;
   // weight matrix from layer 2 to 3
   fWeightMatrix2to3[0][0] = -1.72499844801882;
   fWeightMatrix2to3[1][0] = -0.531052363646801;
   fWeightMatrix2to3[2][0] = -2.93624830279925;
   fWeightMatrix2to3[3][0] = 0.163261664591349;
   fWeightMatrix2to3[4][0] = -1.15482801151158;
   fWeightMatrix2to3[5][0] = -1.28848983749236;
   fWeightMatrix2to3[6][0] = -1.89302102089988;
   fWeightMatrix2to3[7][0] = 0.350825900076541;
   fWeightMatrix2to3[8][0] = 0.677251462953592;
   fWeightMatrix2to3[9][0] = -0.558419205276536;
   fWeightMatrix2to3[10][0] = -1.63313167730545;
   fWeightMatrix2to3[11][0] = -0.570299547810228;
   fWeightMatrix2to3[12][0] = -0.218699368824228;
   fWeightMatrix2to3[13][0] = 0.256665490062219;
   fWeightMatrix2to3[0][1] = 0.815709996863479;
   fWeightMatrix2to3[1][1] = -0.192196717281366;
   fWeightMatrix2to3[2][1] = -0.41846211112697;
   fWeightMatrix2to3[3][1] = -0.412090090020723;
   fWeightMatrix2to3[4][1] = -1.78071664408125;
   fWeightMatrix2to3[5][1] = -0.579141089310637;
   fWeightMatrix2to3[6][1] = -1.7128481795282;
   fWeightMatrix2to3[7][1] = -1.53305344260665;
   fWeightMatrix2to3[8][1] = -1.12692194258404;
   fWeightMatrix2to3[9][1] = 1.48268345566288;
   fWeightMatrix2to3[10][1] = -1.69213037813356;
   fWeightMatrix2to3[11][1] = 1.50143640241118;
   fWeightMatrix2to3[12][1] = -1.61358194026607;
   fWeightMatrix2to3[13][1] = 1.03904775934294;
   fWeightMatrix2to3[0][2] = -3.57257309394945;
   fWeightMatrix2to3[1][2] = 0.886811620702693;
   fWeightMatrix2to3[2][2] = -1.20342893697749;
   fWeightMatrix2to3[3][2] = -2.90456500383512;
   fWeightMatrix2to3[4][2] = -0.90696637111502;
   fWeightMatrix2to3[5][2] = 0.313248143379199;
   fWeightMatrix2to3[6][2] = -2.51565011115171;
   fWeightMatrix2to3[7][2] = -2.52333013464318;
   fWeightMatrix2to3[8][2] = -2.42825224540815;
   fWeightMatrix2to3[9][2] = -1.91253456876457;
   fWeightMatrix2to3[10][2] = 0.424157868667571;
   fWeightMatrix2to3[11][2] = -1.12277807380573;
   fWeightMatrix2to3[12][2] = -0.0782848867444244;
   fWeightMatrix2to3[13][2] = -1.16947101352576;
   fWeightMatrix2to3[0][3] = 1.21975091655368;
   fWeightMatrix2to3[1][3] = -1.65390283550608;
   fWeightMatrix2to3[2][3] = -2.79717288139133;
   fWeightMatrix2to3[3][3] = -2.24872733536246;
   fWeightMatrix2to3[4][3] = -0.0262894210450931;
   fWeightMatrix2to3[5][3] = -1.32586021410678;
   fWeightMatrix2to3[6][3] = -1.20510447654705;
   fWeightMatrix2to3[7][3] = 1.93614251916744;
   fWeightMatrix2to3[8][3] = 0.555896576372896;
   fWeightMatrix2to3[9][3] = -0.0181514626326235;
   fWeightMatrix2to3[10][3] = 2.14383686618079;
   fWeightMatrix2to3[11][3] = -2.83851581586094;
   fWeightMatrix2to3[12][3] = 0.66080275665295;
   fWeightMatrix2to3[13][3] = 0.287921765160627;
   fWeightMatrix2to3[0][4] = -3.2010296641112;
   fWeightMatrix2to3[1][4] = -0.908874533495397;
   fWeightMatrix2to3[2][4] = 0.66516738612763;
   fWeightMatrix2to3[3][4] = -0.851248663786853;
   fWeightMatrix2to3[4][4] = -0.714182246144015;
   fWeightMatrix2to3[5][4] = 1.6634911943352;
   fWeightMatrix2to3[6][4] = 2.01231412379637;
   fWeightMatrix2to3[7][4] = 2.61847639326357;
   fWeightMatrix2to3[8][4] = -2.83869068535986;
   fWeightMatrix2to3[9][4] = 0.322149685704927;
   fWeightMatrix2to3[10][4] = -2.47217953402401;
   fWeightMatrix2to3[11][4] = 2.21270064584386;
   fWeightMatrix2to3[12][4] = -3.04076177830312;
   fWeightMatrix2to3[13][4] = -2.06213474511216;
   fWeightMatrix2to3[0][5] = 0.588382416628441;
   fWeightMatrix2to3[1][5] = 1.43944759789;
   fWeightMatrix2to3[2][5] = 2.34263230550929;
   fWeightMatrix2to3[3][5] = 0.759794110518531;
   fWeightMatrix2to3[4][5] = 0.199965992723056;
   fWeightMatrix2to3[5][5] = -0.189520325824365;
   fWeightMatrix2to3[6][5] = -0.957877790578651;
   fWeightMatrix2to3[7][5] = 0.961096669614863;
   fWeightMatrix2to3[8][5] = 3.01605651103513;
   fWeightMatrix2to3[9][5] = -1.78030436822085;
   fWeightMatrix2to3[10][5] = 0.590040842750053;
   fWeightMatrix2to3[11][5] = -1.64290437950042;
   fWeightMatrix2to3[12][5] = -0.238721012296333;
   fWeightMatrix2to3[13][5] = -0.0527456958980404;
   fWeightMatrix2to3[0][6] = -1.47042352700447;
   fWeightMatrix2to3[1][6] = -1.29413667744288;
   fWeightMatrix2to3[2][6] = 2.59337485910188;
   fWeightMatrix2to3[3][6] = 1.87944207898536;
   fWeightMatrix2to3[4][6] = -0.320860266052751;
   fWeightMatrix2to3[5][6] = -0.540409520113842;
   fWeightMatrix2to3[6][6] = -1.09786304539511;
   fWeightMatrix2to3[7][6] = -2.43798500322132;
   fWeightMatrix2to3[8][6] = -2.59092526232018;
   fWeightMatrix2to3[9][6] = 0.520464350650633;
   fWeightMatrix2to3[10][6] = -1.13225151283201;
   fWeightMatrix2to3[11][6] = -1.03878204548251;
   fWeightMatrix2to3[12][6] = -0.475751686790449;
   fWeightMatrix2to3[13][6] = -2.15852502830486;
   fWeightMatrix2to3[0][7] = -3.55527882406661;
   fWeightMatrix2to3[1][7] = -1.77768820271233;
   fWeightMatrix2to3[2][7] = 1.31863055171727;
   fWeightMatrix2to3[3][7] = -1.02930725976191;
   fWeightMatrix2to3[4][7] = -2.48804141259804;
   fWeightMatrix2to3[5][7] = -1.16250807012297;
   fWeightMatrix2to3[6][7] = -1.75106594204772;
   fWeightMatrix2to3[7][7] = -3.95442678876708;
   fWeightMatrix2to3[8][7] = 0.635858919800354;
   fWeightMatrix2to3[9][7] = -2.72385645987552;
   fWeightMatrix2to3[10][7] = -1.81844964902122;
   fWeightMatrix2to3[11][7] = 3.25704748997591;
   fWeightMatrix2to3[12][7] = 0.013324860343636;
   fWeightMatrix2to3[13][7] = 0.198582120560072;
   fWeightMatrix2to3[0][8] = -1.53001666743734;
   fWeightMatrix2to3[1][8] = 1.31635887470275;
   fWeightMatrix2to3[2][8] = 3.95677357403934;
   fWeightMatrix2to3[3][8] = 1.20456702698939;
   fWeightMatrix2to3[4][8] = -1.34879281963621;
   fWeightMatrix2to3[5][8] = -1.07373281941093;
   fWeightMatrix2to3[6][8] = -2.49792692629853;
   fWeightMatrix2to3[7][8] = -0.265749688419232;
   fWeightMatrix2to3[8][8] = 1.02972793059244;
   fWeightMatrix2to3[9][8] = -1.03943160010079;
   fWeightMatrix2to3[10][8] = 0.485011004100227;
   fWeightMatrix2to3[11][8] = 1.71131118402015;
   fWeightMatrix2to3[12][8] = 1.21018637628756;
   fWeightMatrix2to3[13][8] = -1.38594045403751;
   fWeightMatrix2to3[0][9] = 3.16361356914425;
   fWeightMatrix2to3[1][9] = 0.849058907520198;
   fWeightMatrix2to3[2][9] = -3.83728761567772;
   fWeightMatrix2to3[3][9] = -0.772699286122128;
   fWeightMatrix2to3[4][9] = -1.28671525079259;
   fWeightMatrix2to3[5][9] = 0.983838930351963;
   fWeightMatrix2to3[6][9] = 0.628128100869233;
   fWeightMatrix2to3[7][9] = 1.16492338867106;
   fWeightMatrix2to3[8][9] = 2.43175553618629;
   fWeightMatrix2to3[9][9] = -0.522582381084477;
   fWeightMatrix2to3[10][9] = 1.69168766032486;
   fWeightMatrix2to3[11][9] = -0.511754969170624;
   fWeightMatrix2to3[12][9] = 0.985853914233846;
   fWeightMatrix2to3[13][9] = -1.34814509564175;
   fWeightMatrix2to3[0][10] = 0.730878306397777;
   fWeightMatrix2to3[1][10] = -1.72706066460952;
   fWeightMatrix2to3[2][10] = 0.22011797448315;
   fWeightMatrix2to3[3][10] = 1.26521001455461;
   fWeightMatrix2to3[4][10] = -0.746733750946302;
   fWeightMatrix2to3[5][10] = -0.861423343975359;
   fWeightMatrix2to3[6][10] = 0.0580628890961261;
   fWeightMatrix2to3[7][10] = -1.88603578411685;
   fWeightMatrix2to3[8][10] = 0.549794799020711;
   fWeightMatrix2to3[9][10] = -2.15973630878976;
   fWeightMatrix2to3[10][10] = 0.180587482938349;
   fWeightMatrix2to3[11][10] = -0.960270543564057;
   fWeightMatrix2to3[12][10] = 2.24799065287253;
   fWeightMatrix2to3[13][10] = 0.951719303298611;
   fWeightMatrix2to3[0][11] = 1.26018955268913;
   fWeightMatrix2to3[1][11] = -0.0693858451231033;
   fWeightMatrix2to3[2][11] = -2.29110112133873;
   fWeightMatrix2to3[3][11] = -0.748484136903224;
   fWeightMatrix2to3[4][11] = -0.194241550997822;
   fWeightMatrix2to3[5][11] = -1.9507282849318;
   fWeightMatrix2to3[6][11] = -0.660969129797228;
   fWeightMatrix2to3[7][11] = -0.0161688668702284;
   fWeightMatrix2to3[8][11] = -1.5952147394741;
   fWeightMatrix2to3[9][11] = -1.98536793820871;
   fWeightMatrix2to3[10][11] = -2.00655032230758;
   fWeightMatrix2to3[11][11] = -0.422684709215273;
   fWeightMatrix2to3[12][11] = -1.38311689483153;
   fWeightMatrix2to3[13][11] = -2.87309205766691;
   // weight matrix from layer 3 to 4
   fWeightMatrix3to4[0][0] = -4.0354515434367;
   fWeightMatrix3to4[0][1] = -1.39243635285849;
   fWeightMatrix3to4[0][2] = 2.93130932586537;
   fWeightMatrix3to4[0][3] = 1.00778851066553;
   fWeightMatrix3to4[0][4] = -0.966972911433349;
   fWeightMatrix3to4[0][5] = -0.919387033016854;
   fWeightMatrix3to4[0][6] = -2.80929548908716;
   fWeightMatrix3to4[0][7] = -1.74836276881266;
   fWeightMatrix3to4[0][8] = -2.95086079670023;
   fWeightMatrix3to4[0][9] = -1.66080881532986;
   fWeightMatrix3to4[0][10] = -1.91361412021049;
   fWeightMatrix3to4[0][11] = 0.803415463350192;
   fWeightMatrix3to4[0][12] = -1.57080762279191;
   fWeightMatrix3to4[0][13] = 0.726918688799408;
   fWeightMatrix3to4[0][14] = 0.370304389505516;
}

inline double ReadMLP_ANN_N3_NC300::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   if (inputValues.size() != (unsigned int)fLayerSize[0]-1) {
      std::cout << "Input vector needs to be of size " << fLayerSize[0]-1 << std::endl;
      return 0;
   }

   for (int l=0; l<fLayers; l++)
      for (int i=0; i<fLayerSize[l]; i++) fWeights[l][i]=0;

   for (int l=0; l<fLayers-1; l++)
      fWeights[l][fLayerSize[l]-1]=1;

   for (int i=0; i<fLayerSize[0]-1; i++)
      fWeights[0][i]=inputValues[i];

   // layer 0 to 1
   for (int o=0; o<fLayerSize[1]-1; o++) {
      for (int i=0; i<fLayerSize[0]; i++) {
         double inputVal = fWeightMatrix0to1[o][i] * fWeights[0][i];
         fWeights[1][o] += inputVal;
      }
      fWeights[1][o] = ActivationFnc(fWeights[1][o]);
   }
   // layer 1 to 2
   for (int o=0; o<fLayerSize[2]-1; o++) {
      for (int i=0; i<fLayerSize[1]; i++) {
         double inputVal = fWeightMatrix1to2[o][i] * fWeights[1][i];
         fWeights[2][o] += inputVal;
      }
      fWeights[2][o] = ActivationFnc(fWeights[2][o]);
   }
   // layer 2 to 3
   for (int o=0; o<fLayerSize[3]-1; o++) {
      for (int i=0; i<fLayerSize[2]; i++) {
         double inputVal = fWeightMatrix2to3[o][i] * fWeights[2][i];
         fWeights[3][o] += inputVal;
      }
      fWeights[3][o] = ActivationFnc(fWeights[3][o]);
   }
   // layer 3 to 4
   for (int o=0; o<fLayerSize[4]; o++) {
      for (int i=0; i<fLayerSize[3]; i++) {
         double inputVal = fWeightMatrix3to4[o][i] * fWeights[3][i];
         fWeights[4][o] += inputVal;
      }
      fWeights[4][o] = OutputActivationFnc(fWeights[4][o]);
   }

   return fWeights[4][0];
}

double ReadMLP_ANN_N3_NC300::ActivationFnc(double x) const {
   // sigmoid
   return 1.0/(1.0+exp(-x));
}
double ReadMLP_ANN_N3_NC300::OutputActivationFnc(double x) const {
   // sigmoid
   return 1.0/(1.0+exp(-x));
}
   
// Clean up
inline void ReadMLP_ANN_N3_NC300::Clear() 
{
   // clean up the arrays
   for (int lIdx = 0; lIdx < 5; lIdx++) {
      delete[] fWeights[lIdx];
   }
}
   inline double ReadMLP_ANN_N3_NC300::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            iV.reserve(inputValues.size());
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
         else {
            std::vector<double> iV;
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(*varIt);
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
      }

      return retval;
   }

//_______________________________________________________________________
inline void ReadMLP_ANN_N3_NC300::InitTransform_1()
{
   // Normalization transformation, initialisation
   fMin_1[0][0] = 110.048698425;
   fMax_1[0][0] = 1277.92980957;
   fMin_1[1][0] = 110.057556152;
   fMax_1[1][0] = 1572.76037598;
   fMin_1[2][0] = 110.048698425;
   fMax_1[2][0] = 1572.76037598;
   fMin_1[0][1] = 5.00075817108;
   fMax_1[0][1] = 29.9497737885;
   fMin_1[1][1] = 5.00135278702;
   fMax_1[1][1] = 29.9984378815;
   fMin_1[2][1] = 5.00075817108;
   fMax_1[2][1] = 29.9984378815;
   fMin_1[0][2] = -1;
   fMax_1[0][2] = 1;
   fMin_1[1][2] = -1;
   fMax_1[1][2] = 1;
   fMin_1[2][2] = -1;
   fMax_1[2][2] = 1;
   fMin_1[0][3] = -2.4711689949;
   fMax_1[0][3] = 2.37911462784;
   fMin_1[1][3] = -2.48411560059;
   fMax_1[1][3] = 2.49880051613;
   fMin_1[2][3] = -2.48411560059;
   fMax_1[2][3] = 2.49880051613;
   fMin_1[0][4] = 280.2293396;
   fMax_1[0][4] = 1251.49438477;
   fMin_1[1][4] = 280.020294189;
   fMax_1[1][4] = 1289.47937012;
   fMin_1[2][4] = 280.020294189;
   fMax_1[2][4] = 1289.47937012;
   fMin_1[0][5] = 0.0557334087789;
   fMax_1[0][5] = 300.527191162;
   fMin_1[1][5] = 0.000537815736607;
   fMax_1[1][5] = 215.792510986;
   fMin_1[2][5] = 0.000537815736607;
   fMax_1[2][5] = 300.527191162;
   fMin_1[0][6] = 117.352531433;
   fMax_1[0][6] = 2347.48510742;
   fMin_1[1][6] = 112.003395081;
   fMax_1[1][6] = 4504.87304688;
   fMin_1[2][6] = 112.003395081;
   fMax_1[2][6] = 4504.87304688;
   fMin_1[0][7] = 0;
   fMax_1[0][7] = 5;
   fMin_1[1][7] = 0;
   fMax_1[1][7] = 6;
   fMin_1[2][7] = 0;
   fMax_1[2][7] = 6;
   fMin_1[0][8] = 1;
   fMax_1[0][8] = 11;
   fMin_1[1][8] = 1;
   fMax_1[1][8] = 14;
   fMin_1[2][8] = 1;
   fMax_1[2][8] = 14;
   fMin_1[0][9] = 20.0573444366;
   fMax_1[0][9] = 1057.04370117;
   fMin_1[1][9] = -999;
   fMax_1[1][9] = 1378.42883301;
   fMin_1[2][9] = -999;
   fMax_1[2][9] = 1378.42883301;
   fMin_1[0][10] = 6.27087429166e-05;
   fMax_1[0][10] = 4.95768356323;
   fMin_1[1][10] = -999;
   fMax_1[1][10] = 5.38026332855;
   fMin_1[2][10] = -999;
   fMax_1[2][10] = 5.38026332855;
}

//_______________________________________________________________________
inline void ReadMLP_ANN_N3_NC300::Transform_1( std::vector<double>& iv, int cls) const
{
   // Normalization transformation
   if (cls < 0 || cls > 2) {
   if (2 > 1 ) cls = 2;
      else cls = 2;
   }
   const int nVar = 11;

   // get indices of used variables

   // define the indices of the variables which are transformed by this transformation
   static std::vector<int> indicesGet;
   static std::vector<int> indicesPut;

   if ( indicesGet.empty() ) { 
      indicesGet.reserve(fNvars);
      indicesGet.push_back( 0);
      indicesGet.push_back( 1);
      indicesGet.push_back( 2);
      indicesGet.push_back( 3);
      indicesGet.push_back( 4);
      indicesGet.push_back( 5);
      indicesGet.push_back( 6);
      indicesGet.push_back( 7);
      indicesGet.push_back( 8);
      indicesGet.push_back( 9);
      indicesGet.push_back( 10);
   } 
   if ( indicesPut.empty() ) { 
      indicesPut.reserve(fNvars);
      indicesPut.push_back( 0);
      indicesPut.push_back( 1);
      indicesPut.push_back( 2);
      indicesPut.push_back( 3);
      indicesPut.push_back( 4);
      indicesPut.push_back( 5);
      indicesPut.push_back( 6);
      indicesPut.push_back( 7);
      indicesPut.push_back( 8);
      indicesPut.push_back( 9);
      indicesPut.push_back( 10);
   } 

   static std::vector<double> dv;
   dv.resize(nVar);
   for (int ivar=0; ivar<nVar; ivar++) dv[ivar] = iv[indicesGet.at(ivar)];
   for (int ivar=0;ivar<11;ivar++) {
      double offset = fMin_1[cls][ivar];
      double scale  = 1.0/(fMax_1[cls][ivar]-fMin_1[cls][ivar]);
      iv[indicesPut.at(ivar)] = (dv[ivar]-offset)*scale * 2 - 1;
   }
}

//_______________________________________________________________________
inline void ReadMLP_ANN_N3_NC300::InitTransform()
{
   InitTransform_1();
}

//_______________________________________________________________________
inline void ReadMLP_ANN_N3_NC300::Transform( std::vector<double>& iv, int sigOrBgd ) const
{
   Transform_1( iv, sigOrBgd );
}
