// Class: ReadMLP_ANN_N-7_NC500
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : MLP::MLP_ANN_N-7_NC500
TMVA Release   : 4.2.1         [262657]
ROOT Release   : 6.06/01       [394753]
Creator        : brucms16
Date           : Tue Sep  6 18:42:41 2016
Host           : Linux vocms0315.cern.ch 2.6.32-573.26.1.el6.x86_64 #1 SMP Wed May 4 09:23:05 CEST 2016 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /home/t3cms/brucms16/CMSSW_8_0_14/src/UserCode/SkeletonAnalysis/macros
Training events: 15056
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
NCycles: "500" [Number of training cycles]
HiddenLayers: "N,N,N+-7" [Specification of hidden layer architecture]
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
VarTransform: "Norm" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
H: "False" [Print method-specific help message]
LearningRate: "9.000000e-02" [ANN learning rate parameter]
DecayRate: "1.000000e-02" [Decay rate for learning parameter]
# Default:
NeuronType: "sigmoid" [Neuron activation function type]
RandomSeed: "1" [Random seed for initial synapse weights (0 means unique seed for each run; default value '1')]
EstimatorType: "CE" [MSE (Mean Square Estimator) for Gaussian Likelihood or CE(Cross-Entropy) for Bernoulli Likelihood]
NeuronInputType: "sum" [Neuron input function type]
VerbosityLevel: "Default" [Verbosity level]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
TrainingMethod: "BP" [Train with Back-Propagation (BP), BFGS Algorithm (BFGS), or Genetic Algorithm (GA - slower and worse)]
TestRate: "10" [Test for overtraining performed at each #th epochs]
EpochMonitoring: "False" [Provide epoch-wise monitoring plots according to TestRate (caution: causes big ROOT output file!)]
Sampling: "1.000000e+00" [Only 'Sampling' (randomly selected) events are trained each epoch]
SamplingEpoch: "1.000000e+00" [Sampling is used for the first 'SamplingEpoch' epochs, afterwards, all events are taken for training]
SamplingImportance: "1.000000e+00" [ The sampling weights of events in epochs which successful (worse estimator than before) are multiplied with SamplingImportance, else they are divided.]
SamplingTraining: "True" [The training sample is sampled]
SamplingTesting: "False" [The testing sample is sampled]
ResetStep: "50" [How often BFGS should reset history]
Tau: "3.000000e+00" [LineSearch "size step"]
BPMode: "sequential" [Back-propagation learning mode: sequential or batch]
BatchSize: "-1" [Batch size: number of events/batch, only set if in Batch Mode, -1 for BatchSize=number_of_events]
ConvergenceImprove: "1.000000e-30" [Minimum improvement which counts as improvement (<0 means automatic convergence check is turned off)]
ConvergenceTests: "-1" [Number of steps (without improvement) required for convergence (<0 means automatic convergence check is turned off)]
UseRegulator: "False" [Use regulator to avoid over-training]
UpdateLimit: "10000" [Maximum times of regulator update]
CalculateErrors: "False" [Calculates inverse Hessian matrix at the end of the training to be able to calculate the uncertainties of an MVA value]
WeightRange: "1.000000e+00" [Take the events for the estimator calculations from small deviations from the desired value to large deviations only over the weight range]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 11
Jet1Pt                        Jet1Pt                        Jet1Pt                        Jet1Pt                                                          'F'    [110.048698425,1572.76037598]
LepPt                         LepPt                         LepPt                         LepPt                                                           'F'    [5.00075817108,29.9984378815]
LepChg                        LepChg                        LepChg                        LepChg                                                          'F'    [-1,1]
LepEta                        LepEta                        LepEta                        LepEta                                                          'F'    [-2.48411560059,2.49880051613]
Met                           Met                           Met                           Met                                                             'F'    [280.020294189,1289.47937012]
mt                            mt                            mt                            mt                                                              'F'    [0.000537815736607,300.527191162]
HT20                          HT20                          HT20                          HT20                                                            'F'    [112.003395081,4504.87304688]
NbLoose30                     NbLoose30                     NbLoose30                     NbLoose30                                                       'F'    [0,6]
Njet                          Njet                          Njet                          Njet                                                            'F'    [1,14]
JetHBpt                       JetHBpt                       JetHBpt                       JetHBpt                                                         'F'    [-999,1378.42883301]
DrJetHBLep                    DrJetHBLep                    DrJetHBLep                    DrJetHBLep                                                      'F'    [-999,5.38026332855]
NSpec 0


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadMLP_ANN_N-7_NC500 : public IClassifierReader {

 public:

   // constructor
   ReadMLP_ANN_N-7_NC500( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadMLP_ANN_N-7_NC500" ),
        fNvars( 11 ),
        fIsNormalised( false )
   {      
      // the training input variables
      const char* inputVars[] = { "Jet1Pt", "LepPt", "LepChg", "LepEta", "Met", "mt", "HT20", "NbLoose30", "Njet", "JetHBpt", "DrJetHBLep" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = -1;
      fVmax[0] = 1;
      fVmin[1] = -1;
      fVmax[1] = 0.99999988079071;
      fVmin[2] = -1;
      fVmax[2] = 1;
      fVmin[3] = -1;
      fVmax[3] = 1;
      fVmin[4] = -1;
      fVmax[4] = 1;
      fVmin[5] = -1;
      fVmax[5] = 1;
      fVmin[6] = -1;
      fVmax[6] = 1;
      fVmin[7] = -1;
      fVmax[7] = 1;
      fVmin[8] = -1;
      fVmax[8] = 1;
      fVmin[9] = -1;
      fVmax[9] = 1;
      fVmin[10] = -1;
      fVmax[10] = 1;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';
      fType[4] = 'F';
      fType[5] = 'F';
      fType[6] = 'F';
      fType[7] = 'F';
      fType[8] = 'F';
      fType[9] = 'F';
      fType[10] = 'F';

      // initialize constants
      Initialize();

      // initialize transformation
      InitTransform();
   }

   // destructor
   virtual ~ReadMLP_ANN_N-7_NC500() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // input variable transformation

   double fMin_1[3][11];
   double fMax_1[3][11];
   void InitTransform_1();
   void Transform_1( std::vector<double> & iv, int sigOrBgd ) const;
   void InitTransform();
   void Transform( std::vector<double> & iv, int sigOrBgd ) const;

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[11];
   double fVmax[11];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[11];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)

   double ActivationFnc(double x) const;
   double OutputActivationFnc(double x) const;

   int fLayers;
   int fLayerSize[5];
   double fWeightMatrix0to1[12][12];   // weight matrix from layer 0 to 1
   double fWeightMatrix1to2[12][12];   // weight matrix from layer 1 to 2
   double fWeightMatrix2to3[12][12];   // weight matrix from layer 2 to 3
   double fWeightMatrix3to4[1][12];   // weight matrix from layer 3 to 4

   double * fWeights[5];
};

inline void ReadMLP_ANN_N-7_NC500::Initialize()
{
   // build network structure
   fLayers = 5;
   fLayerSize[0] = 12; fWeights[0] = new double[12]; 
   fLayerSize[1] = 12; fWeights[1] = new double[12]; 
   fLayerSize[2] = 12; fWeights[2] = new double[12]; 
   fLayerSize[3] = 12; fWeights[3] = new double[12]; 
   fLayerSize[4] = 1; fWeights[4] = new double[1]; 
   // weight matrix from layer 0 to 1
   fWeightMatrix0to1[0][0] = 0.900746761458126;
   fWeightMatrix0to1[1][0] = 2.04474561860379;
   fWeightMatrix0to1[2][0] = 4.14434138967196;
   fWeightMatrix0to1[3][0] = -0.0883457428786254;
   fWeightMatrix0to1[4][0] = -0.22441046955937;
   fWeightMatrix0to1[5][0] = -1.65812192446895;
   fWeightMatrix0to1[6][0] = -3.28772106418406;
   fWeightMatrix0to1[7][0] = 1.95992759517711;
   fWeightMatrix0to1[8][0] = 0.511696830026638;
   fWeightMatrix0to1[9][0] = 0.166102434661322;
   fWeightMatrix0to1[10][0] = -1.75044156195378;
   fWeightMatrix0to1[0][1] = 1.64516293835304;
   fWeightMatrix0to1[1][1] = -2.13499705110284;
   fWeightMatrix0to1[2][1] = 0.0407356554812246;
   fWeightMatrix0to1[3][1] = 0.251160450723961;
   fWeightMatrix0to1[4][1] = 1.76810279044216;
   fWeightMatrix0to1[5][1] = -0.768910885726235;
   fWeightMatrix0to1[6][1] = 5.5502584193056;
   fWeightMatrix0to1[7][1] = 0.170553377502136;
   fWeightMatrix0to1[8][1] = 2.67234242293143;
   fWeightMatrix0to1[9][1] = 2.88724661645776;
   fWeightMatrix0to1[10][1] = -2.11887225426242;
   fWeightMatrix0to1[0][2] = 0.93887964056495;
   fWeightMatrix0to1[1][2] = -1.04316995832852;
   fWeightMatrix0to1[2][2] = -0.502373530671361;
   fWeightMatrix0to1[3][2] = 0.265639444527448;
   fWeightMatrix0to1[4][2] = -1.14317069340213;
   fWeightMatrix0to1[5][2] = -3.07652634754898;
   fWeightMatrix0to1[6][2] = -0.575360264405076;
   fWeightMatrix0to1[7][2] = -0.183814142548387;
   fWeightMatrix0to1[8][2] = -0.339431842880734;
   fWeightMatrix0to1[9][2] = 1.85164182968611;
   fWeightMatrix0to1[10][2] = 0.800353888095624;
   fWeightMatrix0to1[0][3] = -1.32697176451147;
   fWeightMatrix0to1[1][3] = 2.65770326740868;
   fWeightMatrix0to1[2][3] = 0.401983292869215;
   fWeightMatrix0to1[3][3] = 0.144100977967868;
   fWeightMatrix0to1[4][3] = 8.52847114966897;
   fWeightMatrix0to1[5][3] = -0.148154624261637;
   fWeightMatrix0to1[6][3] = -1.02114158384289;
   fWeightMatrix0to1[7][3] = 0.696680861153847;
   fWeightMatrix0to1[8][3] = -2.05171578681862;
   fWeightMatrix0to1[9][3] = -0.324188239190845;
   fWeightMatrix0to1[10][3] = 0.277364625054896;
   fWeightMatrix0to1[0][4] = 5.11944142062845;
   fWeightMatrix0to1[1][4] = -0.21100549461661;
   fWeightMatrix0to1[2][4] = 4.42803192410515;
   fWeightMatrix0to1[3][4] = 1.96308866560967;
   fWeightMatrix0to1[4][4] = 0.0581676771135396;
   fWeightMatrix0to1[5][4] = -0.26225478579108;
   fWeightMatrix0to1[6][4] = -1.08229004494277;
   fWeightMatrix0to1[7][4] = 1.7441354952689;
   fWeightMatrix0to1[8][4] = -8.95789579321367;
   fWeightMatrix0to1[9][4] = 0.417169900508482;
   fWeightMatrix0to1[10][4] = -7.95593832959749;
   fWeightMatrix0to1[0][5] = -1.37014330945567;
   fWeightMatrix0to1[1][5] = -2.30419207356919;
   fWeightMatrix0to1[2][5] = -11.5823541183081;
   fWeightMatrix0to1[3][5] = 17.5568510384711;
   fWeightMatrix0to1[4][5] = 0.665111430574515;
   fWeightMatrix0to1[5][5] = -2.66149411710239;
   fWeightMatrix0to1[6][5] = 0.878861573790866;
   fWeightMatrix0to1[7][5] = -0.461992966879863;
   fWeightMatrix0to1[8][5] = -1.57080199752494;
   fWeightMatrix0to1[9][5] = 2.98949609946226;
   fWeightMatrix0to1[10][5] = -2.74782418914194;
   fWeightMatrix0to1[0][6] = -1.16006317756322;
   fWeightMatrix0to1[1][6] = -1.45781490007053;
   fWeightMatrix0to1[2][6] = 0.936428364912803;
   fWeightMatrix0to1[3][6] = -4.39943129060269;
   fWeightMatrix0to1[4][6] = 0.692988840441714;
   fWeightMatrix0to1[5][6] = -1.53960823922998;
   fWeightMatrix0to1[6][6] = 1.60476249639029;
   fWeightMatrix0to1[7][6] = 1.00656891062963;
   fWeightMatrix0to1[8][6] = 6.41936608446241;
   fWeightMatrix0to1[9][6] = 0.795516293152729;
   fWeightMatrix0to1[10][6] = 2.37109052518119;
   fWeightMatrix0to1[0][7] = -6.37192417791061;
   fWeightMatrix0to1[1][7] = -0.912704317070025;
   fWeightMatrix0to1[2][7] = 1.10699960036814;
   fWeightMatrix0to1[3][7] = 0.753216533964962;
   fWeightMatrix0to1[4][7] = 0.0462622032434712;
   fWeightMatrix0to1[5][7] = 2.655620551506;
   fWeightMatrix0to1[6][7] = -0.583304960727743;
   fWeightMatrix0to1[7][7] = -1.03065601004183;
   fWeightMatrix0to1[8][7] = 2.0298768174134;
   fWeightMatrix0to1[9][7] = 0.866943430278752;
   fWeightMatrix0to1[10][7] = 3.07524475848154;
   fWeightMatrix0to1[0][8] = -7.78713786372874;
   fWeightMatrix0to1[1][8] = -2.2197039250351;
   fWeightMatrix0to1[2][8] = 0.685547466166226;
   fWeightMatrix0to1[3][8] = -0.741058990991133;
   fWeightMatrix0to1[4][8] = 0.429621221225481;
   fWeightMatrix0to1[5][8] = -2.39490190662718;
   fWeightMatrix0to1[6][8] = -2.03599515161452;
   fWeightMatrix0to1[7][8] = 1.47178749232589;
   fWeightMatrix0to1[8][8] = 1.65142348490215;
   fWeightMatrix0to1[9][8] = -8.72887356840971;
   fWeightMatrix0to1[10][8] = -5.13175111313759;
   fWeightMatrix0to1[0][9] = -1.07834286636112;
   fWeightMatrix0to1[1][9] = -2.65149529735706;
   fWeightMatrix0to1[2][9] = -2.42357849300966;
   fWeightMatrix0to1[3][9] = -2.44802398168835;
   fWeightMatrix0to1[4][9] = -0.283681617345566;
   fWeightMatrix0to1[5][9] = -2.56240705041657;
   fWeightMatrix0to1[6][9] = -2.42139925893809;
   fWeightMatrix0to1[7][9] = -1.04080620285989;
   fWeightMatrix0to1[8][9] = 2.58381343409385;
   fWeightMatrix0to1[9][9] = -1.31486322089935;
   fWeightMatrix0to1[10][9] = 1.72396763130177;
   fWeightMatrix0to1[0][10] = -2.28120089609287;
   fWeightMatrix0to1[1][10] = 0.418013677614718;
   fWeightMatrix0to1[2][10] = 1.00538691744784;
   fWeightMatrix0to1[3][10] = 1.98848897436997;
   fWeightMatrix0to1[4][10] = -1.79753601371913;
   fWeightMatrix0to1[5][10] = 0.85892189535825;
   fWeightMatrix0to1[6][10] = -0.272816000116005;
   fWeightMatrix0to1[7][10] = -0.965017007880276;
   fWeightMatrix0to1[8][10] = -1.60651788502697;
   fWeightMatrix0to1[9][10] = -2.20243652450465;
   fWeightMatrix0to1[10][10] = -3.88100874264034;
   fWeightMatrix0to1[0][11] = -0.320758555239889;
   fWeightMatrix0to1[1][11] = -0.194961157959577;
   fWeightMatrix0to1[2][11] = 1.91514889231981;
   fWeightMatrix0to1[3][11] = 2.32471012455587;
   fWeightMatrix0to1[4][11] = -0.403183942796479;
   fWeightMatrix0to1[5][11] = -1.13189170297835;
   fWeightMatrix0to1[6][11] = -0.249761131697662;
   fWeightMatrix0to1[7][11] = -1.82372958702141;
   fWeightMatrix0to1[8][11] = -0.953772995320286;
   fWeightMatrix0to1[9][11] = -0.927698693048831;
   fWeightMatrix0to1[10][11] = -4.21067777943408;
   // weight matrix from layer 1 to 2
   fWeightMatrix1to2[0][0] = 0.387696728246725;
   fWeightMatrix1to2[1][0] = -1.19562693087438;
   fWeightMatrix1to2[2][0] = 1.67519356512726;
   fWeightMatrix1to2[3][0] = 1.16238286566705;
   fWeightMatrix1to2[4][0] = 4.15386896493147;
   fWeightMatrix1to2[5][0] = -1.96310868034026;
   fWeightMatrix1to2[6][0] = -0.690371631769886;
   fWeightMatrix1to2[7][0] = 5.01557717106855;
   fWeightMatrix1to2[8][0] = 3.32488361984203;
   fWeightMatrix1to2[9][0] = -0.0994393545992187;
   fWeightMatrix1to2[10][0] = -2.69499485277391;
   fWeightMatrix1to2[0][1] = -0.442417621884166;
   fWeightMatrix1to2[1][1] = -1.40258855519103;
   fWeightMatrix1to2[2][1] = 2.8191370605942;
   fWeightMatrix1to2[3][1] = 2.27731849045897;
   fWeightMatrix1to2[4][1] = -0.647540853189315;
   fWeightMatrix1to2[5][1] = -0.641462841687981;
   fWeightMatrix1to2[6][1] = -1.21710355376299;
   fWeightMatrix1to2[7][1] = -2.57205570232621;
   fWeightMatrix1to2[8][1] = 0.812545010386697;
   fWeightMatrix1to2[9][1] = 3.33684408067056;
   fWeightMatrix1to2[10][1] = -1.09224365923907;
   fWeightMatrix1to2[0][2] = 0.193143874626661;
   fWeightMatrix1to2[1][2] = 0.130379249804005;
   fWeightMatrix1to2[2][2] = 1.46448500501365;
   fWeightMatrix1to2[3][2] = -1.9208884242084;
   fWeightMatrix1to2[4][2] = 3.0956544059881;
   fWeightMatrix1to2[5][2] = -1.45246795457623;
   fWeightMatrix1to2[6][2] = 0.782557249363206;
   fWeightMatrix1to2[7][2] = -0.25047190350808;
   fWeightMatrix1to2[8][2] = 4.57981546780038;
   fWeightMatrix1to2[9][2] = 3.42719227157158;
   fWeightMatrix1to2[10][2] = -2.11846341702833;
   fWeightMatrix1to2[0][3] = -1.31721069981101;
   fWeightMatrix1to2[1][3] = -0.172056963857201;
   fWeightMatrix1to2[2][3] = 5.82236064054197;
   fWeightMatrix1to2[3][3] = -3.2441830372921;
   fWeightMatrix1to2[4][3] = -1.06949749946486;
   fWeightMatrix1to2[5][3] = 1.4672361058641;
   fWeightMatrix1to2[6][3] = 2.23233174886718;
   fWeightMatrix1to2[7][3] = 1.2975046276228;
   fWeightMatrix1to2[8][3] = 2.93820032171608;
   fWeightMatrix1to2[9][3] = 4.72013486674634;
   fWeightMatrix1to2[10][3] = -1.80651516002885;
   fWeightMatrix1to2[0][4] = -0.355380471330697;
   fWeightMatrix1to2[1][4] = 0.154600901705805;
   fWeightMatrix1to2[2][4] = 0.280657404680584;
   fWeightMatrix1to2[3][4] = -1.95760512537081;
   fWeightMatrix1to2[4][4] = -3.71457069943174;
   fWeightMatrix1to2[5][4] = 1.04778013578639;
   fWeightMatrix1to2[6][4] = 2.59006588818758;
   fWeightMatrix1to2[7][4] = -4.33877500961593;
   fWeightMatrix1to2[8][4] = -0.959314447726789;
   fWeightMatrix1to2[9][4] = -0.761838948179065;
   fWeightMatrix1to2[10][4] = 2.91581952065788;
   fWeightMatrix1to2[0][5] = 2.40284217263351;
   fWeightMatrix1to2[1][5] = -0.485369733027754;
   fWeightMatrix1to2[2][5] = 0.0169684997690929;
   fWeightMatrix1to2[3][5] = -2.59872562179109;
   fWeightMatrix1to2[4][5] = 0.67166855766604;
   fWeightMatrix1to2[5][5] = 1.35572537973542;
   fWeightMatrix1to2[6][5] = -0.375689422049591;
   fWeightMatrix1to2[7][5] = 0.709889768851603;
   fWeightMatrix1to2[8][5] = -0.272014487567112;
   fWeightMatrix1to2[9][5] = -2.64281167124672;
   fWeightMatrix1to2[10][5] = 1.28671856981466;
   fWeightMatrix1to2[0][6] = 1.8608935850303;
   fWeightMatrix1to2[1][6] = -1.92270847835461;
   fWeightMatrix1to2[2][6] = -1.91029172297502;
   fWeightMatrix1to2[3][6] = 1.87397265862632;
   fWeightMatrix1to2[4][6] = 0.805060652142151;
   fWeightMatrix1to2[5][6] = -1.88546155520501;
   fWeightMatrix1to2[6][6] = 1.08909728018089;
   fWeightMatrix1to2[7][6] = 1.17569551962719;
   fWeightMatrix1to2[8][6] = -2.59883643472683;
   fWeightMatrix1to2[9][6] = -1.58151524474043;
   fWeightMatrix1to2[10][6] = 3.77306096714217;
   fWeightMatrix1to2[0][7] = 1.0186012931585;
   fWeightMatrix1to2[1][7] = 0.433349833605106;
   fWeightMatrix1to2[2][7] = -0.172603204000979;
   fWeightMatrix1to2[3][7] = -2.10270952692695;
   fWeightMatrix1to2[4][7] = -0.966705258190583;
   fWeightMatrix1to2[5][7] = 1.72363839908067;
   fWeightMatrix1to2[6][7] = 1.20827903813513;
   fWeightMatrix1to2[7][7] = 0.827941359521669;
   fWeightMatrix1to2[8][7] = 0.149818351717977;
   fWeightMatrix1to2[9][7] = 1.89639894215679;
   fWeightMatrix1to2[10][7] = -1.70620077116371;
   fWeightMatrix1to2[0][8] = -0.267431560624064;
   fWeightMatrix1to2[1][8] = -0.789505216654006;
   fWeightMatrix1to2[2][8] = -2.51475496675802;
   fWeightMatrix1to2[3][8] = 4.86909275872671;
   fWeightMatrix1to2[4][8] = 2.96765561323365;
   fWeightMatrix1to2[5][8] = -1.1281841093088;
   fWeightMatrix1to2[6][8] = 4.10808024561227;
   fWeightMatrix1to2[7][8] = -0.655970899267826;
   fWeightMatrix1to2[8][8] = -2.63251187659729;
   fWeightMatrix1to2[9][8] = -4.54044976085181;
   fWeightMatrix1to2[10][8] = 3.28293525279771;
   fWeightMatrix1to2[0][9] = 0.953312524866045;
   fWeightMatrix1to2[1][9] = 0.9186276271553;
   fWeightMatrix1to2[2][9] = -2.37694546051927;
   fWeightMatrix1to2[3][9] = 2.59103567775726;
   fWeightMatrix1to2[4][9] = -2.67417111940428;
   fWeightMatrix1to2[5][9] = 1.06017183957122;
   fWeightMatrix1to2[6][9] = -1.23704847353243;
   fWeightMatrix1to2[7][9] = -0.176822455096727;
   fWeightMatrix1to2[8][9] = -2.88614987907997;
   fWeightMatrix1to2[9][9] = -3.07462580268829;
   fWeightMatrix1to2[10][9] = -0.0370715489093439;
   fWeightMatrix1to2[0][10] = -2.65610399825958;
   fWeightMatrix1to2[1][10] = -1.97861956978233;
   fWeightMatrix1to2[2][10] = -4.69045215772393;
   fWeightMatrix1to2[3][10] = 1.9790659350178;
   fWeightMatrix1to2[4][10] = -1.75627988749818;
   fWeightMatrix1to2[5][10] = -1.88479770200158;
   fWeightMatrix1to2[6][10] = 0.964275951737726;
   fWeightMatrix1to2[7][10] = -0.440573948102087;
   fWeightMatrix1to2[8][10] = -1.32036203959597;
   fWeightMatrix1to2[9][10] = -3.66823014996638;
   fWeightMatrix1to2[10][10] = 0.896004173292247;
   fWeightMatrix1to2[0][11] = 1.91364472663406;
   fWeightMatrix1to2[1][11] = 1.34154057776132;
   fWeightMatrix1to2[2][11] = -1.00217130724832;
   fWeightMatrix1to2[3][11] = 0.126700808504799;
   fWeightMatrix1to2[4][11] = -1.21103926037549;
   fWeightMatrix1to2[5][11] = -1.26447546326308;
   fWeightMatrix1to2[6][11] = -2.43479887561303;
   fWeightMatrix1to2[7][11] = -0.791328463582796;
   fWeightMatrix1to2[8][11] = 0.20301449804724;
   fWeightMatrix1to2[9][11] = 2.2921542765937;
   fWeightMatrix1to2[10][11] = -1.20600959649659;
   // weight matrix from layer 2 to 3
   fWeightMatrix2to3[0][0] = 0.839501209661865;
   fWeightMatrix2to3[1][0] = -2.38088289379565;
   fWeightMatrix2to3[2][0] = -2.11454577692613;
   fWeightMatrix2to3[3][0] = 1.25567915052101;
   fWeightMatrix2to3[4][0] = 0.452180732452043;
   fWeightMatrix2to3[5][0] = -2.62620934458898;
   fWeightMatrix2to3[6][0] = -1.24450632763661;
   fWeightMatrix2to3[7][0] = 0.891959225111051;
   fWeightMatrix2to3[8][0] = -0.141713177121949;
   fWeightMatrix2to3[9][0] = 0.763980951771334;
   fWeightMatrix2to3[10][0] = -1.71999812036227;
   fWeightMatrix2to3[0][1] = -0.115696371510577;
   fWeightMatrix2to3[1][1] = 1.12291401016719;
   fWeightMatrix2to3[2][1] = 0.962021150637034;
   fWeightMatrix2to3[3][1] = 1.24031484442672;
   fWeightMatrix2to3[4][1] = -0.352635277410548;
   fWeightMatrix2to3[5][1] = 0.217075892623612;
   fWeightMatrix2to3[6][1] = -0.157259826605038;
   fWeightMatrix2to3[7][1] = -1.04809928349708;
   fWeightMatrix2to3[8][1] = -0.750527410261396;
   fWeightMatrix2to3[9][1] = -1.52336990500743;
   fWeightMatrix2to3[10][1] = -2.14760204483274;
   fWeightMatrix2to3[0][2] = -3.15046030076113;
   fWeightMatrix2to3[1][2] = 2.28384937846254;
   fWeightMatrix2to3[2][2] = -1.85237798136528;
   fWeightMatrix2to3[3][2] = 0.519206294539694;
   fWeightMatrix2to3[4][2] = -1.60201148740851;
   fWeightMatrix2to3[5][2] = 0.106192383498128;
   fWeightMatrix2to3[6][2] = -1.77033877295207;
   fWeightMatrix2to3[7][2] = -1.13403649116835;
   fWeightMatrix2to3[8][2] = 2.09008094545959;
   fWeightMatrix2to3[9][2] = -3.81627235291224;
   fWeightMatrix2to3[10][2] = 1.17668197457445;
   fWeightMatrix2to3[0][3] = 1.79049451361241;
   fWeightMatrix2to3[1][3] = -3.56685408456308;
   fWeightMatrix2to3[2][3] = -1.64278978511711;
   fWeightMatrix2to3[3][3] = -0.423620731143711;
   fWeightMatrix2to3[4][3] = -1.60224574458476;
   fWeightMatrix2to3[5][3] = 0.405488521170436;
   fWeightMatrix2to3[6][3] = -0.150983430394582;
   fWeightMatrix2to3[7][3] = 1.6243226799148;
   fWeightMatrix2to3[8][3] = -4.0680248853505;
   fWeightMatrix2to3[9][3] = 1.65768994967634;
   fWeightMatrix2to3[10][3] = -2.35999124877169;
   fWeightMatrix2to3[0][4] = -2.21834453587568;
   fWeightMatrix2to3[1][4] = -3.46765768697776;
   fWeightMatrix2to3[2][4] = 0.947042349815525;
   fWeightMatrix2to3[3][4] = -2.61771985455607;
   fWeightMatrix2to3[4][4] = -1.44592704593727;
   fWeightMatrix2to3[5][4] = 0.878619205063994;
   fWeightMatrix2to3[6][4] = -0.314982886827952;
   fWeightMatrix2to3[7][4] = -1.66196198575981;
   fWeightMatrix2to3[8][4] = 3.14252007661067;
   fWeightMatrix2to3[9][4] = -1.64061929839324;
   fWeightMatrix2to3[10][4] = 1.4387061992739;
   fWeightMatrix2to3[0][5] = 0.906798133819347;
   fWeightMatrix2to3[1][5] = -0.729908432782754;
   fWeightMatrix2to3[2][5] = -0.816754270714644;
   fWeightMatrix2to3[3][5] = 0.110984377212565;
   fWeightMatrix2to3[4][5] = -1.20482977968848;
   fWeightMatrix2to3[5][5] = 0.464695251261676;
   fWeightMatrix2to3[6][5] = 1.92206464676169;
   fWeightMatrix2to3[7][5] = 1.44309279533937;
   fWeightMatrix2to3[8][5] = 1.57931010768195;
   fWeightMatrix2to3[9][5] = -1.33170989884868;
   fWeightMatrix2to3[10][5] = 0.652254483912277;
   fWeightMatrix2to3[0][6] = -3.31305415460912;
   fWeightMatrix2to3[1][6] = -0.158530139895603;
   fWeightMatrix2to3[2][6] = -1.91856010448231;
   fWeightMatrix2to3[3][6] = -2.78018052470656;
   fWeightMatrix2to3[4][6] = -0.910364204822403;
   fWeightMatrix2to3[5][6] = 0.302162314297337;
   fWeightMatrix2to3[6][6] = 0.866978770179287;
   fWeightMatrix2to3[7][6] = 1.41809727973399;
   fWeightMatrix2to3[8][6] = -0.626500961441264;
   fWeightMatrix2to3[9][6] = 2.77482963987005;
   fWeightMatrix2to3[10][6] = -2.44404369988311;
   fWeightMatrix2to3[0][7] = 0.204252251971946;
   fWeightMatrix2to3[1][7] = 3.47854148888133;
   fWeightMatrix2to3[2][7] = -1.59345882348179;
   fWeightMatrix2to3[3][7] = -1.65604582127033;
   fWeightMatrix2to3[4][7] = -1.5842372934276;
   fWeightMatrix2to3[5][7] = -1.40635169354079;
   fWeightMatrix2to3[6][7] = -0.916029911902724;
   fWeightMatrix2to3[7][7] = -2.68540377582674;
   fWeightMatrix2to3[8][7] = -1.0851091292427;
   fWeightMatrix2to3[9][7] = -1.05743489609448;
   fWeightMatrix2to3[10][7] = 2.96241437542409;
   fWeightMatrix2to3[0][8] = 0.851298497226994;
   fWeightMatrix2to3[1][8] = -0.000938998850210375;
   fWeightMatrix2to3[2][8] = -0.966007802263119;
   fWeightMatrix2to3[3][8] = -3.19433054993219;
   fWeightMatrix2to3[4][8] = -1.86875266965275;
   fWeightMatrix2to3[5][8] = -0.230216659299348;
   fWeightMatrix2to3[6][8] = -0.663037701812901;
   fWeightMatrix2to3[7][8] = -1.95959257306085;
   fWeightMatrix2to3[8][8] = 0.616251880504028;
   fWeightMatrix2to3[9][8] = -3.18230794224657;
   fWeightMatrix2to3[10][8] = -2.1396757134951;
   fWeightMatrix2to3[0][9] = -3.55450267942504;
   fWeightMatrix2to3[1][9] = 0.723829137332636;
   fWeightMatrix2to3[2][9] = -1.43196304091351;
   fWeightMatrix2to3[3][9] = -2.40051573641507;
   fWeightMatrix2to3[4][9] = -0.787215649137316;
   fWeightMatrix2to3[5][9] = -2.10583291564231;
   fWeightMatrix2to3[6][9] = -2.32090087692981;
   fWeightMatrix2to3[7][9] = 0.58193124917;
   fWeightMatrix2to3[8][9] = -0.0230006868337265;
   fWeightMatrix2to3[9][9] = -2.99551560319063;
   fWeightMatrix2to3[10][9] = 2.45174244819726;
   fWeightMatrix2to3[0][10] = 0.405170565454923;
   fWeightMatrix2to3[1][10] = -1.12616078185017;
   fWeightMatrix2to3[2][10] = -0.0339249164962604;
   fWeightMatrix2to3[3][10] = 2.34682678704408;
   fWeightMatrix2to3[4][10] = 1.06376629400183;
   fWeightMatrix2to3[5][10] = 0.0883590184335421;
   fWeightMatrix2to3[6][10] = -0.818030451930235;
   fWeightMatrix2to3[7][10] = -0.0652284678163981;
   fWeightMatrix2to3[8][10] = -3.66849143858936;
   fWeightMatrix2to3[9][10] = 3.58688882146579;
   fWeightMatrix2to3[10][10] = -0.257786655214878;
   fWeightMatrix2to3[0][11] = 0.00914925977633358;
   fWeightMatrix2to3[1][11] = -0.210487532158528;
   fWeightMatrix2to3[2][11] = 0.769436318042529;
   fWeightMatrix2to3[3][11] = 1.77121801757904;
   fWeightMatrix2to3[4][11] = -2.19918415321436;
   fWeightMatrix2to3[5][11] = -0.262026777031965;
   fWeightMatrix2to3[6][11] = 0.360650920863458;
   fWeightMatrix2to3[7][11] = -1.76436126349698;
   fWeightMatrix2to3[8][11] = -1.89756098197184;
   fWeightMatrix2to3[9][11] = -0.726097163164913;
   fWeightMatrix2to3[10][11] = -0.813055351992891;
   // weight matrix from layer 3 to 4
   fWeightMatrix3to4[0][0] = -1.47540129590711;
   fWeightMatrix3to4[0][1] = 3.76954642030206;
   fWeightMatrix3to4[0][2] = 1.69508758679144;
   fWeightMatrix3to4[0][3] = -2.13665425750056;
   fWeightMatrix3to4[0][4] = 1.17615274915483;
   fWeightMatrix3to4[0][5] = -0.374232513573954;
   fWeightMatrix3to4[0][6] = -0.227107376348769;
   fWeightMatrix3to4[0][7] = -2.53461647602594;
   fWeightMatrix3to4[0][8] = 1.766610693429;
   fWeightMatrix3to4[0][9] = -1.80877958372074;
   fWeightMatrix3to4[0][10] = 1.99403196731194;
   fWeightMatrix3to4[0][11] = -0.0151210582023705;
}

inline double ReadMLP_ANN_N-7_NC500::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   if (inputValues.size() != (unsigned int)fLayerSize[0]-1) {
      std::cout << "Input vector needs to be of size " << fLayerSize[0]-1 << std::endl;
      return 0;
   }

   for (int l=0; l<fLayers; l++)
      for (int i=0; i<fLayerSize[l]; i++) fWeights[l][i]=0;

   for (int l=0; l<fLayers-1; l++)
      fWeights[l][fLayerSize[l]-1]=1;

   for (int i=0; i<fLayerSize[0]-1; i++)
      fWeights[0][i]=inputValues[i];

   // layer 0 to 1
   for (int o=0; o<fLayerSize[1]-1; o++) {
      for (int i=0; i<fLayerSize[0]; i++) {
         double inputVal = fWeightMatrix0to1[o][i] * fWeights[0][i];
         fWeights[1][o] += inputVal;
      }
      fWeights[1][o] = ActivationFnc(fWeights[1][o]);
   }
   // layer 1 to 2
   for (int o=0; o<fLayerSize[2]-1; o++) {
      for (int i=0; i<fLayerSize[1]; i++) {
         double inputVal = fWeightMatrix1to2[o][i] * fWeights[1][i];
         fWeights[2][o] += inputVal;
      }
      fWeights[2][o] = ActivationFnc(fWeights[2][o]);
   }
   // layer 2 to 3
   for (int o=0; o<fLayerSize[3]-1; o++) {
      for (int i=0; i<fLayerSize[2]; i++) {
         double inputVal = fWeightMatrix2to3[o][i] * fWeights[2][i];
         fWeights[3][o] += inputVal;
      }
      fWeights[3][o] = ActivationFnc(fWeights[3][o]);
   }
   // layer 3 to 4
   for (int o=0; o<fLayerSize[4]; o++) {
      for (int i=0; i<fLayerSize[3]; i++) {
         double inputVal = fWeightMatrix3to4[o][i] * fWeights[3][i];
         fWeights[4][o] += inputVal;
      }
      fWeights[4][o] = OutputActivationFnc(fWeights[4][o]);
   }

   return fWeights[4][0];
}

double ReadMLP_ANN_N-7_NC500::ActivationFnc(double x) const {
   // sigmoid
   return 1.0/(1.0+exp(-x));
}
double ReadMLP_ANN_N-7_NC500::OutputActivationFnc(double x) const {
   // sigmoid
   return 1.0/(1.0+exp(-x));
}
   
// Clean up
inline void ReadMLP_ANN_N-7_NC500::Clear() 
{
   // clean up the arrays
   for (int lIdx = 0; lIdx < 5; lIdx++) {
      delete[] fWeights[lIdx];
   }
}
   inline double ReadMLP_ANN_N-7_NC500::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            iV.reserve(inputValues.size());
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
         else {
            std::vector<double> iV;
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(*varIt);
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
      }

      return retval;
   }

//_______________________________________________________________________
inline void ReadMLP_ANN_N-7_NC500::InitTransform_1()
{
   // Normalization transformation, initialisation
   fMin_1[0][0] = 110.048698425;
   fMax_1[0][0] = 1277.92980957;
   fMin_1[1][0] = 110.057556152;
   fMax_1[1][0] = 1572.76037598;
   fMin_1[2][0] = 110.048698425;
   fMax_1[2][0] = 1572.76037598;
   fMin_1[0][1] = 5.00075817108;
   fMax_1[0][1] = 29.9497737885;
   fMin_1[1][1] = 5.00135278702;
   fMax_1[1][1] = 29.9984378815;
   fMin_1[2][1] = 5.00075817108;
   fMax_1[2][1] = 29.9984378815;
   fMin_1[0][2] = -1;
   fMax_1[0][2] = 1;
   fMin_1[1][2] = -1;
   fMax_1[1][2] = 1;
   fMin_1[2][2] = -1;
   fMax_1[2][2] = 1;
   fMin_1[0][3] = -2.4711689949;
   fMax_1[0][3] = 2.37911462784;
   fMin_1[1][3] = -2.48411560059;
   fMax_1[1][3] = 2.49880051613;
   fMin_1[2][3] = -2.48411560059;
   fMax_1[2][3] = 2.49880051613;
   fMin_1[0][4] = 280.2293396;
   fMax_1[0][4] = 1251.49438477;
   fMin_1[1][4] = 280.020294189;
   fMax_1[1][4] = 1289.47937012;
   fMin_1[2][4] = 280.020294189;
   fMax_1[2][4] = 1289.47937012;
   fMin_1[0][5] = 0.0557334087789;
   fMax_1[0][5] = 300.527191162;
   fMin_1[1][5] = 0.000537815736607;
   fMax_1[1][5] = 215.792510986;
   fMin_1[2][5] = 0.000537815736607;
   fMax_1[2][5] = 300.527191162;
   fMin_1[0][6] = 117.352531433;
   fMax_1[0][6] = 2347.48510742;
   fMin_1[1][6] = 112.003395081;
   fMax_1[1][6] = 4504.87304688;
   fMin_1[2][6] = 112.003395081;
   fMax_1[2][6] = 4504.87304688;
   fMin_1[0][7] = 0;
   fMax_1[0][7] = 5;
   fMin_1[1][7] = 0;
   fMax_1[1][7] = 6;
   fMin_1[2][7] = 0;
   fMax_1[2][7] = 6;
   fMin_1[0][8] = 1;
   fMax_1[0][8] = 11;
   fMin_1[1][8] = 1;
   fMax_1[1][8] = 14;
   fMin_1[2][8] = 1;
   fMax_1[2][8] = 14;
   fMin_1[0][9] = 20.0573444366;
   fMax_1[0][9] = 1057.04370117;
   fMin_1[1][9] = -999;
   fMax_1[1][9] = 1378.42883301;
   fMin_1[2][9] = -999;
   fMax_1[2][9] = 1378.42883301;
   fMin_1[0][10] = 6.27087429166e-05;
   fMax_1[0][10] = 4.95768356323;
   fMin_1[1][10] = -999;
   fMax_1[1][10] = 5.38026332855;
   fMin_1[2][10] = -999;
   fMax_1[2][10] = 5.38026332855;
}

//_______________________________________________________________________
inline void ReadMLP_ANN_N-7_NC500::Transform_1( std::vector<double>& iv, int cls) const
{
   // Normalization transformation
   if (cls < 0 || cls > 2) {
   if (2 > 1 ) cls = 2;
      else cls = 2;
   }
   const int nVar = 11;

   // get indices of used variables

   // define the indices of the variables which are transformed by this transformation
   static std::vector<int> indicesGet;
   static std::vector<int> indicesPut;

   if ( indicesGet.empty() ) { 
      indicesGet.reserve(fNvars);
      indicesGet.push_back( 0);
      indicesGet.push_back( 1);
      indicesGet.push_back( 2);
      indicesGet.push_back( 3);
      indicesGet.push_back( 4);
      indicesGet.push_back( 5);
      indicesGet.push_back( 6);
      indicesGet.push_back( 7);
      indicesGet.push_back( 8);
      indicesGet.push_back( 9);
      indicesGet.push_back( 10);
   } 
   if ( indicesPut.empty() ) { 
      indicesPut.reserve(fNvars);
      indicesPut.push_back( 0);
      indicesPut.push_back( 1);
      indicesPut.push_back( 2);
      indicesPut.push_back( 3);
      indicesPut.push_back( 4);
      indicesPut.push_back( 5);
      indicesPut.push_back( 6);
      indicesPut.push_back( 7);
      indicesPut.push_back( 8);
      indicesPut.push_back( 9);
      indicesPut.push_back( 10);
   } 

   static std::vector<double> dv;
   dv.resize(nVar);
   for (int ivar=0; ivar<nVar; ivar++) dv[ivar] = iv[indicesGet.at(ivar)];
   for (int ivar=0;ivar<11;ivar++) {
      double offset = fMin_1[cls][ivar];
      double scale  = 1.0/(fMax_1[cls][ivar]-fMin_1[cls][ivar]);
      iv[indicesPut.at(ivar)] = (dv[ivar]-offset)*scale * 2 - 1;
   }
}

//_______________________________________________________________________
inline void ReadMLP_ANN_N-7_NC500::InitTransform()
{
   InitTransform_1();
}

//_______________________________________________________________________
inline void ReadMLP_ANN_N-7_NC500::Transform( std::vector<double>& iv, int sigOrBgd ) const
{
   Transform_1( iv, sigOrBgd );
}
