// Class: ReadMLP_ANN_N3_NC700
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : MLP::MLP_ANN_N3_NC700
TMVA Release   : 4.2.1         [262657]
ROOT Release   : 6.06/01       [394753]
Creator        : brucms16
Date           : Wed Sep  7 03:46:56 2016
Host           : Linux vocms0315.cern.ch 2.6.32-573.26.1.el6.x86_64 #1 SMP Wed May 4 09:23:05 CEST 2016 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /home/t3cms/brucms16/CMSSW_8_0_14/src/UserCode/SkeletonAnalysis/macros
Training events: 15056
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
NCycles: "700" [Number of training cycles]
HiddenLayers: "N,N,N+3" [Specification of hidden layer architecture]
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
VarTransform: "Norm" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
H: "False" [Print method-specific help message]
LearningRate: "9.000000e-02" [ANN learning rate parameter]
DecayRate: "1.000000e-02" [Decay rate for learning parameter]
# Default:
NeuronType: "sigmoid" [Neuron activation function type]
RandomSeed: "1" [Random seed for initial synapse weights (0 means unique seed for each run; default value '1')]
EstimatorType: "CE" [MSE (Mean Square Estimator) for Gaussian Likelihood or CE(Cross-Entropy) for Bernoulli Likelihood]
NeuronInputType: "sum" [Neuron input function type]
VerbosityLevel: "Default" [Verbosity level]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
TrainingMethod: "BP" [Train with Back-Propagation (BP), BFGS Algorithm (BFGS), or Genetic Algorithm (GA - slower and worse)]
TestRate: "10" [Test for overtraining performed at each #th epochs]
EpochMonitoring: "False" [Provide epoch-wise monitoring plots according to TestRate (caution: causes big ROOT output file!)]
Sampling: "1.000000e+00" [Only 'Sampling' (randomly selected) events are trained each epoch]
SamplingEpoch: "1.000000e+00" [Sampling is used for the first 'SamplingEpoch' epochs, afterwards, all events are taken for training]
SamplingImportance: "1.000000e+00" [ The sampling weights of events in epochs which successful (worse estimator than before) are multiplied with SamplingImportance, else they are divided.]
SamplingTraining: "True" [The training sample is sampled]
SamplingTesting: "False" [The testing sample is sampled]
ResetStep: "50" [How often BFGS should reset history]
Tau: "3.000000e+00" [LineSearch "size step"]
BPMode: "sequential" [Back-propagation learning mode: sequential or batch]
BatchSize: "-1" [Batch size: number of events/batch, only set if in Batch Mode, -1 for BatchSize=number_of_events]
ConvergenceImprove: "1.000000e-30" [Minimum improvement which counts as improvement (<0 means automatic convergence check is turned off)]
ConvergenceTests: "-1" [Number of steps (without improvement) required for convergence (<0 means automatic convergence check is turned off)]
UseRegulator: "False" [Use regulator to avoid over-training]
UpdateLimit: "10000" [Maximum times of regulator update]
CalculateErrors: "False" [Calculates inverse Hessian matrix at the end of the training to be able to calculate the uncertainties of an MVA value]
WeightRange: "1.000000e+00" [Take the events for the estimator calculations from small deviations from the desired value to large deviations only over the weight range]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 11
Jet1Pt                        Jet1Pt                        Jet1Pt                        Jet1Pt                                                          'F'    [110.048698425,1572.76037598]
LepPt                         LepPt                         LepPt                         LepPt                                                           'F'    [5.00075817108,29.9984378815]
LepChg                        LepChg                        LepChg                        LepChg                                                          'F'    [-1,1]
LepEta                        LepEta                        LepEta                        LepEta                                                          'F'    [-2.48411560059,2.49880051613]
Met                           Met                           Met                           Met                                                             'F'    [280.020294189,1289.47937012]
mt                            mt                            mt                            mt                                                              'F'    [0.000537815736607,300.527191162]
HT20                          HT20                          HT20                          HT20                                                            'F'    [112.003395081,4504.87304688]
NbLoose30                     NbLoose30                     NbLoose30                     NbLoose30                                                       'F'    [0,6]
Njet                          Njet                          Njet                          Njet                                                            'F'    [1,14]
JetHBpt                       JetHBpt                       JetHBpt                       JetHBpt                                                         'F'    [-999,1378.42883301]
DrJetHBLep                    DrJetHBLep                    DrJetHBLep                    DrJetHBLep                                                      'F'    [-999,5.38026332855]
NSpec 0


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadMLP_ANN_N3_NC700 : public IClassifierReader {

 public:

   // constructor
   ReadMLP_ANN_N3_NC700( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadMLP_ANN_N3_NC700" ),
        fNvars( 11 ),
        fIsNormalised( false )
   {      
      // the training input variables
      const char* inputVars[] = { "Jet1Pt", "LepPt", "LepChg", "LepEta", "Met", "mt", "HT20", "NbLoose30", "Njet", "JetHBpt", "DrJetHBLep" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = -1;
      fVmax[0] = 1;
      fVmin[1] = -1;
      fVmax[1] = 0.99999988079071;
      fVmin[2] = -1;
      fVmax[2] = 1;
      fVmin[3] = -1;
      fVmax[3] = 1;
      fVmin[4] = -1;
      fVmax[4] = 1;
      fVmin[5] = -1;
      fVmax[5] = 1;
      fVmin[6] = -1;
      fVmax[6] = 1;
      fVmin[7] = -1;
      fVmax[7] = 1;
      fVmin[8] = -1;
      fVmax[8] = 1;
      fVmin[9] = -1;
      fVmax[9] = 1;
      fVmin[10] = -1;
      fVmax[10] = 1;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';
      fType[4] = 'F';
      fType[5] = 'F';
      fType[6] = 'F';
      fType[7] = 'F';
      fType[8] = 'F';
      fType[9] = 'F';
      fType[10] = 'F';

      // initialize constants
      Initialize();

      // initialize transformation
      InitTransform();
   }

   // destructor
   virtual ~ReadMLP_ANN_N3_NC700() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // input variable transformation

   double fMin_1[3][11];
   double fMax_1[3][11];
   void InitTransform_1();
   void Transform_1( std::vector<double> & iv, int sigOrBgd ) const;
   void InitTransform();
   void Transform( std::vector<double> & iv, int sigOrBgd ) const;

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[11];
   double fVmax[11];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[11];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)

   double ActivationFnc(double x) const;
   double OutputActivationFnc(double x) const;

   int fLayers;
   int fLayerSize[5];
   double fWeightMatrix0to1[12][12];   // weight matrix from layer 0 to 1
   double fWeightMatrix1to2[12][12];   // weight matrix from layer 1 to 2
   double fWeightMatrix2to3[15][12];   // weight matrix from layer 2 to 3
   double fWeightMatrix3to4[1][15];   // weight matrix from layer 3 to 4

   double * fWeights[5];
};

inline void ReadMLP_ANN_N3_NC700::Initialize()
{
   // build network structure
   fLayers = 5;
   fLayerSize[0] = 12; fWeights[0] = new double[12]; 
   fLayerSize[1] = 12; fWeights[1] = new double[12]; 
   fLayerSize[2] = 12; fWeights[2] = new double[12]; 
   fLayerSize[3] = 15; fWeights[3] = new double[15]; 
   fLayerSize[4] = 1; fWeights[4] = new double[1]; 
   // weight matrix from layer 0 to 1
   fWeightMatrix0to1[0][0] = 0.826124503539001;
   fWeightMatrix0to1[1][0] = 0.541838881252339;
   fWeightMatrix0to1[2][0] = 1.44887512119256;
   fWeightMatrix0to1[3][0] = 4.2446316690656;
   fWeightMatrix0to1[4][0] = -2.02962275082089;
   fWeightMatrix0to1[5][0] = -0.521329870843346;
   fWeightMatrix0to1[6][0] = 1.38696687571461;
   fWeightMatrix0to1[7][0] = 1.44688075351307;
   fWeightMatrix0to1[8][0] = -2.2195464569688;
   fWeightMatrix0to1[9][0] = -0.3807171146618;
   fWeightMatrix0to1[10][0] = -3.42064297607332;
   fWeightMatrix0to1[0][1] = 2.49932726548661;
   fWeightMatrix0to1[1][1] = -0.3970854982323;
   fWeightMatrix0to1[2][1] = -3.16602080576884;
   fWeightMatrix0to1[3][1] = -0.401564361039449;
   fWeightMatrix0to1[4][1] = 0.97189186419308;
   fWeightMatrix0to1[5][1] = -1.89717618631342;
   fWeightMatrix0to1[6][1] = 2.38864077495725;
   fWeightMatrix0to1[7][1] = -0.191626896961931;
   fWeightMatrix0to1[8][1] = 3.12456030264362;
   fWeightMatrix0to1[9][1] = 1.08382802420844;
   fWeightMatrix0to1[10][1] = -0.229841060969676;
   fWeightMatrix0to1[0][2] = 1.42988765477086;
   fWeightMatrix0to1[1][2] = 0.0814046030050056;
   fWeightMatrix0to1[2][2] = 0.507662247117426;
   fWeightMatrix0to1[3][2] = -4.25490317809569;
   fWeightMatrix0to1[4][2] = 1.22934291526562;
   fWeightMatrix0to1[5][2] = 0.582157608362458;
   fWeightMatrix0to1[6][2] = -3.64896012362339;
   fWeightMatrix0to1[7][2] = 0.551318276727493;
   fWeightMatrix0to1[8][2] = -0.386037429964509;
   fWeightMatrix0to1[9][2] = -0.139329808685972;
   fWeightMatrix0to1[10][2] = -0.770397312366642;
   fWeightMatrix0to1[0][3] = 0.0121265007057155;
   fWeightMatrix0to1[1][3] = 0.0547721745198936;
   fWeightMatrix0to1[2][3] = 1.57958362977565;
   fWeightMatrix0to1[3][3] = -1.07524798333472;
   fWeightMatrix0to1[4][3] = 1.53278444006607;
   fWeightMatrix0to1[5][3] = -2.41185633497734;
   fWeightMatrix0to1[6][3] = 0.658712846744803;
   fWeightMatrix0to1[7][3] = 1.00623892791927;
   fWeightMatrix0to1[8][3] = -0.388960546788141;
   fWeightMatrix0to1[9][3] = 5.20769415686929;
   fWeightMatrix0to1[10][3] = -2.96485666922399;
   fWeightMatrix0to1[0][4] = 6.28619938336519;
   fWeightMatrix0to1[1][4] = -2.92784416680203;
   fWeightMatrix0to1[2][4] = 9.09704670918835;
   fWeightMatrix0to1[3][4] = 0.673801227910187;
   fWeightMatrix0to1[4][4] = 2.51557866272594;
   fWeightMatrix0to1[5][4] = 6.82264114503622;
   fWeightMatrix0to1[6][4] = 4.06054828145702;
   fWeightMatrix0to1[7][4] = 1.09370580746648;
   fWeightMatrix0to1[8][4] = -4.35578967119365;
   fWeightMatrix0to1[9][4] = 0.210085341751426;
   fWeightMatrix0to1[10][4] = -0.490408662134464;
   fWeightMatrix0to1[0][5] = -1.60887965734029;
   fWeightMatrix0to1[1][5] = -17.8174107575712;
   fWeightMatrix0to1[2][5] = 0.116486486633129;
   fWeightMatrix0to1[3][5] = 3.44601237889445;
   fWeightMatrix0to1[4][5] = 0.0760083740895087;
   fWeightMatrix0to1[5][5] = -2.82365227430178;
   fWeightMatrix0to1[6][5] = -0.014667964058278;
   fWeightMatrix0to1[7][5] = -0.765645409090048;
   fWeightMatrix0to1[8][5] = 2.76384724920882;
   fWeightMatrix0to1[9][5] = 2.32251529043123;
   fWeightMatrix0to1[10][5] = 3.43142075163251;
   fWeightMatrix0to1[0][6] = -1.371327034463;
   fWeightMatrix0to1[1][6] = 3.62382496012302;
   fWeightMatrix0to1[2][6] = -4.37455108685297;
   fWeightMatrix0to1[3][6] = -0.707933652648408;
   fWeightMatrix0to1[4][6] = -0.60921923823508;
   fWeightMatrix0to1[5][6] = -1.9480108772347;
   fWeightMatrix0to1[6][6] = -0.147154549639722;
   fWeightMatrix0to1[7][6] = 0.607667088510254;
   fWeightMatrix0to1[8][6] = 3.69607432674189;
   fWeightMatrix0to1[9][6] = 1.8092315687376;
   fWeightMatrix0to1[10][6] = -0.683956609386623;
   fWeightMatrix0to1[0][7] = -6.6563513386232;
   fWeightMatrix0to1[1][7] = -0.377664252094515;
   fWeightMatrix0to1[2][7] = -3.76903844464002;
   fWeightMatrix0to1[3][7] = 0.341348839536804;
   fWeightMatrix0to1[4][7] = 1.70634724213141;
   fWeightMatrix0to1[5][7] = 1.438942333311;
   fWeightMatrix0to1[6][7] = -2.9603196044278;
   fWeightMatrix0to1[7][7] = -1.3450462203204;
   fWeightMatrix0to1[8][7] = 0.669513883124115;
   fWeightMatrix0to1[9][7] = 0.219754090214569;
   fWeightMatrix0to1[10][7] = -0.888432607710391;
   fWeightMatrix0to1[0][8] = -5.8452412064002;
   fWeightMatrix0to1[1][8] = 0.273545027857735;
   fWeightMatrix0to1[2][8] = -0.768708226488148;
   fWeightMatrix0to1[3][8] = 1.27408866365233;
   fWeightMatrix0to1[4][8] = 1.60132766873369;
   fWeightMatrix0to1[5][8] = -1.09104517836382;
   fWeightMatrix0to1[6][8] = -2.21482780027767;
   fWeightMatrix0to1[7][8] = 1.68045230751908;
   fWeightMatrix0to1[8][8] = -3.80171696469246;
   fWeightMatrix0to1[9][8] = -5.76575370597412;
   fWeightMatrix0to1[10][8] = -6.51735980468837;
   fWeightMatrix0to1[0][9] = -1.52566294324382;
   fWeightMatrix0to1[1][9] = 3.24169291394732;
   fWeightMatrix0to1[2][9] = -5.35766788999614;
   fWeightMatrix0to1[3][9] = 1.08628953635581;
   fWeightMatrix0to1[4][9] = 1.29304021619957;
   fWeightMatrix0to1[5][9] = 0.19477725983479;
   fWeightMatrix0to1[6][9] = 3.75069881018852;
   fWeightMatrix0to1[7][9] = -1.13039772847508;
   fWeightMatrix0to1[8][9] = 0.399349801459185;
   fWeightMatrix0to1[9][9] = -1.28159448940483;
   fWeightMatrix0to1[10][9] = -0.391418385559401;
   fWeightMatrix0to1[0][10] = -1.77696309102307;
   fWeightMatrix0to1[1][10] = -2.30339330930864;
   fWeightMatrix0to1[2][10] = 1.24018765573249;
   fWeightMatrix0to1[3][10] = 1.01314419337096;
   fWeightMatrix0to1[4][10] = -1.74608173488246;
   fWeightMatrix0to1[5][10] = 2.74283412773413;
   fWeightMatrix0to1[6][10] = 0.473920387966489;
   fWeightMatrix0to1[7][10] = -0.519806294963082;
   fWeightMatrix0to1[8][10] = -0.462554145970248;
   fWeightMatrix0to1[9][10] = -2.51689175450384;
   fWeightMatrix0to1[10][10] = -4.3419357822763;
   fWeightMatrix0to1[0][11] = 0.181383486466404;
   fWeightMatrix0to1[1][11] = -2.98244668555341;
   fWeightMatrix0to1[2][11] = 2.4566066442889;
   fWeightMatrix0to1[3][11] = 1.30481421237311;
   fWeightMatrix0to1[4][11] = -0.364824146784392;
   fWeightMatrix0to1[5][11] = 0.502888362117278;
   fWeightMatrix0to1[6][11] = 0.169388096387099;
   fWeightMatrix0to1[7][11] = -1.36269219055004;
   fWeightMatrix0to1[8][11] = 0.259695249373518;
   fWeightMatrix0to1[9][11] = -0.93563785071009;
   fWeightMatrix0to1[10][11] = -4.42071846877196;
   // weight matrix from layer 1 to 2
   fWeightMatrix1to2[0][0] = 0.717423152577354;
   fWeightMatrix1to2[1][0] = -0.798241727021845;
   fWeightMatrix1to2[2][0] = 1.82154472362755;
   fWeightMatrix1to2[3][0] = -1.46727635888107;
   fWeightMatrix1to2[4][0] = 3.30544896650777;
   fWeightMatrix1to2[5][0] = -2.33192712078715;
   fWeightMatrix1to2[6][0] = -1.56314085976463;
   fWeightMatrix1to2[7][0] = 3.53265361722104;
   fWeightMatrix1to2[8][0] = 1.84527598392194;
   fWeightMatrix1to2[9][0] = -3.87031972034688;
   fWeightMatrix1to2[10][0] = -1.69613287777288;
   fWeightMatrix1to2[0][1] = 1.26891869368672;
   fWeightMatrix1to2[1][1] = -3.54304664927347;
   fWeightMatrix1to2[2][1] = 0.824064970246656;
   fWeightMatrix1to2[3][1] = 3.4608600191888;
   fWeightMatrix1to2[4][1] = -2.40578269946476;
   fWeightMatrix1to2[5][1] = 0.259397998289145;
   fWeightMatrix1to2[6][1] = -2.38848026094053;
   fWeightMatrix1to2[7][1] = -5.05946467360658;
   fWeightMatrix1to2[8][1] = -2.28717046340657;
   fWeightMatrix1to2[9][1] = -1.31045525488041;
   fWeightMatrix1to2[10][1] = -1.25111548626838;
   fWeightMatrix1to2[0][2] = -0.917574945805214;
   fWeightMatrix1to2[1][2] = 0.216181801491229;
   fWeightMatrix1to2[2][2] = 1.76524004351396;
   fWeightMatrix1to2[3][2] = -2.61266002753458;
   fWeightMatrix1to2[4][2] = -0.881222843905596;
   fWeightMatrix1to2[5][2] = -1.08009065528233;
   fWeightMatrix1to2[6][2] = 3.6886488883835;
   fWeightMatrix1to2[7][2] = 3.00351023333962;
   fWeightMatrix1to2[8][2] = 2.95844224205354;
   fWeightMatrix1to2[9][2] = -1.89512007180518;
   fWeightMatrix1to2[10][2] = 2.19569513828904;
   fWeightMatrix1to2[0][3] = -0.789929806978961;
   fWeightMatrix1to2[1][3] = -0.833760358778937;
   fWeightMatrix1to2[2][3] = 1.13615926391989;
   fWeightMatrix1to2[3][3] = -1.59306461868419;
   fWeightMatrix1to2[4][3] = -0.167681106862471;
   fWeightMatrix1to2[5][3] = 0.824369865391189;
   fWeightMatrix1to2[6][3] = 2.41278000876248;
   fWeightMatrix1to2[7][3] = 0.766045739346503;
   fWeightMatrix1to2[8][3] = 2.68326706582484;
   fWeightMatrix1to2[9][3] = 4.18773700567017;
   fWeightMatrix1to2[10][3] = -2.20291191371018;
   fWeightMatrix1to2[0][4] = 0.50083361858435;
   fWeightMatrix1to2[1][4] = -0.0581159784108057;
   fWeightMatrix1to2[2][4] = 0.634884825853459;
   fWeightMatrix1to2[3][4] = -1.86343946684247;
   fWeightMatrix1to2[4][4] = -1.01094526876679;
   fWeightMatrix1to2[5][4] = 1.30012511935244;
   fWeightMatrix1to2[6][4] = 2.69251267370564;
   fWeightMatrix1to2[7][4] = -1.00912274602879;
   fWeightMatrix1to2[8][4] = 0.163430724405904;
   fWeightMatrix1to2[9][4] = -0.381396105097574;
   fWeightMatrix1to2[10][4] = 0.40346645012115;
   fWeightMatrix1to2[0][5] = 0.777233637707763;
   fWeightMatrix1to2[1][5] = -0.142671354096474;
   fWeightMatrix1to2[2][5] = 1.10016301249777;
   fWeightMatrix1to2[3][5] = -2.73103900177471;
   fWeightMatrix1to2[4][5] = 2.96376737621578;
   fWeightMatrix1to2[5][5] = 2.51478161625934;
   fWeightMatrix1to2[6][5] = 2.97962401148973;
   fWeightMatrix1to2[7][5] = -2.01039376629037;
   fWeightMatrix1to2[8][5] = -1.4073499899461;
   fWeightMatrix1to2[9][5] = -4.67478468238693;
   fWeightMatrix1to2[10][5] = 0.0417208507258414;
   fWeightMatrix1to2[0][6] = 0.839748686727042;
   fWeightMatrix1to2[1][6] = -1.1706367740006;
   fWeightMatrix1to2[2][6] = 3.76498082071627;
   fWeightMatrix1to2[3][6] = -0.755462624911128;
   fWeightMatrix1to2[4][6] = -0.0485693304273847;
   fWeightMatrix1to2[5][6] = -2.9499866789038;
   fWeightMatrix1to2[6][6] = 1.87596909918374;
   fWeightMatrix1to2[7][6] = 3.395562947966;
   fWeightMatrix1to2[8][6] = 0.321605643257771;
   fWeightMatrix1to2[9][6] = -1.27504175932664;
   fWeightMatrix1to2[10][6] = 1.86191373475908;
   fWeightMatrix1to2[0][7] = 1.0994146856924;
   fWeightMatrix1to2[1][7] = 0.421435367640221;
   fWeightMatrix1to2[2][7] = -0.181075698964774;
   fWeightMatrix1to2[3][7] = -1.78785590925497;
   fWeightMatrix1to2[4][7] = -0.937878119550537;
   fWeightMatrix1to2[5][7] = 1.94847424210498;
   fWeightMatrix1to2[6][7] = 1.43392976694781;
   fWeightMatrix1to2[7][7] = 0.954414924685745;
   fWeightMatrix1to2[8][7] = 0.502974361611004;
   fWeightMatrix1to2[9][7] = 1.98327951085341;
   fWeightMatrix1to2[10][7] = -1.61807035472224;
   fWeightMatrix1to2[0][8] = -1.96432004219655;
   fWeightMatrix1to2[1][8] = -0.604484997520152;
   fWeightMatrix1to2[2][8] = -3.23566029432556;
   fWeightMatrix1to2[3][8] = 3.21703581759824;
   fWeightMatrix1to2[4][8] = 1.07759329887243;
   fWeightMatrix1to2[5][8] = -2.40968268563073;
   fWeightMatrix1to2[6][8] = -2.48592180368849;
   fWeightMatrix1to2[7][8] = -3.14601975421127;
   fWeightMatrix1to2[8][8] = -2.90563281199929;
   fWeightMatrix1to2[9][8] = 1.38859125886773;
   fWeightMatrix1to2[10][8] = 0.279229912599822;
   fWeightMatrix1to2[0][9] = 1.13167535276903;
   fWeightMatrix1to2[1][9] = 0.904846355566625;
   fWeightMatrix1to2[2][9] = -4.62524080456914;
   fWeightMatrix1to2[3][9] = 1.33325631506498;
   fWeightMatrix1to2[4][9] = -3.04954301573283;
   fWeightMatrix1to2[5][9] = 0.937292648700027;
   fWeightMatrix1to2[6][9] = -0.303395522286206;
   fWeightMatrix1to2[7][9] = -2.38284493668144;
   fWeightMatrix1to2[8][9] = -2.25240605202218;
   fWeightMatrix1to2[9][9] = -0.159994731765628;
   fWeightMatrix1to2[10][9] = -0.351410083495043;
   fWeightMatrix1to2[0][10] = -3.36242257075174;
   fWeightMatrix1to2[1][10] = -1.3054839185675;
   fWeightMatrix1to2[2][10] = -4.79381855721025;
   fWeightMatrix1to2[3][10] = 1.75317073494308;
   fWeightMatrix1to2[4][10] = -2.27760878375184;
   fWeightMatrix1to2[5][10] = -2.13254089908094;
   fWeightMatrix1to2[6][10] = 0.635165372895121;
   fWeightMatrix1to2[7][10] = -5.82101059972273;
   fWeightMatrix1to2[8][10] = -2.36095247224;
   fWeightMatrix1to2[9][10] = -2.00350067698142;
   fWeightMatrix1to2[10][10] = -0.612226573049234;
   fWeightMatrix1to2[0][11] = 1.97568196413525;
   fWeightMatrix1to2[1][11] = 0.961757761917959;
   fWeightMatrix1to2[2][11] = 0.00411453570353283;
   fWeightMatrix1to2[3][11] = -0.893413160667913;
   fWeightMatrix1to2[4][11] = -1.86664165953118;
   fWeightMatrix1to2[5][11] = -0.132921493848141;
   fWeightMatrix1to2[6][11] = -2.21813469350111;
   fWeightMatrix1to2[7][11] = 2.25379743834997;
   fWeightMatrix1to2[8][11] = -0.824103271172032;
   fWeightMatrix1to2[9][11] = 1.56342970370681;
   fWeightMatrix1to2[10][11] = -0.966186718187148;
   // weight matrix from layer 2 to 3
   fWeightMatrix2to3[0][0] = -1.88170903896375;
   fWeightMatrix2to3[1][0] = -0.555666213397011;
   fWeightMatrix2to3[2][0] = -2.97849526366049;
   fWeightMatrix2to3[3][0] = 0.165901054591437;
   fWeightMatrix2to3[4][0] = -1.21878500924094;
   fWeightMatrix2to3[5][0] = -1.3079156949708;
   fWeightMatrix2to3[6][0] = -1.97159197335492;
   fWeightMatrix2to3[7][0] = 0.355246066780571;
   fWeightMatrix2to3[8][0] = 0.6636211110645;
   fWeightMatrix2to3[9][0] = -0.610120762866682;
   fWeightMatrix2to3[10][0] = -1.70144644383603;
   fWeightMatrix2to3[11][0] = -0.540801661387737;
   fWeightMatrix2to3[12][0] = -0.326590310954187;
   fWeightMatrix2to3[13][0] = 0.270241136546518;
   fWeightMatrix2to3[0][1] = 0.787364343409076;
   fWeightMatrix2to3[1][1] = -0.181962245847999;
   fWeightMatrix2to3[2][1] = -0.508233306547064;
   fWeightMatrix2to3[3][1] = -0.440584539209697;
   fWeightMatrix2to3[4][1] = -1.78542588218952;
   fWeightMatrix2to3[5][1] = -0.572460352109159;
   fWeightMatrix2to3[6][1] = -1.67997535531725;
   fWeightMatrix2to3[7][1] = -1.52883271475279;
   fWeightMatrix2to3[8][1] = -1.0218462478668;
   fWeightMatrix2to3[9][1] = 1.48282639578064;
   fWeightMatrix2to3[10][1] = -1.69828863071613;
   fWeightMatrix2to3[11][1] = 1.53981706920322;
   fWeightMatrix2to3[12][1] = -1.60178357013984;
   fWeightMatrix2to3[13][1] = 1.03358513486004;
   fWeightMatrix2to3[0][2] = -3.68041342490338;
   fWeightMatrix2to3[1][2] = 1.06636105873379;
   fWeightMatrix2to3[2][2] = -1.25180729548492;
   fWeightMatrix2to3[3][2] = -2.97107255059108;
   fWeightMatrix2to3[4][2] = -0.90231925836739;
   fWeightMatrix2to3[5][2] = 0.328679303563898;
   fWeightMatrix2to3[6][2] = -2.56538704805594;
   fWeightMatrix2to3[7][2] = -2.53111486748731;
   fWeightMatrix2to3[8][2] = -2.45654708041847;
   fWeightMatrix2to3[9][2] = -1.92195190144933;
   fWeightMatrix2to3[10][2] = 0.421017392584563;
   fWeightMatrix2to3[11][2] = -1.1455841364332;
   fWeightMatrix2to3[12][2] = -0.0165455941265695;
   fWeightMatrix2to3[13][2] = -1.16660206384379;
   fWeightMatrix2to3[0][3] = 1.44222776476742;
   fWeightMatrix2to3[1][3] = -1.67893334497697;
   fWeightMatrix2to3[2][3] = -2.85653746903836;
   fWeightMatrix2to3[3][3] = -2.21510718743152;
   fWeightMatrix2to3[4][3] = -0.0286662957596588;
   fWeightMatrix2to3[5][3] = -1.3256614091749;
   fWeightMatrix2to3[6][3] = -1.23238750915023;
   fWeightMatrix2to3[7][3] = 1.94598406968731;
   fWeightMatrix2to3[8][3] = 0.434496809067301;
   fWeightMatrix2to3[9][3] = -0.0278910497722906;
   fWeightMatrix2to3[10][3] = 2.13989126394691;
   fWeightMatrix2to3[11][3] = -2.82354274403463;
   fWeightMatrix2to3[12][3] = 0.539244559373142;
   fWeightMatrix2to3[13][3] = 0.308310783141748;
   fWeightMatrix2to3[0][4] = -3.32111087968423;
   fWeightMatrix2to3[1][4] = -0.899598637350469;
   fWeightMatrix2to3[2][4] = 0.577443344694755;
   fWeightMatrix2to3[3][4] = -0.826667777428329;
   fWeightMatrix2to3[4][4] = -0.74019776534899;
   fWeightMatrix2to3[5][4] = 1.6709042523706;
   fWeightMatrix2to3[6][4] = 2.04347490102228;
   fWeightMatrix2to3[7][4] = 2.81686595150703;
   fWeightMatrix2to3[8][4] = -2.79862371437297;
   fWeightMatrix2to3[9][4] = 0.308123507297084;
   fWeightMatrix2to3[10][4] = -2.46025838364294;
   fWeightMatrix2to3[11][4] = 2.33724061789533;
   fWeightMatrix2to3[12][4] = -3.03860846109191;
   fWeightMatrix2to3[13][4] = -2.06213469134354;
   fWeightMatrix2to3[0][5] = 0.619743769819746;
   fWeightMatrix2to3[1][5] = 1.47484598812519;
   fWeightMatrix2to3[2][5] = 2.49311556105326;
   fWeightMatrix2to3[3][5] = 0.758526102900168;
   fWeightMatrix2to3[4][5] = 0.195664060073511;
   fWeightMatrix2to3[5][5] = -0.197271408399652;
   fWeightMatrix2to3[6][5] = -0.969654986862044;
   fWeightMatrix2to3[7][5] = 0.955142592816416;
   fWeightMatrix2to3[8][5] = 3.05138832195749;
   fWeightMatrix2to3[9][5] = -1.78847251096402;
   fWeightMatrix2to3[10][5] = 0.597586499879465;
   fWeightMatrix2to3[11][5] = -1.66063897188468;
   fWeightMatrix2to3[12][5] = -0.163560846901056;
   fWeightMatrix2to3[13][5] = -0.0532196702234156;
   fWeightMatrix2to3[0][6] = -1.48443497492619;
   fWeightMatrix2to3[1][6] = -1.24849603168423;
   fWeightMatrix2to3[2][6] = 2.69795325168378;
   fWeightMatrix2to3[3][6] = 1.89449995995255;
   fWeightMatrix2to3[4][6] = -0.333251216665661;
   fWeightMatrix2to3[5][6] = -0.559705398167955;
   fWeightMatrix2to3[6][6] = -1.14421685438421;
   fWeightMatrix2to3[7][6] = -2.52899270886498;
   fWeightMatrix2to3[8][6] = -2.69344082632757;
   fWeightMatrix2to3[9][6] = 0.513611754901189;
   fWeightMatrix2to3[10][6] = -1.13164717718743;
   fWeightMatrix2to3[11][6] = -0.995175867451641;
   fWeightMatrix2to3[12][6] = -0.538883129950928;
   fWeightMatrix2to3[13][6] = -2.1615835680622;
   fWeightMatrix2to3[0][7] = -3.67142210408599;
   fWeightMatrix2to3[1][7] = -1.77084023946388;
   fWeightMatrix2to3[2][7] = 1.22882934110623;
   fWeightMatrix2to3[3][7] = -1.08913944093637;
   fWeightMatrix2to3[4][7] = -2.48139891292738;
   fWeightMatrix2to3[5][7] = -1.1382390417999;
   fWeightMatrix2to3[6][7] = -1.71863815768448;
   fWeightMatrix2to3[7][7] = -4.01020726548053;
   fWeightMatrix2to3[8][7] = 0.83163991964419;
   fWeightMatrix2to3[9][7] = -2.72320283112555;
   fWeightMatrix2to3[10][7] = -1.86712239798272;
   fWeightMatrix2to3[11][7] = 3.31241618288867;
   fWeightMatrix2to3[12][7] = 0.0120365234792353;
   fWeightMatrix2to3[13][7] = 0.193620023917824;
   fWeightMatrix2to3[0][8] = -1.55244104736062;
   fWeightMatrix2to3[1][8] = 1.37293748396559;
   fWeightMatrix2to3[2][8] = 4.11114302643295;
   fWeightMatrix2to3[3][8] = 1.17075015406692;
   fWeightMatrix2to3[4][8] = -1.34139485870289;
   fWeightMatrix2to3[5][8] = -1.05934269852438;
   fWeightMatrix2to3[6][8] = -2.50516178044148;
   fWeightMatrix2to3[7][8] = -0.270256137973675;
   fWeightMatrix2to3[8][8] = 1.23645458607782;
   fWeightMatrix2to3[9][8] = -1.03980634383989;
   fWeightMatrix2to3[10][8] = 0.498995817499133;
   fWeightMatrix2to3[11][8] = 1.73956469857406;
   fWeightMatrix2to3[12][8] = 1.2420860826093;
   fWeightMatrix2to3[13][8] = -1.39416074568608;
   fWeightMatrix2to3[0][9] = 3.21738798582869;
   fWeightMatrix2to3[1][9] = 0.826579692550863;
   fWeightMatrix2to3[2][9] = -3.84905063408365;
   fWeightMatrix2to3[3][9] = -0.776558478823457;
   fWeightMatrix2to3[4][9] = -1.29349429735306;
   fWeightMatrix2to3[5][9] = 0.966756392321344;
   fWeightMatrix2to3[6][9] = 0.621210021289242;
   fWeightMatrix2to3[7][9] = 1.14948512982957;
   fWeightMatrix2to3[8][9] = 2.47830377373116;
   fWeightMatrix2to3[9][9] = -0.523135681435188;
   fWeightMatrix2to3[10][9] = 1.64381177798638;
   fWeightMatrix2to3[11][9] = -0.487449454023572;
   fWeightMatrix2to3[12][9] = 0.954522171623853;
   fWeightMatrix2to3[13][9] = -1.3483940503313;
   fWeightMatrix2to3[0][10] = 0.696951988075437;
   fWeightMatrix2to3[1][10] = -1.65234068628916;
   fWeightMatrix2to3[2][10] = 0.15355072773157;
   fWeightMatrix2to3[3][10] = 1.22497396477507;
   fWeightMatrix2to3[4][10] = -0.762322539041731;
   fWeightMatrix2to3[5][10] = -0.860461062538263;
   fWeightMatrix2to3[6][10] = 0.0510568272394606;
   fWeightMatrix2to3[7][10] = -1.90726881739391;
   fWeightMatrix2to3[8][10] = 0.668881495662087;
   fWeightMatrix2to3[9][10] = -2.17031675433199;
   fWeightMatrix2to3[10][10] = 0.183914731202522;
   fWeightMatrix2to3[11][10] = -1.00404721780016;
   fWeightMatrix2to3[12][10] = 2.38503498731156;
   fWeightMatrix2to3[13][10] = 0.944952113473517;
   fWeightMatrix2to3[0][11] = 1.30824640190413;
   fWeightMatrix2to3[1][11] = 0.0459558455121077;
   fWeightMatrix2to3[2][11] = -2.35345274529471;
   fWeightMatrix2to3[3][11] = -0.750087994969391;
   fWeightMatrix2to3[4][11] = -0.22275203878263;
   fWeightMatrix2to3[5][11] = -1.94710675593676;
   fWeightMatrix2to3[6][11] = -0.670173420438475;
   fWeightMatrix2to3[7][11] = -0.0159543075908973;
   fWeightMatrix2to3[8][11] = -1.54196120596164;
   fWeightMatrix2to3[9][11] = -2.00561774127697;
   fWeightMatrix2to3[10][11] = -2.01295275150033;
   fWeightMatrix2to3[11][11] = -0.324922321162709;
   fWeightMatrix2to3[12][11] = -1.43506161743873;
   fWeightMatrix2to3[13][11] = -2.86613129488773;
   // weight matrix from layer 3 to 4
   fWeightMatrix3to4[0][0] = -4.17723662720697;
   fWeightMatrix3to4[0][1] = -1.50910167985851;
   fWeightMatrix3to4[0][2] = 2.92983983183746;
   fWeightMatrix3to4[0][3] = 1.07868399039923;
   fWeightMatrix3to4[0][4] = -0.950122942700989;
   fWeightMatrix3to4[0][5] = -0.925158842906643;
   fWeightMatrix3to4[0][6] = -2.83779151948539;
   fWeightMatrix3to4[0][7] = -1.85887205329886;
   fWeightMatrix3to4[0][8] = -3.03969916955419;
   fWeightMatrix3to4[0][9] = -1.65073224044542;
   fWeightMatrix3to4[0][10] = -1.93188942762593;
   fWeightMatrix3to4[0][11] = 0.804582549196686;
   fWeightMatrix3to4[0][12] = -1.66077235003483;
   fWeightMatrix3to4[0][13] = 0.738695889291182;
   fWeightMatrix3to4[0][14] = 0.484707068293433;
}

inline double ReadMLP_ANN_N3_NC700::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   if (inputValues.size() != (unsigned int)fLayerSize[0]-1) {
      std::cout << "Input vector needs to be of size " << fLayerSize[0]-1 << std::endl;
      return 0;
   }

   for (int l=0; l<fLayers; l++)
      for (int i=0; i<fLayerSize[l]; i++) fWeights[l][i]=0;

   for (int l=0; l<fLayers-1; l++)
      fWeights[l][fLayerSize[l]-1]=1;

   for (int i=0; i<fLayerSize[0]-1; i++)
      fWeights[0][i]=inputValues[i];

   // layer 0 to 1
   for (int o=0; o<fLayerSize[1]-1; o++) {
      for (int i=0; i<fLayerSize[0]; i++) {
         double inputVal = fWeightMatrix0to1[o][i] * fWeights[0][i];
         fWeights[1][o] += inputVal;
      }
      fWeights[1][o] = ActivationFnc(fWeights[1][o]);
   }
   // layer 1 to 2
   for (int o=0; o<fLayerSize[2]-1; o++) {
      for (int i=0; i<fLayerSize[1]; i++) {
         double inputVal = fWeightMatrix1to2[o][i] * fWeights[1][i];
         fWeights[2][o] += inputVal;
      }
      fWeights[2][o] = ActivationFnc(fWeights[2][o]);
   }
   // layer 2 to 3
   for (int o=0; o<fLayerSize[3]-1; o++) {
      for (int i=0; i<fLayerSize[2]; i++) {
         double inputVal = fWeightMatrix2to3[o][i] * fWeights[2][i];
         fWeights[3][o] += inputVal;
      }
      fWeights[3][o] = ActivationFnc(fWeights[3][o]);
   }
   // layer 3 to 4
   for (int o=0; o<fLayerSize[4]; o++) {
      for (int i=0; i<fLayerSize[3]; i++) {
         double inputVal = fWeightMatrix3to4[o][i] * fWeights[3][i];
         fWeights[4][o] += inputVal;
      }
      fWeights[4][o] = OutputActivationFnc(fWeights[4][o]);
   }

   return fWeights[4][0];
}

double ReadMLP_ANN_N3_NC700::ActivationFnc(double x) const {
   // sigmoid
   return 1.0/(1.0+exp(-x));
}
double ReadMLP_ANN_N3_NC700::OutputActivationFnc(double x) const {
   // sigmoid
   return 1.0/(1.0+exp(-x));
}
   
// Clean up
inline void ReadMLP_ANN_N3_NC700::Clear() 
{
   // clean up the arrays
   for (int lIdx = 0; lIdx < 5; lIdx++) {
      delete[] fWeights[lIdx];
   }
}
   inline double ReadMLP_ANN_N3_NC700::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            iV.reserve(inputValues.size());
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
         else {
            std::vector<double> iV;
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(*varIt);
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
      }

      return retval;
   }

//_______________________________________________________________________
inline void ReadMLP_ANN_N3_NC700::InitTransform_1()
{
   // Normalization transformation, initialisation
   fMin_1[0][0] = 110.048698425;
   fMax_1[0][0] = 1277.92980957;
   fMin_1[1][0] = 110.057556152;
   fMax_1[1][0] = 1572.76037598;
   fMin_1[2][0] = 110.048698425;
   fMax_1[2][0] = 1572.76037598;
   fMin_1[0][1] = 5.00075817108;
   fMax_1[0][1] = 29.9497737885;
   fMin_1[1][1] = 5.00135278702;
   fMax_1[1][1] = 29.9984378815;
   fMin_1[2][1] = 5.00075817108;
   fMax_1[2][1] = 29.9984378815;
   fMin_1[0][2] = -1;
   fMax_1[0][2] = 1;
   fMin_1[1][2] = -1;
   fMax_1[1][2] = 1;
   fMin_1[2][2] = -1;
   fMax_1[2][2] = 1;
   fMin_1[0][3] = -2.4711689949;
   fMax_1[0][3] = 2.37911462784;
   fMin_1[1][3] = -2.48411560059;
   fMax_1[1][3] = 2.49880051613;
   fMin_1[2][3] = -2.48411560059;
   fMax_1[2][3] = 2.49880051613;
   fMin_1[0][4] = 280.2293396;
   fMax_1[0][4] = 1251.49438477;
   fMin_1[1][4] = 280.020294189;
   fMax_1[1][4] = 1289.47937012;
   fMin_1[2][4] = 280.020294189;
   fMax_1[2][4] = 1289.47937012;
   fMin_1[0][5] = 0.0557334087789;
   fMax_1[0][5] = 300.527191162;
   fMin_1[1][5] = 0.000537815736607;
   fMax_1[1][5] = 215.792510986;
   fMin_1[2][5] = 0.000537815736607;
   fMax_1[2][5] = 300.527191162;
   fMin_1[0][6] = 117.352531433;
   fMax_1[0][6] = 2347.48510742;
   fMin_1[1][6] = 112.003395081;
   fMax_1[1][6] = 4504.87304688;
   fMin_1[2][6] = 112.003395081;
   fMax_1[2][6] = 4504.87304688;
   fMin_1[0][7] = 0;
   fMax_1[0][7] = 5;
   fMin_1[1][7] = 0;
   fMax_1[1][7] = 6;
   fMin_1[2][7] = 0;
   fMax_1[2][7] = 6;
   fMin_1[0][8] = 1;
   fMax_1[0][8] = 11;
   fMin_1[1][8] = 1;
   fMax_1[1][8] = 14;
   fMin_1[2][8] = 1;
   fMax_1[2][8] = 14;
   fMin_1[0][9] = 20.0573444366;
   fMax_1[0][9] = 1057.04370117;
   fMin_1[1][9] = -999;
   fMax_1[1][9] = 1378.42883301;
   fMin_1[2][9] = -999;
   fMax_1[2][9] = 1378.42883301;
   fMin_1[0][10] = 6.27087429166e-05;
   fMax_1[0][10] = 4.95768356323;
   fMin_1[1][10] = -999;
   fMax_1[1][10] = 5.38026332855;
   fMin_1[2][10] = -999;
   fMax_1[2][10] = 5.38026332855;
}

//_______________________________________________________________________
inline void ReadMLP_ANN_N3_NC700::Transform_1( std::vector<double>& iv, int cls) const
{
   // Normalization transformation
   if (cls < 0 || cls > 2) {
   if (2 > 1 ) cls = 2;
      else cls = 2;
   }
   const int nVar = 11;

   // get indices of used variables

   // define the indices of the variables which are transformed by this transformation
   static std::vector<int> indicesGet;
   static std::vector<int> indicesPut;

   if ( indicesGet.empty() ) { 
      indicesGet.reserve(fNvars);
      indicesGet.push_back( 0);
      indicesGet.push_back( 1);
      indicesGet.push_back( 2);
      indicesGet.push_back( 3);
      indicesGet.push_back( 4);
      indicesGet.push_back( 5);
      indicesGet.push_back( 6);
      indicesGet.push_back( 7);
      indicesGet.push_back( 8);
      indicesGet.push_back( 9);
      indicesGet.push_back( 10);
   } 
   if ( indicesPut.empty() ) { 
      indicesPut.reserve(fNvars);
      indicesPut.push_back( 0);
      indicesPut.push_back( 1);
      indicesPut.push_back( 2);
      indicesPut.push_back( 3);
      indicesPut.push_back( 4);
      indicesPut.push_back( 5);
      indicesPut.push_back( 6);
      indicesPut.push_back( 7);
      indicesPut.push_back( 8);
      indicesPut.push_back( 9);
      indicesPut.push_back( 10);
   } 

   static std::vector<double> dv;
   dv.resize(nVar);
   for (int ivar=0; ivar<nVar; ivar++) dv[ivar] = iv[indicesGet.at(ivar)];
   for (int ivar=0;ivar<11;ivar++) {
      double offset = fMin_1[cls][ivar];
      double scale  = 1.0/(fMax_1[cls][ivar]-fMin_1[cls][ivar]);
      iv[indicesPut.at(ivar)] = (dv[ivar]-offset)*scale * 2 - 1;
   }
}

//_______________________________________________________________________
inline void ReadMLP_ANN_N3_NC700::InitTransform()
{
   InitTransform_1();
}

//_______________________________________________________________________
inline void ReadMLP_ANN_N3_NC700::Transform( std::vector<double>& iv, int sigOrBgd ) const
{
   Transform_1( iv, sigOrBgd );
}
