// Class: ReadMLP_ANN_N0_NC900
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : MLP::MLP_ANN_N0_NC900
TMVA Release   : 4.2.1         [262657]
ROOT Release   : 6.06/01       [394753]
Creator        : brucms16
Date           : Wed Sep  7 01:47:32 2016
Host           : Linux vocms0315.cern.ch 2.6.32-573.26.1.el6.x86_64 #1 SMP Wed May 4 09:23:05 CEST 2016 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /home/t3cms/brucms16/CMSSW_8_0_14/src/UserCode/SkeletonAnalysis/macros
Training events: 15056
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
NCycles: "900" [Number of training cycles]
HiddenLayers: "N,N,N+0" [Specification of hidden layer architecture]
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
VarTransform: "Norm" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
H: "False" [Print method-specific help message]
LearningRate: "9.000000e-02" [ANN learning rate parameter]
DecayRate: "1.000000e-02" [Decay rate for learning parameter]
# Default:
NeuronType: "sigmoid" [Neuron activation function type]
RandomSeed: "1" [Random seed for initial synapse weights (0 means unique seed for each run; default value '1')]
EstimatorType: "CE" [MSE (Mean Square Estimator) for Gaussian Likelihood or CE(Cross-Entropy) for Bernoulli Likelihood]
NeuronInputType: "sum" [Neuron input function type]
VerbosityLevel: "Default" [Verbosity level]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
TrainingMethod: "BP" [Train with Back-Propagation (BP), BFGS Algorithm (BFGS), or Genetic Algorithm (GA - slower and worse)]
TestRate: "10" [Test for overtraining performed at each #th epochs]
EpochMonitoring: "False" [Provide epoch-wise monitoring plots according to TestRate (caution: causes big ROOT output file!)]
Sampling: "1.000000e+00" [Only 'Sampling' (randomly selected) events are trained each epoch]
SamplingEpoch: "1.000000e+00" [Sampling is used for the first 'SamplingEpoch' epochs, afterwards, all events are taken for training]
SamplingImportance: "1.000000e+00" [ The sampling weights of events in epochs which successful (worse estimator than before) are multiplied with SamplingImportance, else they are divided.]
SamplingTraining: "True" [The training sample is sampled]
SamplingTesting: "False" [The testing sample is sampled]
ResetStep: "50" [How often BFGS should reset history]
Tau: "3.000000e+00" [LineSearch "size step"]
BPMode: "sequential" [Back-propagation learning mode: sequential or batch]
BatchSize: "-1" [Batch size: number of events/batch, only set if in Batch Mode, -1 for BatchSize=number_of_events]
ConvergenceImprove: "1.000000e-30" [Minimum improvement which counts as improvement (<0 means automatic convergence check is turned off)]
ConvergenceTests: "-1" [Number of steps (without improvement) required for convergence (<0 means automatic convergence check is turned off)]
UseRegulator: "False" [Use regulator to avoid over-training]
UpdateLimit: "10000" [Maximum times of regulator update]
CalculateErrors: "False" [Calculates inverse Hessian matrix at the end of the training to be able to calculate the uncertainties of an MVA value]
WeightRange: "1.000000e+00" [Take the events for the estimator calculations from small deviations from the desired value to large deviations only over the weight range]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 11
Jet1Pt                        Jet1Pt                        Jet1Pt                        Jet1Pt                                                          'F'    [110.048698425,1572.76037598]
LepPt                         LepPt                         LepPt                         LepPt                                                           'F'    [5.00075817108,29.9984378815]
LepChg                        LepChg                        LepChg                        LepChg                                                          'F'    [-1,1]
LepEta                        LepEta                        LepEta                        LepEta                                                          'F'    [-2.48411560059,2.49880051613]
Met                           Met                           Met                           Met                                                             'F'    [280.020294189,1289.47937012]
mt                            mt                            mt                            mt                                                              'F'    [0.000537815736607,300.527191162]
HT20                          HT20                          HT20                          HT20                                                            'F'    [112.003395081,4504.87304688]
NbLoose30                     NbLoose30                     NbLoose30                     NbLoose30                                                       'F'    [0,6]
Njet                          Njet                          Njet                          Njet                                                            'F'    [1,14]
JetHBpt                       JetHBpt                       JetHBpt                       JetHBpt                                                         'F'    [-999,1378.42883301]
DrJetHBLep                    DrJetHBLep                    DrJetHBLep                    DrJetHBLep                                                      'F'    [-999,5.38026332855]
NSpec 0


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadMLP_ANN_N0_NC900 : public IClassifierReader {

 public:

   // constructor
   ReadMLP_ANN_N0_NC900( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadMLP_ANN_N0_NC900" ),
        fNvars( 11 ),
        fIsNormalised( false )
   {      
      // the training input variables
      const char* inputVars[] = { "Jet1Pt", "LepPt", "LepChg", "LepEta", "Met", "mt", "HT20", "NbLoose30", "Njet", "JetHBpt", "DrJetHBLep" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = -1;
      fVmax[0] = 1;
      fVmin[1] = -1;
      fVmax[1] = 0.99999988079071;
      fVmin[2] = -1;
      fVmax[2] = 1;
      fVmin[3] = -1;
      fVmax[3] = 1;
      fVmin[4] = -1;
      fVmax[4] = 1;
      fVmin[5] = -1;
      fVmax[5] = 1;
      fVmin[6] = -1;
      fVmax[6] = 1;
      fVmin[7] = -1;
      fVmax[7] = 1;
      fVmin[8] = -1;
      fVmax[8] = 1;
      fVmin[9] = -1;
      fVmax[9] = 1;
      fVmin[10] = -1;
      fVmax[10] = 1;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';
      fType[4] = 'F';
      fType[5] = 'F';
      fType[6] = 'F';
      fType[7] = 'F';
      fType[8] = 'F';
      fType[9] = 'F';
      fType[10] = 'F';

      // initialize constants
      Initialize();

      // initialize transformation
      InitTransform();
   }

   // destructor
   virtual ~ReadMLP_ANN_N0_NC900() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // input variable transformation

   double fMin_1[3][11];
   double fMax_1[3][11];
   void InitTransform_1();
   void Transform_1( std::vector<double> & iv, int sigOrBgd ) const;
   void InitTransform();
   void Transform( std::vector<double> & iv, int sigOrBgd ) const;

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[11];
   double fVmax[11];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[11];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)

   double ActivationFnc(double x) const;
   double OutputActivationFnc(double x) const;

   int fLayers;
   int fLayerSize[5];
   double fWeightMatrix0to1[12][12];   // weight matrix from layer 0 to 1
   double fWeightMatrix1to2[12][12];   // weight matrix from layer 1 to 2
   double fWeightMatrix2to3[12][12];   // weight matrix from layer 2 to 3
   double fWeightMatrix3to4[1][12];   // weight matrix from layer 3 to 4

   double * fWeights[5];
};

inline void ReadMLP_ANN_N0_NC900::Initialize()
{
   // build network structure
   fLayers = 5;
   fLayerSize[0] = 12; fWeights[0] = new double[12]; 
   fLayerSize[1] = 12; fWeights[1] = new double[12]; 
   fLayerSize[2] = 12; fWeights[2] = new double[12]; 
   fLayerSize[3] = 12; fWeights[3] = new double[12]; 
   fLayerSize[4] = 1; fWeights[4] = new double[1]; 
   // weight matrix from layer 0 to 1
   fWeightMatrix0to1[0][0] = 0.900509223046399;
   fWeightMatrix0to1[1][0] = 2.05635726021717;
   fWeightMatrix0to1[2][0] = 4.13503074646897;
   fWeightMatrix0to1[3][0] = -0.093329817717279;
   fWeightMatrix0to1[4][0] = -0.217459191770483;
   fWeightMatrix0to1[5][0] = -1.65687089051197;
   fWeightMatrix0to1[6][0] = -3.28438193111354;
   fWeightMatrix0to1[7][0] = 1.9586296939222;
   fWeightMatrix0to1[8][0] = 0.513620933351216;
   fWeightMatrix0to1[9][0] = 0.16469971319772;
   fWeightMatrix0to1[10][0] = -1.74838283575332;
   fWeightMatrix0to1[0][1] = 1.648087515228;
   fWeightMatrix0to1[1][1] = -2.16040862476118;
   fWeightMatrix0to1[2][1] = 0.040560415688546;
   fWeightMatrix0to1[3][1] = 0.251446316420647;
   fWeightMatrix0to1[4][1] = 1.7724698319469;
   fWeightMatrix0to1[5][1] = -0.794722854434262;
   fWeightMatrix0to1[6][1] = 5.56055558064091;
   fWeightMatrix0to1[7][1] = 0.172196206995706;
   fWeightMatrix0to1[8][1] = 2.66598818454227;
   fWeightMatrix0to1[9][1] = 2.88392965438078;
   fWeightMatrix0to1[10][1] = -2.11845422995358;
   fWeightMatrix0to1[0][2] = 0.936511701662671;
   fWeightMatrix0to1[1][2] = -1.06217533735964;
   fWeightMatrix0to1[2][2] = -0.498791066725485;
   fWeightMatrix0to1[3][2] = 0.269146525816461;
   fWeightMatrix0to1[4][2] = -1.14599998195746;
   fWeightMatrix0to1[5][2] = -3.08370510808544;
   fWeightMatrix0to1[6][2] = -0.576921674283707;
   fWeightMatrix0to1[7][2] = -0.189810769376273;
   fWeightMatrix0to1[8][2] = -0.340952155934506;
   fWeightMatrix0to1[9][2] = 1.84894461257057;
   fWeightMatrix0to1[10][2] = 0.8016748402624;
   fWeightMatrix0to1[0][3] = -1.31903288893882;
   fWeightMatrix0to1[1][3] = 2.6609073858396;
   fWeightMatrix0to1[2][3] = 0.40475606200886;
   fWeightMatrix0to1[3][3] = 0.143921280785363;
   fWeightMatrix0to1[4][3] = 8.5375293462286;
   fWeightMatrix0to1[5][3] = -0.129195409897864;
   fWeightMatrix0to1[6][3] = -1.01830368170222;
   fWeightMatrix0to1[7][3] = 0.693764767955818;
   fWeightMatrix0to1[8][3] = -2.05400457009437;
   fWeightMatrix0to1[9][3] = -0.318833460730325;
   fWeightMatrix0to1[10][3] = 0.28068129192507;
   fWeightMatrix0to1[0][4] = 5.11464647277764;
   fWeightMatrix0to1[1][4] = -0.206498924183807;
   fWeightMatrix0to1[2][4] = 4.40516048328337;
   fWeightMatrix0to1[3][4] = 1.93552778592388;
   fWeightMatrix0to1[4][4] = 0.0509622462879534;
   fWeightMatrix0to1[5][4] = -0.262443049939489;
   fWeightMatrix0to1[6][4] = -1.0754961979593;
   fWeightMatrix0to1[7][4] = 1.74619648727837;
   fWeightMatrix0to1[8][4] = -8.95235667118522;
   fWeightMatrix0to1[9][4] = 0.419110625896709;
   fWeightMatrix0to1[10][4] = -7.94317037275244;
   fWeightMatrix0to1[0][5] = -1.37297903656637;
   fWeightMatrix0to1[1][5] = -2.31654404115972;
   fWeightMatrix0to1[2][5] = -11.6016391595874;
   fWeightMatrix0to1[3][5] = 17.5999161912364;
   fWeightMatrix0to1[4][5] = 0.668450982049673;
   fWeightMatrix0to1[5][5] = -2.66707469972014;
   fWeightMatrix0to1[6][5] = 0.871578835739453;
   fWeightMatrix0to1[7][5] = -0.46677545739286;
   fWeightMatrix0to1[8][5] = -1.58714300508143;
   fWeightMatrix0to1[9][5] = 2.99896142348002;
   fWeightMatrix0to1[10][5] = -2.74399147798395;
   fWeightMatrix0to1[0][6] = -1.14791667793435;
   fWeightMatrix0to1[1][6] = -1.44301846513497;
   fWeightMatrix0to1[2][6] = 0.946769541056451;
   fWeightMatrix0to1[3][6] = -4.40213573989143;
   fWeightMatrix0to1[4][6] = 0.697722785720439;
   fWeightMatrix0to1[5][6] = -1.55212935407327;
   fWeightMatrix0to1[6][6] = 1.61323019111075;
   fWeightMatrix0to1[7][6] = 1.00257874181375;
   fWeightMatrix0to1[8][6] = 6.42306901797725;
   fWeightMatrix0to1[9][6] = 0.797176794581131;
   fWeightMatrix0to1[10][6] = 2.38658045897574;
   fWeightMatrix0to1[0][7] = -6.38043067995597;
   fWeightMatrix0to1[1][7] = -0.930771812631334;
   fWeightMatrix0to1[2][7] = 1.09543549979676;
   fWeightMatrix0to1[3][7] = 0.749052071326903;
   fWeightMatrix0to1[4][7] = 0.0406172099583621;
   fWeightMatrix0to1[5][7] = 2.66316793158997;
   fWeightMatrix0to1[6][7] = -0.577783181675078;
   fWeightMatrix0to1[7][7] = -1.03620988520113;
   fWeightMatrix0to1[8][7] = 2.01336857784497;
   fWeightMatrix0to1[9][7] = 0.861194421990692;
   fWeightMatrix0to1[10][7] = 3.05717209575874;
   fWeightMatrix0to1[0][8] = -7.79740932903628;
   fWeightMatrix0to1[1][8] = -2.20105810729296;
   fWeightMatrix0to1[2][8] = 0.678776201270954;
   fWeightMatrix0to1[3][8] = -0.747018370932545;
   fWeightMatrix0to1[4][8] = 0.433392175411679;
   fWeightMatrix0to1[5][8] = -2.40512631122944;
   fWeightMatrix0to1[6][8] = -2.05289432647239;
   fWeightMatrix0to1[7][8] = 1.46991438130285;
   fWeightMatrix0to1[8][8] = 1.66043997168634;
   fWeightMatrix0to1[9][8] = -8.72671791313644;
   fWeightMatrix0to1[10][8] = -5.12726815014066;
   fWeightMatrix0to1[0][9] = -1.08806318793246;
   fWeightMatrix0to1[1][9] = -2.655907156741;
   fWeightMatrix0to1[2][9] = -2.42600767283212;
   fWeightMatrix0to1[3][9] = -2.44645570392265;
   fWeightMatrix0to1[4][9] = -0.310845671596093;
   fWeightMatrix0to1[5][9] = -2.58139712519791;
   fWeightMatrix0to1[6][9] = -2.45308895425554;
   fWeightMatrix0to1[7][9] = -1.04240937833606;
   fWeightMatrix0to1[8][9] = 2.5932933126366;
   fWeightMatrix0to1[9][9] = -1.34009678134149;
   fWeightMatrix0to1[10][9] = 1.72174810145391;
   fWeightMatrix0to1[0][10] = -2.285907990573;
   fWeightMatrix0to1[1][10] = 0.420513489064406;
   fWeightMatrix0to1[2][10] = 0.990530561335465;
   fWeightMatrix0to1[3][10] = 1.9829860188483;
   fWeightMatrix0to1[4][10] = -1.79440060788146;
   fWeightMatrix0to1[5][10] = 0.854652909713831;
   fWeightMatrix0to1[6][10] = -0.269449404052925;
   fWeightMatrix0to1[7][10] = -0.959388286655225;
   fWeightMatrix0to1[8][10] = -1.61309032267638;
   fWeightMatrix0to1[9][10] = -2.20000272655962;
   fWeightMatrix0to1[10][10] = -3.87228770698323;
   fWeightMatrix0to1[0][11] = -0.325061810817491;
   fWeightMatrix0to1[1][11] = -0.192608389235634;
   fWeightMatrix0to1[2][11] = 1.89679813874821;
   fWeightMatrix0to1[3][11] = 2.31953975430232;
   fWeightMatrix0to1[4][11] = -0.400021047170608;
   fWeightMatrix0to1[5][11] = -1.13538948183753;
   fWeightMatrix0to1[6][11] = -0.244849624664275;
   fWeightMatrix0to1[7][11] = -1.81812407464887;
   fWeightMatrix0to1[8][11] = -0.960014233496885;
   fWeightMatrix0to1[9][11] = -0.925555934380477;
   fWeightMatrix0to1[10][11] = -4.20289179146756;
   // weight matrix from layer 1 to 2
   fWeightMatrix1to2[0][0] = 0.392323278916632;
   fWeightMatrix1to2[1][0] = -1.19664656395513;
   fWeightMatrix1to2[2][0] = 1.66811370075872;
   fWeightMatrix1to2[3][0] = 1.18110631147716;
   fWeightMatrix1to2[4][0] = 4.15744928971678;
   fWeightMatrix1to2[5][0] = -1.96273575194086;
   fWeightMatrix1to2[6][0] = -0.671666295808943;
   fWeightMatrix1to2[7][0] = 5.03614754258479;
   fWeightMatrix1to2[8][0] = 3.32386100390932;
   fWeightMatrix1to2[9][0] = -0.124245070314768;
   fWeightMatrix1to2[10][0] = -2.71119753306995;
   fWeightMatrix1to2[0][1] = -0.446821916289512;
   fWeightMatrix1to2[1][1] = -1.39577270804249;
   fWeightMatrix1to2[2][1] = 2.82684191414952;
   fWeightMatrix1to2[3][1] = 2.28968873366313;
   fWeightMatrix1to2[4][1] = -0.655241048947293;
   fWeightMatrix1to2[5][1] = -0.64277805297942;
   fWeightMatrix1to2[6][1] = -1.22803565589927;
   fWeightMatrix1to2[7][1] = -2.58871688589994;
   fWeightMatrix1to2[8][1] = 0.819827729796128;
   fWeightMatrix1to2[9][1] = 3.34851824012408;
   fWeightMatrix1to2[10][1] = -1.09162447516484;
   fWeightMatrix1to2[0][2] = 0.20870409202597;
   fWeightMatrix1to2[1][2] = 0.125054434981414;
   fWeightMatrix1to2[2][2] = 1.46059198485551;
   fWeightMatrix1to2[3][2] = -1.93352825708571;
   fWeightMatrix1to2[4][2] = 3.093182208994;
   fWeightMatrix1to2[5][2] = -1.44890245622352;
   fWeightMatrix1to2[6][2] = 0.767258653541586;
   fWeightMatrix1to2[7][2] = -0.252730895475887;
   fWeightMatrix1to2[8][2] = 4.59489938972653;
   fWeightMatrix1to2[9][2] = 3.45016680415301;
   fWeightMatrix1to2[10][2] = -2.12297420148236;
   fWeightMatrix1to2[0][3] = -1.32040732455052;
   fWeightMatrix1to2[1][3] = -0.166746332503518;
   fWeightMatrix1to2[2][3] = 5.83260045831619;
   fWeightMatrix1to2[3][3] = -3.24980250972832;
   fWeightMatrix1to2[4][3] = -1.08652208231363;
   fWeightMatrix1to2[5][3] = 1.46486037902548;
   fWeightMatrix1to2[6][3] = 2.24945373485026;
   fWeightMatrix1to2[7][3] = 1.28901222950954;
   fWeightMatrix1to2[8][3] = 2.94274591326618;
   fWeightMatrix1to2[9][3] = 4.72150299629953;
   fWeightMatrix1to2[10][3] = -1.81635342776789;
   fWeightMatrix1to2[0][4] = -0.373069505619089;
   fWeightMatrix1to2[1][4] = 0.157531601363756;
   fWeightMatrix1to2[2][4] = 0.29070537863565;
   fWeightMatrix1to2[3][4] = -1.9705846846693;
   fWeightMatrix1to2[4][4] = -3.73422977701581;
   fWeightMatrix1to2[5][4] = 1.05056404834991;
   fWeightMatrix1to2[6][4] = 2.60948362158501;
   fWeightMatrix1to2[7][4] = -4.34172270448808;
   fWeightMatrix1to2[8][4] = -0.946628558603181;
   fWeightMatrix1to2[9][4] = -0.742570937704899;
   fWeightMatrix1to2[10][4] = 2.92971895879763;
   fWeightMatrix1to2[0][5] = 2.40739507198975;
   fWeightMatrix1to2[1][5] = -0.483987272631189;
   fWeightMatrix1to2[2][5] = 0.0202878127587196;
   fWeightMatrix1to2[3][5] = -2.60891653674233;
   fWeightMatrix1to2[4][5] = 0.674763185260379;
   fWeightMatrix1to2[5][5] = 1.35191873648208;
   fWeightMatrix1to2[6][5] = -0.382959877297298;
   fWeightMatrix1to2[7][5] = 0.720508050957496;
   fWeightMatrix1to2[8][5] = -0.284768474857233;
   fWeightMatrix1to2[9][5] = -2.65492021150147;
   fWeightMatrix1to2[10][5] = 1.30987732577568;
   fWeightMatrix1to2[0][6] = 1.87964725009082;
   fWeightMatrix1to2[1][6] = -1.93073595928509;
   fWeightMatrix1to2[2][6] = -1.91975327065082;
   fWeightMatrix1to2[3][6] = 1.87330990734324;
   fWeightMatrix1to2[4][6] = 0.829457806866442;
   fWeightMatrix1to2[5][6] = -1.88697967009639;
   fWeightMatrix1to2[6][6] = 1.07313649853707;
   fWeightMatrix1to2[7][6] = 1.16744731574035;
   fWeightMatrix1to2[8][6] = -2.6008213499713;
   fWeightMatrix1to2[9][6] = -1.58317712158149;
   fWeightMatrix1to2[10][6] = 3.79104382416324;
   fWeightMatrix1to2[0][7] = 1.01794555309567;
   fWeightMatrix1to2[1][7] = 0.431935660884834;
   fWeightMatrix1to2[2][7] = -0.171428177286995;
   fWeightMatrix1to2[3][7] = -2.10662370934706;
   fWeightMatrix1to2[4][7] = -0.96784501951055;
   fWeightMatrix1to2[5][7] = 1.72374500037378;
   fWeightMatrix1to2[6][7] = 1.20604922868931;
   fWeightMatrix1to2[7][7] = 0.830467351449543;
   fWeightMatrix1to2[8][7] = 0.149573351322857;
   fWeightMatrix1to2[9][7] = 1.8960297809907;
   fWeightMatrix1to2[10][7] = -1.70655330036392;
   fWeightMatrix1to2[0][8] = -0.264157180459749;
   fWeightMatrix1to2[1][8] = -0.795436622688693;
   fWeightMatrix1to2[2][8] = -2.50445375761744;
   fWeightMatrix1to2[3][8] = 4.87683755435654;
   fWeightMatrix1to2[4][8] = 2.98966504803751;
   fWeightMatrix1to2[5][8] = -1.13071637567982;
   fWeightMatrix1to2[6][8] = 4.13092539602662;
   fWeightMatrix1to2[7][8] = -0.67085556149079;
   fWeightMatrix1to2[8][8] = -2.62108222646485;
   fWeightMatrix1to2[9][8] = -4.54944892518842;
   fWeightMatrix1to2[10][8] = 3.28355891118016;
   fWeightMatrix1to2[0][9] = 0.971427284665188;
   fWeightMatrix1to2[1][9] = 0.910428421689268;
   fWeightMatrix1to2[2][9] = -2.37475907487272;
   fWeightMatrix1to2[3][9] = 2.59839290714768;
   fWeightMatrix1to2[4][9] = -2.68535668309283;
   fWeightMatrix1to2[5][9] = 1.06368271160679;
   fWeightMatrix1to2[6][9] = -1.25113495675172;
   fWeightMatrix1to2[7][9] = -0.164245364129008;
   fWeightMatrix1to2[8][9] = -2.91426008806356;
   fWeightMatrix1to2[9][9] = -3.07387716827752;
   fWeightMatrix1to2[10][9] = -0.0476461750983227;
   fWeightMatrix1to2[0][10] = -2.6666308389169;
   fWeightMatrix1to2[1][10] = -1.97874845283589;
   fWeightMatrix1to2[2][10] = -4.70117049105989;
   fWeightMatrix1to2[3][10] = 1.97806635795427;
   fWeightMatrix1to2[4][10] = -1.74283348344817;
   fWeightMatrix1to2[5][10] = -1.88590402661847;
   fWeightMatrix1to2[6][10] = 0.968110936284735;
   fWeightMatrix1to2[7][10] = -0.423026522967081;
   fWeightMatrix1to2[8][10] = -1.33871893181727;
   fWeightMatrix1to2[9][10] = -3.67756553016205;
   fWeightMatrix1to2[10][10] = 0.905518425385882;
   fWeightMatrix1to2[0][11] = 1.91157792489698;
   fWeightMatrix1to2[1][11] = 1.34895473887441;
   fWeightMatrix1to2[2][11] = -1.00789381854426;
   fWeightMatrix1to2[3][11] = 0.135206352769534;
   fWeightMatrix1to2[4][11] = -1.21078832494398;
   fWeightMatrix1to2[5][11] = -1.26901861418436;
   fWeightMatrix1to2[6][11] = -2.436090623135;
   fWeightMatrix1to2[7][11] = -0.795238516701422;
   fWeightMatrix1to2[8][11] = 0.200447603965734;
   fWeightMatrix1to2[9][11] = 2.30439774660157;
   fWeightMatrix1to2[10][11] = -1.22495140261139;
   // weight matrix from layer 2 to 3
   fWeightMatrix2to3[0][0] = 0.844630604234877;
   fWeightMatrix2to3[1][0] = -2.39238403637549;
   fWeightMatrix2to3[2][0] = -2.11284609685823;
   fWeightMatrix2to3[3][0] = 1.26459019802146;
   fWeightMatrix2to3[4][0] = 0.453615634205809;
   fWeightMatrix2to3[5][0] = -2.62884550821114;
   fWeightMatrix2to3[6][0] = -1.24758275444261;
   fWeightMatrix2to3[7][0] = 0.899890528397486;
   fWeightMatrix2to3[8][0] = -0.138748965394313;
   fWeightMatrix2to3[9][0] = 0.756390835042817;
   fWeightMatrix2to3[10][0] = -1.72264369778383;
   fWeightMatrix2to3[0][1] = -0.117617804408833;
   fWeightMatrix2to3[1][1] = 1.13353011606252;
   fWeightMatrix2to3[2][1] = 0.961961258352466;
   fWeightMatrix2to3[3][1] = 1.24153147422324;
   fWeightMatrix2to3[4][1] = -0.352632018692457;
   fWeightMatrix2to3[5][1] = 0.217515000439977;
   fWeightMatrix2to3[6][1] = -0.157231115939221;
   fWeightMatrix2to3[7][1] = -1.03976853753185;
   fWeightMatrix2to3[8][1] = -0.751145662444878;
   fWeightMatrix2to3[9][1] = -1.52217307915006;
   fWeightMatrix2to3[10][1] = -2.15484217233215;
   fWeightMatrix2to3[0][2] = -3.15723635525075;
   fWeightMatrix2to3[1][2] = 2.29394450671116;
   fWeightMatrix2to3[2][2] = -1.85278162578818;
   fWeightMatrix2to3[3][2] = 0.513406226628507;
   fWeightMatrix2to3[4][2] = -1.60200069727422;
   fWeightMatrix2to3[5][2] = 0.106122758181751;
   fWeightMatrix2to3[6][2] = -1.7702459699819;
   fWeightMatrix2to3[7][2] = -1.13314635729159;
   fWeightMatrix2to3[8][2] = 2.09506316754808;
   fWeightMatrix2to3[9][2] = -3.83253351496407;
   fWeightMatrix2to3[10][2] = 1.17036032332246;
   fWeightMatrix2to3[0][3] = 1.79342034406967;
   fWeightMatrix2to3[1][3] = -3.57410698217221;
   fWeightMatrix2to3[2][3] = -1.64096986551723;
   fWeightMatrix2to3[3][3] = -0.398444794125005;
   fWeightMatrix2to3[4][3] = -1.60116207827274;
   fWeightMatrix2to3[5][3] = 0.40292740480191;
   fWeightMatrix2to3[6][3] = -0.154002304104348;
   fWeightMatrix2to3[7][3] = 1.63338708861359;
   fWeightMatrix2to3[8][3] = -4.09366765950241;
   fWeightMatrix2to3[9][3] = 1.66947884056185;
   fWeightMatrix2to3[10][3] = -2.35859841397418;
   fWeightMatrix2to3[0][4] = -2.2160657691931;
   fWeightMatrix2to3[1][4] = -3.49174253267307;
   fWeightMatrix2to3[2][4] = 0.947266297261955;
   fWeightMatrix2to3[3][4] = -2.6286274181412;
   fWeightMatrix2to3[4][4] = -1.44599568188329;
   fWeightMatrix2to3[5][4] = 0.877581654458291;
   fWeightMatrix2to3[6][4] = -0.31687123022206;
   fWeightMatrix2to3[7][4] = -1.66406973676137;
   fWeightMatrix2to3[8][4] = 3.15632838804098;
   fWeightMatrix2to3[9][4] = -1.64036346309708;
   fWeightMatrix2to3[10][4] = 1.43997486173947;
   fWeightMatrix2to3[0][5] = 0.906525462550987;
   fWeightMatrix2to3[1][5] = -0.719371233345614;
   fWeightMatrix2to3[2][5] = -0.816775201259568;
   fWeightMatrix2to3[3][5] = 0.111926729450707;
   fWeightMatrix2to3[4][5] = -1.20484194109077;
   fWeightMatrix2to3[5][5] = 0.464732932293298;
   fWeightMatrix2to3[6][5] = 1.92210769636632;
   fWeightMatrix2to3[7][5] = 1.44395410063769;
   fWeightMatrix2to3[8][5] = 1.58064780402601;
   fWeightMatrix2to3[9][5] = -1.33122987064565;
   fWeightMatrix2to3[10][5] = 0.651724962223734;
   fWeightMatrix2to3[0][6] = -3.34304538118849;
   fWeightMatrix2to3[1][6] = -0.1552884000632;
   fWeightMatrix2to3[2][6] = -1.91759590866628;
   fWeightMatrix2to3[3][6] = -2.8041126127021;
   fWeightMatrix2to3[4][6] = -0.910007720605739;
   fWeightMatrix2to3[5][6] = 0.300899372505829;
   fWeightMatrix2to3[6][6] = 0.86561411077554;
   fWeightMatrix2to3[7][6] = 1.42350598374907;
   fWeightMatrix2to3[8][6] = -0.62012825166975;
   fWeightMatrix2to3[9][6] = 2.8005928323054;
   fWeightMatrix2to3[10][6] = -2.4384945810436;
   fWeightMatrix2to3[0][7] = 0.221566821622657;
   fWeightMatrix2to3[1][7] = 3.49345482995046;
   fWeightMatrix2to3[2][7] = -1.59319535967628;
   fWeightMatrix2to3[3][7] = -1.66834734190817;
   fWeightMatrix2to3[4][7] = -1.58361491695338;
   fWeightMatrix2to3[5][7] = -1.40873791372822;
   fWeightMatrix2to3[6][7] = -0.918865869270832;
   fWeightMatrix2to3[7][7] = -2.7127226059146;
   fWeightMatrix2to3[8][7] = -1.08793613335403;
   fWeightMatrix2to3[9][7] = -1.07414994314178;
   fWeightMatrix2to3[10][7] = 2.9688914449451;
   fWeightMatrix2to3[0][8] = 0.855362050507794;
   fWeightMatrix2to3[1][8] = -0.0130330911849467;
   fWeightMatrix2to3[2][8] = -0.964466668488279;
   fWeightMatrix2to3[3][8] = -3.21698087592825;
   fWeightMatrix2to3[4][8] = -1.86826587064888;
   fWeightMatrix2to3[5][8] = -0.230738087350325;
   fWeightMatrix2to3[6][8] = -0.663995502120831;
   fWeightMatrix2to3[7][8] = -1.94107688935777;
   fWeightMatrix2to3[8][8] = 0.617862725648155;
   fWeightMatrix2to3[9][8] = -3.19033012612205;
   fWeightMatrix2to3[10][8] = -2.16165559065707;
   fWeightMatrix2to3[0][9] = -3.57775855821443;
   fWeightMatrix2to3[1][9] = 0.721204434028675;
   fWeightMatrix2to3[2][9] = -1.4311270927795;
   fWeightMatrix2to3[3][9] = -2.40998393008316;
   fWeightMatrix2to3[4][9] = -0.787080089995988;
   fWeightMatrix2to3[5][9] = -2.10532409346572;
   fWeightMatrix2to3[6][9] = -2.32066000953353;
   fWeightMatrix2to3[7][9] = 0.607179627847044;
   fWeightMatrix2to3[8][9] = -0.0151280906552256;
   fWeightMatrix2to3[9][9] = -3.01004271231735;
   fWeightMatrix2to3[10][9] = 2.45629478774367;
   fWeightMatrix2to3[0][10] = 0.409907337376199;
   fWeightMatrix2to3[1][10] = -1.12621128996833;
   fWeightMatrix2to3[2][10] = -0.0329889262716452;
   fWeightMatrix2to3[3][10] = 2.36195492199614;
   fWeightMatrix2to3[4][10] = 1.06518385004486;
   fWeightMatrix2to3[5][10] = 0.0861843470565756;
   fWeightMatrix2to3[6][10] = -0.820087000972431;
   fWeightMatrix2to3[7][10] = -0.0783641904653546;
   fWeightMatrix2to3[8][10] = -3.67122549424503;
   fWeightMatrix2to3[9][10] = 3.61955970941472;
   fWeightMatrix2to3[10][10] = -0.243949354661408;
   fWeightMatrix2to3[0][11] = 0.00729231712874934;
   fWeightMatrix2to3[1][11] = -0.204667890046544;
   fWeightMatrix2to3[2][11] = 0.771759010432494;
   fWeightMatrix2to3[3][11] = 1.77828178243764;
   fWeightMatrix2to3[4][11] = -2.19764142944759;
   fWeightMatrix2to3[5][11] = -0.264726191795568;
   fWeightMatrix2to3[6][11] = 0.357600158225241;
   fWeightMatrix2to3[7][11] = -1.7656639431626;
   fWeightMatrix2to3[8][11] = -1.89574463478472;
   fWeightMatrix2to3[9][11] = -0.730483867458652;
   fWeightMatrix2to3[10][11] = -0.822241871494682;
   // weight matrix from layer 3 to 4
   fWeightMatrix3to4[0][0] = -1.47829697344994;
   fWeightMatrix3to4[0][1] = 3.79905747659372;
   fWeightMatrix3to4[0][2] = 1.69648140484582;
   fWeightMatrix3to4[0][3] = -2.16201157434638;
   fWeightMatrix3to4[0][4] = 1.17751203847962;
   fWeightMatrix3to4[0][5] = -0.3674081532133;
   fWeightMatrix3to4[0][6] = -0.212191172547676;
   fWeightMatrix3to4[0][7] = -2.55080020979824;
   fWeightMatrix3to4[0][8] = 1.77269007314187;
   fWeightMatrix3to4[0][9] = -1.80781123000111;
   fWeightMatrix3to4[0][10] = 2.0153519732535;
   fWeightMatrix3to4[0][11] = -0.0109211344271761;
}

inline double ReadMLP_ANN_N0_NC900::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   if (inputValues.size() != (unsigned int)fLayerSize[0]-1) {
      std::cout << "Input vector needs to be of size " << fLayerSize[0]-1 << std::endl;
      return 0;
   }

   for (int l=0; l<fLayers; l++)
      for (int i=0; i<fLayerSize[l]; i++) fWeights[l][i]=0;

   for (int l=0; l<fLayers-1; l++)
      fWeights[l][fLayerSize[l]-1]=1;

   for (int i=0; i<fLayerSize[0]-1; i++)
      fWeights[0][i]=inputValues[i];

   // layer 0 to 1
   for (int o=0; o<fLayerSize[1]-1; o++) {
      for (int i=0; i<fLayerSize[0]; i++) {
         double inputVal = fWeightMatrix0to1[o][i] * fWeights[0][i];
         fWeights[1][o] += inputVal;
      }
      fWeights[1][o] = ActivationFnc(fWeights[1][o]);
   }
   // layer 1 to 2
   for (int o=0; o<fLayerSize[2]-1; o++) {
      for (int i=0; i<fLayerSize[1]; i++) {
         double inputVal = fWeightMatrix1to2[o][i] * fWeights[1][i];
         fWeights[2][o] += inputVal;
      }
      fWeights[2][o] = ActivationFnc(fWeights[2][o]);
   }
   // layer 2 to 3
   for (int o=0; o<fLayerSize[3]-1; o++) {
      for (int i=0; i<fLayerSize[2]; i++) {
         double inputVal = fWeightMatrix2to3[o][i] * fWeights[2][i];
         fWeights[3][o] += inputVal;
      }
      fWeights[3][o] = ActivationFnc(fWeights[3][o]);
   }
   // layer 3 to 4
   for (int o=0; o<fLayerSize[4]; o++) {
      for (int i=0; i<fLayerSize[3]; i++) {
         double inputVal = fWeightMatrix3to4[o][i] * fWeights[3][i];
         fWeights[4][o] += inputVal;
      }
      fWeights[4][o] = OutputActivationFnc(fWeights[4][o]);
   }

   return fWeights[4][0];
}

double ReadMLP_ANN_N0_NC900::ActivationFnc(double x) const {
   // sigmoid
   return 1.0/(1.0+exp(-x));
}
double ReadMLP_ANN_N0_NC900::OutputActivationFnc(double x) const {
   // sigmoid
   return 1.0/(1.0+exp(-x));
}
   
// Clean up
inline void ReadMLP_ANN_N0_NC900::Clear() 
{
   // clean up the arrays
   for (int lIdx = 0; lIdx < 5; lIdx++) {
      delete[] fWeights[lIdx];
   }
}
   inline double ReadMLP_ANN_N0_NC900::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            iV.reserve(inputValues.size());
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
         else {
            std::vector<double> iV;
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(*varIt);
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
      }

      return retval;
   }

//_______________________________________________________________________
inline void ReadMLP_ANN_N0_NC900::InitTransform_1()
{
   // Normalization transformation, initialisation
   fMin_1[0][0] = 110.048698425;
   fMax_1[0][0] = 1277.92980957;
   fMin_1[1][0] = 110.057556152;
   fMax_1[1][0] = 1572.76037598;
   fMin_1[2][0] = 110.048698425;
   fMax_1[2][0] = 1572.76037598;
   fMin_1[0][1] = 5.00075817108;
   fMax_1[0][1] = 29.9497737885;
   fMin_1[1][1] = 5.00135278702;
   fMax_1[1][1] = 29.9984378815;
   fMin_1[2][1] = 5.00075817108;
   fMax_1[2][1] = 29.9984378815;
   fMin_1[0][2] = -1;
   fMax_1[0][2] = 1;
   fMin_1[1][2] = -1;
   fMax_1[1][2] = 1;
   fMin_1[2][2] = -1;
   fMax_1[2][2] = 1;
   fMin_1[0][3] = -2.4711689949;
   fMax_1[0][3] = 2.37911462784;
   fMin_1[1][3] = -2.48411560059;
   fMax_1[1][3] = 2.49880051613;
   fMin_1[2][3] = -2.48411560059;
   fMax_1[2][3] = 2.49880051613;
   fMin_1[0][4] = 280.2293396;
   fMax_1[0][4] = 1251.49438477;
   fMin_1[1][4] = 280.020294189;
   fMax_1[1][4] = 1289.47937012;
   fMin_1[2][4] = 280.020294189;
   fMax_1[2][4] = 1289.47937012;
   fMin_1[0][5] = 0.0557334087789;
   fMax_1[0][5] = 300.527191162;
   fMin_1[1][5] = 0.000537815736607;
   fMax_1[1][5] = 215.792510986;
   fMin_1[2][5] = 0.000537815736607;
   fMax_1[2][5] = 300.527191162;
   fMin_1[0][6] = 117.352531433;
   fMax_1[0][6] = 2347.48510742;
   fMin_1[1][6] = 112.003395081;
   fMax_1[1][6] = 4504.87304688;
   fMin_1[2][6] = 112.003395081;
   fMax_1[2][6] = 4504.87304688;
   fMin_1[0][7] = 0;
   fMax_1[0][7] = 5;
   fMin_1[1][7] = 0;
   fMax_1[1][7] = 6;
   fMin_1[2][7] = 0;
   fMax_1[2][7] = 6;
   fMin_1[0][8] = 1;
   fMax_1[0][8] = 11;
   fMin_1[1][8] = 1;
   fMax_1[1][8] = 14;
   fMin_1[2][8] = 1;
   fMax_1[2][8] = 14;
   fMin_1[0][9] = 20.0573444366;
   fMax_1[0][9] = 1057.04370117;
   fMin_1[1][9] = -999;
   fMax_1[1][9] = 1378.42883301;
   fMin_1[2][9] = -999;
   fMax_1[2][9] = 1378.42883301;
   fMin_1[0][10] = 6.27087429166e-05;
   fMax_1[0][10] = 4.95768356323;
   fMin_1[1][10] = -999;
   fMax_1[1][10] = 5.38026332855;
   fMin_1[2][10] = -999;
   fMax_1[2][10] = 5.38026332855;
}

//_______________________________________________________________________
inline void ReadMLP_ANN_N0_NC900::Transform_1( std::vector<double>& iv, int cls) const
{
   // Normalization transformation
   if (cls < 0 || cls > 2) {
   if (2 > 1 ) cls = 2;
      else cls = 2;
   }
   const int nVar = 11;

   // get indices of used variables

   // define the indices of the variables which are transformed by this transformation
   static std::vector<int> indicesGet;
   static std::vector<int> indicesPut;

   if ( indicesGet.empty() ) { 
      indicesGet.reserve(fNvars);
      indicesGet.push_back( 0);
      indicesGet.push_back( 1);
      indicesGet.push_back( 2);
      indicesGet.push_back( 3);
      indicesGet.push_back( 4);
      indicesGet.push_back( 5);
      indicesGet.push_back( 6);
      indicesGet.push_back( 7);
      indicesGet.push_back( 8);
      indicesGet.push_back( 9);
      indicesGet.push_back( 10);
   } 
   if ( indicesPut.empty() ) { 
      indicesPut.reserve(fNvars);
      indicesPut.push_back( 0);
      indicesPut.push_back( 1);
      indicesPut.push_back( 2);
      indicesPut.push_back( 3);
      indicesPut.push_back( 4);
      indicesPut.push_back( 5);
      indicesPut.push_back( 6);
      indicesPut.push_back( 7);
      indicesPut.push_back( 8);
      indicesPut.push_back( 9);
      indicesPut.push_back( 10);
   } 

   static std::vector<double> dv;
   dv.resize(nVar);
   for (int ivar=0; ivar<nVar; ivar++) dv[ivar] = iv[indicesGet.at(ivar)];
   for (int ivar=0;ivar<11;ivar++) {
      double offset = fMin_1[cls][ivar];
      double scale  = 1.0/(fMax_1[cls][ivar]-fMin_1[cls][ivar]);
      iv[indicesPut.at(ivar)] = (dv[ivar]-offset)*scale * 2 - 1;
   }
}

//_______________________________________________________________________
inline void ReadMLP_ANN_N0_NC900::InitTransform()
{
   InitTransform_1();
}

//_______________________________________________________________________
inline void ReadMLP_ANN_N0_NC900::Transform( std::vector<double>& iv, int sigOrBgd ) const
{
   Transform_1( iv, sigOrBgd );
}
