// Class: ReadMLP_ANN_N-3_NC200
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : MLP::MLP_ANN_N-3_NC200
TMVA Release   : 4.2.1         [262657]
ROOT Release   : 6.06/01       [394753]
Creator        : brucms16
Date           : Tue Sep  6 22:59:36 2016
Host           : Linux vocms0315.cern.ch 2.6.32-573.26.1.el6.x86_64 #1 SMP Wed May 4 09:23:05 CEST 2016 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /home/t3cms/brucms16/CMSSW_8_0_14/src/UserCode/SkeletonAnalysis/macros
Training events: 15056
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
NCycles: "200" [Number of training cycles]
HiddenLayers: "N,N,N+-3" [Specification of hidden layer architecture]
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
VarTransform: "Norm" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
H: "False" [Print method-specific help message]
LearningRate: "9.000000e-02" [ANN learning rate parameter]
DecayRate: "1.000000e-02" [Decay rate for learning parameter]
# Default:
NeuronType: "sigmoid" [Neuron activation function type]
RandomSeed: "1" [Random seed for initial synapse weights (0 means unique seed for each run; default value '1')]
EstimatorType: "CE" [MSE (Mean Square Estimator) for Gaussian Likelihood or CE(Cross-Entropy) for Bernoulli Likelihood]
NeuronInputType: "sum" [Neuron input function type]
VerbosityLevel: "Default" [Verbosity level]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
TrainingMethod: "BP" [Train with Back-Propagation (BP), BFGS Algorithm (BFGS), or Genetic Algorithm (GA - slower and worse)]
TestRate: "10" [Test for overtraining performed at each #th epochs]
EpochMonitoring: "False" [Provide epoch-wise monitoring plots according to TestRate (caution: causes big ROOT output file!)]
Sampling: "1.000000e+00" [Only 'Sampling' (randomly selected) events are trained each epoch]
SamplingEpoch: "1.000000e+00" [Sampling is used for the first 'SamplingEpoch' epochs, afterwards, all events are taken for training]
SamplingImportance: "1.000000e+00" [ The sampling weights of events in epochs which successful (worse estimator than before) are multiplied with SamplingImportance, else they are divided.]
SamplingTraining: "True" [The training sample is sampled]
SamplingTesting: "False" [The testing sample is sampled]
ResetStep: "50" [How often BFGS should reset history]
Tau: "3.000000e+00" [LineSearch "size step"]
BPMode: "sequential" [Back-propagation learning mode: sequential or batch]
BatchSize: "-1" [Batch size: number of events/batch, only set if in Batch Mode, -1 for BatchSize=number_of_events]
ConvergenceImprove: "1.000000e-30" [Minimum improvement which counts as improvement (<0 means automatic convergence check is turned off)]
ConvergenceTests: "-1" [Number of steps (without improvement) required for convergence (<0 means automatic convergence check is turned off)]
UseRegulator: "False" [Use regulator to avoid over-training]
UpdateLimit: "10000" [Maximum times of regulator update]
CalculateErrors: "False" [Calculates inverse Hessian matrix at the end of the training to be able to calculate the uncertainties of an MVA value]
WeightRange: "1.000000e+00" [Take the events for the estimator calculations from small deviations from the desired value to large deviations only over the weight range]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 11
Jet1Pt                        Jet1Pt                        Jet1Pt                        Jet1Pt                                                          'F'    [110.048698425,1572.76037598]
LepPt                         LepPt                         LepPt                         LepPt                                                           'F'    [5.00075817108,29.9984378815]
LepChg                        LepChg                        LepChg                        LepChg                                                          'F'    [-1,1]
LepEta                        LepEta                        LepEta                        LepEta                                                          'F'    [-2.48411560059,2.49880051613]
Met                           Met                           Met                           Met                                                             'F'    [280.020294189,1289.47937012]
mt                            mt                            mt                            mt                                                              'F'    [0.000537815736607,300.527191162]
HT20                          HT20                          HT20                          HT20                                                            'F'    [112.003395081,4504.87304688]
NbLoose30                     NbLoose30                     NbLoose30                     NbLoose30                                                       'F'    [0,6]
Njet                          Njet                          Njet                          Njet                                                            'F'    [1,14]
JetHBpt                       JetHBpt                       JetHBpt                       JetHBpt                                                         'F'    [-999,1378.42883301]
DrJetHBLep                    DrJetHBLep                    DrJetHBLep                    DrJetHBLep                                                      'F'    [-999,5.38026332855]
NSpec 0


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadMLP_ANN_N-3_NC200 : public IClassifierReader {

 public:

   // constructor
   ReadMLP_ANN_N-3_NC200( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadMLP_ANN_N-3_NC200" ),
        fNvars( 11 ),
        fIsNormalised( false )
   {      
      // the training input variables
      const char* inputVars[] = { "Jet1Pt", "LepPt", "LepChg", "LepEta", "Met", "mt", "HT20", "NbLoose30", "Njet", "JetHBpt", "DrJetHBLep" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = -1;
      fVmax[0] = 1;
      fVmin[1] = -1;
      fVmax[1] = 0.99999988079071;
      fVmin[2] = -1;
      fVmax[2] = 1;
      fVmin[3] = -1;
      fVmax[3] = 1;
      fVmin[4] = -1;
      fVmax[4] = 1;
      fVmin[5] = -1;
      fVmax[5] = 1;
      fVmin[6] = -1;
      fVmax[6] = 1;
      fVmin[7] = -1;
      fVmax[7] = 1;
      fVmin[8] = -1;
      fVmax[8] = 1;
      fVmin[9] = -1;
      fVmax[9] = 1;
      fVmin[10] = -1;
      fVmax[10] = 1;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';
      fType[4] = 'F';
      fType[5] = 'F';
      fType[6] = 'F';
      fType[7] = 'F';
      fType[8] = 'F';
      fType[9] = 'F';
      fType[10] = 'F';

      // initialize constants
      Initialize();

      // initialize transformation
      InitTransform();
   }

   // destructor
   virtual ~ReadMLP_ANN_N-3_NC200() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // input variable transformation

   double fMin_1[3][11];
   double fMax_1[3][11];
   void InitTransform_1();
   void Transform_1( std::vector<double> & iv, int sigOrBgd ) const;
   void InitTransform();
   void Transform( std::vector<double> & iv, int sigOrBgd ) const;

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[11];
   double fVmax[11];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[11];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)

   double ActivationFnc(double x) const;
   double OutputActivationFnc(double x) const;

   int fLayers;
   int fLayerSize[5];
   double fWeightMatrix0to1[12][12];   // weight matrix from layer 0 to 1
   double fWeightMatrix1to2[12][12];   // weight matrix from layer 1 to 2
   double fWeightMatrix2to3[12][12];   // weight matrix from layer 2 to 3
   double fWeightMatrix3to4[1][12];   // weight matrix from layer 3 to 4

   double * fWeights[5];
};

inline void ReadMLP_ANN_N-3_NC200::Initialize()
{
   // build network structure
   fLayers = 5;
   fLayerSize[0] = 12; fWeights[0] = new double[12]; 
   fLayerSize[1] = 12; fWeights[1] = new double[12]; 
   fLayerSize[2] = 12; fWeights[2] = new double[12]; 
   fLayerSize[3] = 12; fWeights[3] = new double[12]; 
   fLayerSize[4] = 1; fWeights[4] = new double[1]; 
   // weight matrix from layer 0 to 1
   fWeightMatrix0to1[0][0] = 0.87154494984095;
   fWeightMatrix0to1[1][0] = 1.8281883856652;
   fWeightMatrix0to1[2][0] = 4.22881850495058;
   fWeightMatrix0to1[3][0] = -0.0697236182722272;
   fWeightMatrix0to1[4][0] = -0.398829109189259;
   fWeightMatrix0to1[5][0] = -1.63274208330115;
   fWeightMatrix0to1[6][0] = -3.24575783893688;
   fWeightMatrix0to1[7][0] = 1.97615181461271;
   fWeightMatrix0to1[8][0] = 0.452069851869632;
   fWeightMatrix0to1[9][0] = 0.156889657644827;
   fWeightMatrix0to1[10][0] = -1.75509460392134;
   fWeightMatrix0to1[0][1] = 1.57789871723195;
   fWeightMatrix0to1[1][1] = -1.8124244864212;
   fWeightMatrix0to1[2][1] = 0.0229944277298713;
   fWeightMatrix0to1[3][1] = 0.278238482458335;
   fWeightMatrix0to1[4][1] = 1.69223383108992;
   fWeightMatrix0to1[5][1] = -0.417217602189109;
   fWeightMatrix0to1[6][1] = 5.41278246722413;
   fWeightMatrix0to1[7][1] = 0.137727702816142;
   fWeightMatrix0to1[8][1] = 2.73328559643506;
   fWeightMatrix0to1[9][1] = 2.87718352723208;
   fWeightMatrix0to1[10][1] = -2.14216553165685;
   fWeightMatrix0to1[0][2] = 0.960523180132559;
   fWeightMatrix0to1[1][2] = -0.740344217206176;
   fWeightMatrix0to1[2][2] = -0.591384558347366;
   fWeightMatrix0to1[3][2] = 0.215845603997985;
   fWeightMatrix0to1[4][2] = -1.08903702263647;
   fWeightMatrix0to1[5][2] = -2.94420979165357;
   fWeightMatrix0to1[6][2] = -0.553007599421034;
   fWeightMatrix0to1[7][2] = -0.0994489686740265;
   fWeightMatrix0to1[8][2] = -0.297274775193911;
   fWeightMatrix0to1[9][2] = 1.87678096122731;
   fWeightMatrix0to1[10][2] = 0.774585184890395;
   fWeightMatrix0to1[0][3] = -1.41820887153782;
   fWeightMatrix0to1[1][3] = 2.49128305268883;
   fWeightMatrix0to1[2][3] = 0.294608587555841;
   fWeightMatrix0to1[3][3] = 0.130185842217617;
   fWeightMatrix0to1[4][3] = 8.29000658864586;
   fWeightMatrix0to1[5][3] = -0.485024738516274;
   fWeightMatrix0to1[6][3] = -1.05773469041326;
   fWeightMatrix0to1[7][3] = 0.74696363704164;
   fWeightMatrix0to1[8][3] = -2.0736612712938;
   fWeightMatrix0to1[9][3] = -0.378469933839765;
   fWeightMatrix0to1[10][3] = 0.252006946213509;
   fWeightMatrix0to1[0][4] = 5.14408801323265;
   fWeightMatrix0to1[1][4] = -0.281652069234401;
   fWeightMatrix0to1[2][4] = 4.77921143241228;
   fWeightMatrix0to1[3][4] = 2.40456337290744;
   fWeightMatrix0to1[4][4] = 0.210881219312169;
   fWeightMatrix0to1[5][4] = -0.233168005370024;
   fWeightMatrix0to1[6][4] = -1.19928010066454;
   fWeightMatrix0to1[7][4] = 1.7103209943344;
   fWeightMatrix0to1[8][4] = -8.97505483093672;
   fWeightMatrix0to1[9][4] = 0.362495759077193;
   fWeightMatrix0to1[10][4] = -8.08170745010517;
   fWeightMatrix0to1[0][5] = -1.25407837546495;
   fWeightMatrix0to1[1][5] = -2.11675786177465;
   fWeightMatrix0to1[2][5] = -11.1342533456235;
   fWeightMatrix0to1[3][5] = 16.6986954212994;
   fWeightMatrix0to1[4][5] = 0.615440081066833;
   fWeightMatrix0to1[5][5] = -2.57723602084574;
   fWeightMatrix0to1[6][5] = 1.03275977404038;
   fWeightMatrix0to1[7][5] = -0.396258345772182;
   fWeightMatrix0to1[8][5] = -1.23048292440882;
   fWeightMatrix0to1[9][5] = 2.8517446241211;
   fWeightMatrix0to1[10][5] = -2.85565668660899;
   fWeightMatrix0to1[0][6] = -1.31607510094651;
   fWeightMatrix0to1[1][6] = -1.6425285493611;
   fWeightMatrix0to1[2][6] = 0.783014864250652;
   fWeightMatrix0to1[3][6] = -4.33253397772381;
   fWeightMatrix0to1[4][6] = 0.568975805546004;
   fWeightMatrix0to1[5][6] = -1.32982102074501;
   fWeightMatrix0to1[6][6] = 1.45218895931236;
   fWeightMatrix0to1[7][6] = 1.06056030881553;
   fWeightMatrix0to1[8][6] = 6.2914948463586;
   fWeightMatrix0to1[9][6] = 0.746514989066206;
   fWeightMatrix0to1[10][6] = 2.08291840267276;
   fWeightMatrix0to1[0][7] = -6.18365323468265;
   fWeightMatrix0to1[1][7] = -0.644218797153839;
   fWeightMatrix0to1[2][7] = 1.33940572512343;
   fWeightMatrix0to1[3][7] = 0.84524274019081;
   fWeightMatrix0to1[4][7] = 0.197925170379515;
   fWeightMatrix0to1[5][7] = 2.47628460336085;
   fWeightMatrix0to1[6][7] = -0.664198320405532;
   fWeightMatrix0to1[7][7] = -0.954835621989931;
   fWeightMatrix0to1[8][7] = 2.27674128269952;
   fWeightMatrix0to1[9][7] = 0.91321312786342;
   fWeightMatrix0to1[10][7] = 3.31816903709763;
   fWeightMatrix0to1[0][8] = -7.55557155255788;
   fWeightMatrix0to1[1][8] = -2.42600454581425;
   fWeightMatrix0to1[2][8] = 0.838335858598131;
   fWeightMatrix0to1[3][8] = -0.661960646127539;
   fWeightMatrix0to1[4][8] = 0.415737286792454;
   fWeightMatrix0to1[5][8] = -2.2647662180681;
   fWeightMatrix0to1[6][8] = -1.79675612479785;
   fWeightMatrix0to1[7][8] = 1.49980744013487;
   fWeightMatrix0to1[8][8] = 1.5203941580809;
   fWeightMatrix0to1[9][8] = -8.71336278432218;
   fWeightMatrix0to1[10][8] = -5.10741443679369;
   fWeightMatrix0to1[0][9] = -0.911210717219816;
   fWeightMatrix0to1[1][9] = -2.56650011575807;
   fWeightMatrix0to1[2][9] = -2.30642563008831;
   fWeightMatrix0to1[3][9] = -2.44454516404359;
   fWeightMatrix0to1[4][9] = 0.144646608614824;
   fWeightMatrix0to1[5][9] = -2.22061319454571;
   fWeightMatrix0to1[6][9] = -1.81293335659397;
   fWeightMatrix0to1[7][9] = -1.01953875668028;
   fWeightMatrix0to1[8][9] = 2.33116970277603;
   fWeightMatrix0to1[9][9] = -0.874225679776577;
   fWeightMatrix0to1[10][9] = 1.7088317922609;
   fWeightMatrix0to1[0][10] = -2.19724481487101;
   fWeightMatrix0to1[1][10] = 0.353448305299856;
   fWeightMatrix0to1[2][10] = 1.25310697721869;
   fWeightMatrix0to1[3][10] = 2.03848395687026;
   fWeightMatrix0to1[4][10] = -1.82477212775691;
   fWeightMatrix0to1[5][10] = 0.886734702393125;
   fWeightMatrix0to1[6][10] = -0.269644982360473;
   fWeightMatrix0to1[7][10] = -1.03917087486485;
   fWeightMatrix0to1[8][10] = -1.48786170294975;
   fWeightMatrix0to1[9][10] = -2.23221704158713;
   fWeightMatrix0to1[10][10] = -3.98835121825006;
   fWeightMatrix0to1[0][11] = -0.244369044627659;
   fWeightMatrix0to1[1][11] = -0.257425539382131;
   fWeightMatrix0to1[2][11] = 2.22038173151583;
   fWeightMatrix0to1[3][11] = 2.36907751122885;
   fWeightMatrix0to1[4][11] = -0.430601989389842;
   fWeightMatrix0to1[5][11] = -1.11824957486912;
   fWeightMatrix0to1[6][11] = -0.277540907531132;
   fWeightMatrix0to1[7][11] = -1.89727295817313;
   fWeightMatrix0to1[8][11] = -0.840291306379548;
   fWeightMatrix0to1[9][11] = -0.953365594837184;
   fWeightMatrix0to1[10][11] = -4.30161390959883;
   // weight matrix from layer 1 to 2
   fWeightMatrix1to2[0][0] = 0.273813575861548;
   fWeightMatrix1to2[1][0] = -1.18098046323972;
   fWeightMatrix1to2[2][0] = 1.75374605588559;
   fWeightMatrix1to2[3][0] = 0.857633158656928;
   fWeightMatrix1to2[4][0] = 4.14197593699164;
   fWeightMatrix1to2[5][0] = -1.95002258812842;
   fWeightMatrix1to2[6][0] = -0.944040288596365;
   fWeightMatrix1to2[7][0] = 4.6240635634663;
   fWeightMatrix1to2[8][0] = 3.2922571074844;
   fWeightMatrix1to2[9][0] = 0.250814820304785;
   fWeightMatrix1to2[10][0] = -2.42854518396331;
   fWeightMatrix1to2[0][1] = -0.374655336453688;
   fWeightMatrix1to2[1][1] = -1.52859687753249;
   fWeightMatrix1to2[2][1] = 2.65279007730055;
   fWeightMatrix1to2[3][1] = 2.07410620977014;
   fWeightMatrix1to2[4][1] = -0.533057725299401;
   fWeightMatrix1to2[5][1] = -0.611159970703938;
   fWeightMatrix1to2[6][1] = -1.07168097343934;
   fWeightMatrix1to2[7][1] = -2.30900167256695;
   fWeightMatrix1to2[8][1] = 0.680636262086284;
   fWeightMatrix1to2[9][1] = 3.054961366881;
   fWeightMatrix1to2[10][1] = -1.03939739107607;
   fWeightMatrix1to2[0][2] = -0.0605941463226355;
   fWeightMatrix1to2[1][2] = 0.197487519822836;
   fWeightMatrix1to2[2][2] = 1.5061660276669;
   fWeightMatrix1to2[3][2] = -1.69093570469483;
   fWeightMatrix1to2[4][2] = 3.11618364807862;
   fWeightMatrix1to2[5][2] = -1.5136936107451;
   fWeightMatrix1to2[6][2] = 1.05991951820637;
   fWeightMatrix1to2[7][2] = -0.241557582486388;
   fWeightMatrix1to2[8][2] = 4.33337604175486;
   fWeightMatrix1to2[9][2] = 3.08121752172523;
   fWeightMatrix1to2[10][2] = -2.06137417989139;
   fWeightMatrix1to2[0][3] = -1.20574973411663;
   fWeightMatrix1to2[1][3] = -0.25006768352826;
   fWeightMatrix1to2[2][3] = 5.63984354674119;
   fWeightMatrix1to2[3][3] = -3.15794203127884;
   fWeightMatrix1to2[4][3] = -0.796904803437779;
   fWeightMatrix1to2[5][3] = 1.50595855316683;
   fWeightMatrix1to2[6][3] = 1.96897511665302;
   fWeightMatrix1to2[7][3] = 1.31904807786363;
   fWeightMatrix1to2[8][3] = 2.80163058711675;
   fWeightMatrix1to2[9][3] = 4.67178475746127;
   fWeightMatrix1to2[10][3] = -1.75365019498075;
   fWeightMatrix1to2[0][4] = -0.055872191769637;
   fWeightMatrix1to2[1][4] = 0.122914770200524;
   fWeightMatrix1to2[2][4] = 0.144523070713585;
   fWeightMatrix1to2[3][4] = -1.75056861099627;
   fWeightMatrix1to2[4][4] = -3.30358935253595;
   fWeightMatrix1to2[5][4] = 1.00941110446571;
   fWeightMatrix1to2[6][4] = 2.34278784854583;
   fWeightMatrix1to2[7][4] = -4.27437452838681;
   fWeightMatrix1to2[8][4] = -1.1732108833895;
   fWeightMatrix1to2[9][4] = -1.08937838897304;
   fWeightMatrix1to2[10][4] = 2.62969774431164;
   fWeightMatrix1to2[0][5] = 2.29359084890904;
   fWeightMatrix1to2[1][5] = -0.483348590545033;
   fWeightMatrix1to2[2][5] = -0.035038102510728;
   fWeightMatrix1to2[3][5] = -2.46179971741342;
   fWeightMatrix1to2[4][5] = 0.65040554025641;
   fWeightMatrix1to2[5][5] = 1.39827090020056;
   fWeightMatrix1to2[6][5] = -0.211509831862937;
   fWeightMatrix1to2[7][5] = 0.540101312179444;
   fWeightMatrix1to2[8][5] = -0.0600169997999698;
   fWeightMatrix1to2[9][5] = -2.44694264678326;
   fWeightMatrix1to2[10][5] = 0.919453964377016;
   fWeightMatrix1to2[0][6] = 1.52134791499635;
   fWeightMatrix1to2[1][6] = -1.81439714131337;
   fWeightMatrix1to2[2][6] = -1.7419782002204;
   fWeightMatrix1to2[3][6] = 1.8897383061465;
   fWeightMatrix1to2[4][6] = 0.41942408575636;
   fWeightMatrix1to2[5][6] = -1.87558383523062;
   fWeightMatrix1to2[6][6] = 1.32349008745724;
   fWeightMatrix1to2[7][6] = 1.32041803693946;
   fWeightMatrix1to2[8][6] = -2.60308589696948;
   fWeightMatrix1to2[9][6] = -1.50588331593954;
   fWeightMatrix1to2[10][6] = 3.48611083578253;
   fWeightMatrix1to2[0][7] = 1.03060486948162;
   fWeightMatrix1to2[1][7] = 0.451061310884112;
   fWeightMatrix1to2[2][7] = -0.187642512570264;
   fWeightMatrix1to2[3][7] = -2.04681534435154;
   fWeightMatrix1to2[4][7] = -0.951283689846275;
   fWeightMatrix1to2[5][7] = 1.72263484030818;
   fWeightMatrix1to2[6][7] = 1.24192219098384;
   fWeightMatrix1to2[7][7] = 0.791051856544501;
   fWeightMatrix1to2[8][7] = 0.154759646729826;
   fWeightMatrix1to2[9][7] = 1.90369800813284;
   fWeightMatrix1to2[10][7] = -1.70087570832409;
   fWeightMatrix1to2[0][8] = -0.318491292858195;
   fWeightMatrix1to2[1][8] = -0.694097494166537;
   fWeightMatrix1to2[2][8] = -2.64584804219015;
   fWeightMatrix1to2[3][8] = 4.71600473647213;
   fWeightMatrix1to2[4][8] = 2.51385883300552;
   fWeightMatrix1to2[5][8] = -1.09755337840917;
   fWeightMatrix1to2[6][8] = 3.66454114417014;
   fWeightMatrix1to2[7][8] = -0.435203179428705;
   fWeightMatrix1to2[8][8] = -2.77388172216061;
   fWeightMatrix1to2[9][8] = -4.32350369812137;
   fWeightMatrix1to2[10][8] = 3.24541582804128;
   fWeightMatrix1to2[0][9] = 0.614614147594348;
   fWeightMatrix1to2[1][9] = 1.04041368610348;
   fWeightMatrix1to2[2][9] = -2.3441693009655;
   fWeightMatrix1to2[3][9] = 2.52005268340916;
   fWeightMatrix1to2[4][9] = -2.46562908883534;
   fWeightMatrix1to2[5][9] = 1.01055717672065;
   fWeightMatrix1to2[6][9] = -0.977400359456508;
   fWeightMatrix1to2[7][9] = -0.346508069735241;
   fWeightMatrix1to2[8][9] = -2.5547071222279;
   fWeightMatrix1to2[9][9] = -3.03634718211462;
   fWeightMatrix1to2[10][9] = 0.155243954273589;
   fWeightMatrix1to2[0][10] = -2.50340263967048;
   fWeightMatrix1to2[1][10] = -1.96007588575612;
   fWeightMatrix1to2[2][10] = -4.4561693647013;
   fWeightMatrix1to2[3][10] = 2.00253809033974;
   fWeightMatrix1to2[4][10] = -1.91239492609391;
   fWeightMatrix1to2[5][10] = -1.86735101683297;
   fWeightMatrix1to2[6][10] = 0.863455079871879;
   fWeightMatrix1to2[7][10] = -0.700880055190393;
   fWeightMatrix1to2[8][10] = -1.0565498605097;
   fWeightMatrix1to2[9][10] = -3.55685220703033;
   fWeightMatrix1to2[10][10] = 0.738854961156773;
   fWeightMatrix1to2[0][11] = 1.957066302333;
   fWeightMatrix1to2[1][11] = 1.21565414222701;
   fWeightMatrix1to2[2][11] = -0.932415040583036;
   fWeightMatrix1to2[3][11] = -0.0391145673960741;
   fWeightMatrix1to2[4][11] = -1.17988343396679;
   fWeightMatrix1to2[5][11] = -1.18374388457537;
   fWeightMatrix1to2[6][11] = -2.42231661062006;
   fWeightMatrix1to2[7][11] = -0.74346273709093;
   fWeightMatrix1to2[8][11] = 0.206897468743678;
   fWeightMatrix1to2[9][11] = 2.07891759682447;
   fWeightMatrix1to2[10][11] = -0.905188806447063;
   // weight matrix from layer 2 to 3
   fWeightMatrix2to3[0][0] = 0.752079651666575;
   fWeightMatrix2to3[1][0] = -2.12900841213657;
   fWeightMatrix2to3[2][0] = -2.13411543746986;
   fWeightMatrix2to3[3][0] = 1.09511392615713;
   fWeightMatrix2to3[4][0] = 0.43242031849479;
   fWeightMatrix2to3[5][0] = -2.57551218016006;
   fWeightMatrix2to3[6][0] = -1.16122881448067;
   fWeightMatrix2to3[7][0] = 0.765348183940911;
   fWeightMatrix2to3[8][0] = -0.19098311183317;
   fWeightMatrix2to3[9][0] = 0.886779446324791;
   fWeightMatrix2to3[10][0] = -1.66344207036818;
   fWeightMatrix2to3[0][1] = -0.10288434162145;
   fWeightMatrix2to3[1][1] = 0.943868253463903;
   fWeightMatrix2to3[2][1] = 0.964950672061626;
   fWeightMatrix2to3[3][1] = 1.21959795892332;
   fWeightMatrix2to3[4][1] = -0.352432782337047;
   fWeightMatrix2to3[5][1] = 0.206478425548181;
   fWeightMatrix2to3[6][1] = -0.159842900672179;
   fWeightMatrix2to3[7][1] = -1.16815127081121;
   fWeightMatrix2to3[8][1] = -0.746024699682953;
   fWeightMatrix2to3[9][1] = -1.55400075631927;
   fWeightMatrix2to3[10][1] = -2.02928776551196;
   fWeightMatrix2to3[0][2] = -2.99302098315702;
   fWeightMatrix2to3[1][2] = 2.1159914244941;
   fWeightMatrix2to3[2][2] = -1.8457188779316;
   fWeightMatrix2to3[3][2] = 0.62744268151366;
   fWeightMatrix2to3[4][2] = -1.60184957530747;
   fWeightMatrix2to3[5][2] = 0.110350799512303;
   fWeightMatrix2to3[6][2] = -1.77355247544021;
   fWeightMatrix2to3[7][2] = -1.05740185730233;
   fWeightMatrix2to3[8][2] = 1.99371439939784;
   fWeightMatrix2to3[9][2] = -3.52738448951239;
   fWeightMatrix2to3[10][2] = 1.22932048307824;
   fWeightMatrix2to3[0][3] = 1.71941030151;
   fWeightMatrix2to3[1][3] = -3.43691577664424;
   fWeightMatrix2to3[2][3] = -1.66656459877452;
   fWeightMatrix2to3[3][3] = -0.840387583466088;
   fWeightMatrix2to3[4][3] = -1.61620606134437;
   fWeightMatrix2to3[5][3] = 0.454952052674821;
   fWeightMatrix2to3[6][3] = -0.0703540071782616;
   fWeightMatrix2to3[7][3] = 1.41457793934392;
   fWeightMatrix2to3[8][3] = -3.66192266039853;
   fWeightMatrix2to3[9][3] = 1.41230589862453;
   fWeightMatrix2to3[10][3] = -2.37990515573624;
   fWeightMatrix2to3[0][4] = -2.16632826203719;
   fWeightMatrix2to3[1][4] = -3.11555882477688;
   fWeightMatrix2to3[2][4] = 0.944463391796945;
   fWeightMatrix2to3[3][4] = -2.39309862363339;
   fWeightMatrix2to3[4][4] = -1.44386260683806;
   fWeightMatrix2to3[5][4] = 0.901794624544616;
   fWeightMatrix2to3[6][4] = -0.257478876474659;
   fWeightMatrix2to3[7][4] = -1.55490886012465;
   fWeightMatrix2to3[8][4] = 2.93081740611501;
   fWeightMatrix2to3[9][4] = -1.71361959098132;
   fWeightMatrix2to3[10][4] = 1.41523521488314;
   fWeightMatrix2to3[0][5] = 0.907142901869405;
   fWeightMatrix2to3[1][5] = -0.901615650398549;
   fWeightMatrix2to3[2][5] = -0.816003533065547;
   fWeightMatrix2to3[3][5] = 0.0922816192223465;
   fWeightMatrix2to3[4][5] = -1.20449991139482;
   fWeightMatrix2to3[5][5] = 0.463862438255641;
   fWeightMatrix2to3[6][5] = 1.92029609923354;
   fWeightMatrix2to3[7][5] = 1.42145851492797;
   fWeightMatrix2to3[8][5] = 1.55576103509922;
   fWeightMatrix2to3[9][5] = -1.34474568280786;
   fWeightMatrix2to3[10][5] = 0.661843133922277;
   fWeightMatrix2to3[0][6] = -2.81730812216479;
   fWeightMatrix2to3[1][6] = -0.207131634854838;
   fWeightMatrix2to3[2][6] = -1.92954596604074;
   fWeightMatrix2to3[3][6] = -2.453861485305;
   fWeightMatrix2to3[4][6] = -0.914557010486111;
   fWeightMatrix2to3[5][6] = 0.318750581633964;
   fWeightMatrix2to3[6][6] = 0.899373307792585;
   fWeightMatrix2to3[7][6] = 1.34580693498488;
   fWeightMatrix2to3[8][6] = -0.720032942698366;
   fWeightMatrix2to3[9][6] = 2.34108989502088;
   fWeightMatrix2to3[10][6] = -2.50824177894674;
   fWeightMatrix2to3[0][7] = -0.0760746453818837;
   fWeightMatrix2to3[1][7] = 3.24754816462889;
   fWeightMatrix2to3[2][7] = -1.59884228412549;
   fWeightMatrix2to3[3][7] = -1.42985517557781;
   fWeightMatrix2to3[4][7] = -1.59262872361615;
   fWeightMatrix2to3[5][7] = -1.35593887362875;
   fWeightMatrix2to3[6][7] = -0.831514429468607;
   fWeightMatrix2to3[7][7] = -2.23162619485631;
   fWeightMatrix2to3[8][7] = -1.03720627625337;
   fWeightMatrix2to3[9][7] = -0.768279137125611;
   fWeightMatrix2to3[10][7] = 2.78605132311468;
   fWeightMatrix2to3[0][8] = 0.800528577069914;
   fWeightMatrix2to3[1][8] = 0.170322467468551;
   fWeightMatrix2to3[2][8] = -0.982387486183587;
   fWeightMatrix2to3[3][8] = -2.94545119508872;
   fWeightMatrix2to3[4][8] = -1.87454927015666;
   fWeightMatrix2to3[5][8] = -0.22230569139395;
   fWeightMatrix2to3[6][8] = -0.641464828900138;
   fWeightMatrix2to3[7][8] = -2.23686619384138;
   fWeightMatrix2to3[8][8] = 0.582412801028491;
   fWeightMatrix2to3[9][8] = -3.0509896067829;
   fWeightMatrix2to3[10][8] = -1.78083253927343;
   fWeightMatrix2to3[0][9] = -3.22916224207647;
   fWeightMatrix2to3[1][9] = 0.76621747107506;
   fWeightMatrix2to3[2][9] = -1.43383260423212;
   fWeightMatrix2to3[3][9] = -2.2902401440221;
   fWeightMatrix2to3[4][9] = -0.787193045213211;
   fWeightMatrix2to3[5][9] = -2.11788058947775;
   fWeightMatrix2to3[6][9] = -2.33467826945485;
   fWeightMatrix2to3[7][9] = 0.239396949402539;
   fWeightMatrix2to3[8][9] = -0.158965055289015;
   fWeightMatrix2to3[9][9] = -2.69359136491622;
   fWeightMatrix2to3[10][9] = 2.38082963996826;
   fWeightMatrix2to3[0][10] = 0.363914083724248;
   fWeightMatrix2to3[1][10] = -1.1246660574643;
   fWeightMatrix2to3[2][10] = -0.0442201370319291;
   fWeightMatrix2to3[3][10] = 2.13105153271839;
   fWeightMatrix2to3[4][10] = 1.04319915272776;
   fWeightMatrix2to3[5][10] = 0.124917489775085;
   fWeightMatrix2to3[6][10] = -0.76498805130186;
   fWeightMatrix2to3[7][10] = 0.091568405534876;
   fWeightMatrix2to3[8][10] = -3.6005947690317;
   fWeightMatrix2to3[9][10] = 3.07155857649418;
   fWeightMatrix2to3[10][10] = -0.446259282268457;
   fWeightMatrix2to3[0][11] = 0.0321810556367816;
   fWeightMatrix2to3[1][11] = -0.266799154074196;
   fWeightMatrix2to3[2][11] = 0.742387780357288;
   fWeightMatrix2to3[3][11] = 1.63095024493121;
   fWeightMatrix2to3[4][11] = -2.22044558239566;
   fWeightMatrix2to3[5][11] = -0.209529615434227;
   fWeightMatrix2to3[6][11] = 0.442293047475981;
   fWeightMatrix2to3[7][11] = -1.81310606559716;
   fWeightMatrix2to3[8][11] = -1.92697398809407;
   fWeightMatrix2to3[9][11] = -0.632559098648286;
   fWeightMatrix2to3[10][11] = -0.640642312126789;
   // weight matrix from layer 3 to 4
   fWeightMatrix3to4[0][0] = -1.47803438501039;
   fWeightMatrix3to4[0][1] = 3.29761859263944;
   fWeightMatrix3to4[0][2] = 1.67869156919671;
   fWeightMatrix3to4[0][3] = -1.79457364170133;
   fWeightMatrix3to4[0][4] = 1.15714258259784;
   fWeightMatrix3to4[0][5] = -0.477413703814383;
   fWeightMatrix3to4[0][6] = -0.473193070070186;
   fWeightMatrix3to4[0][7] = -2.24946142689666;
   fWeightMatrix3to4[0][8] = 1.69182617450171;
   fWeightMatrix3to4[0][9] = -1.84799825936573;
   fWeightMatrix3to4[0][10] = 1.727793457764;
   fWeightMatrix3to4[0][11] = -0.0897738407014329;
}

inline double ReadMLP_ANN_N-3_NC200::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   if (inputValues.size() != (unsigned int)fLayerSize[0]-1) {
      std::cout << "Input vector needs to be of size " << fLayerSize[0]-1 << std::endl;
      return 0;
   }

   for (int l=0; l<fLayers; l++)
      for (int i=0; i<fLayerSize[l]; i++) fWeights[l][i]=0;

   for (int l=0; l<fLayers-1; l++)
      fWeights[l][fLayerSize[l]-1]=1;

   for (int i=0; i<fLayerSize[0]-1; i++)
      fWeights[0][i]=inputValues[i];

   // layer 0 to 1
   for (int o=0; o<fLayerSize[1]-1; o++) {
      for (int i=0; i<fLayerSize[0]; i++) {
         double inputVal = fWeightMatrix0to1[o][i] * fWeights[0][i];
         fWeights[1][o] += inputVal;
      }
      fWeights[1][o] = ActivationFnc(fWeights[1][o]);
   }
   // layer 1 to 2
   for (int o=0; o<fLayerSize[2]-1; o++) {
      for (int i=0; i<fLayerSize[1]; i++) {
         double inputVal = fWeightMatrix1to2[o][i] * fWeights[1][i];
         fWeights[2][o] += inputVal;
      }
      fWeights[2][o] = ActivationFnc(fWeights[2][o]);
   }
   // layer 2 to 3
   for (int o=0; o<fLayerSize[3]-1; o++) {
      for (int i=0; i<fLayerSize[2]; i++) {
         double inputVal = fWeightMatrix2to3[o][i] * fWeights[2][i];
         fWeights[3][o] += inputVal;
      }
      fWeights[3][o] = ActivationFnc(fWeights[3][o]);
   }
   // layer 3 to 4
   for (int o=0; o<fLayerSize[4]; o++) {
      for (int i=0; i<fLayerSize[3]; i++) {
         double inputVal = fWeightMatrix3to4[o][i] * fWeights[3][i];
         fWeights[4][o] += inputVal;
      }
      fWeights[4][o] = OutputActivationFnc(fWeights[4][o]);
   }

   return fWeights[4][0];
}

double ReadMLP_ANN_N-3_NC200::ActivationFnc(double x) const {
   // sigmoid
   return 1.0/(1.0+exp(-x));
}
double ReadMLP_ANN_N-3_NC200::OutputActivationFnc(double x) const {
   // sigmoid
   return 1.0/(1.0+exp(-x));
}
   
// Clean up
inline void ReadMLP_ANN_N-3_NC200::Clear() 
{
   // clean up the arrays
   for (int lIdx = 0; lIdx < 5; lIdx++) {
      delete[] fWeights[lIdx];
   }
}
   inline double ReadMLP_ANN_N-3_NC200::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            iV.reserve(inputValues.size());
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
         else {
            std::vector<double> iV;
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(*varIt);
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
      }

      return retval;
   }

//_______________________________________________________________________
inline void ReadMLP_ANN_N-3_NC200::InitTransform_1()
{
   // Normalization transformation, initialisation
   fMin_1[0][0] = 110.048698425;
   fMax_1[0][0] = 1277.92980957;
   fMin_1[1][0] = 110.057556152;
   fMax_1[1][0] = 1572.76037598;
   fMin_1[2][0] = 110.048698425;
   fMax_1[2][0] = 1572.76037598;
   fMin_1[0][1] = 5.00075817108;
   fMax_1[0][1] = 29.9497737885;
   fMin_1[1][1] = 5.00135278702;
   fMax_1[1][1] = 29.9984378815;
   fMin_1[2][1] = 5.00075817108;
   fMax_1[2][1] = 29.9984378815;
   fMin_1[0][2] = -1;
   fMax_1[0][2] = 1;
   fMin_1[1][2] = -1;
   fMax_1[1][2] = 1;
   fMin_1[2][2] = -1;
   fMax_1[2][2] = 1;
   fMin_1[0][3] = -2.4711689949;
   fMax_1[0][3] = 2.37911462784;
   fMin_1[1][3] = -2.48411560059;
   fMax_1[1][3] = 2.49880051613;
   fMin_1[2][3] = -2.48411560059;
   fMax_1[2][3] = 2.49880051613;
   fMin_1[0][4] = 280.2293396;
   fMax_1[0][4] = 1251.49438477;
   fMin_1[1][4] = 280.020294189;
   fMax_1[1][4] = 1289.47937012;
   fMin_1[2][4] = 280.020294189;
   fMax_1[2][4] = 1289.47937012;
   fMin_1[0][5] = 0.0557334087789;
   fMax_1[0][5] = 300.527191162;
   fMin_1[1][5] = 0.000537815736607;
   fMax_1[1][5] = 215.792510986;
   fMin_1[2][5] = 0.000537815736607;
   fMax_1[2][5] = 300.527191162;
   fMin_1[0][6] = 117.352531433;
   fMax_1[0][6] = 2347.48510742;
   fMin_1[1][6] = 112.003395081;
   fMax_1[1][6] = 4504.87304688;
   fMin_1[2][6] = 112.003395081;
   fMax_1[2][6] = 4504.87304688;
   fMin_1[0][7] = 0;
   fMax_1[0][7] = 5;
   fMin_1[1][7] = 0;
   fMax_1[1][7] = 6;
   fMin_1[2][7] = 0;
   fMax_1[2][7] = 6;
   fMin_1[0][8] = 1;
   fMax_1[0][8] = 11;
   fMin_1[1][8] = 1;
   fMax_1[1][8] = 14;
   fMin_1[2][8] = 1;
   fMax_1[2][8] = 14;
   fMin_1[0][9] = 20.0573444366;
   fMax_1[0][9] = 1057.04370117;
   fMin_1[1][9] = -999;
   fMax_1[1][9] = 1378.42883301;
   fMin_1[2][9] = -999;
   fMax_1[2][9] = 1378.42883301;
   fMin_1[0][10] = 6.27087429166e-05;
   fMax_1[0][10] = 4.95768356323;
   fMin_1[1][10] = -999;
   fMax_1[1][10] = 5.38026332855;
   fMin_1[2][10] = -999;
   fMax_1[2][10] = 5.38026332855;
}

//_______________________________________________________________________
inline void ReadMLP_ANN_N-3_NC200::Transform_1( std::vector<double>& iv, int cls) const
{
   // Normalization transformation
   if (cls < 0 || cls > 2) {
   if (2 > 1 ) cls = 2;
      else cls = 2;
   }
   const int nVar = 11;

   // get indices of used variables

   // define the indices of the variables which are transformed by this transformation
   static std::vector<int> indicesGet;
   static std::vector<int> indicesPut;

   if ( indicesGet.empty() ) { 
      indicesGet.reserve(fNvars);
      indicesGet.push_back( 0);
      indicesGet.push_back( 1);
      indicesGet.push_back( 2);
      indicesGet.push_back( 3);
      indicesGet.push_back( 4);
      indicesGet.push_back( 5);
      indicesGet.push_back( 6);
      indicesGet.push_back( 7);
      indicesGet.push_back( 8);
      indicesGet.push_back( 9);
      indicesGet.push_back( 10);
   } 
   if ( indicesPut.empty() ) { 
      indicesPut.reserve(fNvars);
      indicesPut.push_back( 0);
      indicesPut.push_back( 1);
      indicesPut.push_back( 2);
      indicesPut.push_back( 3);
      indicesPut.push_back( 4);
      indicesPut.push_back( 5);
      indicesPut.push_back( 6);
      indicesPut.push_back( 7);
      indicesPut.push_back( 8);
      indicesPut.push_back( 9);
      indicesPut.push_back( 10);
   } 

   static std::vector<double> dv;
   dv.resize(nVar);
   for (int ivar=0; ivar<nVar; ivar++) dv[ivar] = iv[indicesGet.at(ivar)];
   for (int ivar=0;ivar<11;ivar++) {
      double offset = fMin_1[cls][ivar];
      double scale  = 1.0/(fMax_1[cls][ivar]-fMin_1[cls][ivar]);
      iv[indicesPut.at(ivar)] = (dv[ivar]-offset)*scale * 2 - 1;
   }
}

//_______________________________________________________________________
inline void ReadMLP_ANN_N-3_NC200::InitTransform()
{
   InitTransform_1();
}

//_______________________________________________________________________
inline void ReadMLP_ANN_N-3_NC200::Transform( std::vector<double>& iv, int sigOrBgd ) const
{
   Transform_1( iv, sigOrBgd );
}
