// Class: ReadMLP_ANN_N1_NC1000
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : MLP::MLP_ANN_N1_NC1000
TMVA Release   : 4.2.1         [262657]
ROOT Release   : 6.06/01       [394753]
Creator        : brucms16
Date           : Wed Sep  7 02:39:07 2016
Host           : Linux vocms0315.cern.ch 2.6.32-573.26.1.el6.x86_64 #1 SMP Wed May 4 09:23:05 CEST 2016 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /home/t3cms/brucms16/CMSSW_8_0_14/src/UserCode/SkeletonAnalysis/macros
Training events: 15056
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
NCycles: "1000" [Number of training cycles]
HiddenLayers: "N,N,N+1" [Specification of hidden layer architecture]
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
VarTransform: "Norm" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
H: "False" [Print method-specific help message]
LearningRate: "9.000000e-02" [ANN learning rate parameter]
DecayRate: "1.000000e-02" [Decay rate for learning parameter]
# Default:
NeuronType: "sigmoid" [Neuron activation function type]
RandomSeed: "1" [Random seed for initial synapse weights (0 means unique seed for each run; default value '1')]
EstimatorType: "CE" [MSE (Mean Square Estimator) for Gaussian Likelihood or CE(Cross-Entropy) for Bernoulli Likelihood]
NeuronInputType: "sum" [Neuron input function type]
VerbosityLevel: "Default" [Verbosity level]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
TrainingMethod: "BP" [Train with Back-Propagation (BP), BFGS Algorithm (BFGS), or Genetic Algorithm (GA - slower and worse)]
TestRate: "10" [Test for overtraining performed at each #th epochs]
EpochMonitoring: "False" [Provide epoch-wise monitoring plots according to TestRate (caution: causes big ROOT output file!)]
Sampling: "1.000000e+00" [Only 'Sampling' (randomly selected) events are trained each epoch]
SamplingEpoch: "1.000000e+00" [Sampling is used for the first 'SamplingEpoch' epochs, afterwards, all events are taken for training]
SamplingImportance: "1.000000e+00" [ The sampling weights of events in epochs which successful (worse estimator than before) are multiplied with SamplingImportance, else they are divided.]
SamplingTraining: "True" [The training sample is sampled]
SamplingTesting: "False" [The testing sample is sampled]
ResetStep: "50" [How often BFGS should reset history]
Tau: "3.000000e+00" [LineSearch "size step"]
BPMode: "sequential" [Back-propagation learning mode: sequential or batch]
BatchSize: "-1" [Batch size: number of events/batch, only set if in Batch Mode, -1 for BatchSize=number_of_events]
ConvergenceImprove: "1.000000e-30" [Minimum improvement which counts as improvement (<0 means automatic convergence check is turned off)]
ConvergenceTests: "-1" [Number of steps (without improvement) required for convergence (<0 means automatic convergence check is turned off)]
UseRegulator: "False" [Use regulator to avoid over-training]
UpdateLimit: "10000" [Maximum times of regulator update]
CalculateErrors: "False" [Calculates inverse Hessian matrix at the end of the training to be able to calculate the uncertainties of an MVA value]
WeightRange: "1.000000e+00" [Take the events for the estimator calculations from small deviations from the desired value to large deviations only over the weight range]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 11
Jet1Pt                        Jet1Pt                        Jet1Pt                        Jet1Pt                                                          'F'    [110.048698425,1572.76037598]
LepPt                         LepPt                         LepPt                         LepPt                                                           'F'    [5.00075817108,29.9984378815]
LepChg                        LepChg                        LepChg                        LepChg                                                          'F'    [-1,1]
LepEta                        LepEta                        LepEta                        LepEta                                                          'F'    [-2.48411560059,2.49880051613]
Met                           Met                           Met                           Met                                                             'F'    [280.020294189,1289.47937012]
mt                            mt                            mt                            mt                                                              'F'    [0.000537815736607,300.527191162]
HT20                          HT20                          HT20                          HT20                                                            'F'    [112.003395081,4504.87304688]
NbLoose30                     NbLoose30                     NbLoose30                     NbLoose30                                                       'F'    [0,6]
Njet                          Njet                          Njet                          Njet                                                            'F'    [1,14]
JetHBpt                       JetHBpt                       JetHBpt                       JetHBpt                                                         'F'    [-999,1378.42883301]
DrJetHBLep                    DrJetHBLep                    DrJetHBLep                    DrJetHBLep                                                      'F'    [-999,5.38026332855]
NSpec 0


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadMLP_ANN_N1_NC1000 : public IClassifierReader {

 public:

   // constructor
   ReadMLP_ANN_N1_NC1000( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadMLP_ANN_N1_NC1000" ),
        fNvars( 11 ),
        fIsNormalised( false )
   {      
      // the training input variables
      const char* inputVars[] = { "Jet1Pt", "LepPt", "LepChg", "LepEta", "Met", "mt", "HT20", "NbLoose30", "Njet", "JetHBpt", "DrJetHBLep" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = -1;
      fVmax[0] = 1;
      fVmin[1] = -1;
      fVmax[1] = 0.99999988079071;
      fVmin[2] = -1;
      fVmax[2] = 1;
      fVmin[3] = -1;
      fVmax[3] = 1;
      fVmin[4] = -1;
      fVmax[4] = 1;
      fVmin[5] = -1;
      fVmax[5] = 1;
      fVmin[6] = -1;
      fVmax[6] = 1;
      fVmin[7] = -1;
      fVmax[7] = 1;
      fVmin[8] = -1;
      fVmax[8] = 1;
      fVmin[9] = -1;
      fVmax[9] = 1;
      fVmin[10] = -1;
      fVmax[10] = 1;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';
      fType[4] = 'F';
      fType[5] = 'F';
      fType[6] = 'F';
      fType[7] = 'F';
      fType[8] = 'F';
      fType[9] = 'F';
      fType[10] = 'F';

      // initialize constants
      Initialize();

      // initialize transformation
      InitTransform();
   }

   // destructor
   virtual ~ReadMLP_ANN_N1_NC1000() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // input variable transformation

   double fMin_1[3][11];
   double fMax_1[3][11];
   void InitTransform_1();
   void Transform_1( std::vector<double> & iv, int sigOrBgd ) const;
   void InitTransform();
   void Transform( std::vector<double> & iv, int sigOrBgd ) const;

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[11];
   double fVmax[11];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[11];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)

   double ActivationFnc(double x) const;
   double OutputActivationFnc(double x) const;

   int fLayers;
   int fLayerSize[5];
   double fWeightMatrix0to1[12][12];   // weight matrix from layer 0 to 1
   double fWeightMatrix1to2[12][12];   // weight matrix from layer 1 to 2
   double fWeightMatrix2to3[13][12];   // weight matrix from layer 2 to 3
   double fWeightMatrix3to4[1][13];   // weight matrix from layer 3 to 4

   double * fWeights[5];
};

inline void ReadMLP_ANN_N1_NC1000::Initialize()
{
   // build network structure
   fLayers = 5;
   fLayerSize[0] = 12; fWeights[0] = new double[12]; 
   fLayerSize[1] = 12; fWeights[1] = new double[12]; 
   fLayerSize[2] = 12; fWeights[2] = new double[12]; 
   fLayerSize[3] = 13; fWeights[3] = new double[13]; 
   fLayerSize[4] = 1; fWeights[4] = new double[1]; 
   // weight matrix from layer 0 to 1
   fWeightMatrix0to1[0][0] = -0.198525979042836;
   fWeightMatrix0to1[1][0] = -0.111876502662971;
   fWeightMatrix0to1[2][0] = -0.107936038019017;
   fWeightMatrix0to1[3][0] = -2.14230510248717;
   fWeightMatrix0to1[4][0] = -4.15216515116792;
   fWeightMatrix0to1[5][0] = 0.20152304347482;
   fWeightMatrix0to1[6][0] = 1.08997290051917;
   fWeightMatrix0to1[7][0] = 2.24451712372895;
   fWeightMatrix0to1[8][0] = -4.0376476093239;
   fWeightMatrix0to1[9][0] = -0.190401142649239;
   fWeightMatrix0to1[10][0] = -3.45288113451922;
   fWeightMatrix0to1[0][1] = -2.5528578696568;
   fWeightMatrix0to1[1][1] = 0.358088807084646;
   fWeightMatrix0to1[2][1] = 0.0459387347331812;
   fWeightMatrix0to1[3][1] = -2.55998261920587;
   fWeightMatrix0to1[4][1] = 1.79823779645473;
   fWeightMatrix0to1[5][1] = 1.34891017473172;
   fWeightMatrix0to1[6][1] = 1.89299359820394;
   fWeightMatrix0to1[7][1] = 0.232480901389576;
   fWeightMatrix0to1[8][1] = 4.14534270253689;
   fWeightMatrix0to1[9][1] = 0.566737488020241;
   fWeightMatrix0to1[10][1] = -0.101071366647856;
   fWeightMatrix0to1[0][2] = 0.836018628528785;
   fWeightMatrix0to1[1][2] = 0.108509486118284;
   fWeightMatrix0to1[2][2] = -0.117328500407406;
   fWeightMatrix0to1[3][2] = -1.97698932892217;
   fWeightMatrix0to1[4][2] = 2.76744600335673;
   fWeightMatrix0to1[5][2] = -1.20375851301417;
   fWeightMatrix0to1[6][2] = -3.592397509944;
   fWeightMatrix0to1[7][2] = -0.18880909993389;
   fWeightMatrix0to1[8][2] = -0.693420232773325;
   fWeightMatrix0to1[9][2] = -0.556263688385496;
   fWeightMatrix0to1[10][2] = -0.544830636552705;
   fWeightMatrix0to1[0][3] = 1.16124038420508;
   fWeightMatrix0to1[1][3] = 0.612333467603261;
   fWeightMatrix0to1[2][3] = 0.032200992468871;
   fWeightMatrix0to1[3][3] = 0.704956685491351;
   fWeightMatrix0to1[4][3] = 2.60106551907818;
   fWeightMatrix0to1[5][3] = -1.7581765021135;
   fWeightMatrix0to1[6][3] = 0.333885891419368;
   fWeightMatrix0to1[7][3] = 1.14300976849857;
   fWeightMatrix0to1[8][3] = -0.844252571546309;
   fWeightMatrix0to1[9][3] = 7.20304017104074;
   fWeightMatrix0to1[10][3] = -2.80213424731347;
   fWeightMatrix0to1[0][4] = 8.37196926083263;
   fWeightMatrix0to1[1][4] = -1.11822966488453;
   fWeightMatrix0to1[2][4] = 8.88858942749034;
   fWeightMatrix0to1[3][4] = -1.6394262919094;
   fWeightMatrix0to1[4][4] = -2.10386801257096;
   fWeightMatrix0to1[5][4] = 3.40889400907635;
   fWeightMatrix0to1[6][4] = 5.23528202789215;
   fWeightMatrix0to1[7][4] = 0.496802924166853;
   fWeightMatrix0to1[8][4] = -0.788217954528826;
   fWeightMatrix0to1[9][4] = -0.0862435725844332;
   fWeightMatrix0to1[10][4] = -0.930057250676984;
   fWeightMatrix0to1[0][5] = 0.703349069354042;
   fWeightMatrix0to1[1][5] = -17.3418260275595;
   fWeightMatrix0to1[2][5] = 0.00847869402375777;
   fWeightMatrix0to1[3][5] = 2.35632258450879;
   fWeightMatrix0to1[4][5] = 1.69781205542697;
   fWeightMatrix0to1[5][5] = -4.51678884443931;
   fWeightMatrix0to1[6][5] = 1.471301930231;
   fWeightMatrix0to1[7][5] = -0.551031319838296;
   fWeightMatrix0to1[8][5] = 3.97190666856311;
   fWeightMatrix0to1[9][5] = 0.448608351448909;
   fWeightMatrix0to1[10][5] = 3.03567282828115;
   fWeightMatrix0to1[0][6] = -4.85463424090616;
   fWeightMatrix0to1[1][6] = 2.61064292105325;
   fWeightMatrix0to1[2][6] = -5.34627662995827;
   fWeightMatrix0to1[3][6] = -1.6885768238534;
   fWeightMatrix0to1[4][6] = -0.0421072356660985;
   fWeightMatrix0to1[5][6] = 0.172823597534918;
   fWeightMatrix0to1[6][6] = -1.08447089496824;
   fWeightMatrix0to1[7][6] = 1.17859560823375;
   fWeightMatrix0to1[8][6] = 2.0364802699231;
   fWeightMatrix0to1[9][6] = 2.06738925106915;
   fWeightMatrix0to1[10][6] = -0.730078908019529;
   fWeightMatrix0to1[0][7] = -3.98773389412992;
   fWeightMatrix0to1[1][7] = -0.913821472655707;
   fWeightMatrix0to1[2][7] = -0.455745215011602;
   fWeightMatrix0to1[3][7] = 5.10319894984704;
   fWeightMatrix0to1[4][7] = 2.76048710699895;
   fWeightMatrix0to1[5][7] = 1.64928000545054;
   fWeightMatrix0to1[6][7] = -1.92557689184609;
   fWeightMatrix0to1[7][7] = -1.10151900498869;
   fWeightMatrix0to1[8][7] = 0.0629980261934862;
   fWeightMatrix0to1[9][7] = 1.51326876929483;
   fWeightMatrix0to1[10][7] = 0.69683831842064;
   fWeightMatrix0to1[0][8] = -2.50955269995814;
   fWeightMatrix0to1[1][8] = 0.341763760569805;
   fWeightMatrix0to1[2][8] = 3.17196722524844;
   fWeightMatrix0to1[3][8] = 2.51786045196879;
   fWeightMatrix0to1[4][8] = -0.149100244903158;
   fWeightMatrix0to1[5][8] = -2.93783984155451;
   fWeightMatrix0to1[6][8] = -4.4538549997791;
   fWeightMatrix0to1[7][8] = 1.74473459576462;
   fWeightMatrix0to1[8][8] = -1.55494571001806;
   fWeightMatrix0to1[9][8] = -5.49195088390344;
   fWeightMatrix0to1[10][8] = -6.70522567226217;
   fWeightMatrix0to1[0][9] = -3.66217613915692;
   fWeightMatrix0to1[1][9] = 0.448183702376656;
   fWeightMatrix0to1[2][9] = -5.90767788502695;
   fWeightMatrix0to1[3][9] = 0.773443292469684;
   fWeightMatrix0to1[4][9] = 0.936650159620613;
   fWeightMatrix0to1[5][9] = -2.08976734492852;
   fWeightMatrix0to1[6][9] = 3.41925262851138;
   fWeightMatrix0to1[7][9] = -1.09753902659204;
   fWeightMatrix0to1[8][9] = -3.51463647745614;
   fWeightMatrix0to1[9][9] = -0.780007479170856;
   fWeightMatrix0to1[10][9] = 0.272483949536846;
   fWeightMatrix0to1[0][10] = -0.576516904277212;
   fWeightMatrix0to1[1][10] = -2.28455932081391;
   fWeightMatrix0to1[2][10] = 0.88942679083509;
   fWeightMatrix0to1[3][10] = 0.500606401761462;
   fWeightMatrix0to1[4][10] = -0.0242698624348818;
   fWeightMatrix0to1[5][10] = 1.38848274986089;
   fWeightMatrix0to1[6][10] = 0.280857337195112;
   fWeightMatrix0to1[7][10] = -0.467236620166057;
   fWeightMatrix0to1[8][10] = -0.0994904938602354;
   fWeightMatrix0to1[9][10] = -2.58864465259824;
   fWeightMatrix0to1[10][10] = -3.81327485079281;
   fWeightMatrix0to1[0][11] = 1.29781996051951;
   fWeightMatrix0to1[1][11] = -2.95515519963546;
   fWeightMatrix0to1[2][11] = 1.82202702920258;
   fWeightMatrix0to1[3][11] = 0.757842599314415;
   fWeightMatrix0to1[4][11] = 1.58428834107256;
   fWeightMatrix0to1[5][11] = -0.842779584849658;
   fWeightMatrix0to1[6][11] = -0.00725932030191606;
   fWeightMatrix0to1[7][11] = -1.31080148317857;
   fWeightMatrix0to1[8][11] = 0.894214250531315;
   fWeightMatrix0to1[9][11] = -1.17572491261732;
   fWeightMatrix0to1[10][11] = -3.87288374972366;
   // weight matrix from layer 1 to 2
   fWeightMatrix1to2[0][0] = -2.74074496658114;
   fWeightMatrix1to2[1][0] = -1.49449542196891;
   fWeightMatrix1to2[2][0] = -1.37246537290708;
   fWeightMatrix1to2[3][0] = 1.90594325808274;
   fWeightMatrix1to2[4][0] = 2.08122718997518;
   fWeightMatrix1to2[5][0] = -2.88047643854572;
   fWeightMatrix1to2[6][0] = -1.40744160192641;
   fWeightMatrix1to2[7][0] = 6.21276109451266;
   fWeightMatrix1to2[8][0] = 6.2937954646112;
   fWeightMatrix1to2[9][0] = -1.87119507798574;
   fWeightMatrix1to2[10][0] = -2.85835199187131;
   fWeightMatrix1to2[0][1] = 1.039869519834;
   fWeightMatrix1to2[1][1] = -0.701530906813077;
   fWeightMatrix1to2[2][1] = 1.64686700118795;
   fWeightMatrix1to2[3][1] = -0.933848066652459;
   fWeightMatrix1to2[4][1] = -4.29498759575448;
   fWeightMatrix1to2[5][1] = -0.845978786522134;
   fWeightMatrix1to2[6][1] = -0.621129783868999;
   fWeightMatrix1to2[7][1] = -4.79977878825358;
   fWeightMatrix1to2[8][1] = -1.63884783879413;
   fWeightMatrix1to2[9][1] = 2.27834380151543;
   fWeightMatrix1to2[10][1] = -0.649685278146749;
   fWeightMatrix1to2[0][2] = -0.269210609061865;
   fWeightMatrix1to2[1][2] = -0.114570780846591;
   fWeightMatrix1to2[2][2] = 0.548495230701847;
   fWeightMatrix1to2[3][2] = 2.96749098779916;
   fWeightMatrix1to2[4][2] = 3.90341453581095;
   fWeightMatrix1to2[5][2] = -3.2406491878549;
   fWeightMatrix1to2[6][2] = 0.454906358258627;
   fWeightMatrix1to2[7][2] = 1.44416931672463;
   fWeightMatrix1to2[8][2] = 3.1839228263063;
   fWeightMatrix1to2[9][2] = -2.62652439831193;
   fWeightMatrix1to2[10][2] = 0.391268382769219;
   fWeightMatrix1to2[0][3] = -2.03858914407889;
   fWeightMatrix1to2[1][3] = -0.959389446358285;
   fWeightMatrix1to2[2][3] = 1.83030843429628;
   fWeightMatrix1to2[3][3] = 2.17012542965984;
   fWeightMatrix1to2[4][3] = -1.5297489231346;
   fWeightMatrix1to2[5][3] = 2.47669238845314;
   fWeightMatrix1to2[6][3] = 1.17534271517087;
   fWeightMatrix1to2[7][3] = -1.81964899007292;
   fWeightMatrix1to2[8][3] = 4.29146170260937;
   fWeightMatrix1to2[9][3] = 4.24369875894871;
   fWeightMatrix1to2[10][3] = -3.68142332246533;
   fWeightMatrix1to2[0][4] = 0.709238702001485;
   fWeightMatrix1to2[1][4] = -0.410731238878792;
   fWeightMatrix1to2[2][4] = 1.72074542090367;
   fWeightMatrix1to2[3][4] = -2.18807632038183;
   fWeightMatrix1to2[4][4] = -0.196469839688097;
   fWeightMatrix1to2[5][4] = -0.00550844439459862;
   fWeightMatrix1to2[6][4] = 2.66430852691986;
   fWeightMatrix1to2[7][4] = -1.04741169635892;
   fWeightMatrix1to2[8][4] = -1.35865340708679;
   fWeightMatrix1to2[9][4] = -1.25690982721716;
   fWeightMatrix1to2[10][4] = 1.06697303759908;
   fWeightMatrix1to2[0][5] = 5.76795100429319;
   fWeightMatrix1to2[1][5] = -0.703358157588886;
   fWeightMatrix1to2[2][5] = -0.841650110114721;
   fWeightMatrix1to2[3][5] = -0.862287264194301;
   fWeightMatrix1to2[4][5] = -0.255269812297476;
   fWeightMatrix1to2[5][5] = 1.56528349042046;
   fWeightMatrix1to2[6][5] = 1.62212169601638;
   fWeightMatrix1to2[7][5] = -1.84369851641852;
   fWeightMatrix1to2[8][5] = 0.0962113422253831;
   fWeightMatrix1to2[9][5] = -3.61587908812189;
   fWeightMatrix1to2[10][5] = -0.36242827758751;
   fWeightMatrix1to2[0][6] = 2.07205604638627;
   fWeightMatrix1to2[1][6] = -1.30752562339998;
   fWeightMatrix1to2[2][6] = -0.415300425718465;
   fWeightMatrix1to2[3][6] = 0.328869359237194;
   fWeightMatrix1to2[4][6] = 3.67993850171258;
   fWeightMatrix1to2[5][6] = -1.23550789788539;
   fWeightMatrix1to2[6][6] = -0.537546150965228;
   fWeightMatrix1to2[7][6] = 0.0268610622466748;
   fWeightMatrix1to2[8][6] = 1.98510712102559;
   fWeightMatrix1to2[9][6] = 0.296944851588225;
   fWeightMatrix1to2[10][6] = 0.974562946504032;
   fWeightMatrix1to2[0][7] = 0.943710999258276;
   fWeightMatrix1to2[1][7] = 0.616194295896803;
   fWeightMatrix1to2[2][7] = -0.0948928568200842;
   fWeightMatrix1to2[3][7] = -2.04974996354172;
   fWeightMatrix1to2[4][7] = -0.980895336505691;
   fWeightMatrix1to2[5][7] = 1.90911783263284;
   fWeightMatrix1to2[6][7] = 1.09306852805164;
   fWeightMatrix1to2[7][7] = 0.759099681852393;
   fWeightMatrix1to2[8][7] = -0.175061413777496;
   fWeightMatrix1to2[9][7] = 2.10482203405269;
   fWeightMatrix1to2[10][7] = -1.72303755803094;
   fWeightMatrix1to2[0][8] = -4.13227864074902;
   fWeightMatrix1to2[1][8] = 0.921845920715356;
   fWeightMatrix1to2[2][8] = -1.38812940435061;
   fWeightMatrix1to2[3][8] = -2.4348927272416;
   fWeightMatrix1to2[4][8] = 3.34242722801496;
   fWeightMatrix1to2[5][8] = -0.497882093438129;
   fWeightMatrix1to2[6][8] = 3.81021345881129;
   fWeightMatrix1to2[7][8] = 0.379372988045119;
   fWeightMatrix1to2[8][8] = -4.12509515271735;
   fWeightMatrix1to2[9][8] = -0.240898581168286;
   fWeightMatrix1to2[10][8] = 0.195635513952089;
   fWeightMatrix1to2[0][9] = -2.38478581138675;
   fWeightMatrix1to2[1][9] = 2.56060053835996;
   fWeightMatrix1to2[2][9] = 1.91835400683071;
   fWeightMatrix1to2[3][9] = 0.509424761735158;
   fWeightMatrix1to2[4][9] = -3.09408064857997;
   fWeightMatrix1to2[5][9] = 1.18890280024048;
   fWeightMatrix1to2[6][9] = 0.628313764548428;
   fWeightMatrix1to2[7][9] = -1.5325557643253;
   fWeightMatrix1to2[8][9] = -4.03460527389676;
   fWeightMatrix1to2[9][9] = -4.07423277428358;
   fWeightMatrix1to2[10][9] = -0.210515413530456;
   fWeightMatrix1to2[0][10] = -2.66765536932271;
   fWeightMatrix1to2[1][10] = -2.305063858615;
   fWeightMatrix1to2[2][10] = -2.11465889726953;
   fWeightMatrix1to2[3][10] = -0.854218675579465;
   fWeightMatrix1to2[4][10] = -4.43774719546027;
   fWeightMatrix1to2[5][10] = -1.54025125379181;
   fWeightMatrix1to2[6][10] = 4.20196510506802;
   fWeightMatrix1to2[7][10] = -2.2532098686032;
   fWeightMatrix1to2[8][10] = -2.48301669237291;
   fWeightMatrix1to2[9][10] = -1.90069040763445;
   fWeightMatrix1to2[10][10] = -0.52179579688067;
   fWeightMatrix1to2[0][11] = 2.46744716438756;
   fWeightMatrix1to2[1][11] = 1.26427237200976;
   fWeightMatrix1to2[2][11] = -0.679714663081142;
   fWeightMatrix1to2[3][11] = -1.45699483178493;
   fWeightMatrix1to2[4][11] = -1.00649507752385;
   fWeightMatrix1to2[5][11] = -1.95565746015062;
   fWeightMatrix1to2[6][11] = -1.64855952380958;
   fWeightMatrix1to2[7][11] = 0.617968843185379;
   fWeightMatrix1to2[8][11] = -0.836268718405668;
   fWeightMatrix1to2[9][11] = 0.55735020524707;
   fWeightMatrix1to2[10][11] = -0.411540796396968;
   // weight matrix from layer 2 to 3
   fWeightMatrix2to3[0][0] = -0.568457632277826;
   fWeightMatrix2to3[1][0] = -2.80593881565214;
   fWeightMatrix2to3[2][0] = -5.1041582219527;
   fWeightMatrix2to3[3][0] = 0.136716251434423;
   fWeightMatrix2to3[4][0] = 2.67860076252527;
   fWeightMatrix2to3[5][0] = -3.19704256359213;
   fWeightMatrix2to3[6][0] = -3.09565229942279;
   fWeightMatrix2to3[7][0] = 0.60594507062768;
   fWeightMatrix2to3[8][0] = -0.0781306348290443;
   fWeightMatrix2to3[9][0] = 0.967519498079343;
   fWeightMatrix2to3[10][0] = 0.218312515134032;
   fWeightMatrix2to3[11][0] = -1.65939246898633;
   fWeightMatrix2to3[0][1] = 1.15901851625957;
   fWeightMatrix2to3[1][1] = 1.29522708609662;
   fWeightMatrix2to3[2][1] = 0.601422655287771;
   fWeightMatrix2to3[3][1] = -0.551404755742277;
   fWeightMatrix2to3[4][1] = -0.331295638125883;
   fWeightMatrix2to3[5][1] = -1.07004425960322;
   fWeightMatrix2to3[6][1] = -2.21427796842203;
   fWeightMatrix2to3[7][1] = -0.540681432442049;
   fWeightMatrix2to3[8][1] = -1.74318119149375;
   fWeightMatrix2to3[9][1] = -1.30185052220611;
   fWeightMatrix2to3[10][1] = -2.4470413865857;
   fWeightMatrix2to3[11][1] = 1.15715640377407;
   fWeightMatrix2to3[0][2] = -2.25941469565399;
   fWeightMatrix2to3[1][2] = 1.25091374252203;
   fWeightMatrix2to3[2][2] = -2.16813831148734;
   fWeightMatrix2to3[3][2] = 0.792101727074727;
   fWeightMatrix2to3[4][2] = 0.5426358291233;
   fWeightMatrix2to3[5][2] = -0.186005794505024;
   fWeightMatrix2to3[6][2] = 0.695158856307996;
   fWeightMatrix2to3[7][2] = -2.10300024869483;
   fWeightMatrix2to3[8][2] = -0.0452248358213677;
   fWeightMatrix2to3[9][2] = 1.06876569888704;
   fWeightMatrix2to3[10][2] = -2.53685972016499;
   fWeightMatrix2to3[11][2] = -2.6606275685198;
   fWeightMatrix2to3[0][3] = -2.21400647858681;
   fWeightMatrix2to3[1][3] = -1.17449726509626;
   fWeightMatrix2to3[2][3] = 2.91281944644687;
   fWeightMatrix2to3[3][3] = -1.08333982385513;
   fWeightMatrix2to3[4][3] = 0.845178282632878;
   fWeightMatrix2to3[5][3] = -0.785093966466213;
   fWeightMatrix2to3[6][3] = -1.34013542203912;
   fWeightMatrix2to3[7][3] = -1.75718311336358;
   fWeightMatrix2to3[8][3] = -1.66308042947222;
   fWeightMatrix2to3[9][3] = -1.28421189886934;
   fWeightMatrix2to3[10][3] = 1.46402130588705;
   fWeightMatrix2to3[11][3] = -1.46006613900448;
   fWeightMatrix2to3[0][4] = -2.63726265324544;
   fWeightMatrix2to3[1][4] = 0.367542432538058;
   fWeightMatrix2to3[2][4] = 1.527289469374;
   fWeightMatrix2to3[3][4] = -1.93471414967649;
   fWeightMatrix2to3[4][4] = 1.47803513154847;
   fWeightMatrix2to3[5][4] = -2.54066298631619;
   fWeightMatrix2to3[6][4] = 0.6891993955874;
   fWeightMatrix2to3[7][4] = 0.809226438240743;
   fWeightMatrix2to3[8][4] = -1.68944338227671;
   fWeightMatrix2to3[9][4] = -0.571794834334166;
   fWeightMatrix2to3[10][4] = 0.658699581459856;
   fWeightMatrix2to3[11][4] = -2.59972176758721;
   fWeightMatrix2to3[0][5] = 0.44406525472092;
   fWeightMatrix2to3[1][5] = 2.23246431059568;
   fWeightMatrix2to3[2][5] = 0.856272724777257;
   fWeightMatrix2to3[3][5] = 2.07384506719014;
   fWeightMatrix2to3[4][5] = -1.85475769650831;
   fWeightMatrix2to3[5][5] = 1.37208326240177;
   fWeightMatrix2to3[6][5] = -1.95437528808959;
   fWeightMatrix2to3[7][5] = 0.655776879370403;
   fWeightMatrix2to3[8][5] = -1.70303306844337;
   fWeightMatrix2to3[9][5] = -1.89611786999299;
   fWeightMatrix2to3[10][5] = -0.225845951658246;
   fWeightMatrix2to3[11][5] = 1.24917689879353;
   fWeightMatrix2to3[0][6] = 0.402573160850399;
   fWeightMatrix2to3[1][6] = -0.0613149468524594;
   fWeightMatrix2to3[2][6] = -0.198483071497155;
   fWeightMatrix2to3[3][6] = -0.354759391943461;
   fWeightMatrix2to3[4][6] = -4.22892334190304;
   fWeightMatrix2to3[5][6] = 0.299626181774308;
   fWeightMatrix2to3[6][6] = 0.669743293736589;
   fWeightMatrix2to3[7][6] = -1.61989831122954;
   fWeightMatrix2to3[8][6] = -0.967488380345367;
   fWeightMatrix2to3[9][6] = -1.74323403375625;
   fWeightMatrix2to3[10][6] = -2.45910917906703;
   fWeightMatrix2to3[11][6] = -0.159568387791808;
   fWeightMatrix2to3[0][7] = -0.892118007672557;
   fWeightMatrix2to3[1][7] = -2.78851174024722;
   fWeightMatrix2to3[2][7] = 3.3107437608969;
   fWeightMatrix2to3[3][7] = 0.962931289452009;
   fWeightMatrix2to3[4][7] = -0.0829727614091524;
   fWeightMatrix2to3[5][7] = -1.39012855923056;
   fWeightMatrix2to3[6][7] = -0.395751169124699;
   fWeightMatrix2to3[7][7] = -1.45212338384354;
   fWeightMatrix2to3[8][7] = -1.89153028285859;
   fWeightMatrix2to3[9][7] = 0.886048865241426;
   fWeightMatrix2to3[10][7] = 1.29568445175483;
   fWeightMatrix2to3[11][7] = -2.1880056778481;
   fWeightMatrix2to3[0][8] = -0.146367737462065;
   fWeightMatrix2to3[1][8] = -4.0201756865572;
   fWeightMatrix2to3[2][8] = -0.441879148455184;
   fWeightMatrix2to3[3][8] = -2.22014687276524;
   fWeightMatrix2to3[4][8] = 0.0648081084014904;
   fWeightMatrix2to3[5][8] = -3.48170726423563;
   fWeightMatrix2to3[6][8] = -2.2258624586025;
   fWeightMatrix2to3[7][8] = -0.664602549436165;
   fWeightMatrix2to3[8][8] = -1.53402282531578;
   fWeightMatrix2to3[9][8] = -1.6629314570128;
   fWeightMatrix2to3[10][8] = 2.78425639583501;
   fWeightMatrix2to3[11][8] = -1.62510221146879;
   fWeightMatrix2to3[0][9] = -1.90636932860696;
   fWeightMatrix2to3[1][9] = 2.5543430934325;
   fWeightMatrix2to3[2][9] = 0.021974610393041;
   fWeightMatrix2to3[3][9] = 0.766964479970346;
   fWeightMatrix2to3[4][9] = -0.294090694484781;
   fWeightMatrix2to3[5][9] = 2.3239976861153;
   fWeightMatrix2to3[6][9] = 3.08294326517194;
   fWeightMatrix2to3[7][9] = 0.68574583613052;
   fWeightMatrix2to3[8][9] = -0.81031211881262;
   fWeightMatrix2to3[9][9] = -0.892828190484845;
   fWeightMatrix2to3[10][9] = -1.19761261799117;
   fWeightMatrix2to3[11][9] = 0.999339449117062;
   fWeightMatrix2to3[0][10] = 0.173581566166199;
   fWeightMatrix2to3[1][10] = -2.0555571176309;
   fWeightMatrix2to3[2][10] = -0.575443182209862;
   fWeightMatrix2to3[3][10] = -0.385898846501114;
   fWeightMatrix2to3[4][10] = 0.44145868280257;
   fWeightMatrix2to3[5][10] = -2.12524998004018;
   fWeightMatrix2to3[6][10] = 0.564527519035355;
   fWeightMatrix2to3[7][10] = 0.715153149374003;
   fWeightMatrix2to3[8][10] = -2.79513200818146;
   fWeightMatrix2to3[9][10] = -0.20069738711934;
   fWeightMatrix2to3[10][10] = -2.25172227684295;
   fWeightMatrix2to3[11][10] = 0.354896653430283;
   fWeightMatrix2to3[0][11] = 0.377525185850745;
   fWeightMatrix2to3[1][11] = -0.557861033681215;
   fWeightMatrix2to3[2][11] = 0.0115374621431919;
   fWeightMatrix2to3[3][11] = -0.91797993108708;
   fWeightMatrix2to3[4][11] = -0.424604536576128;
   fWeightMatrix2to3[5][11] = 1.79470344788473;
   fWeightMatrix2to3[6][11] = -0.689523585962363;
   fWeightMatrix2to3[7][11] = -1.24678896469671;
   fWeightMatrix2to3[8][11] = 0.0963109052146767;
   fWeightMatrix2to3[9][11] = -1.98787335457614;
   fWeightMatrix2to3[10][11] = -1.13235389223817;
   fWeightMatrix2to3[11][11] = 1.41730483551497;
   // weight matrix from layer 3 to 4
   fWeightMatrix3to4[0][0] = -2.15895309334421;
   fWeightMatrix3to4[0][1] = -3.34418689064491;
   fWeightMatrix3to4[0][2] = 1.82309188759928;
   fWeightMatrix3to4[0][3] = -1.15507620241227;
   fWeightMatrix3to4[0][4] = 1.52808938537937;
   fWeightMatrix3to4[0][5] = -3.30151244497105;
   fWeightMatrix3to4[0][6] = -2.54849218187681;
   fWeightMatrix3to4[0][7] = -0.653845977356494;
   fWeightMatrix3to4[0][8] = -0.506816570513931;
   fWeightMatrix3to4[0][9] = 1.2918016273773;
   fWeightMatrix3to4[0][10] = 1.89991661395967;
   fWeightMatrix3to4[0][11] = -1.72359751504163;
   fWeightMatrix3to4[0][12] = 0.0848713181341314;
}

inline double ReadMLP_ANN_N1_NC1000::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   if (inputValues.size() != (unsigned int)fLayerSize[0]-1) {
      std::cout << "Input vector needs to be of size " << fLayerSize[0]-1 << std::endl;
      return 0;
   }

   for (int l=0; l<fLayers; l++)
      for (int i=0; i<fLayerSize[l]; i++) fWeights[l][i]=0;

   for (int l=0; l<fLayers-1; l++)
      fWeights[l][fLayerSize[l]-1]=1;

   for (int i=0; i<fLayerSize[0]-1; i++)
      fWeights[0][i]=inputValues[i];

   // layer 0 to 1
   for (int o=0; o<fLayerSize[1]-1; o++) {
      for (int i=0; i<fLayerSize[0]; i++) {
         double inputVal = fWeightMatrix0to1[o][i] * fWeights[0][i];
         fWeights[1][o] += inputVal;
      }
      fWeights[1][o] = ActivationFnc(fWeights[1][o]);
   }
   // layer 1 to 2
   for (int o=0; o<fLayerSize[2]-1; o++) {
      for (int i=0; i<fLayerSize[1]; i++) {
         double inputVal = fWeightMatrix1to2[o][i] * fWeights[1][i];
         fWeights[2][o] += inputVal;
      }
      fWeights[2][o] = ActivationFnc(fWeights[2][o]);
   }
   // layer 2 to 3
   for (int o=0; o<fLayerSize[3]-1; o++) {
      for (int i=0; i<fLayerSize[2]; i++) {
         double inputVal = fWeightMatrix2to3[o][i] * fWeights[2][i];
         fWeights[3][o] += inputVal;
      }
      fWeights[3][o] = ActivationFnc(fWeights[3][o]);
   }
   // layer 3 to 4
   for (int o=0; o<fLayerSize[4]; o++) {
      for (int i=0; i<fLayerSize[3]; i++) {
         double inputVal = fWeightMatrix3to4[o][i] * fWeights[3][i];
         fWeights[4][o] += inputVal;
      }
      fWeights[4][o] = OutputActivationFnc(fWeights[4][o]);
   }

   return fWeights[4][0];
}

double ReadMLP_ANN_N1_NC1000::ActivationFnc(double x) const {
   // sigmoid
   return 1.0/(1.0+exp(-x));
}
double ReadMLP_ANN_N1_NC1000::OutputActivationFnc(double x) const {
   // sigmoid
   return 1.0/(1.0+exp(-x));
}
   
// Clean up
inline void ReadMLP_ANN_N1_NC1000::Clear() 
{
   // clean up the arrays
   for (int lIdx = 0; lIdx < 5; lIdx++) {
      delete[] fWeights[lIdx];
   }
}
   inline double ReadMLP_ANN_N1_NC1000::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            iV.reserve(inputValues.size());
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
         else {
            std::vector<double> iV;
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(*varIt);
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
      }

      return retval;
   }

//_______________________________________________________________________
inline void ReadMLP_ANN_N1_NC1000::InitTransform_1()
{
   // Normalization transformation, initialisation
   fMin_1[0][0] = 110.048698425;
   fMax_1[0][0] = 1277.92980957;
   fMin_1[1][0] = 110.057556152;
   fMax_1[1][0] = 1572.76037598;
   fMin_1[2][0] = 110.048698425;
   fMax_1[2][0] = 1572.76037598;
   fMin_1[0][1] = 5.00075817108;
   fMax_1[0][1] = 29.9497737885;
   fMin_1[1][1] = 5.00135278702;
   fMax_1[1][1] = 29.9984378815;
   fMin_1[2][1] = 5.00075817108;
   fMax_1[2][1] = 29.9984378815;
   fMin_1[0][2] = -1;
   fMax_1[0][2] = 1;
   fMin_1[1][2] = -1;
   fMax_1[1][2] = 1;
   fMin_1[2][2] = -1;
   fMax_1[2][2] = 1;
   fMin_1[0][3] = -2.4711689949;
   fMax_1[0][3] = 2.37911462784;
   fMin_1[1][3] = -2.48411560059;
   fMax_1[1][3] = 2.49880051613;
   fMin_1[2][3] = -2.48411560059;
   fMax_1[2][3] = 2.49880051613;
   fMin_1[0][4] = 280.2293396;
   fMax_1[0][4] = 1251.49438477;
   fMin_1[1][4] = 280.020294189;
   fMax_1[1][4] = 1289.47937012;
   fMin_1[2][4] = 280.020294189;
   fMax_1[2][4] = 1289.47937012;
   fMin_1[0][5] = 0.0557334087789;
   fMax_1[0][5] = 300.527191162;
   fMin_1[1][5] = 0.000537815736607;
   fMax_1[1][5] = 215.792510986;
   fMin_1[2][5] = 0.000537815736607;
   fMax_1[2][5] = 300.527191162;
   fMin_1[0][6] = 117.352531433;
   fMax_1[0][6] = 2347.48510742;
   fMin_1[1][6] = 112.003395081;
   fMax_1[1][6] = 4504.87304688;
   fMin_1[2][6] = 112.003395081;
   fMax_1[2][6] = 4504.87304688;
   fMin_1[0][7] = 0;
   fMax_1[0][7] = 5;
   fMin_1[1][7] = 0;
   fMax_1[1][7] = 6;
   fMin_1[2][7] = 0;
   fMax_1[2][7] = 6;
   fMin_1[0][8] = 1;
   fMax_1[0][8] = 11;
   fMin_1[1][8] = 1;
   fMax_1[1][8] = 14;
   fMin_1[2][8] = 1;
   fMax_1[2][8] = 14;
   fMin_1[0][9] = 20.0573444366;
   fMax_1[0][9] = 1057.04370117;
   fMin_1[1][9] = -999;
   fMax_1[1][9] = 1378.42883301;
   fMin_1[2][9] = -999;
   fMax_1[2][9] = 1378.42883301;
   fMin_1[0][10] = 6.27087429166e-05;
   fMax_1[0][10] = 4.95768356323;
   fMin_1[1][10] = -999;
   fMax_1[1][10] = 5.38026332855;
   fMin_1[2][10] = -999;
   fMax_1[2][10] = 5.38026332855;
}

//_______________________________________________________________________
inline void ReadMLP_ANN_N1_NC1000::Transform_1( std::vector<double>& iv, int cls) const
{
   // Normalization transformation
   if (cls < 0 || cls > 2) {
   if (2 > 1 ) cls = 2;
      else cls = 2;
   }
   const int nVar = 11;

   // get indices of used variables

   // define the indices of the variables which are transformed by this transformation
   static std::vector<int> indicesGet;
   static std::vector<int> indicesPut;

   if ( indicesGet.empty() ) { 
      indicesGet.reserve(fNvars);
      indicesGet.push_back( 0);
      indicesGet.push_back( 1);
      indicesGet.push_back( 2);
      indicesGet.push_back( 3);
      indicesGet.push_back( 4);
      indicesGet.push_back( 5);
      indicesGet.push_back( 6);
      indicesGet.push_back( 7);
      indicesGet.push_back( 8);
      indicesGet.push_back( 9);
      indicesGet.push_back( 10);
   } 
   if ( indicesPut.empty() ) { 
      indicesPut.reserve(fNvars);
      indicesPut.push_back( 0);
      indicesPut.push_back( 1);
      indicesPut.push_back( 2);
      indicesPut.push_back( 3);
      indicesPut.push_back( 4);
      indicesPut.push_back( 5);
      indicesPut.push_back( 6);
      indicesPut.push_back( 7);
      indicesPut.push_back( 8);
      indicesPut.push_back( 9);
      indicesPut.push_back( 10);
   } 

   static std::vector<double> dv;
   dv.resize(nVar);
   for (int ivar=0; ivar<nVar; ivar++) dv[ivar] = iv[indicesGet.at(ivar)];
   for (int ivar=0;ivar<11;ivar++) {
      double offset = fMin_1[cls][ivar];
      double scale  = 1.0/(fMax_1[cls][ivar]-fMin_1[cls][ivar]);
      iv[indicesPut.at(ivar)] = (dv[ivar]-offset)*scale * 2 - 1;
   }
}

//_______________________________________________________________________
inline void ReadMLP_ANN_N1_NC1000::InitTransform()
{
   InitTransform_1();
}

//_______________________________________________________________________
inline void ReadMLP_ANN_N1_NC1000::Transform( std::vector<double>& iv, int sigOrBgd ) const
{
   Transform_1( iv, sigOrBgd );
}
