// Class: ReadMLP_ANN_N-4_NC400
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : MLP::MLP_ANN_N-4_NC400
TMVA Release   : 4.2.1         [262657]
ROOT Release   : 6.06/01       [394753]
Creator        : brucms16
Date           : Tue Sep  6 22:19:31 2016
Host           : Linux vocms0315.cern.ch 2.6.32-573.26.1.el6.x86_64 #1 SMP Wed May 4 09:23:05 CEST 2016 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /home/t3cms/brucms16/CMSSW_8_0_14/src/UserCode/SkeletonAnalysis/macros
Training events: 15056
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
NCycles: "400" [Number of training cycles]
HiddenLayers: "N,N,N+-4" [Specification of hidden layer architecture]
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
VarTransform: "Norm" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
H: "False" [Print method-specific help message]
LearningRate: "9.000000e-02" [ANN learning rate parameter]
DecayRate: "1.000000e-02" [Decay rate for learning parameter]
# Default:
NeuronType: "sigmoid" [Neuron activation function type]
RandomSeed: "1" [Random seed for initial synapse weights (0 means unique seed for each run; default value '1')]
EstimatorType: "CE" [MSE (Mean Square Estimator) for Gaussian Likelihood or CE(Cross-Entropy) for Bernoulli Likelihood]
NeuronInputType: "sum" [Neuron input function type]
VerbosityLevel: "Default" [Verbosity level]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
TrainingMethod: "BP" [Train with Back-Propagation (BP), BFGS Algorithm (BFGS), or Genetic Algorithm (GA - slower and worse)]
TestRate: "10" [Test for overtraining performed at each #th epochs]
EpochMonitoring: "False" [Provide epoch-wise monitoring plots according to TestRate (caution: causes big ROOT output file!)]
Sampling: "1.000000e+00" [Only 'Sampling' (randomly selected) events are trained each epoch]
SamplingEpoch: "1.000000e+00" [Sampling is used for the first 'SamplingEpoch' epochs, afterwards, all events are taken for training]
SamplingImportance: "1.000000e+00" [ The sampling weights of events in epochs which successful (worse estimator than before) are multiplied with SamplingImportance, else they are divided.]
SamplingTraining: "True" [The training sample is sampled]
SamplingTesting: "False" [The testing sample is sampled]
ResetStep: "50" [How often BFGS should reset history]
Tau: "3.000000e+00" [LineSearch "size step"]
BPMode: "sequential" [Back-propagation learning mode: sequential or batch]
BatchSize: "-1" [Batch size: number of events/batch, only set if in Batch Mode, -1 for BatchSize=number_of_events]
ConvergenceImprove: "1.000000e-30" [Minimum improvement which counts as improvement (<0 means automatic convergence check is turned off)]
ConvergenceTests: "-1" [Number of steps (without improvement) required for convergence (<0 means automatic convergence check is turned off)]
UseRegulator: "False" [Use regulator to avoid over-training]
UpdateLimit: "10000" [Maximum times of regulator update]
CalculateErrors: "False" [Calculates inverse Hessian matrix at the end of the training to be able to calculate the uncertainties of an MVA value]
WeightRange: "1.000000e+00" [Take the events for the estimator calculations from small deviations from the desired value to large deviations only over the weight range]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 11
Jet1Pt                        Jet1Pt                        Jet1Pt                        Jet1Pt                                                          'F'    [110.048698425,1572.76037598]
LepPt                         LepPt                         LepPt                         LepPt                                                           'F'    [5.00075817108,29.9984378815]
LepChg                        LepChg                        LepChg                        LepChg                                                          'F'    [-1,1]
LepEta                        LepEta                        LepEta                        LepEta                                                          'F'    [-2.48411560059,2.49880051613]
Met                           Met                           Met                           Met                                                             'F'    [280.020294189,1289.47937012]
mt                            mt                            mt                            mt                                                              'F'    [0.000537815736607,300.527191162]
HT20                          HT20                          HT20                          HT20                                                            'F'    [112.003395081,4504.87304688]
NbLoose30                     NbLoose30                     NbLoose30                     NbLoose30                                                       'F'    [0,6]
Njet                          Njet                          Njet                          Njet                                                            'F'    [1,14]
JetHBpt                       JetHBpt                       JetHBpt                       JetHBpt                                                         'F'    [-999,1378.42883301]
DrJetHBLep                    DrJetHBLep                    DrJetHBLep                    DrJetHBLep                                                      'F'    [-999,5.38026332855]
NSpec 0


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadMLP_ANN_N-4_NC400 : public IClassifierReader {

 public:

   // constructor
   ReadMLP_ANN_N-4_NC400( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadMLP_ANN_N-4_NC400" ),
        fNvars( 11 ),
        fIsNormalised( false )
   {      
      // the training input variables
      const char* inputVars[] = { "Jet1Pt", "LepPt", "LepChg", "LepEta", "Met", "mt", "HT20", "NbLoose30", "Njet", "JetHBpt", "DrJetHBLep" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = -1;
      fVmax[0] = 1;
      fVmin[1] = -1;
      fVmax[1] = 0.99999988079071;
      fVmin[2] = -1;
      fVmax[2] = 1;
      fVmin[3] = -1;
      fVmax[3] = 1;
      fVmin[4] = -1;
      fVmax[4] = 1;
      fVmin[5] = -1;
      fVmax[5] = 1;
      fVmin[6] = -1;
      fVmax[6] = 1;
      fVmin[7] = -1;
      fVmax[7] = 1;
      fVmin[8] = -1;
      fVmax[8] = 1;
      fVmin[9] = -1;
      fVmax[9] = 1;
      fVmin[10] = -1;
      fVmax[10] = 1;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';
      fType[4] = 'F';
      fType[5] = 'F';
      fType[6] = 'F';
      fType[7] = 'F';
      fType[8] = 'F';
      fType[9] = 'F';
      fType[10] = 'F';

      // initialize constants
      Initialize();

      // initialize transformation
      InitTransform();
   }

   // destructor
   virtual ~ReadMLP_ANN_N-4_NC400() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // input variable transformation

   double fMin_1[3][11];
   double fMax_1[3][11];
   void InitTransform_1();
   void Transform_1( std::vector<double> & iv, int sigOrBgd ) const;
   void InitTransform();
   void Transform( std::vector<double> & iv, int sigOrBgd ) const;

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[11];
   double fVmax[11];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[11];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)

   double ActivationFnc(double x) const;
   double OutputActivationFnc(double x) const;

   int fLayers;
   int fLayerSize[5];
   double fWeightMatrix0to1[12][12];   // weight matrix from layer 0 to 1
   double fWeightMatrix1to2[12][12];   // weight matrix from layer 1 to 2
   double fWeightMatrix2to3[12][12];   // weight matrix from layer 2 to 3
   double fWeightMatrix3to4[1][12];   // weight matrix from layer 3 to 4

   double * fWeights[5];
};

inline void ReadMLP_ANN_N-4_NC400::Initialize()
{
   // build network structure
   fLayers = 5;
   fLayerSize[0] = 12; fWeights[0] = new double[12]; 
   fLayerSize[1] = 12; fWeights[1] = new double[12]; 
   fLayerSize[2] = 12; fWeights[2] = new double[12]; 
   fLayerSize[3] = 12; fWeights[3] = new double[12]; 
   fLayerSize[4] = 1; fWeights[4] = new double[1]; 
   // weight matrix from layer 0 to 1
   fWeightMatrix0to1[0][0] = 0.900811039294019;
   fWeightMatrix0to1[1][0] = 2.02566117788814;
   fWeightMatrix0to1[2][0] = 4.15900453579885;
   fWeightMatrix0to1[3][0] = -0.0813220120010151;
   fWeightMatrix0to1[4][0] = -0.23603980651404;
   fWeightMatrix0to1[5][0] = -1.65952737814296;
   fWeightMatrix0to1[6][0] = -3.29218967665255;
   fWeightMatrix0to1[7][0] = 1.96195097700449;
   fWeightMatrix0to1[8][0] = 0.507877322206457;
   fWeightMatrix0to1[9][0] = 0.167798528351214;
   fWeightMatrix0to1[10][0] = -1.7535609506982;
   fWeightMatrix0to1[0][1] = 1.64075957310873;
   fWeightMatrix0to1[1][1] = -2.09553237724748;
   fWeightMatrix0to1[2][1] = 0.0402213938924065;
   fWeightMatrix0to1[3][1] = 0.251100591821478;
   fWeightMatrix0to1[4][1] = 1.7618352935901;
   fWeightMatrix0to1[5][1] = -0.728044480334402;
   fWeightMatrix0to1[6][1] = 5.53323676990769;
   fWeightMatrix0to1[7][1] = 0.167757909410403;
   fWeightMatrix0to1[8][1] = 2.68171101157162;
   fWeightMatrix0to1[9][1] = 2.89270431915652;
   fWeightMatrix0to1[10][1] = -2.11930496595856;
   fWeightMatrix0to1[0][2] = 0.943830922627782;
   fWeightMatrix0to1[1][2] = -1.0123299850742;
   fWeightMatrix0to1[2][2] = -0.510100061976127;
   fWeightMatrix0to1[3][2] = 0.261190422707999;
   fWeightMatrix0to1[4][2] = -1.13929011789364;
   fWeightMatrix0to1[5][2] = -3.0642463285561;
   fWeightMatrix0to1[6][2] = -0.573361700710247;
   fWeightMatrix0to1[7][2] = -0.174207832545757;
   fWeightMatrix0to1[8][2] = -0.335865650915026;
   fWeightMatrix0to1[9][2] = 1.85643063889498;
   fWeightMatrix0to1[10][2] = 0.79766089582767;
   fWeightMatrix0to1[0][3] = -1.33880780369848;
   fWeightMatrix0to1[1][3] = 2.65048441052028;
   fWeightMatrix0to1[2][3] = 0.395560409415047;
   fWeightMatrix0to1[3][3] = 0.145182262540348;
   fWeightMatrix0to1[4][3] = 8.51216434759431;
   fWeightMatrix0to1[5][3] = -0.179550209753802;
   fWeightMatrix0to1[6][3] = -1.02636118694036;
   fWeightMatrix0to1[7][3] = 0.701482665008384;
   fWeightMatrix0to1[8][3] = -2.04881179810835;
   fWeightMatrix0to1[9][3] = -0.331621652238142;
   fWeightMatrix0to1[10][3] = 0.27239415644354;
   fWeightMatrix0to1[0][4] = 5.12682035465549;
   fWeightMatrix0to1[1][4] = -0.217616885129652;
   fWeightMatrix0to1[2][4] = 4.46509881349075;
   fWeightMatrix0to1[3][4] = 2.00801639920408;
   fWeightMatrix0to1[4][4] = 0.0712732413380679;
   fWeightMatrix0to1[5][4] = -0.261675534194727;
   fWeightMatrix0to1[6][4] = -1.09347516758198;
   fWeightMatrix0to1[7][4] = 1.7407421720688;
   fWeightMatrix0to1[8][4] = -8.96690075712094;
   fWeightMatrix0to1[9][4] = 0.413983543709202;
   fWeightMatrix0to1[10][4] = -7.97568819587194;
   fWeightMatrix0to1[0][5] = -1.36452012838583;
   fWeightMatrix0to1[1][5] = -2.28489295116242;
   fWeightMatrix0to1[2][5] = -11.5490218777558;
   fWeightMatrix0to1[3][5] = 17.484043309226;
   fWeightMatrix0to1[4][5] = 0.659716687524989;
   fWeightMatrix0to1[5][5] = -2.6524929686395;
   fWeightMatrix0to1[6][5] = 0.891379442236961;
   fWeightMatrix0to1[7][5] = -0.454399684480838;
   fWeightMatrix0to1[8][5] = -1.54241397788904;
   fWeightMatrix0to1[9][5] = 2.97398209863056;
   fWeightMatrix0to1[10][5] = -2.75484386275427;
   fWeightMatrix0to1[0][6] = -1.17912714158962;
   fWeightMatrix0to1[1][6] = -1.48076778510846;
   fWeightMatrix0to1[2][6] = 0.919602806953894;
   fWeightMatrix0to1[3][6] = -4.3947463131836;
   fWeightMatrix0to1[4][6] = 0.685121491058366;
   fWeightMatrix0to1[5][6] = -1.51899597707676;
   fWeightMatrix0to1[6][6] = 1.5904866526813;
   fWeightMatrix0to1[7][6] = 1.01289760486223;
   fWeightMatrix0to1[8][6] = 6.41152374129144;
   fWeightMatrix0to1[9][6] = 0.792594403603965;
   fWeightMatrix0to1[10][6] = 2.34515052301082;
   fWeightMatrix0to1[0][7] = -6.35692201179914;
   fWeightMatrix0to1[1][7] = -0.883439956680014;
   fWeightMatrix0to1[2][7] = 1.12618509316597;
   fWeightMatrix0to1[3][7] = 0.76049301094322;
   fWeightMatrix0to1[4][7] = 0.0564389637656452;
   fWeightMatrix0to1[5][7] = 2.64244897338739;
   fWeightMatrix0to1[6][7] = -0.592672855390308;
   fWeightMatrix0to1[7][7] = -1.02181204785673;
   fWeightMatrix0to1[8][7] = 2.05597984869541;
   fWeightMatrix0to1[9][7] = 0.875267502184066;
   fWeightMatrix0to1[10][7] = 3.10305454187397;
   fWeightMatrix0to1[0][8] = -7.76937461185423;
   fWeightMatrix0to1[1][8] = -2.24839954463133;
   fWeightMatrix0to1[2][8] = 0.696230320056812;
   fWeightMatrix0to1[3][8] = -0.731761042392514;
   fWeightMatrix0to1[4][8] = 0.424258165238329;
   fWeightMatrix0to1[5][8] = -2.37837080122649;
   fWeightMatrix0to1[6][8] = -2.00941152001813;
   fWeightMatrix0to1[7][8] = 1.47482982339961;
   fWeightMatrix0to1[8][8] = 1.63627013625124;
   fWeightMatrix0to1[9][8] = -8.73133451760157;
   fWeightMatrix0to1[10][8] = -5.13861227073038;
   fWeightMatrix0to1[0][9] = -1.06237889834721;
   fWeightMatrix0to1[1][9] = -2.64407674405485;
   fWeightMatrix0to1[2][9] = -2.41862977228076;
   fWeightMatrix0to1[3][9] = -2.45029210308474;
   fWeightMatrix0to1[4][9] = -0.239150876846552;
   fWeightMatrix0to1[5][9] = -2.53088113043694;
   fWeightMatrix0to1[6][9] = -2.36824032489333;
   fWeightMatrix0to1[7][9] = -1.03827767740425;
   fWeightMatrix0to1[8][9] = 2.56745467127214;
   fWeightMatrix0to1[9][9] = -1.27268813527091;
   fWeightMatrix0to1[10][9] = 1.72749598670373;
   fWeightMatrix0to1[0][10] = -2.27325602545851;
   fWeightMatrix0to1[1][10] = 0.412956149142588;
   fWeightMatrix0to1[2][10] = 1.02972610386011;
   fWeightMatrix0to1[3][10] = 1.99712356103951;
   fWeightMatrix0to1[4][10] = -1.80296294583762;
   fWeightMatrix0to1[5][10] = 0.865429505959394;
   fWeightMatrix0to1[6][10] = -0.27746804676286;
   fWeightMatrix0to1[7][10] = -0.973907939086595;
   fWeightMatrix0to1[8][10] = -1.5947119156526;
   fWeightMatrix0to1[9][10] = -2.20649105257498;
   fWeightMatrix0to1[10][10] = -3.89467843474188;
   fWeightMatrix0to1[0][11] = -0.313490449345291;
   fWeightMatrix0to1[1][11] = -0.199784297793074;
   fWeightMatrix0to1[2][11] = 1.94516670582003;
   fWeightMatrix0to1[3][11] = 2.33279675824377;
   fWeightMatrix0to1[4][11] = -0.408658032312081;
   fWeightMatrix0to1[5][11] = -1.12666560355325;
   fWeightMatrix0to1[6][11] = -0.25701725692315;
   fWeightMatrix0to1[7][11] = -1.83257889783525;
   fWeightMatrix0to1[8][11] = -0.942492117986331;
   fWeightMatrix0to1[9][11] = -0.931290089731145;
   fWeightMatrix0to1[10][11] = -4.22280120484923;
   // weight matrix from layer 1 to 2
   fWeightMatrix1to2[0][0] = 0.37955982123245;
   fWeightMatrix1to2[1][0] = -1.19375739074144;
   fWeightMatrix1to2[2][0] = 1.68473868566419;
   fWeightMatrix1to2[3][0] = 1.13289766069115;
   fWeightMatrix1to2[4][0] = 4.14801400955681;
   fWeightMatrix1to2[5][0] = -1.9634164148905;
   fWeightMatrix1to2[6][0] = -0.719945459016091;
   fWeightMatrix1to2[7][0] = 4.98025536428597;
   fWeightMatrix1to2[8][0] = 3.32512778053931;
   fWeightMatrix1to2[9][0] = -0.0598503852004198;
   fWeightMatrix1to2[10][0] = -2.66765123903618;
   fWeightMatrix1to2[0][1] = -0.435428791078956;
   fWeightMatrix1to2[1][1] = -1.4138691486391;
   fWeightMatrix1to2[2][1] = 2.80512859665083;
   fWeightMatrix1to2[3][1] = 2.2567332833604;
   fWeightMatrix1to2[4][1] = -0.635845763254348;
   fWeightMatrix1to2[5][1] = -0.639060116700377;
   fWeightMatrix1to2[6][1] = -1.20030322513766;
   fWeightMatrix1to2[7][1] = -2.5460842109828;
   fWeightMatrix1to2[8][1] = 0.800369694515846;
   fWeightMatrix1to2[9][1] = 3.31564994682168;
   fWeightMatrix1to2[10][1] = -1.09132548466586;
   fWeightMatrix1to2[0][2] = 0.167347368090259;
   fWeightMatrix1to2[1][2] = 0.138800323792134;
   fWeightMatrix1to2[2][2] = 1.47026446892706;
   fWeightMatrix1to2[3][2] = -1.90002633935818;
   fWeightMatrix1to2[4][2] = 3.09926107450975;
   fWeightMatrix1to2[5][2] = -1.45829579162106;
   fWeightMatrix1to2[6][2] = 0.807829406469146;
   fWeightMatrix1to2[7][2] = -0.24786571075159;
   fWeightMatrix1to2[8][2] = 4.55522433909289;
   fWeightMatrix1to2[9][2] = 3.39008674899267;
   fWeightMatrix1to2[10][2] = -2.11097071614565;
   fWeightMatrix1to2[0][3] = -1.31103605973767;
   fWeightMatrix1to2[1][3] = -0.180625029984013;
   fWeightMatrix1to2[2][3] = 5.80486367824138;
   fWeightMatrix1to2[3][3] = -3.23603773156356;
   fWeightMatrix1to2[4][3] = -1.04195921204453;
   fWeightMatrix1to2[5][3] = 1.47116440484268;
   fWeightMatrix1to2[6][3] = 2.20494027917055;
   fWeightMatrix1to2[7][3] = 1.30930894121242;
   fWeightMatrix1to2[8][3] = 2.92987449818824;
   fWeightMatrix1to2[9][3] = 4.7171652904534;
   fWeightMatrix1to2[10][3] = -1.79202063091699;
   fWeightMatrix1to2[0][4] = -0.32632100687884;
   fWeightMatrix1to2[1][4] = 0.150180633012305;
   fWeightMatrix1to2[2][4] = 0.264166050284641;
   fWeightMatrix1to2[3][4] = -1.93641866854433;
   fWeightMatrix1to2[4][4] = -3.68160765670898;
   fWeightMatrix1to2[5][4] = 1.04330753155554;
   fWeightMatrix1to2[6][4] = 2.55934400235569;
   fWeightMatrix1to2[7][4] = -4.33442957823652;
   fWeightMatrix1to2[8][4] = -0.980052302118471;
   fWeightMatrix1to2[9][4] = -0.794229934623037;
   fWeightMatrix1to2[10][4] = 2.89249317858186;
   fWeightMatrix1to2[0][5] = 2.39491080961625;
   fWeightMatrix1to2[1][5] = -0.48705482190583;
   fWeightMatrix1to2[2][5] = 0.0107873013456564;
   fWeightMatrix1to2[3][5] = -2.58232434091652;
   fWeightMatrix1to2[4][5] = 0.6667546478267;
   fWeightMatrix1to2[5][5] = 1.36175509165539;
   fWeightMatrix1to2[6][5] = -0.363555395734411;
   fWeightMatrix1to2[7][5] = 0.692082661043265;
   fWeightMatrix1to2[8][5] = -0.250329100885554;
   fWeightMatrix1to2[9][5] = -2.62338150510198;
   fWeightMatrix1to2[10][5] = 1.24954046422192;
   fWeightMatrix1to2[0][6] = 1.82985290278009;
   fWeightMatrix1to2[1][6] = -1.90979146718937;
   fWeightMatrix1to2[2][6] = -1.89548712215299;
   fWeightMatrix1to2[3][6] = 1.87511062739404;
   fWeightMatrix1to2[4][6] = 0.764624658189323;
   fWeightMatrix1to2[5][6] = -1.88322235347385;
   fWeightMatrix1to2[6][6] = 1.1149018436326;
   fWeightMatrix1to2[7][6] = 1.18919568635183;
   fWeightMatrix1to2[8][6] = -2.59647175252984;
   fWeightMatrix1to2[9][6] = -1.57814929072356;
   fWeightMatrix1to2[10][6] = 3.74452699029745;
   fWeightMatrix1to2[0][7] = 1.01969491836667;
   fWeightMatrix1to2[1][7] = 0.435568609028799;
   fWeightMatrix1to2[2][7] = -0.174447575547356;
   fWeightMatrix1to2[3][7] = -2.09646100555367;
   fWeightMatrix1to2[4][7] = -0.964889090964821;
   fWeightMatrix1to2[5][7] = 1.72347772498275;
   fWeightMatrix1to2[6][7] = 1.21187924293468;
   fWeightMatrix1to2[7][7] = 0.823879092128389;
   fWeightMatrix1to2[8][7] = 0.150232809183713;
   fWeightMatrix1to2[9][7] = 1.89702132099204;
   fWeightMatrix1to2[10][7] = -1.70563098981572;
   fWeightMatrix1to2[0][8] = -0.272708868042457;
   fWeightMatrix1to2[1][8] = -0.779746141389781;
   fWeightMatrix1to2[2][8] = -2.53110035120063;
   fWeightMatrix1to2[3][8] = 4.85599241571089;
   fWeightMatrix1to2[4][8] = 2.93032015082578;
   fWeightMatrix1to2[5][8] = -1.12419410717883;
   fWeightMatrix1to2[6][8] = 4.06971700199566;
   fWeightMatrix1to2[7][8] = -0.63189004583191;
   fWeightMatrix1to2[8][8] = -2.65009577998349;
   fWeightMatrix1to2[9][8] = -4.52491545067245;
   fWeightMatrix1to2[10][8] = 3.28174198683371;
   fWeightMatrix1to2[0][9] = 0.922796250849978;
   fWeightMatrix1to2[1][9] = 0.932022053768456;
   fWeightMatrix1to2[2][9] = -2.37994856610402;
   fWeightMatrix1to2[3][9] = 2.57964745437481;
   fWeightMatrix1to2[4][9] = -2.65579403939442;
   fWeightMatrix1to2[5][9] = 1.05454207691358;
   fWeightMatrix1to2[6][9] = -1.21332832065013;
   fWeightMatrix1to2[7][9] = -0.196876463404485;
   fWeightMatrix1to2[8][9] = -2.84273793925362;
   fWeightMatrix1to2[9][9] = -3.07473355752907;
   fWeightMatrix1to2[10][9] = -0.0189504654022792;
   fWeightMatrix1to2[0][10] = -2.63916373778584;
   fWeightMatrix1to2[1][10] = -1.97810502030918;
   fWeightMatrix1to2[2][10] = -4.67299572985536;
   fWeightMatrix1to2[3][10] = 1.98110392358279;
   fWeightMatrix1to2[4][10] = -1.77835502410836;
   fWeightMatrix1to2[5][10] = -1.88293886024565;
   fWeightMatrix1to2[6][10] = 0.956678272951615;
   fWeightMatrix1to2[7][10] = -0.469535816292245;
   fWeightMatrix1to2[8][10] = -1.29140010145388;
   fWeightMatrix1to2[9][10] = -3.65423744597167;
   fWeightMatrix1to2[10][10] = 0.881354513172248;
   fWeightMatrix1to2[0][11] = 1.91719267217908;
   fWeightMatrix1to2[1][11] = 1.32942949661104;
   fWeightMatrix1to2[2][11] = -0.994282626199941;
   fWeightMatrix1to2[3][11] = 0.111908408689954;
   fWeightMatrix1to2[4][11] = -1.21181142524117;
   fWeightMatrix1to2[5][11] = -1.25688565455475;
   fWeightMatrix1to2[6][11] = -2.43316929094169;
   fWeightMatrix1to2[7][11] = -0.786195098648383;
   fWeightMatrix1to2[8][11] = 0.206743467900555;
   fWeightMatrix1to2[9][11] = 2.27134951341694;
   fWeightMatrix1to2[10][11] = -1.17416677191237;
   // weight matrix from layer 2 to 3
   fWeightMatrix2to3[0][0] = 0.830911061884887;
   fWeightMatrix2to3[1][0] = -2.36088727053134;
   fWeightMatrix2to3[2][0] = -2.11714731139351;
   fWeightMatrix2to3[3][0] = 1.24103925411539;
   fWeightMatrix2to3[4][0] = 0.449905012848874;
   fWeightMatrix2to3[5][0] = -2.62179565840059;
   fWeightMatrix2to3[6][0] = -1.23900788123214;
   fWeightMatrix2to3[7][0] = 0.878784790860201;
   fWeightMatrix2to3[8][0] = -0.146312997664524;
   fWeightMatrix2to3[9][0] = 0.776756014090844;
   fWeightMatrix2to3[10][0] = -1.7155965967617;
   fWeightMatrix2to3[0][1] = -0.112867889614116;
   fWeightMatrix2to3[1][1] = 1.10547232761842;
   fWeightMatrix2to3[2][1] = 0.962156483908467;
   fWeightMatrix2to3[3][1] = 1.23826698620224;
   fWeightMatrix2to3[4][1] = -0.352635146714635;
   fWeightMatrix2to3[5][1] = 0.216308453952175;
   fWeightMatrix2to3[6][1] = -0.157326999542919;
   fWeightMatrix2to3[7][1] = -1.06156080864029;
   fWeightMatrix2to3[8][1] = -0.749538289755774;
   fWeightMatrix2to3[9][1] = -1.52552938503503;
   fWeightMatrix2to3[10][1] = -2.13574743990465;
   fWeightMatrix2to3[0][2] = -3.13846230469097;
   fWeightMatrix2to3[1][2] = 2.26771838381288;
   fWeightMatrix2to3[2][2] = -1.85170749663334;
   fWeightMatrix2to3[3][2] = 0.528467457372677;
   fWeightMatrix2to3[4][2] = -1.6020160717844;
   fWeightMatrix2to3[5][2] = 0.106343754984371;
   fWeightMatrix2to3[6][2] = -1.77050636836744;
   fWeightMatrix2to3[7][2] = -1.13371074070834;
   fWeightMatrix2to3[8][2] = 2.08212152982176;
   fWeightMatrix2to3[9][2] = -3.78958076571882;
   fWeightMatrix2to3[10][2] = 1.18547563789829;
   fWeightMatrix2to3[0][3] = 1.7852533447032;
   fWeightMatrix2to3[1][3] = -3.55530561618234;
   fWeightMatrix2to3[2][3] = -1.64563957039246;
   fWeightMatrix2to3[3][3] = -0.46411690759966;
   fWeightMatrix2to3[4][3] = -1.60396352956994;
   fWeightMatrix2to3[5][3] = 0.409774937088992;
   fWeightMatrix2to3[6][3] = -0.145589800925668;
   fWeightMatrix2to3[7][3] = 1.60870929844561;
   fWeightMatrix2to3[8][3] = -4.02634567830534;
   fWeightMatrix2to3[9][3] = 1.63823312857132;
   fWeightMatrix2to3[10][3] = -2.36277757374748;
   fWeightMatrix2to3[0][4] = -2.22171045330829;
   fWeightMatrix2to3[1][4] = -3.42914139305826;
   fWeightMatrix2to3[2][4] = 0.946754179926598;
   fWeightMatrix2to3[3][4] = -2.59901971833387;
   fWeightMatrix2to3[4][4] = -1.44579868195859;
   fWeightMatrix2to3[5][4] = 0.880344390195403;
   fWeightMatrix2to3[6][4] = -0.31158989724428;
   fWeightMatrix2to3[7][4] = -1.6573804786169;
   fWeightMatrix2to3[8][4] = 3.12018579804208;
   fWeightMatrix2to3[9][4] = -1.64200939855861;
   fWeightMatrix2to3[10][4] = 1.43644013744079;
   fWeightMatrix2to3[0][5] = 0.907191598277407;
   fWeightMatrix2to3[1][5] = -0.747060470827178;
   fWeightMatrix2to3[2][5] = -0.816712649254756;
   fWeightMatrix2to3[3][5] = 0.109314847548235;
   fWeightMatrix2to3[4][5] = -1.2048067105828;
   fWeightMatrix2to3[5][5] = 0.464630005216907;
   fWeightMatrix2to3[6][5] = 1.921983124284;
   fWeightMatrix2to3[7][5] = 1.44153305877026;
   fWeightMatrix2to3[8][5] = 1.57715971669933;
   fWeightMatrix2to3[9][5] = -1.33259895463219;
   fWeightMatrix2to3[10][5] = 0.653129249939072;
   fWeightMatrix2to3[0][6] = -3.26365998903586;
   fWeightMatrix2to3[1][6] = -0.163273801112152;
   fWeightMatrix2to3[2][6] = -1.92003936523321;
   fWeightMatrix2to3[3][6] = -2.74223060753906;
   fWeightMatrix2to3[4][6] = -0.910911121362821;
   fWeightMatrix2to3[5][6] = 0.304185905537215;
   fWeightMatrix2to3[6][6] = 0.869368608967087;
   fWeightMatrix2to3[7][6] = 1.40908732072383;
   fWeightMatrix2to3[8][6] = -0.636404696797914;
   fWeightMatrix2to3[9][6] = 2.73270285031962;
   fWeightMatrix2to3[10][6] = -2.45281137521898;
   fWeightMatrix2to3[0][7] = 0.175087226738536;
   fWeightMatrix2to3[1][7] = 3.45393112117783;
   fWeightMatrix2to3[2][7] = -1.59388572472592;
   fWeightMatrix2to3[3][7] = -1.63556044507137;
   fWeightMatrix2to3[4][7] = -1.58522252762463;
   fWeightMatrix2to3[5][7] = -1.40228957422959;
   fWeightMatrix2to3[6][7] = -0.910906883646433;
   fWeightMatrix2to3[7][7] = -2.64032596801309;
   fWeightMatrix2to3[8][7] = -1.08062006089766;
   fWeightMatrix2to3[9][7] = -1.03004991414342;
   fWeightMatrix2to3[10][7] = 2.95026057718018;
   fWeightMatrix2to3[0][8] = 0.844802152230286;
   fWeightMatrix2to3[1][8] = 0.0184381515393011;
   fWeightMatrix2to3[2][8] = -0.968343005989624;
   fWeightMatrix2to3[3][8] = -3.15921269481453;
   fWeightMatrix2to3[4][8] = -1.86950629921955;
   fWeightMatrix2to3[5][8] = -0.22936408337926;
   fWeightMatrix2to3[6][8] = -0.661334431026771;
   fWeightMatrix2to3[7][8] = -1.98935829685252;
   fWeightMatrix2to3[8][8] = 0.613794113812058;
   fWeightMatrix2to3[9][8] = -3.16859645538187;
   fWeightMatrix2to3[10][8] = -2.10406473626832;
   fWeightMatrix2to3[0][9] = -3.51734306608486;
   fWeightMatrix2to3[1][9] = 0.728307774162686;
   fWeightMatrix2to3[2][9] = -1.4330950980197;
   fWeightMatrix2to3[3][9] = -2.38624481811206;
   fWeightMatrix2to3[4][9] = -0.787385993832004;
   fWeightMatrix2to3[5][9] = -2.10673638119084;
   fWeightMatrix2to3[6][9] = -2.32139361569323;
   fWeightMatrix2to3[7][9] = 0.541165149260992;
   fWeightMatrix2to3[8][9] = -0.0355816991188554;
   fWeightMatrix2to3[9][9] = -2.97040983091611;
   fWeightMatrix2to3[10][9] = 2.44387394027469;
   fWeightMatrix2to3[0][10] = 0.398104754926518;
   fWeightMatrix2to3[1][10] = -1.1258508604853;
   fWeightMatrix2to3[2][10] = -0.0353413652878834;
   fWeightMatrix2to3[3][10] = 2.32264214497598;
   fWeightMatrix2to3[4][10] = 1.06150282629133;
   fWeightMatrix2to3[5][10] = 0.091932138575565;
   fWeightMatrix2to3[6][10] = -0.814395633993297;
   fWeightMatrix2to3[7][10] = -0.045210221136853;
   fWeightMatrix2to3[8][10] = -3.66354389905676;
   fWeightMatrix2to3[9][10] = 3.53382732080192;
   fWeightMatrix2to3[10][10] = -0.279887899662912;
   fWeightMatrix2to3[0][11] = 0.0118631297285912;
   fWeightMatrix2to3[1][11] = -0.219268542042869;
   fWeightMatrix2to3[2][11] = 0.76587540540247;
   fWeightMatrix2to3[3][11] = 1.75946890452209;
   fWeightMatrix2to3[4][11] = -2.20162887372933;
   fWeightMatrix2to3[5][11] = -0.257519305399759;
   fWeightMatrix2to3[6][11] = 0.366091238536479;
   fWeightMatrix2to3[7][11] = -1.7638325105987;
   fWeightMatrix2to3[8][11] = -1.9002079599051;
   fWeightMatrix2to3[9][11] = -0.718184274584834;
   fWeightMatrix2to3[10][11] = -0.797877653448526;
   // weight matrix from layer 3 to 4
   fWeightMatrix3to4[0][0] = -1.47255244035414;
   fWeightMatrix3to4[0][1] = 3.72174005178914;
   fWeightMatrix3to4[0][2] = 1.69294742105799;
   fWeightMatrix3to4[0][3] = -2.09649031905793;
   fWeightMatrix3to4[0][4] = 1.17399362450447;
   fWeightMatrix3to4[0][5] = -0.385208268479988;
   fWeightMatrix3to4[0][6] = -0.251462533899953;
   fWeightMatrix3to4[0][7] = -2.50765557822693;
   fWeightMatrix3to4[0][8] = 1.75718981628613;
   fWeightMatrix3to4[0][9] = -1.81056850275782;
   fWeightMatrix3to4[0][10] = 1.95966340296106;
   fWeightMatrix3to4[0][11] = -0.0235253007193069;
}

inline double ReadMLP_ANN_N-4_NC400::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   if (inputValues.size() != (unsigned int)fLayerSize[0]-1) {
      std::cout << "Input vector needs to be of size " << fLayerSize[0]-1 << std::endl;
      return 0;
   }

   for (int l=0; l<fLayers; l++)
      for (int i=0; i<fLayerSize[l]; i++) fWeights[l][i]=0;

   for (int l=0; l<fLayers-1; l++)
      fWeights[l][fLayerSize[l]-1]=1;

   for (int i=0; i<fLayerSize[0]-1; i++)
      fWeights[0][i]=inputValues[i];

   // layer 0 to 1
   for (int o=0; o<fLayerSize[1]-1; o++) {
      for (int i=0; i<fLayerSize[0]; i++) {
         double inputVal = fWeightMatrix0to1[o][i] * fWeights[0][i];
         fWeights[1][o] += inputVal;
      }
      fWeights[1][o] = ActivationFnc(fWeights[1][o]);
   }
   // layer 1 to 2
   for (int o=0; o<fLayerSize[2]-1; o++) {
      for (int i=0; i<fLayerSize[1]; i++) {
         double inputVal = fWeightMatrix1to2[o][i] * fWeights[1][i];
         fWeights[2][o] += inputVal;
      }
      fWeights[2][o] = ActivationFnc(fWeights[2][o]);
   }
   // layer 2 to 3
   for (int o=0; o<fLayerSize[3]-1; o++) {
      for (int i=0; i<fLayerSize[2]; i++) {
         double inputVal = fWeightMatrix2to3[o][i] * fWeights[2][i];
         fWeights[3][o] += inputVal;
      }
      fWeights[3][o] = ActivationFnc(fWeights[3][o]);
   }
   // layer 3 to 4
   for (int o=0; o<fLayerSize[4]; o++) {
      for (int i=0; i<fLayerSize[3]; i++) {
         double inputVal = fWeightMatrix3to4[o][i] * fWeights[3][i];
         fWeights[4][o] += inputVal;
      }
      fWeights[4][o] = OutputActivationFnc(fWeights[4][o]);
   }

   return fWeights[4][0];
}

double ReadMLP_ANN_N-4_NC400::ActivationFnc(double x) const {
   // sigmoid
   return 1.0/(1.0+exp(-x));
}
double ReadMLP_ANN_N-4_NC400::OutputActivationFnc(double x) const {
   // sigmoid
   return 1.0/(1.0+exp(-x));
}
   
// Clean up
inline void ReadMLP_ANN_N-4_NC400::Clear() 
{
   // clean up the arrays
   for (int lIdx = 0; lIdx < 5; lIdx++) {
      delete[] fWeights[lIdx];
   }
}
   inline double ReadMLP_ANN_N-4_NC400::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            iV.reserve(inputValues.size());
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
         else {
            std::vector<double> iV;
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(*varIt);
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
      }

      return retval;
   }

//_______________________________________________________________________
inline void ReadMLP_ANN_N-4_NC400::InitTransform_1()
{
   // Normalization transformation, initialisation
   fMin_1[0][0] = 110.048698425;
   fMax_1[0][0] = 1277.92980957;
   fMin_1[1][0] = 110.057556152;
   fMax_1[1][0] = 1572.76037598;
   fMin_1[2][0] = 110.048698425;
   fMax_1[2][0] = 1572.76037598;
   fMin_1[0][1] = 5.00075817108;
   fMax_1[0][1] = 29.9497737885;
   fMin_1[1][1] = 5.00135278702;
   fMax_1[1][1] = 29.9984378815;
   fMin_1[2][1] = 5.00075817108;
   fMax_1[2][1] = 29.9984378815;
   fMin_1[0][2] = -1;
   fMax_1[0][2] = 1;
   fMin_1[1][2] = -1;
   fMax_1[1][2] = 1;
   fMin_1[2][2] = -1;
   fMax_1[2][2] = 1;
   fMin_1[0][3] = -2.4711689949;
   fMax_1[0][3] = 2.37911462784;
   fMin_1[1][3] = -2.48411560059;
   fMax_1[1][3] = 2.49880051613;
   fMin_1[2][3] = -2.48411560059;
   fMax_1[2][3] = 2.49880051613;
   fMin_1[0][4] = 280.2293396;
   fMax_1[0][4] = 1251.49438477;
   fMin_1[1][4] = 280.020294189;
   fMax_1[1][4] = 1289.47937012;
   fMin_1[2][4] = 280.020294189;
   fMax_1[2][4] = 1289.47937012;
   fMin_1[0][5] = 0.0557334087789;
   fMax_1[0][5] = 300.527191162;
   fMin_1[1][5] = 0.000537815736607;
   fMax_1[1][5] = 215.792510986;
   fMin_1[2][5] = 0.000537815736607;
   fMax_1[2][5] = 300.527191162;
   fMin_1[0][6] = 117.352531433;
   fMax_1[0][6] = 2347.48510742;
   fMin_1[1][6] = 112.003395081;
   fMax_1[1][6] = 4504.87304688;
   fMin_1[2][6] = 112.003395081;
   fMax_1[2][6] = 4504.87304688;
   fMin_1[0][7] = 0;
   fMax_1[0][7] = 5;
   fMin_1[1][7] = 0;
   fMax_1[1][7] = 6;
   fMin_1[2][7] = 0;
   fMax_1[2][7] = 6;
   fMin_1[0][8] = 1;
   fMax_1[0][8] = 11;
   fMin_1[1][8] = 1;
   fMax_1[1][8] = 14;
   fMin_1[2][8] = 1;
   fMax_1[2][8] = 14;
   fMin_1[0][9] = 20.0573444366;
   fMax_1[0][9] = 1057.04370117;
   fMin_1[1][9] = -999;
   fMax_1[1][9] = 1378.42883301;
   fMin_1[2][9] = -999;
   fMax_1[2][9] = 1378.42883301;
   fMin_1[0][10] = 6.27087429166e-05;
   fMax_1[0][10] = 4.95768356323;
   fMin_1[1][10] = -999;
   fMax_1[1][10] = 5.38026332855;
   fMin_1[2][10] = -999;
   fMax_1[2][10] = 5.38026332855;
}

//_______________________________________________________________________
inline void ReadMLP_ANN_N-4_NC400::Transform_1( std::vector<double>& iv, int cls) const
{
   // Normalization transformation
   if (cls < 0 || cls > 2) {
   if (2 > 1 ) cls = 2;
      else cls = 2;
   }
   const int nVar = 11;

   // get indices of used variables

   // define the indices of the variables which are transformed by this transformation
   static std::vector<int> indicesGet;
   static std::vector<int> indicesPut;

   if ( indicesGet.empty() ) { 
      indicesGet.reserve(fNvars);
      indicesGet.push_back( 0);
      indicesGet.push_back( 1);
      indicesGet.push_back( 2);
      indicesGet.push_back( 3);
      indicesGet.push_back( 4);
      indicesGet.push_back( 5);
      indicesGet.push_back( 6);
      indicesGet.push_back( 7);
      indicesGet.push_back( 8);
      indicesGet.push_back( 9);
      indicesGet.push_back( 10);
   } 
   if ( indicesPut.empty() ) { 
      indicesPut.reserve(fNvars);
      indicesPut.push_back( 0);
      indicesPut.push_back( 1);
      indicesPut.push_back( 2);
      indicesPut.push_back( 3);
      indicesPut.push_back( 4);
      indicesPut.push_back( 5);
      indicesPut.push_back( 6);
      indicesPut.push_back( 7);
      indicesPut.push_back( 8);
      indicesPut.push_back( 9);
      indicesPut.push_back( 10);
   } 

   static std::vector<double> dv;
   dv.resize(nVar);
   for (int ivar=0; ivar<nVar; ivar++) dv[ivar] = iv[indicesGet.at(ivar)];
   for (int ivar=0;ivar<11;ivar++) {
      double offset = fMin_1[cls][ivar];
      double scale  = 1.0/(fMax_1[cls][ivar]-fMin_1[cls][ivar]);
      iv[indicesPut.at(ivar)] = (dv[ivar]-offset)*scale * 2 - 1;
   }
}

//_______________________________________________________________________
inline void ReadMLP_ANN_N-4_NC400::InitTransform()
{
   InitTransform_1();
}

//_______________________________________________________________________
inline void ReadMLP_ANN_N-4_NC400::Transform( std::vector<double>& iv, int sigOrBgd ) const
{
   Transform_1( iv, sigOrBgd );
}
